### ISSUE TITLE
feat(docker-compose): Add a `docker-compose.yml`

### ISSUE THREAD

**Issue by ryanrussell** [dragonflydb/dragonfly#100]
Issue: When I googled to see if there's a ready-made `docker-compose.yml` I could plug in, I get a different `DragonFly` project all together.

This is frustrating to a new user looking for a quick and dirty way to test in 5 minutes.

![image](https://user-images.githubusercontent.com/523300/172057695-581a2b0f-7c37-4453-b6bf-3dc6343f608b.png)

Solution: Add a `docker-compose.yml` and `Quick Start` guide.

Suggestion: Make sure `docker-compose` + `docker stack deploy` Quick Start guides work. IMO `Swarm Mode` has quietly become respectable as a lower-maintenance multi-node scheduler.

@romange Do you already have a compose file or opinions on where you want them file-wise(I see your dockerfiles in `tools/docker`)?

Or I can stage one if you prefer....

**Comment by romange** [comment]
Hi Ryan,

It's a great suggestion. I would put docker-compose.yml under contrib/.

tools/docker is for project maintainers to describe how to build docker
imagers so i think it's not the right place for deployment scripts.

Regarding the quickstart - i would put a dedicated markdown file under doc
dir and link it from Readme. What do you think?

**Comment by ryanrussell** [comment]
Sounds good. 

It's on my todo list for my own uses; give me a couple days to shake it down and I'll post a version for the OSS repo.

**Comment by ryanrussell** [comment]
@romange 

- Need some easier channel for quick questions please
You have a matrix/discord/slack/signal/etc app you prefer? Maybe invite me to a new private repo with however you want to communicate...
- How much `docs` do you want in Git/Markdown vs making a real docs site? Finding it a bit cumbersome to make something nice here vs just using SvelteKit and a cname...
- Should come up with a canonical s3 object store(assets.dragonflydb.io). 
Absolutely do not want to bloat the repo size with tutorial screenshots. Once they are in; the repo is always going to be big for no reason...

For example, a little screenshot of the browser GUI would be nice, but doesn't belong in the repo:
![image](https://user-images.githubusercontent.com/523300/172745709-de009f5b-c82f-4dbb-8334-93bc371e955d.png)

**Comment by romange** [comment]
1. @ryanrussell  https://discord.gg/HsPjXGVH85
(I need to add a proper link to the README)

2. Your idea with screenshots is great! 
3. I do not have the capacity right now for real docs site. I think once we have md content here, it will be much easier to decide how to migrate them if needed. It can wait a month or two though. (We have dragonflydb.io that is rendered with hugo and thought to use its properties for real docs as well).
4. Re bloated git - I hear you brother. I also hate downloading bloated repos. I have never tried Git Lfs. Do not even know its product proposition. Will it solve the problem? If Git Lfs does not  work, on your opinion, I can setup an s3 assets bucket in 72h. How you would suggest managing it though? Through me? (sharing write permissions with collaborators seems like a bit premature for the second week of a project).  

FYI, I will be less responsive today and tomorrow.

**Comment by romange** [comment]
Update: I've read about Git LFs. seems like exactly what we need, don't you think?

**Comment by TamCore** [comment]
I'd be careful about it. In the past, i had pretty bad experience with Git LFs. To the extent where I had nothing but garbage left. For the beginning I'd simply recommend to not worry about it (but also don't commit 4k sized screenshots into Git) and when (if) it becomes necessary, a migration can still be done.

**Comment by romange** [comment]
But then we would be stack with already uploaded images, don't we?
I've tried to look up anything that is related to bad experience with git lfs, did not find anything substantial. Maybe those problems are long gone? Also, I've read that Unreal use git-lfs for their repo. 

One minor con is that folks that clone the repo will need to install lfs plugin  in order to access these files. But usually, people read docs directly from github so I do not see it as huge blocker and contributors will manage.

**Comment by ryanrussell** [comment]
Hey @romange -- joined the discord channel so we can discuss ideas quicker/more easily. Need to update the permissions to allow users to send messages in the room.

I believe I should just submit the basic yaml and README with no images for now. Git LFS is a permanent decision we don't need(want?)

Seems WAY easier to just wait to include images and put images in a  non-git-repo location in the future.

Will send PR later to keep things moving forward.

**Comment by romange** [comment]
Ok, so 2 people more experienced than me are inclined against Git LFS. cloud bucket it is but I will manage it.

**Comment by ryanrussell** [comment]
Housekeeping. Re-open if necessary.
