### ISSUE TITLE
Cluster emulation : READONLY not implemented

### ISSUE THREAD

**Issue by PhenixH** [dragonflydb/dragonfly#1003]
**Describe the bug**
The READONLY command in cluster emulated mode is not implemented, which can generated some migration issues because some libraries use READONLY command just after starting the redis connection to evaluate the possibility to reach a slave replica if needed (for exemple https://github.com/mediocregopher/radix).

**To Reproduce**
1. Start dragonflydb on cluster mode emulated
2. Execute READONLY command
3. see error : (error) unknown command `READONLY`

How i found it : 
I have a project that use https://github.com/mediocregopher/radix with a rediscluster config and tried to migrate to dragonglydb without code rework. At connection I get the error (error) unknown command `READONLY`.

**Expected behavior**
Get "OK" 

**Environment (please complete the following information):**

 - Containerized?:  Docker Compose
 - Dragonfly Version: v1.0.0

**Comment by ashotland** [comment]
Thanks for reporting - I can take a look.
