### ISSUE TITLE
feat(timeseries): Where in the DragonFly Roadmap?

### ISSUE THREAD

**Issue by ryanrussell** [dragonflydb/dragonfly#101]
Curious where this stands in the roadmap. 

Opening an issue to discuss.

Initial Thoughts:
- Time Series is the fastest growing DB segment
- Not sure how the `replication` major would block
- Opens the discussion of `streams` in parallel or quickly after(before?) `timeseries`

@romange Where do you see `timeseries` in the overall priority of commands to add to DragonFly?

[Redis Time Series Commands](https://redis.io/commands/?group=timeseries)

![image](https://user-images.githubusercontent.com/523300/172063846-35b63659-1db9-4e10-9bdb-8340859a36f2.png)

**Comment by romange** [comment]
I do not think it will be done in 2022, realistically speaking. Replication is a big task. And then we have to implement the rest of the commands to be on par with Redis 6 at least. Plus we have some other interesting features we had in mind.

**Comment by romange** [comment]
Specifically, I would love to see streams and replication implemented first. To design replication well in Dragonfly is a much harder task than in Redis.

**Comment by fuwwy** [comment]
> I do not think it will be done in 2022, realistically speaking. Replication is a big task. And then we have to implement the rest of the commands to be on par with Redis 6 at least. Plus we have some other interesting features we had in mind.

Is this estimate just for timeseries or replication too?

**Comment by romange** [comment]
Replication is one of the higher priority tasks i need to do . In fact, you
already can use DF as readonly replica for Redis.
