### ISSUE TITLE
helm: Remove unnecessary extra lines and enable linting

### ISSUE THREAD

**Issue by Pothulapati** [dragonflydb/dragonfly#1014]
**Describe the bug**

Currently, Due to the way, we have all the templating in the `_pod.tpl`, Based on
configurations set by the user, It might result in empty lines. This is not fatal as 
Kubernetes ignores them.

But it would be better to fix the formatting instead of having to fight these
extra lines.

**Additional context**

**Comment by romange** [comment]
Can we close this @Pothulapati  ?

**Comment by Pothulapati** [comment]
Yep!
