### ISSUE TITLE
Replication - replica should support setting up new master while its in loading state

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#1017]
**Describe the bug**
Today we return error on `replicaof <localhost> <port>` command if replica is in loading state, it returns "ERR Can not execute during LOADING"

**Expected behavior**
on loading state if `replicaof <localhost> <port>` command is executed, start replication with new master

Question:
What should happen if `replicaof no one` is executed during loading state? should we return error? Should we return ok and flush all the data?

.

**Comment by royjacobson** [comment]
@romange @Pothulapati 

What should happen if `replicaof no one` interrupts the replication? My preference is to be conservative and keep returning the error. Second option I thought about was to return an error, stop the replication, and flush all data.

**Comment by romange** [comment]
'replicaof no one' is like, "stop the replication, you are no more a slave". I think it's a valid usecase and it should be respected

**Comment by Pothulapati** [comment]
Great work @royjacobson! I triggered https://github.com/dragonflydb/dragonfly/actions/runs/4730432577 to test this out with the operator!
