### ISSUE TITLE
can't start since 1.1.0

### ISSUE THREAD

**Issue by yovanoc** [dragonflydb/dragonfly#1029]
with the docker-compose example:

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/7302317/229372979-f74e14c6-0fd0-4d12-a237-233c043f9924.png">

**Comment by romange** [comment]
@yovanoc  thanks for reporting so quickly. Can you please state your kernel version with "uname -a"  ?

**Comment by yovanoc** [comment]
How can I do that with the docker compose example ?

**Comment by romange** [comment]
You do not need to. Just run `uname -a` in your shell. What's your OS distribution?

**Comment by yovanoc** [comment]
Oh ok

```
Darwin devchris-mac.home 22.5.0 Darwin Kernel Version 22.5.0: Fri Mar 17 14:37:58 PDT 2023; root:xnu-8796.120.16~15/RELEASE_X86_64 x86_64
```

**Comment by romange** [comment]
Ok, and if you run `docker run   --rm ubuntu uname -a` - what does it output?

**Comment by yovanoc** [comment]
I don't know how I can pass `--rm ubuntu uname -a` to the docker compose up command

**Comment by romange** [comment]
just run  `docker run   --rm ubuntu uname -a` from the command line, no need for compose

**Comment by yovanoc** [comment]
<img width="834" alt="image" src="https://user-images.githubusercontent.com/7302317/229375370-8717b9de-bce4-4e9d-b9f0-cd70768d1041.png">

**Comment by romange** [comment]
found the problem, the fix will be release soon

**Comment by yovanoc** [comment]
glad to help
