### ISSUE TITLE
Start service configuration file specification

### ISSUE THREAD

**Issue by boomballa** [dragonflydb/dragonfly#1035]
At present, when dragonfly starts the service, can it only specify the required configuration parameters one by one when starting the service, and does not support putting the content of the configuration file into a config file, and pass `dragonfly --conf=dragonfly.conf &`or `dragonfly dragonfly.conf &` the way to load the configuration file? If it is not supported, can this function be added? I feel that it is very troublesome to specify parameters every time it is started.

**Comment by romange** [comment]
@adiholden , we should probably document it both at https://dragonflydb.io/docs/getting-started/binary and also in one of the docs in the repo.

@boomballa  you can use `--flagfile` argument . See here https://discord.com/channels/981533931486724126/981533931960676364/1090913368820428832  for more info.

**Comment by romange** [comment]
btw, our debian package already installs such a file at `/etc/dragonfly/dragonfly.conf`

**Comment by boomballa** [comment]
> @adiholden , we should probably document it both at https://dragonflydb.io/docs/getting-started/binary and also in one of the docs in the repo.
> 
> @boomballa you can use `--flagfile` argument . See here https://discord.com/channels/981533931486724126/981533931960676364/1090913368820428832 for more info.

@romange  OK, got it, let's try it out.thanks.

**Comment by boomballa** [comment]
> btw, our debian package already installs such a file at `/etc/dragonfly/dragonfly.conf`
@romange  Okay, I will try this too, but most of our production environment deployments may still use binary packages for deployment, because there may be a situation where a physical machine has multiple cluster nodes, use binary packages with absolute paths, for It may be more convenient for us to upgrade and maintain.
