### ISSUE TITLE
No backpressure on pubsub and monitor leads to piling up messages

### ISSUE THREAD

**Issue by dranikpg** [dragonflydb/dragonfly#1039]
Same effect as #1034 (memory overflow), though not a leak

With pubsub, if the producer is much faster than the consumer, the messages pile up in `Connection::dispatch_q_` as `SendMsgVecAsync` is fully async and does not provide any backpressure

**Comment by dranikpg** [comment]
My findings about Redis. It doesn't provide any backpressure. Once the connection buffer fills up - it just kills the connection 🤷🏻 So when you run memtier publish vs python subscriber it just stops after a few seconds. 

Instead of doing backpressure, which slows down everything, we can do the same - stop when we accumulated too much memory.

The only issue is that:
* We have a much higher memory overhead - redis is much more efficient. Pubsub stores currently two shared_ptr<string> - thats dozens of bytes even for a tiny message.
* We allow much higher throughout, on multiple threads, so a faster producer can fill up the buffer much faster.

Meaning, if you start publish on a few threads with go and consume them with python - you won't be able to. You need to manually slow down the producer. Same with Redis, but again, much less of a problem.

**Comment by romange** [comment]
My opinion: backpressure is better than closing a connection. Redis closes a connection because its infrastructure does not allow backpressure and not because they do not want to. Closing connections abruptly is bad product behavior. 

If we implement backpressure, we could expose expose stats how many times it was activated. For example, now, with us owning fibers lib, we can introduce fiber generation number that is increased each time we switch to a fiber. With such a generation number we can recognize context switches in our code.

**Comment by dranikpg** [comment]
> My opinion: backpressure is better than closing a connection. [...] Closing connections abruptly is bad product behavior.

Agree, its really weird from a users perspective.

So I'll proceed with actual backpressue. The biggest issue is that it slows down pubsub measurably. We now need to dispatch a fiber for blocking, not a brief callback.

`slows down` is objective in some cases. I usually measure only producer througput. With a slow consumer, the producer just fills the datastore ahead and then the slow consumer still takes around the same time to read all those messages. So the load is just spread differently, the full delivery of messages takes around the same time.

**Comment by romange** [comment]
Dispatching a fiber is indeed a problem. Where do you need to replace it?

**Comment by dranikpg** [comment]
Right here,

https://github.com/dragonflydb/dragonfly/blob/002ec8a6217cfd6cf026737f233612682c21c91d/src/server/main_service.cc#L1471

**Comment by romange** [comment]
Spawning a fiber on each request is not an option. I see two options here:
1. to introduce a back pressure on the produce side, i.e. you to not even try sending anything unless the metric is above a certain limit.
2. To introduce a dedicated FiberQueue similar to the one that handles transactions.
