### ISSUE TITLE
support for JSON commands

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#104]
AWS Elasticache recently released JSON support as part of their service.

We should implement a compatible API. See 
https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/json-list-commands.html

for command reference.

**Comment by romange** [comment]
https://github.com/danielaparker/jsoncons/tree/master/include/jsoncons is a good candidate for supporting jsonpath.

**Comment by ryanrussell** [comment]
Equivalent RedisJSON command set for reference: [RedisJSON Commands](https://redis.io/commands/?group=json)

![image](https://user-images.githubusercontent.com/523300/172269071-3690a37f-34dc-48ea-8f6c-d64de3299d41.png)

**Comment by romange** [comment]
@iko1  pls take a look at this issue. You can continue working on Json branch - https://github.com/dragonflydb/dragonfly/tree/Json  .

The initial milestone would be to add json_familyXX files that implement `JSON.GET` command.
The syntax is `json.get <key> <path>`. See elasticache documentation for that.
the command should work on string types. it should try and parse the string into json. if it succeeds, apply the "path" query on the json object. The command should handle properly states like wrong type or "not a json" and output the error response accordingly.

**Comment by romange** [comment]
Due to #238 we must introduce internally a dedicated type for json. That means we will need to support json inside compact_object. Still, I want relaxed semantics for READONLY json commands. For example, `JSON.GET` should work on both strings and json types. `JSON.SET` should produce json types only.

**Comment by iko1** [comment]
@romange, I assume you can close this issue after all JSON commands were merged into the main branch.

**Comment by romange** [comment]
Thanks @iko1 . I still consider #238  unfinished. The team will continue from here (add "scan", "type" integration. add rdb support etc).

**Comment by iko1** [comment]
@romange, The basic JSON support is done with some exceptions like what you mentioned.
Can you elaborate on the missing things that should be implemented when I have a spare time can I take them on myself?

**Comment by romange** [comment]
You already did huge part of this effort. I would like to finish the rest
internally 🙏

**Comment by romange** [comment]
Closing as finished, will open a new task for the missing features.
