### ISSUE TITLE
Save on SIGTERM and SIGINT

### ISSUE THREAD

**Issue by heikomat** [dragonflydb/dragonfly#1045]
**Did you search GitHub Issues and GitHub Discussions First?**
Yes, although there are a lot, and i might have overlooked something.

**Is your feature request related to a problem? Please describe.**
When updating Dragonfly (by increasing the version-number in the `docker-compose.yml` and running `docker compose up -d`), the updated instance is empty

**Describe the solution you'd like**
I'd like to have Dragonfly perform a `save` when receiving a SIGTERM or SIGINT, similar to how [Redis handles these signals](https://redis.io/docs/reference/signals#sigterm-and-sigint).
If i'm not mistaken that should create a dump that should automatically be restored when the new Dragonfly instance starts up, so no data is lost.

**Describe alternatives you've considered**
For my personal use case, i'll create a small update script that tells Dragonfly to `save` before recreating the container.

**Additional context**
It's not a big deal, but having Dragonfly save itself on SIGTERM/SIGINT would be convinient.

**Comment by JQuags** [comment]
For those looking for a resolution in the mean time, before a shut down use SAVE

IE
redis-cli -h localhost -p 6379 SAVE
