### ISSUE TITLE
Dragonfly's config get databases not compatible with redis

### ISSUE THREAD

**Issue by KarelWintersky** [dragonflydb/dragonfly#1046]
**Describe the bug**

```
$ sudo systemctl start dragonfly
$ redis-cli
127.0.0.1:6379> config get databases
1) "databases"
2) "tbd"
```

what is `tbd` mean? Mystery... let's try redis:

```
$ sudo systemctl stop dragonfly
$ sudo systemctl start redis-server
$ redis-cli
127.0.0.1:6379> config get databases
1) "databases"
2) "16"
```

Actual databases count... 

**Expected behavior**

Dragonfly must return actual databases count instead of `tbd` value. 

**Environment (please complete the following information):**
 - OS: `ubuntu 22.04`
 - Kernel: `Linux AmberTower 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
 - Containerized?: No, installed from DEB package
 - Dragonfly Version: v1.1.2-6d269096df37e9f4389d4d2b354113a0c8cbfb74

**Comment by KarelWintersky** [comment]
My `dragonfly.conf`:
```
--dbnum=32
--pidfile=/var/run/dragonfly/dragonfly.pid
--log_dir=/var/log/dragonfly
--dir=/var/run/dragonfly
--version_check=true
--logtostderr
```

**Comment by romange** [comment]
We should implement for now precisely those attributes that are requestes. @KarelWintersky  do you need anything besides `dbnum` with config get?

**Comment by KarelWintersky** [comment]
No ideas ATM... 

The problem is that without  `config get databases` command, the database selection in [phpRedisAdmin](https://github.com/erikdubbelboer/phpRedisAdmin) does not work.

![изображение](https://user-images.githubusercontent.com/2164874/231827278-77815646-5f18-4194-88f2-f3d6c05fd5cf.png)

instead of:

![изображение](https://user-images.githubusercontent.com/2164874/231827218-b6a8e343-84f7-4052-96c8-7b9eab7f182a.png)

**Comment by KarelWintersky** [comment]
https://redis.io/commands/config-get/ 

> The CONFIG GET command is used to read the configuration parameters of a running Redis server.

If it is not possible to implement all possible answers, then it would be reasonable to implement the following:

- "maxmemory"
- "cluster-enabled"
- "maxclients"
- "databases"

**Comment by romange** [comment]
1. May I ask for reasons you want to switch from Redis? What's your workload and where you feel the pain?

2. Have you confirmed that DF  besides this issue has no other barriers for you to switch?

**Comment by chakaz** [comment]
FWIW, looking at [phpRedisAdmin](https://github.com/erikdubbelboer/phpRedisAdmin), it looks like the only config commands issued are `GET databases` and `RESETSTAT`:

```
$ grep -r "redis->config" .
./index.php:  $databases = $redis->config('GET', 'databases');
./info.php:  $redis->config('resetstat');
```

(admittedly this isn't a very thorough lookup, but hopefully it'll do the trick)

`RESETSTAT` seems to be already supported by DragonflyDB: https://github.com/dragonflydb/dragonfly/blob/fcb1c7bd555192b353cd37316fb4c1c6c362838c/src/server/server_family.cc#L1321-L1329

Which leaves us with just `GET databases` as described in the first comment.

Looking at [Redis' CONFIG GET](https://redis.io/commands/config-get/) manual, I see that it refers to all settings available under `redis.conf`. @romange, am I correct to say that Dragonfly does not use such a config file, but uses command-line flags instead?

We could hack a simple solution to only support `GET`ting `databases`, or do something more generic depending on the above answer (and how much we want to invest here). Any thoughts?

**Comment by romange** [comment]
I do not want to develop a generic solution, so supporting specific options will hopefully be enough.
Let's implement "maxmemory" and "databases" support - I think it's a few lines of code.

**Comment by chakaz** [comment]
SG, please see the PR.

I would say that, ideally, we will expose the db count as a method rather than rely on the flag, but I imagine it's beyond the scope of this CL (although I'm happy to do it now if you think that's worthwhile!)

**Comment by KarelWintersky** [comment]
Thank you for release [1.2.0](https://github.com/dragonflydb/dragonfly/releases/tag/v1.2.0) with this fix.

**Comment by KarelWintersky** [comment]
@romange , of course 

> May I ask for reasons you want to switch from Redis? What's your workload and where you feel the pain?

We do not have an optimized and high perfomance system infrastructure (one server, without clustering and all that). A single-threaded Rediis periodically falls into a stupor when there are too many keys (about one and a half million) and active work is being done with them.

We cannot increase server resources. We have to look for optimization methods. Judging by the readme, dragonfly should help us with this.

> Have you confirmed that DF besides this issue has no other barriers for you to switch?

Looks like there are no other barries... for now.

**Comment by KarelWintersky** [comment]
> Please be advised that Dragonfly works smoother on servers with more than 1 CPU.

it is a intel xeon X5660, not a size-unlimited virtual infrastructure ;-)
