### ISSUE TITLE
Tried to start Dragonfly on WSL but when I connect it goes crash

### ISSUE THREAD

**Issue by DarckRM** [dragonflydb/dragonfly#1056]
**Describe the bug**
On wsl enviroment I tried to boot dragonfly with recommended command(change the port at 6380), eveything went well until i visit dragonfly on localhost:6380 then dragonfly crashed, and i tried connect with Redis Desketop Manager but the dragonfly still went crash
**To Reproduce**
1. just download `dragonfly-x86_64` which released on repo release page
2. use command `./dragonfly-x86_64 --logtostderr --requirepass=youshallnotpass --cache_mode=true -dbnum 1 --bind localhost --port 6380  --save_schedule "*:30" --maxmemory=12gb --keys_output_limit=12288 --dbfilename dump.rdb`
3. connect from browser or RDM
4. dragonfly shutdown

**Expected behavior**
I hope it can run properly

**Screenshots**
![image](https://user-images.githubusercontent.com/39851504/230761398-e49ec837-c4cd-4e89-b67f-85acf76b07a7.png)

**Environment (please complete the following information):**
 - OS: [ubuntu 20.04]
 - Kernel: Linux DESKTOP-H72A044 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
 - Containerized?: no
 - Dragonfly Version: 1.1.2

**Comment by DarckRM** [comment]
I tried an older version 1.0.0 and now it can run, but on my terminal it still has this output
`dfly_main.cc:142] Remote version - connection error [version.dragonflydb.io:443] : Transport endpoint is already connected`
I'm not sure if this is my configure issue or anything else,,,

**Comment by romange** [comment]
Will be fixed in the next version but "remote version" error will stay (not important). Btw, I checked on WSL2 (windows 10, kernel 5.15.90.1-microsoft-standard-WSL2) - everything works fine.
