### ISSUE TITLE
Master node crashes after executing slaveof command on slave node

### ISSUE THREAD

**Issue by Tieger** [dragonflydb/dragonfly#1063]
Hello,

I encountered a crash in my application when I executed the `slaveof` command on a slave node. The master node crashes immediately after I run the command: `slaveof 10.0.1.57 6379`. The error message is as follows:

F20230410 08:01:42.748535 109108 epoll_socket.cc:67] Check failed: arm_index_ < 0 (2 vs. 0)

The stack trace is as follows:

*** Check failure stack trace: ***
    @     0x55d28aa50c53  google::LogMessage::SendToLog()
    @     0x55d28aa49417  google::LogMessage::Flush()
    @     0x55d28aa4ad9f  google::LogMessageFatal::~LogMessageFatal()
    @     0x55d28a67e09f  util::epoll::EpollSocket::OnSetProactor()
    @     0x55d28a5c66a6  util::ListenerInterface::Migrate()
    @     0x55d28a762144  dfly::ServerFamily::Dfly()
    @     0x55d28a5ab7c6  dfly::Service::InvokeCmd()
    @     0x55d28a7bf076  dfly::Service::DispatchCommand()
    @     0x55d28a629766  facade::Connection::ParseRedis()
    @     0x55d28a62e2a3  facade::Connection::HandleRequests()
    @     0x55d28a5ea762  util::ListenerInterface::RunSingleConnection()
    @     0x55d28a5eaad9  _ZN5boost6fibers14worker_contextIZN4util17ListenerInterface13RunAcceptLoopEvEUlvE0_JEE4run_EONS_7context5fiberE
    @     0x55d28a5e83c3  _ZN5boost7context6detail11fiber_entryINS1_12fiber_recordINS0_5fiberENS0_21basic_fixedsize_stackINS0_12stack_traitsEEESt5_BindIFMNS_6fibers14worker_contextIZN4util17ListenerInterface13RunAcceptLoopEvEUlvE0_JEEEFS4_OS4_EPSE_St12_PlaceholderILi1EEEEEEEEvNS1_10transfer_tE
    @     0x55d28aad609f  make_fcontext
*** SIGABRT received at time=1681113702 on cpu 0 ***
PC: @     0x7fa699e2203b  (unknown)  raise
Aborted (core dumped)

Here's a brief description of my environment:

- Operating System: Ubuntu 20.04.2 LTS
- Dragonfly Version:  v1.1.2-6d269096df37e9f4389d4d2b354113a0c8cbfb74

To reproduce the issue, I performed the following steps:

1. Set up a master and a slave node.
2. On the slave node, run the command: `slaveof 10.0.1.57 6379`
3. Observe the crash on the master node.

Can you please help me understand what might be causing this issue, and how I can fix it?

Please let me know if you need any additional information, and I'll be happy to provide it.

Thank you!

**Comment by romange** [comment]
@Tieger  do you use docker or native binary?

**Comment by Tieger** [comment]
> @Tieger 您使用 docker 还是本机二进制文件？

二进制文件,  
https://github.com/dragonflydb/dragonfly/releases/download/v1.1.2/dragonfly-x86_64.unstripped.tar.gz

**Comment by romange** [comment]
Will be fixed in the next version.

**Comment by Tieger** [comment]
Thank you very much !  I will close this issue for now and look forward  to the new version.
