### ISSUE TITLE
save is failing with 'Invalid argument" when saving in an unsupported filesystem

### ISSUE THREAD

**Issue by royjacobson** [dragonflydb/dragonfly#1084]
Some filesystems don't support the `O_DIRECT` flag. This makes `open` return `EINVAL`. The client gets just the opaque error 'Invalid argument' which is confusing. This can happen with a tmpfs, for example (which is how I discovered it).

We should probably return a better error and clarify/workaround the filesystem requirements?

**Comment by romange** [comment]
Are you talking about `RdbSnapshot::Start` ?
The code potentially may support non-direct access (see `is_direct`), but I do not remember all the restrictions with iouring.
You can experiment with the flags but I agree that a better error may be enough right now.
