### ISSUE TITLE
Inserting > 150'000'000 keys flaky or not possible

### ISSUE THREAD

**Issue by heikomat** [dragonflydb/dragonfly#1089]
**Describe the bug**
When inserting a lot of keys, they start to not be available. As in: I call `MSET` but not all the set keys are available after the command

**To Reproduce**
1. Insert hundrets of Millions of keys.
   - I do 1 million per call.
   - Each call is a pipeline with 34 MSET commands
   - Each MSET command contains 30k keys (except for the lasst one, which is 10k keys)
   - The keys are just continuous numbers, the values are the index in the current batch (between 0 and 1'000'000)
2. Observe how `DBSIZE` correctly grows in steps of 1 million
3. Observe how at about 150'000'000 keys, DBSize stops being a number of whole millions
4. GET the last inserted keys and see that some are missing

**Expected behavior**
I Expected my keys to exist in the database after having SET them

**Environment (please complete the following information):**
 - OS: macOS 13.2.1
 - Kernel: `Darwin Heikos-MacBook.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64 x86_64`
 - Containerized: Docker Compose
 - Dragonfly Version: 1.1.2

**Reproducible Code Snippet**
Running the test
```TypeScript
const maxKeysPerMSETRequest = 30000;

async function setMultipleOnRedisCache(values) {
  const pipeline = redis.pipeline();

  for (let i = 0; i < values.length / maxKeysPerMSETRequest; i += 1) {
    const batch = values.slice(i * maxKeysPerMSETRequest, (i + 1) * maxKeysPerMSETRequest);
    pipeline.mset(Object.fromEntries(batch));
  }

  await pipeline.exec();
}

async function testKeyCount() {
  let totalKeyCount = 0;
  while (true) {
    const dummyValues = new Array(1000000).fill(null).map((value, index) => {
      return [`${totalKeyCount + index}`, index];
    });
    console.log(`${totalKeyCount + dummyValues.length} entries...`);
    await setMultipleOnRedisCache(dummyValues);
    totalKeyCount += dummyValues.length;
  }
}
```
Observing the db-size
```sh
watch -n 1 docker exec dev-redis-1 redis-cli DBSIZE
```

**Additional context**
- When i let the script run for until about 300'000'000 keys, the DBSize never grew above ~248'000'000 keys
- The MSET-Command does not seem to throw an error
- The problem doesn't seem to exist in redid 6. I ran the same test there until 235'000'000 keys. The DBSIZE was always a number of whole millions, indicating that all keys are in the DB.
  - Though redis did crash at that point, probably due to a lack of memory (was limited to 15GB)

**Comment by romange** [comment]
You are probably out of memory. can you put here `redis-cli info` once dbsize stops growing?

**Comment by heikomat** [comment]
Looks like you're correct, i'm out of memory!

In that case i'd like to apologize and adjust my expectations:
I'd like the server to not silently do nothing when a set didn't actually work because of low memory.
I'd expect the command to error, or at least the server to print a log.

Redis just crashes in that case. Not elegant, but from that i can at least assume that it was out of memory :D

```
# Server
redis_version:6.2.11
dfly_version:df-v1.1.2
redis_mode:standalone
arch_bits:64
multiplexing_api:iouring
tcp_port:6379
uptime_in_seconds:870
uptime_in_days:0

# Clients
connected_clients:2
client_read_buf_capacity:512
blocked_clients:0

# Memory
used_memory:12710470152
used_memory_human:11.84GiB
used_memory_peak:12710470152
comitted_memory:13049774080
used_memory_rss:12870451200
used_memory_rss_human:11.99GiB
object_used_memory:0
table_used_memory:12521566592
num_buckets:325616760
num_entries:261512326
inline_keys:0
strval_bytes:0
updateval_amount:0
listpack_blobs:0
listpack_bytes:0
small_string_bytes:0
pipeline_cache_bytes:0
maxmemory:12689896243
maxmemory_human:11.82GiB
cache_mode:store
maxmemory_policy:noeviction

# Stats
total_connections_received:1135
total_commands_processed:11521
instantaneous_ops_per_sec:2
total_pipelined_commands:9017
total_net_input_bytes:7202851635
total_net_output_bytes:138997
instantaneous_input_kbps:-1
instantaneous_output_kbps:-1
rejected_connections:-1
expired_keys:0
evicted_keys:0
hard_evictions:0
garbage_checked:0
garbage_collected:0
bump_ups:0
stash_unloaded:0
traverse_ttl_sec:0
delete_ttl_sec:0
keyspace_hits:0
keyspace_misses:0
total_reads_processed:235936
total_writes_processed:11496
async_writes_count:0
parser_err_count:0
defrag_attempt_total:0
defrag_realloc_total:0
defrag_task_invocation_total:0

# Replication
role:master
connected_slaves:0
master_replid:179fa6595b88679fa7b3b85c052239b89e6e1764

# Keyspace
db0:keys=0,expires=0,avg_ttl=-1
db1:keys=261512326,expires=0,avg_ttl=-1

# CPU
used_cpu_sys:125.214453
used_cpu_user:421.651303
used_cpu_sys_children:0.4896
used_cpu_user_children:0.705
used_cpu_sys_main_thread:18.326004
used_cpu_user_main_thread:73.969656

# Cluster
cluster_enabled:0
```

**Comment by romange** [comment]
We should report "out of memory" errors actually.  In fact, we have a test that verifies this. Moreover, I just manually reached a similar state on my machine and then I run in redis-cli:
```
127.0.0.1:6379> set mee aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
(error) ERR Out of memory
```

I am not sure why you do not receive those errors but I suggest checking with redis-cli directly when you reach this state.

**Comment by romange** [comment]
And "not elegant" is an understatement  :)

**Comment by heikomat** [comment]
Two things i noticed:
1. Used memory ist 20 MB above max memory in the redis-cli info I posted earlier
2. You tested with SET, I used MSET. Just maybe there is a bug that prevents the error from being thrown when setting multiple keys at once using MSET.

Another difference: I sent multiple MSET in a pipeline. Maybe that pipeline also affects wether the error gets returned correctly

**Comment by romange** [comment]
Checked with MSET as well - works. Tried with python client:
```py
import redis
p = r.pipeline(transaction=False)
p.mset({"foo" : "aaaaaaaaaaaaaaaaaaaaaaaa"})
p.mset({"foo" : "aaaaaaaaaaaaaaaaaaaaaaaa"})
p.execute()
```

got:
```
...
    self.raise_first_error(commands, response)
  File "/home/roman/.local/lib/python3.10/site-packages/redis/client.py", line 2038, in raise_first_error
    raise r
  File "/home/roman/.local/lib/python3.10/site-packages/redis/client.py", line 2026, in _execute_pipeline
    response.append(self.parse_response(connection, args[0], **options))
  File "/home/roman/.local/lib/python3.10/site-packages/redis/client.py", line 2049, in parse_response
    result = Redis.parse_response(self, connection, command_name, **options)
  File "/home/roman/.local/lib/python3.10/site-packages/redis/client.py", line 1275, in parse_response
    response = connection.read_response()
  File "/home/roman/.local/lib/python3.10/site-packages/redis/connection.py", line 882, in read_response
    raise response
redis.exceptions.ResponseError: Command # 1 (MSET foo aaaaaaaaaaaaaaaaaaaaaaaa) of pipeline caused error: Out of memory
```

**Comment by heikomat** [comment]
Hmm... Interesting. I'll try a couple more things tomorrow to find out why I don't get that error. Maybe a bug in my code that makes it so the error isn't taken into account

**Comment by heikomat** [comment]
@romange sorry for all the fuss. Dragonfly is working fine, it was my code that swallowed the error.

Turns out that [ioredis](https://github.com/luin/ioredis#readme) doesn't *throw* any errors when dealing with a pipeline. instead all errors of the commands in the pipeline are *returned*.

I now added a piece of code that checks all responses for non-null error values and actually throws the first one it finds.
Now i get the out-of-memory errors just fine.

Please remove the bug label :D
