### ISSUE TITLE
Frequent keys with squashing in non-atomic mode

### ISSUE THREAD

**Issue by dranikpg** [dragonflydb/dragonfly#1091]
In non-atomic eval mode, contended keys can become part of a large squash batch and thus complicate locking.

For example:
```lua
for i = 1, #KEYS+1 do
  redis.acall('LPUSH', KEYS[i], 'value')
done
redis.acall('INCR', 'num-ops')
```

Here, `num-ops` might be accessed by many many scripts running in parallel. If they run in non-atomic mode, then the batch will have to lock the whole KEYS array **and num-ops** for doing one squashed hop with all of them. If num-ops is locked for all operations, then they become effectively sequential and not parallel at all.

What is more, it makes replacing `call` with `acall` dangerous for arbitrary scripts, as it can absolutely ruin performance.

For scripts, you can use regular `redis.call` for hot keys. Downside: it requires users to be aware of it.

**Comment by romange** [comment]
@dranikpg  it's not a bug if it's not actionable.

**Comment by dranikpg** [comment]
We changed non atomic mode and it doesn't look in batches
