### ISSUE TITLE
Missing SINTERCARD command

### ISSUE THREAD

**Issue by 0xManjeet** [dragonflydb/dragonfly#1099]

**Comment by romange** [comment]
Yeah, we do not support redis 7.0 API yet. Why do you need it?

**Comment by 0xManjeet** [comment]
My app maintains a list of users who are currently online, and this list can potentially reach millions in number. In addition, the app has several group chats, each with thousands of members.

My plan was to store the active users in a sorted set (which gets cleaned up the set every few minutes.), 
and the group members for each chat in regular set.

And the cardinality of the intersected set would give me the number of active users in a specific group chat.

**Comment by romange** [comment]
I see. So you need to intersect a sorted set with a regular set?

**Comment by 0xManjeet** [comment]
Yes, exactly. One way is that I can first ZINTERSTORE and then get the cardinality of the new set, and clean up the new set after that, but a single command to do that will be much simple and better.

**Comment by 0xManjeet** [comment]
Hi @romange,

Do you have any timeline for possibly implementing SINTERCARD in DragonflyDB? 

Any rough estimate or roadmap would be helpful for me to plan my usage of DragonflyDB accordingly.

**Comment by romange** [comment]
This quarter :)

**Comment by romange** [comment]
@0xManjeet  btw, given your description you need to use ZINTERCARD and not SINTERCARD because you want to intersect a sorted set with set. Please confirm

**Comment by 0xManjeet** [comment]
You're right, I'll need ZINTERCARD for my specific use case.
