### ISSUE TITLE
PUNSUBSCRIBE/UNSUBSCRIBE without arguments

### ISSUE THREAD

**Issue by alisaifee** [dragonflydb/dragonfly#111]
Both `PUNSUBSCRIBE` and `UNSUBSCRIBE` have command arity `-1` as per the official redis command spec. Calling the commands with no arguments effectively results in unsubscribing from any channels or patterns subscribed to by the client ([Redis command Reference](https://redis.io/commands/unsubscribe/) and [commands.c](https://github.com/redis/redis/blob/unstable/src/commands.c#L3266)).

Both commands currently return an error if no arguments are provided.

**Comment by romange** [comment]
Good catch. I can fix it or, if you want, you can send a PR.

**Comment by alisaifee** [comment]
I'm happy to take a crack at it - just wanted to make sure that it was indeed classified as a bug and that it wasn't an intentional design choice.

**Comment by alisaifee** [comment]
Resolved in #117
