### ISSUE TITLE
docs(ulimit): Dedicated and comprehensive ulimit FAQ

### ISSUE THREAD

**Issue by ryanrussell** [dragonflydb/dragonfly#115]
#### Problem
Many users will encounter various `ulimit` problems that are environment dependent.

#### Goal
Create a single, comprehensive `ulimit` FAQ page that will guide users to self-resolve on `bare metal`, `docker compose` and `k8s`

This should **lower the noise** in issues around various implementation specifics and give a quality canned response when they do arise.

See commit #114 for a starting place and more details.

#### Status
Not Yet Assigned. If someone has bandwidth and knowledge to write a tutorial, please submit a PR

**Comment by romange** [comment]
we have a documentation site. 
Also with presense of helm, docker-compose and the operator the issue is not  raised anymore
