### ISSUE TITLE
Support AUTH and SETNAME options in HELLO

### ISSUE THREAD

**Issue by rueian** [dragonflydb/dragonfly#1151]
Hi, hope you are all doing well.

I am making a redis RESP3 client, rueidis, and one user reported an issue https://github.com/rueian/rueidis/issues/207 about my client implementation can't be authenticated by dragonflydb because my client sent AUTH option in HELLO command which is allowed by redis https://redis.io/commands/hello/.

I noticed that here states Dragonfly doesn't support AUTH and SETNAME options in a HELLO command.
https://github.com/dragonflydb/dragonfly/blob/574ae24feceba600c5aa1fe4683b7eee64fe9ce8/src/server/server_family.cc#L1758-L1760

Not sure why is it, but I believe most RESP3 clients will send these options in HELLO command at once to reduce roundtrips.

**Comment by romange** [comment]
Thank you, @rueian - we should indeed implement it!
