### ISSUE TITLE
XGROUP MKSTREAM option is not supported

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#1158]
Quoting @FZambia from #231 

```
The XGROUP subcommand requires the key to exist. Note that for CREATE you may want to use the MKSTREAM option to create an empty stream automatically.
```

To reproduce with DragonflyDB 1.2.1:

```
127.0.0.1:6379> XGROUP CREATE test test 0 MKSTREAM
(error) ERR The XGROUP subcommand requires the key to exist. Note that for CREATE you may want to use the MKSTREAM option to create an empty stream automatically.
```

While works well with Redis 7.0.8:

```
127.0.0.1:6379> XGROUP CREATE test test 0 MKSTREAM
OK
```

BTW, if the group already exists then Redis provides the following output:

```
(error) BUSYGROUP Consumer Group name already exists
```

Just mentioning because when implementing queue based on Redis stream many implementations rely on the BUSYGROUP prefix to detect that group already exists and the error may be ignored.

Seems like in 5 of 13 failures above the error is the same and may come from the same thing.

**Comment by Abhra303** [comment]
Hey @romange, would like to work on the issue. Could you please assign it to me?
