### ISSUE TITLE
Release --version

### ISSUE THREAD

**Issue by IlanFrumer** [dragonflydb/dragonfly#116]
![image](https://user-images.githubusercontent.com/3116399/172437800-778b92ba-e4d0-44a3-a0d6-99553008bc43.png)

When packaging a release, the version should be a fixed version rather than a git tag.

https://github.com/dragonflydb/dragonfly/blob/4d276c7ef0a1f04c3efddab7c10bca1e8ee820c2/src/server/dfly_main.cc#L151

**Comment by romange** [comment]
@IlanFrumer !!! What's up, man?!!! Long time no heard! Remember that you have been on my wedding?!!

**Comment by romange** [comment]
@IlanFrumer  that's ? just a thumbs up?! You probably did not like my buffet 😛 

Anyway, fixed in https://github.com/dragonflydb/dragonfly/releases/tag/v0.2.0
