### ISSUE TITLE
implement ZINTERCARD 

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#1188]
Please see https://redis.io/commands/zintercard/

There is undocumented feature for ZINTERCARD - it can intersect a regular set (SADD) with sorted set (ZADD).

1. It should be able to intersect multiple zsets and provide the final cardinality number.
2. It should be able to intersect sets and zsets, in fact it can intersect sets without zsets.

**Comment by romange** [comment]
related to https://github.com/dragonflydb/dragonfly/issues/1099

**Comment by daniel-shimon** [comment]
Hi!
Is there a similar undocumented feature in ZINTER? (e.g. with a default score of 1)
If so, should ZINTER’s behavior change as well to allow this?

**Comment by romange** [comment]
Yes, I checked it manually:
```
127.0.0.1:6379> sadd s1 a b c
(integer) 3
127.0.0.1:6379> zadd z1 1 a 2 b
(integer) 2

127.0.0.1:6379> zinter 1 z1
1) "a"
2) "b"
127.0.0.1:6379> zinter 2 z1 s1
1) "a"
2) "b"

127.0.0.1:6379> zinter 1 s1
1) "a"
2) "b"
3) "c"
```

**Comment by pawelKapl** [comment]
Is this smth i can try to implement or might be too tough for now?

**Comment by romange** [comment]
It's being in development right now. I will look for something soon :)

**Comment by pawelKapl** [comment]
Ok, thanks a lot!
