### ISSUE TITLE
Dragonflydb requires an internet connection

### ISSUE THREAD

**Issue by gaby** [dragonflydb/dragonfly#1198]
I'm current in the process of replacing redis with dragonflydb until I ran into the issue where it doesnt work unless there's an internet connection...?

During startup it tries to do DNS resolution regarding my IP which throws an error, it also tries reaching out to check version.dragonflydb.io which also fails and throws a warning.

Visiting localhost:6379 timesout because the default html page serve is using CDN sources for fonts, and trying to download the logo for dragonfly.

The redis client fails to connect with a timeout after this.

**Comment by romange** [comment]
Dragonfly does not require an internet connection. It uses it if it exists but can proceed otherwise. The proof:
```sh
> docker run --name df --network=none   docker.dragonflydb.io/dragonflydb/dragonfly
```
![image](https://github.com/dragonflydb/dragonfly/assets/3674760/eb59e713-ba01-435d-bbcb-7137dc247828)

and then:

![image](https://github.com/dragonflydb/dragonfly/assets/3674760/e1f342d9-e2f6-4a90-9af9-65d2b38d4cd7)

**Comment by gaby** [comment]
@romange Found the issue... I'm using testcontainers-go to test against Redis. I set the WaitForLog to "listening on port" message. For some reason when that message gets printed the port doesnt actually accepts connections, it's not until the one regarding dfly_main version check that I can actually connect/test.

Shouldnt dragonfly accept connectios as soon as it says "listening on port 6379"?

**Comment by romange** [comment]
What if you pass `--noversion_check` ? Does it solve the issue?

**Comment by gaby** [comment]
@romange Yes, that solves the problem. When that flag is passed the server actually starts listening when the log "listening on port 6379" is printed. Without that flag the server will not start listening on port `6379` until after when the `version.dragonflydb.io:443` error shows up.

My guess is that it has something to do with the logic here: https://github.com/dragonflydb/dragonfly/blob/main/src/server/dfly_main.cc#L385

**Comment by gaby** [comment]
@romange Thoughts?

**Comment by romange** [comment]
The problem with be fixed in the next version. Seems that meanwhile, you have the workaround.

**Comment by gaby** [comment]
@romange Thanks!!! 😁
