### ISSUE TITLE
Add versioning information to the replication handshake.

### ISSUE THREAD

**Issue by royjacobson** [dragonflydb/dragonfly#1216]
We want the replication protocol to be future compatible. For that, we'd like to add version information to the protocol.

My rough idea of a plan -

1. Add an enum with protocol versions that we could extend in the future. The versions will be specific to the replication protocol and not to the dragonfly release cycle.
2. Make the client send a `REPLCONF VERSION {CLIENT_VERSION}` command after it detects a dragonfly master.
  a. If it gets an error, the master version is pre-historic.
  b. Else, the master sends back its version.
3. The server assumes that the client has a pre-historic version be default until it gets the version configuration command.

**Comment by chakaz** [comment]
I guess that the train has already left the station for this, but...
Is it too late to use protocol buffers for replication?
I'm asking because protobufs solve a very difficult problem (backward and future compatibility) in a very elegant way, which otherwise requires lots of custom and error prone code, that's also extremely hard to test thoroughly.
Perhaps new versions could use protobufs, while "pre-historic" as you call them ;) could use the existing one?
I imagine the answer is a simple "no", but you know, wishful thinking :)

**Comment by romange** [comment]
@chakaz  protocol buffers indeed help with schema migration at scale. Currently, for this specific use-case I do not feel it justifies bringing them in: 1. this breaks the philosophy of text-based Redis protocol 2. it introduces a pretty heavy 3rd party dependency. 
Moreover, with this example, older Dragonfly masters won't break upon accepting an unknown ACK command, but their behavior will break the replication stream sent back to replica. This is not something protobufs would fix anyway.

**Comment by romange** [comment]
btw, a cool protobuf project would be - to replace our json implementation with serialized protobufs:
1. json stores key names and the json object is wasteful in memory
2. protobufs have a predefined schema so it's not straightforward to use them to parse json values. However, I think it's possible to develop a heuristic that given a json object, derives its schema, finds a pb descriptor that potentially covers that schema and uses the descriptor to create a pb instance. if there is no fit for a pb descriptor in the registry, dynamically creates a new pb descriptor based on the json schema.

**Comment by chakaz** [comment]
I assumed that it's not a great git here, but I thought that the replication protocol is already binary?
Of course my proposal was to use protobufs post-handshake (to be backward compatible), but yeah, it was a slim shot :)
