### ISSUE TITLE
Replication not consistent when running flushall on full sync phase

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#1231]
When creating a snapshot in master for replica if flush all command is executed we write the command to all shard flows.
On replica side rdb loader reads the journal command flush all and executes it.
Because we are reading rdb data per shard and execute the journal changes in each shard, we execute the flushall on replica many times without sync with other rdb loaders and this can cause flushing data which should exist and causes replica to have some missing entries.

journal shard data example:
shard1 data
set x 1
flushall
set x 2

shard2 data
set y 1
flushall
set y 2

in the above example running the flushall of shard2 data can be after running set x 2 of shard 1
therefore the replica will not be consistent with master

**Comment by romange** [comment]
It's weird that flushall is hard to support because what it says effectively to replica is that full sync should be dropped. I understand that it requires a special handling but it is not a hard case.
