### ISSUE TITLE
docker image: missing libxml2

### ISSUE THREAD

**Issue by martadinata666** [dragonflydb/dragonfly#1238]
**Describe the bug**

**To Reproduce**
1. Pull new dragonfly image
2. Start container
3. Container fail start
4. dragonfly: error while loading shared libraries: libxml2.so.2: cannot open shared object file: No such file or directory

**Expected behavior**
Container startup correctly

**Screenshots**

**Environment (please complete the following information):**
 - OS: ubuntu 22.04
 - Kernel: # Command: `Linux homelab 6.3.1-x64v1-xanmod1 #0~20230503.cf0c658 SMP PREEMPT_DYNAMIC Wed May  3 04:32:32 UTC  x86_64 x86_64 x86_64 GNU/Linux`
 - Containerized?: [Docker Compose]
 - Dragonfly Version: [1.3.0]

**Reproducible Code Snippet**
```
# Minimal code snippet to reproduce this bug
```

**Additional context**

**Comment by Pothulapati** [comment]
Thanks @martadinata666 for raising the issue! We also are adding tests (i.e #1240) to not fall into these types of bugs in the future!

**Comment by Pothulapati** [comment]
@martadinata666 Image is updated! You should be able to run `v1.3.0` without any issues now! Thanks!
