### ISSUE TITLE
admin port for dflycluster commands

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#1267]
Allow dflycluster commands run only using admin port

**Comment by adiholden** [comment]
@chakaz I believe we must move all cluster family tests to the regression tests in order to check the port and fail if its not admin port

**Comment by chakaz** [comment]
I think it would be much better to introduce some kind of a test-hook to allow running admin commands.
I'm not saying we should _only_ do that, but it doesn't sound very hard and would still allow to implement unit tests.
