### ISSUE TITLE
Add bloom/cuckoo filter support

### ISSUE THREAD

**Issue by e271828-** [dragonflydb/dragonfly#1275]
**Is your feature request related to a problem? Please describe.**
The redis bloom module is very popular. Probabilistic data structures are required for many problems.

**Describe the solution you'd like**
Basic bloom / counting bloom support at minimum. Ideally full compatibility with redis bloom module.

**Describe alternatives you've considered**
Could do lua bitfields, but bitfield isn't supported either and would be slower.

**Comment by e271828-** [comment]
@romange any plans on this?

**Comment by romange** [comment]
could you provide some context how you use this functionality and why you prefer using Dragonfly with this over Redis?

**Comment by e271828-** [comment]
> could you provide some context how you use this functionality and why you prefer using Dragonfly with this over Redis?

Because sharding redis is inefficient in scenarios where scale-up would suffice.

If you're trying to be compatible with Redis, you'll need to either support modules or build the most popular ones into core. Probabilistic data structures have thousands of applications.

**Comment by romange** [comment]
Our architecture is entirely different that of Redis, so we can not support Redis Modules.
Supporting Redis Bloom filter is currently a low priority and not scheduled for 2023.

**Comment by e271828-** [comment]
OK, thanks for letting us know. Sounds like dragonfly is not going to be a great fit for many use cases this year.

**Comment by jbergstroem** [comment]
I would like to see bloom filter support in dragonflydb as well. Can we reopen this?

**Comment by e271828-** [comment]
@romange FYI.

**Comment by romange** [comment]
The Bloom filter library is pretty big. Do you have specific APIs/commands in mind?

**Comment by e271828-** [comment]
> The Bloom filter library is pretty big. Do you have specific APIs/commands in mind?

Supporting basic Bloom commands would be a good start:
`BF.RESERVE, BF.ADD, BF.EXISTS, BF.MADD, BF.MEXISTS`

I'd suggest adding a modern [counting cuckoo filter](https://arxiv.org/abs/2003.03801) as well.

```
> BF.RESERVE bikes:models 0.001 1000000
OK
> BF.ADD bikes:models "Smoky Mountain Striker"
(integer) 1
> BF.EXISTS bikes:models "Smoky Mountain Striker"
(integer) 1
> BF.MADD bikes:models "Rocky Mountain Racer" "Cloudy City Cruiser" "Windy City Wippet"
1) (integer) 1
2) (integer) 1
3) (integer) 1
> BF.MEXISTS bikes:models "Rocky Mountain Racer" "Cloudy City Cruiser" "Windy City Wippet"
1) (integer) 1
2) (integer) 1
3) (integer) 1
```

**Comment by romange** [comment]
bf.add is supported in v1.16.0. persistence support is coming for the next version

**Comment by e271828-** [comment]
@romange thanks! What about a counting filter? Can split this issue into a new one.

**Comment by romange** [comment]
@e271828-  we currently do not have plans to implement the countring filter. We may consider contributions from the community.

**Comment by romange** [comment]
btw, we support hyper log log api.

**Comment by e271828-** [comment]
> btw, we support hyper log log api.

@romange HLL cannot replace CBF/CCF. If you need membership, deletion, or exact counts (all common requirements) then you will still be out of luck.

**Comment by romange** [comment]
I know Professor Roy Fridman and I agree it's super interesting to implement those data structures. I guess we will have to wait for someone who is willing to use his c++ skills and contribute for this task 🤷🏼
