### ISSUE TITLE
/sys/fs/cgroup/memory/memory.limit_in_bytes not used

### ISSUE THREAD

**Issue by hermanbanken** [dragonflydb/dragonfly#1292]
**Describe the bug**
#1109 added support for reading memory limits in containers. The docs for `UpdateResourceLimitsIfInsideContainer` state that there are 3 locations that are looked at, however, it seems like only the second documented location is implemented.

In our GKE clusters running ContainerOS we only have the last one, `/sys/fs/cgroup/memory/memory.limit_in_bytes` available and therefore our DragonflyDB instance defaults to using 22GiB memory instead of the limit set at 1GiB. 

You can see how this can become a problem.

**To Reproduce**
1. Run GKE with Linux 5.10.162+
2. Set a resource limit to the pod of 1337 MiB
3. Test that `/sys/fs/cgroup/memory.max` does not exist
4. Test that `/sys/fs/cgroup/memory/memory.limit_in_bytes` exists
5. Start DragonflyDB

**Expected behavior**
Should start with configured limit.

**Screenshots**
![image](https://github.com/dragonflydb/dragonfly/assets/791189/1206e7c1-4742-4b51-81c0-ddc671242b77)

**Environment (please complete the following information):**
 - OS: gke-12411-gke1000-cos-97-16919-235-30-v230314-c-pre (COS 97)
 - Kernel: `5.10.162+ #1 SMP Wed Mar 1 15:57:11 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
 - Containerized: Kubernetes GKE 1.24.11-gke.1000
 - Dragonfly Version: 1.2.1

**Comment by romange** [comment]
As workaround - you can set `maxmemory` manually.

**Comment by hermanbanken** [comment]
Is that easy to do with the operator?
