### ISSUE TITLE
implement ZDIFF

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#1311]
Spec: https://redis.io/commands/zdiff/

**Comment by coderr01** [comment]
@romange i would like to contribute on that issue ? Can you please elaborate ?

**Comment by romange** [comment]
sorry, it has been assigned internally 🤷🏼

**Comment by coderr01** [comment]
@romange great

**Comment by coderr01** [comment]
@romange  let me know if there is anything for me to contribute
