### ISSUE TITLE
Handle remove slot from ownership with replica

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#1320]
When executing `DFLYCLUSTER CONFIG` we check for slots that are removed from node ownership and start a fiber to delete this slots data from server. When starting to delete the data we create a new db version, which only entries with version < new version are deleted. The reason for this is that we could get another config update to add the slots to the node ownership, so we want to delete slots data that was inserted before the new config update.
On replica when executing `DFLYCLUSTER CONFIG`  we should not delete slots data for slots that are removed from ownership. This is because the update config might arrive to replica in delay from master and this might cause deleting entries which should not be deleted.
For example:
master
t1: config - slot 1,2
t2: config - slot 1
start delete slot 2 entries
t3: config - slot 1,2
t4: set x y (x is in slot 2)

replica:
t1: config - slot 1,2
t3: config - slot 1
t4: set x y (replicated from master)
t5: config - slot 1,2

In this example if we deleted slot 2 entries after receiving t3 config we will delete x key entry.

To handle slot deleting on replica, we will send to replica "replica flushslots  [slot ids]" command. This command will be send from master on the config command when slots are removed from ownership. It will be sent on all shards, same as flushall. On replica side we will wait for all replica flushslots commands, as we do on flushall, and execute it once.

**Comment by chakaz** [comment]
An easier solution, which on one hand is less error prone with fewer edge cases and easier to program, but on the other hand is definitely more resource consuming, is to just replicate the deletion commands from the master, as if they were regular deletions.
I'm not saying we should definitely go for it, but it is a simpler solution that might be a good middle-ground, at least initially.
