### ISSUE TITLE
Check slot id on config set is less then Max slot

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#1322]

**Comment by chakaz** [comment]
Is this not what we do here?

https://github.com/dragonflydb/dragonfly/blob/e5b5e35e55424df3c70a7d6db5b1fc68395ef611/src/server/cluster/cluster_config.cc#L82

I see that we don't have a unit test for that, I can and should add one.

**Comment by adiholden** [comment]
Oh sorry, it was not clear from the code. I was looking for comparison to kMaxSlotNum.
Will close the issue
