### ISSUE TITLE
Add XTRIM support

### ISSUE THREAD

**Issue by andydunstall** [dragonflydb/dragonfly#1332]
Add `XTRIM` support - which is needed to support BullMQ (see https://github.com/dragonflydb/dragonfly/issues/782)

(I couldn't see any existing issue for `XTRIM` so adding a new issue)

**Comment by romange** [comment]
Yes, please Andy - will assign later

**Comment by ThatOneCalculator** [comment]
This issue can probably be closed now due to #1337 (nice) being merged
