### ISSUE TITLE
Search: Basic document scoring

### ISSUE THREAD

**Issue by dranikpg** [dragonflydb/dragonfly#1345]
Compute document scores and support the most basic scoring functions (like tf/idf https://en.wikipedia.org/wiki/Tf%E2%80%93idf)

**Comment by romange** [comment]
is it done @dranikpg  ?

`__vector_score` is not supported: `FT.SEARCH ann * =>[KNN 10 @vector $BLOB EF_RUNTIME 10] NOCONTENT SORTBY __vector_score LIMIT 0 10 PARAMS 2 BLOB FOO `

**Comment by dranikpg** [comment]
it works, but you have to specify a name for the score field explicitly

**Comment by dranikpg** [comment]
Not planned for now
