### ISSUE TITLE
Script for creating dragonfly cluster

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#1371]
The script will create a cluster of X shards, X masters and X*Y replicas. 
It will configure nodes ports and log dir. It will configure the nodes with dflycluster config command, and will call replicaof command to configure replicas (if exist, i.e Y can be 0).
The script will get input from user to start the cluster or stop the cluster.

**Comment by adiholden** [comment]
@chakaz hi, anythink to add to the script or we can close this issue?

**Comment by chakaz** [comment]
There's migration of data that we can add, but I guess there's no point in keeping the issue opened until that's implemented. So yeah, let's close it for now.
