### ISSUE TITLE
Why does not the default snapshot strategy remove the old and useless dump file?

### ISSUE THREAD

**Issue by XiaooLei** [dragonflydb/dragonfly#1377]
### Discussed in https://github.com/dragonflydb/dragonfly/discussions/1353

<div type='discussions-op-text'>

<sup>Originally posted by **XiaooLei** June  5, 2023</sup>
I am trying to use dragonfly in our systems, but when I was configuring it, I found the the default strategy just don't remove the old snapshot files even if new snapshot file is generated, and as time goes, the snapshot files grows so big and takes up so much storage space. this is different than the Redis snapshot strategy. I finally managed to make it align to Redis by adding command args '''--dbfilename dump.rdb --nodf_snapshot_format''' , But I still can not  figure out why dragonfly team use such a seeming useless snapshot strategy? Really appreciated if my question could be answered</div>

**Comment by romange** [comment]
@XiaooLei why did you specify `--nodf_snapshot_format`?

**Comment by adiholden** [comment]
@XiaooLei by default dragonfly will use filename with timestamp for saving snapshot.
If you dont want to have snapshot file per timestamp you can use the flag --dbfilename <filename> f.e --filename dump (dont add file extension).
Here you can see the documentation  https://www.dragonflydb.io/docs/command-reference/server-management/save

**Comment by XiaooLei** [comment]
> @XiaooLei why did you specify `--nodf_snapshot_format`?

because the snapshot file take too much storage space, I tried make the snapshot file to be the same as redis, and by specifing --nodf_snapshot_format and --dbfilename dump.rdb, it worked.

**Comment by romange** [comment]
yes, we could flip the default and avoid timestamps. I am opening a separate issue for that and closing this one.
