### ISSUE TITLE
Add replicaof command flag

### ISSUE THREAD

**Issue by ut0mt8** [dragonflydb/dragonfly#1381]
as discussed on slack for starting replication from now we need to interact with the redis protocol to set the master.
for auto starting replication we need something like --slaveof= flag. 

(even if some ugly hack with systemd post start is possible)

**Comment by romange** [comment]
Lets make it `--replicaof=foo:port`

**Comment by royjacobson** [comment]
> Lets make it `--replicaof=foo:port`

Just have to make sure we parse IPv6 addresses correctly (see https://softwareengineering.stackexchange.com/questions/311413/how-should-we-represent-an-ipv6-address-with-port-number-in-text)

**Comment by Kelvinyu1117** [comment]
I can help to implement this task.
What kind of argument format do we want to support? I can think of the followings:
* `--replicaof=<ipv4>:port`
* `--replicaof=[<ipv6>]:port`

**Comment by ut0mt8** [comment]
Ideally I think the both seems needed 👍

**Comment by adiholden** [comment]
@talbii Note: we will need to support setting this flag from config set command

**Comment by romange** [comment]
@adiholden  it's not clear what's the expected behavior for this. Lets first check internally if it's really required.

**Comment by talbii** [comment]
Sounds completely reasonable, also won't be a problem to implement in code. I'll do this tomorrow
