### ISSUE TITLE
cannot use lua scripting on slave replica

### ISSUE THREAD

**Issue by ut0mt8** [dragonflydb/dragonfly#1391]
Dragonfly lastest version.

On a replica which is read only (and it's perfectly fine) we cannot use lua scripting. For example the simple example in the redis doc is not working:

127.0.0.1:6379> EVAL "return redis.call('SET', KEYS[1], ARGV[1])" 1 foo bar
(error) ERR Error running script (call to d8f2fad9f8e86a53d2a6ebd960b33c4972cacc37): @user_script:2: -READONLY You can't write against a read only replica.

this is a blocker for adoption for us (we heavily rely on this)

**Comment by romange** [comment]
@ut0mt8  running `SET` will still not work on read-only. But `GET` will.
