### ISSUE TITLE
support redis v7 rdb format

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#1403]
currently Dragonfly supports upto redis RDB upto v6. 
v7 is out for a year now. it's about time we support it as well. See `LoadSmall6` test in rdb_test on how we test v6 compatibility.

Basically, I saved an rdb file using redis-server v6 that contained all the data structure types. See  redis6_small.rdb.
Similarly with v7 - I expect to have `redis7_small.rdb` that contains all the OSS data structures and some of them with different encodings.

**Comment by kostasrim** [comment]
For reference on what changed: 
[version 10](https://github.com/redis/redis/commit/02fd76b97cbc5b8ad6f4c81c8538f02c76cbed46)
[version 11](https://github.com/redis/redis/commit/4e472a1a7fc0dc2c7da2b48ac7342e9385b4f92a)

Both redis v7

**Comment by romange** [comment]
@kostasrim I do not want to support listpack runtime encoding for sets. Therefore, we should only support on-disk `RDB_TYPE_SET_LISTPACK` type and to convert it to Dragonfly set data structure. We won't use RDB_TYPE_SET_LISTPACK  to store sets. With ziplist - we already do the conversions so I suspect this part is mostly a noop but I may be mistaken.
