### ISSUE TITLE
Unix Socket cannot be set in "dragonfly.conf" only in "dragonfly.service"

### ISSUE THREAD

**Issue by dgaastra** [dragonflydb/dragonfly#1414]
**Describe the bug**

--unixsocket /var/run/dragonfly/dragonfly-server.sock

[1] Cannot set this in "/etc/dragonfly/dragonfly.conf" only in "/etc/dragonfly/dragonfly.service": which is not desirable

**To Reproduce**

Set above "--unixsocket /var/run/dragonfly/dragonfly-server.sock" in above files and see result
**Expected behavior**
Things to work when setting  "/etc/dragonfly/dragonfly.conf" 

**Screenshots**
```
░░ The job identifier is 1773.
Jun 15 13:56:11 webbu dragonfly[3166]: ERROR: Unknown command line flag 'unixsocket /var/run/dragonfly/dragonfly-server.sock'
Jun 15 13:56:11 webbu systemd[1]: dragonfly.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
```

**Environment (please complete the following information):**
Debian 11.7

**Comment by admtech** [comment]
The correct command for the config file is:

--unixsocket=/var/run/dragonfly/server.sock

You have forgotten the = sign. Then it works

under Ubuntu this works for me (sample):

```
--pidfile=/var/run/dragonfly/dragonfly.pid
--log_dir=/var/log/dragonfly
--dir=/var/lib/dragonfly
--version_check=true
--save_schedule=*:00
--cache_mode=true
--bind=127.0.0.1
--dbfilename=database
--unixsocket=/var/run/dragonfly/server.sock
--primary_port_http_enabled=false
--timestamp_in_logfile_name=false
```

**Comment by romange** [comment]
working as expected

**Comment by dgaastra** [comment]
Thanks for the = sign tipp. I was used to the Redis config file format. It would be great if DragonFlyDB had something like this with good documentation.
