### ISSUE TITLE
Master/Slave replication with TLS not working.

### ISSUE THREAD

**Issue by ccycv** [dragonflydb/dragonfly#1418]
**Describe the bug**
Replication does not work with TLS enabled.

**To Reproduce**
1. Enable replication, everything works.
2. Enable TLS, replication stop working, if I try to reconnect I get the following error, even with via domain name :
```
127.0.0.1:6379> REPLICAOF 10.13.1.2 6379
(error) ERR could not connect to master: Software caused connection abort
```
3. Connecting from local with redis-cli, only works with parm --insecure, even if the certificates are signed.

**Expected behavior**
Expected to work.

**Screenshots**

Configuration
![image](https://github.com/dragonflydb/dragonfly/assets/23322009/70a951ac-57bf-4092-8078-3fd8e3ee93d6)

Connection via redis-cli
![image](https://github.com/dragonflydb/dragonfly/assets/23322009/2cfc2706-431a-4a90-b256-594db4e2f2f2)

Certificate validation
![image](https://github.com/dragonflydb/dragonfly/assets/23322009/86508ddf-f4ae-414d-bbde-789ebe787c31)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - Kernel: 5.15.0-73-generic # Command: `uname -a`
 - Containerized?:  Cloud Instance, VMware
 - Dragonfly Version: dragonfly v1.3.0-f80afca9c23e2f30373437520a162c591eaa2005

**Comment by kostasrim** [comment]
Hi @ccycv, once my last PR #1525 gets merged you should be able to have tls over replication. Furthermore, my other PR's introduced non-tls connections over admin port (on tls configured dragonfly) and two new flags to allow validation of certificates (and drop the `insecure` flag from redis-cli).
