### ISSUE TITLE
chore(docs): Enforce [a-zA-Z0-9-] regex on doc filenames

### ISSUE THREAD

**Issue by ryanrussell** [dragonflydb/dragonfly#142]
Hey @romange 

I have an OCD thing about URI's to make them easy to canonicalize and believe dashes **should** be the only non-alphanumeric character allowed in a URI.

This would mean a one-time change `/docs/api_status.md` -> `/docs/api-status.md` and updating links in the codebase.

This is MUCH easier to do now than wait until more people are linking your `api_status.md` version.

If you agree on this change, give it a thumbs up... if not just thumbs down and close.

Ryan

**Comment by romange** [comment]
It seems that underscores are allowed in urls, so why dashes are better?

It's not that I have a strong opinion about this but I am used to name c++ filenames with underscores (Google habits). But now I see that google style guide allows dashes as well: https://google.github.io/styleguide/cppguide.html#File_Names

In short, I do not mind changing docs but c++ naming will stay with underscores.

**Comment by ryanrussell** [comment]
This one is just an opinion. Easier to force a single separator(reduces human error in linking and getting multiple versions and broken links), and just believe a dash reads better in google results...

Will see what exists to automate the filename regex checks to be future-proof `/docs/` files

**Comment by romange** [comment]
Hey @ryanrussell, how can we enforce file naming in docs dir?

**Comment by ryanrussell** [comment]
Hey, let me put a couple cycles on this.

If I can't find a clean solution, I will close and keep it manual.

**Comment by ryanrussell** [comment]
This is not a distinct issue to DF. Closing for housekeeping.
