### ISSUE TITLE
rdb_test is sporadically failing

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#1424]
See https://github.com/dragonflydb/dragonfly/actions/runs/5298815352/jobs/9591391349?pr=1422#step:7:3187

It's always this assertion and always the same number 9168.

**Comment by chakaz** [comment]
FWIW I've seen different numbers, but all deltas (by delta I mean `10,000 - X`, where `X` is the number) are dividable by 32...

**Comment by romange** [comment]
another one here: https://github.com/dragonflydb/dragonfly/actions/runs/5312219736/jobs/9616429637#step:7:4043
also 9168

**Comment by romange** [comment]
it could be that alpine increases the likeness of the bug. so worth checking if it reproduces it

**Comment by chakaz** [comment]
Yes, that is exactly my plan :)
