### ISSUE TITLE
chore: automatically bump `version` and `appVersion` in Helm chart when new stable release is published

### ISSUE THREAD

**Issue by TamCore** [dragonflydb/dragonfly#144]
As the title says, the Helm chart's Chart.yaml should be automatically updated when a new stable dragonfly release is published

This is basically a low hanging fruit for potential first time contributors. Would otherwise take care of it, once I'm near a computer again. Might take a while however.

**Comment by romange** [comment]
Where are you going? :) Summer vacation?

**Comment by ryanrussell** [comment]
@TamCore 

Bonus on this task for including the bash commands for a <5 minute Helm Quick Start... 

I was going to modify your `README`.. but saw it's auto-generated...

**Comment by TamCore** [comment]
@romange just a few relaxed offline-ish days around town with my girlfriend :) 

@ryanrussell for the README I used https://github.com/norwoodj/helm-docs. That also supports templating, to add additional info :)
