### ISSUE TITLE
Redis Insight calls JSON keys with a dot instead of the root $

### ISSUE THREAD

**Issue by admtech** [dragonflydb/dragonfly#1456]
**Describe the bug**
Redis Insight (v2) sets the following command to read a Json Key: "JSON.GET" "key" "." 
It sets a dot "." as root path and not a "$". This generates a syntax error with Dragonfly DB and no output in Insight (undefined).

This is probably not a real bug of Dragonfly DB, but for compatibility reasons it should work. 

**To Reproduce**
1. open redis-cli with fireflydb (version 1.4)
2. `JSON.SET doc $ '{"a":2}'`
3. `JSON.GET doc .`
4. ERR syntax error appears

.. or Open Redis Insight (v2), start the Profiler and get a json key.

![redis_insight_v2](https://github.com/dragonflydb/dragonfly/assets/5912839/c49f59a9-f2a3-4b09-b60f-bd456bb2e1ed)

**Expected behavior**
For compatibility reasons and the fact that Redis Insight is used by many developers, the dot should work and be considered as root $. 

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Dragonfly Version: 1.4

**Comment by romange** [comment]
but we are DragonflyDB, not Firefly. Completely different insect! 
![image](https://github.com/dragonflydb/dragonfly/assets/3674760/b1967d16-eeec-4de2-aecc-3de9f32ed4a6)

**Comment by admtech** [comment]
I'm so sorry, how could I have got it wrong? I have corrected it above. ;-)
