### ISSUE TITLE
runtime error: member call on null pointer of type 'struct Journal'

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#1469]
```
  int64_t lag =
          shard->journal()->GetLsn() - info.second->flows[shard->shard_id()].last_acked_lsn;
```

![image](https://github.com/dragonflydb/dragonfly/assets/3674760/8e7934a5-a1cc-4fa0-8ca1-02d748f04c7b)

**Comment by royjacobson** [comment]
Ah, the calculation needs to be restricted for replicas who haven't reached stable sync yet. will submit a patch tomorrow :)
