### ISSUE TITLE
Introduce a test that covers the replication use-case via the admin port

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#1470]
we have 100% reproducible deadlock bug when replica connects to a master via admin port.

the problem is that one of the commands in master (migrate) requires a listener to do the thread migration.
We use hardcoded "main_listener" which is incorrect of course if we connect via admin.

I am going to fix a bug, but we need test coverage for admin port replication. Moreover, we need to scan where we use `main_listener` in the codebase and see if it makes sense for connections coming via admin_listener or uds listener etc

**Comment by adiholden** [comment]
When I run locally the replication with admin port it passes . What is the flow that is calling DFLY THEAD <id> ? I dont find it ..

**Comment by adiholden** [comment]
I dont find from which flow we Call the DFLY THREAD command.. can you share where is this call coming from?

**Comment by romange** [comment]
we do not call it, it's a debug command for us to test thread/connections interactions.
