### ISSUE TITLE
(zset) Inconsistent Output between Redis & DF 

### ISSUE THREAD

**Issue by ugcodrr** [dragonflydb/dragonfly#148]
While messing around with sorted sets in dragonfly, I have noticed some inconsistencies that result in an error on dragonfly and work perfectly on Redis.

``` 
EVAL "return redis.call('zadd', 'hello', 1, 'world')" 0
``` 
Running the above results in `(error) ERR script tried accessing undeclared key` from dragonfly. The expected result happens with Redis (creates a sorted set titled, `hello` with member `world` with a score of `1`).

Another thing I found is that sometimes it doesn't add members to a sorted set. It would keep telling me that `ERR value is not a valid float`. I don't entirely know the exact cause of this problem, all I know for sure is that if a member starts with a number, it will return this error. However, I have seen a few cases where it doesn't start with a number and errors.
```
EVAL "return redis.call('zadd', KEYS[1], 1, '9fe9f1eb-6368-4453-b6f9-64e8856df558')" 1 test
``` 
This behavior is weird because it doesn't occur when directly using `zadd` in the CLI, but happens when using ioredis & eval.

**Comment by romange** [comment]
Thanks for reporting this @ugcodrr 
1. DF implements the stricter spec of Redis eval command where you must declare your keys in advance. so, you need to call it like this `EVAL "return redis.call('zadd', 'hello', 1, 'world')" 1 hello`

2. Regarding "not a valid float" - seems like a bug I would like to get down to it.
   Can you, please, run dragonfly as `./dragonfly --vmodule=main_service=2 --logbuflevel=-1` run your problematic example via ioredis till you get not a valid float response and then attach here file `/tmp/dragonfly.INFO` ?

**Comment by ugcodrr** [comment]
> 1. DF implements the stricter spec of Redis eval command where you must declare your keys in advance. so, you need to call it > like this `EVAL "return redis.call('zadd', 'hello', 1, 'world')" 1 hello`

Makes sense, only found out about it because of the latter issue.
> 2. Regarding "not a valid float" - seems like a bug I would like to get down to it.
> Can you, please, run dragonfly as `./dragonfly --vmodule=main_service=2 --logbuflevel=-1` run your problematic example via 
> ioredis till you get not a valid float response and then attach here file `/tmp/dragonfly.INFO` ?

Happens almost instantly, [dragonfly.txt](https://github.com/dragonflydb/dragonfly/files/8901477/dragonfly.txt)

**Comment by romange** [comment]
@ugcodrr  from the log it seems you did not run any eval statements, only ZADD.  Are you sure it's a log from a faulty run?
Do you have maybe a shot code that reproduces it?

**Comment by ugcodrr** [comment]
Oh sorry about that, I found out about this issue while running my redis testing code. I only went to the eval as a way to compact the code to potentially share here for another question regarding sorted sets.

Here is the eval one,
[dragonflyEval.txt](https://github.com/dragonflydb/dragonfly/files/8903673/dragonflyEval.txt).

**Comment by romange** [comment]
It's all good, @ugcodrr  - i found the bug. the next version will have the fix. Thanks again for reporting it!
