### ISSUE TITLE
Java Integration

### ISSUE THREAD

**Issue by aabolfazl** [dragonflydb/dragonfly#1499]
**Java Integration.**
Hey Dragonfly owners, would you mind writing a client for this library in Java? or will you support this implementation if someone like to do it?

**Use in JVM-based server framework**
As you know Java and JVM-based languages have many powerful web frameworks, I think it will be helpful if we can provide a way to use this library in these frameworks with a standalone Client like [spring-data-redis](https://github.com/spring-projects/spring-data-redis).

**Comment by kostasrim** [comment]
Hi @aabolfazl and thank you for opening an issue.

Dragonfly is redis API compatible (we don't yet support all the currently existing commands, but most of them should be available) which means that third party client libraries should work outside of the box. 

Did you have any issue using Dragonfly with any of the already existing client libraries?

**Comment by brewagebear** [comment]
What you said above seems to be linked to [spring-data-redis](https://github.com/spring-projects/spring-data-redis) api.

i will actually test it after building a cluster in AWS.
If there is a problem in the future, I will register the issue.

**Comment by brewagebear** [comment]
@aabolfazl  

I am also a Java developer, so I became interested in the question you wrote. 
And i did a brief test with reference to what  @kostasrim said above.

repository : https://github.com/brewagebear/counter-api 

### sample code 

+ CacheService.java 

```java
@Service
public class CacheService {

    @CachePut(cacheNames = "namespace", key="#namespace")
    public int updateNamespace(String namespace, Map<String, String> data) {
        return 1;
    }
}
```

+ CacheController 

```java
@RestController
@RequestMapping("/api")
public class CacheController {

    private final CacheService cacheService;

    public CounterController(CacheService cacheService) {
        this.cacheService = cacheService;
    }
    
    @GetMapping("/test")
    public void cache() {
        cacheService.updateNamespace("test", Map.of("test", "1"));
    }
}
```

### result

<img width="1217" alt="Screenshot 2023-07-06 at 17 57 16" src="https://github.com/dragonflydb/dragonfly/assets/22961251/f03328e2-f7db-4f79-973e-d68a90e645fa">

It's a very simple test, so I think I need to check if other APIs are compatible well, but if there's a problem with this part, I'll check and create an issue.

**Comment by romange** [comment]
To conclude - we support Redis client libraries out of the box. Feel free to open a specific issue if you stumble upon any problem.
