### ISSUE TITLE
Use async DNS in replication

### ISSUE THREAD

**Issue by royjacobson** [dragonflydb/dragonfly#1510]
> Do you think this might be a good chance to use Helio's resolve DNS?
> (it's better because it doesn't use blocking APIs, and also saves this messy function)

_Originally posted by @chakaz in https://github.com/dragonflydb/dragonfly/pull/1507#discussion_r1249705197_

**Comment by chakaz** [comment]
2 notes on this:
1. While here, I'd also remove the need to explicitly call `ResolveMasterDns()`. IMHO it should be implicit within `ConnectAndAuth()` (and indeed it is always and unconditionally called before that)
2. I am working on refactoring the code around there, so I would actually **not** do anything on this front ATM

**Comment by chakaz** [comment]
Re/ (1) above: I was actually mistaken, in that there is a call to `ConnectAndAuth()` that's _not_ resolving DNS: https://github.com/dragonflydb/dragonfly/blob/12c893085c0d112db101b48cc39c344f4a306ab9/src/server/replica.cc#L621

However I do not think it's a big deal to "resolve" a DNS again (which is already in the form of an IP so I guess it's a no-op) upon a new replica connection (which is rare and certainly not on any hot path)

**Comment by romange** [comment]
yes, we should resolve
