### ISSUE TITLE
Add support for XINFO STREAM stream_name

### ISSUE THREAD

**Issue by kostasrim** [dragonflydb/dragonfly#1517]
https://redis.io/commands/xinfo-stream/

**Comment by rounaknandanwar** [comment]
@kostasrim 
I would like to take this up. Can you assign this to me ?

**Comment by kostasrim** [comment]
Definitely @rounaknandanwar

**Comment by rounaknandanwar** [comment]
@kostasrim Should I assume we need the options FULL and COUNT as well?
