### ISSUE TITLE
(zset) Slower throughput

### ISSUE THREAD

**Issue by ugcodrr** [dragonflydb/dragonfly#153]
Not the biggest of issues, only making this because dragonfly is presenting itself as being multithreaded. Perhaps there is just a simple config option I am missing. 

My Redis version is `7.0.0` and dragonfly is running on the latest commit (`df-dev`). While running my test script, I notice that Redis is able to handle 70,000+ commands/sec and only use ~30% CPU.  While with dragonfly it is constantly at 100% CPU (1 core as well) and barely reaches 25,000 concurrent commands. Perhaps this is related to pipelining? All of the commands are `zadd`. This difference results in around ~3x slower completion of the test. Might get around to running it on a fresh ubuntu instance to see if the problem still occurs.

**Comment by romange** [comment]
can you put here your test script, please? 
what `uname -a` and `cat /proc/cpuinfo` tell you?

**Comment by romange** [comment]
Also, can you please paste the output of dragonfly when running `./dragonfly --logtostderr`

**Comment by ugcodrr** [comment]
> can you put here your test script, please? what `uname -a` and `cat /proc/cpuinfo` tell you?

`Linux ucody 5.15.0-37-generic #39-Ubuntu SMP Wed Jun 1 19:16:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
[cpu.txt](https://github.com/dragonflydb/dragonfly/files/8904868/cpu.txt)


> Also, can you please paste the output of dragonfly when running `./dragonfly --logtostderr`

```
I20220614 19:16:45.269507 89310 init.cc:56] ./dragonfly running in opt mode.
I20220614 19:16:45.269541 89310 dfly_main.cc:179] maxmemory has not been specified. Deciding myself....
I20220614 19:16:45.269567 89310 dfly_main.cc:184] Found 25.55GiB available memory. Setting maxmemory to 20.44GiB
I20220614 19:16:45.269856 89311 proactor.cc:456] IORing with 1024 entries, allocated 102720 bytes, cq_entries is 2048
I20220614 19:16:45.275472 89310 proactor_pool.cc:66] Running 16 io threads
I20220614 19:16:45.296355 89310 server_family.cc:193] Data directory is "/home/ucody/dragonfly/build-opt"
I20220614 19:16:45.296439 89310 server_family.cc:117] Checking "/home/ucody/dragonfly/build-opt/dump"
I20220614 19:16:45.296496 89313 listener_interface.cc:79] sock[53] AcceptServer - listening on port 6699
```

**Comment by ugcodrr** [comment]
https://github.com/ugcodrr/redis-test

**Comment by romange** [comment]
@ugcodrr  - you are running DF on 16 cores, not on a single core - see `Running 16 io threads`.

Re throughput - it seems you are using a single connection to communicate with Redis, am i right? 
In this case, the throughput is predetermined by the latency of each request. If you want to reach full capabilities of DF you need to use multiple connections. If your prod environment will consist of a single nodejs process with a single connection to Redis, you won't be able to utilize DF scaling capabilities fully.

**Comment by romange** [comment]
Closing. Feel free to reopen if you still have questions,
