### ISSUE TITLE
Add GEOADD support

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#1545]
Once #1543 is submitted there still some unimplemented functionalities l(options, multiple members)  that need to be completed

**Comment by yoelsherwin** [comment]
Hi @romange , I would like to take this issue :) Could you provide some guidance? I saw you left some `todo`s, should I follow them? Is there anything else I should know?

**Comment by romange** [comment]
Gladly! 
Currently geoadd has limited functionality - it does not support multiple locations and does not support options.
Please check out other commands to see how we parse options. Also, TODOs hint you where code changes needed. 
Please ping @chakaz  if you have any issues :)

**Comment by romange** [comment]
@yoelsherwin  feel free to take GEODIST issue too :).
