### ISSUE TITLE
Add GEOPOS support

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#1546]
See here: https://redis.io/commands/geopos/

**Comment by yoelsherwin** [comment]
Hi, I would like to give it a shot :)

**Comment by romange** [comment]
feel free to do so after #1543 is submitted :)

**Comment by yoelsherwin** [comment]
Hi @romange , yes I would like to give it a shot. As this is my first contribution to dragonfly, could you please provide some guidance on where I should begin?

**Comment by yoelsherwin** [comment]
Hi @romange @kostasrim 
I created a test based on the example provided here: https://redis.io/commands/geopos/
```redis> GEOPOS Sicily Palermo Catania NonExisting
1) 1) "13.36138933897018433"
   2) "38.11555639549629859"
2) nil```
But when running it using my implementation I got a different result:
```1127.0.0.1:6379> geopos Sicily Palermo non
1) 1) "13.361389338970184"
   2) "38.1155563954963"
2) (nil)```
It seems like it is an issue with the precision. Do you think this makes sense? I tried working with the infrastructure implemented in #1543 but for some reason, I'm getting different results compared to Redis

**Comment by chakaz** [comment]
Looking at the geopos example, I see that the coordinates are specified using 6 decimal digits, and the divergence in your above print happens many (6 more) digits after, so I personally don't think this is worrisome. @romange do you know if common usage of these methods compare positions with infinite precision?

**Comment by romange** [comment]
@yoelsherwin your results are good. We are using a differrent algorithm printing doubles but essentially these are the same doubles.

```py
>>> 13.36138933897018433 == 13.361389338970184
True
>>> 38.11555639549629859 == 38.1155563954963
True
```

**Comment by yoelsherwin** [comment]
Ok, thanks @romange ! I will go over @chakaz comments today and will submit another review soon
