### ISSUE TITLE
Make --maxmemory changeable at runtime

### ISSUE THREAD

**Issue by ashotland** [dragonflydb/dragonfly#1551]
This will be a nice operational feature to be able to change max memory with no need to restart dragonfly.

To generalize, some flags (not all of them) should be changeable at runtime. We will use `CONFIG SET` command. 
Following the discussion below, the behavior will be that all the modifications will be lost during the process restart.

**Comment by romange** [comment]
what you expect to happen during restarts?

**Comment by ashotland** [comment]
Pick up the value from dragonfly.conf

Or the value that was specified at start time.

I intend to use it in conjunction with updating dragonfly.conf. (in case I want to make the change permanent) 

This applies to any flag value modification at runtime I think.

**Comment by romange** [comment]
hmm, i see how it will quickly become a problem. folks will forget updating the flag file. But I guess we can decouple this
