### ISSUE TITLE
dragonfly support cluster mode like redis?

### ISSUE THREAD

**Issue by idesk2596** [dragonflydb/dragonfly#1553]
Hi,

Can someone elaborate on what cluster mode "emulated" is? or can tell if
possibole to use round-robin dns to 3 servers running dragonfly as a cluster?

Thanks!

**Comment by chakaz** [comment]
Hello!
Currently, Dragonfly supports what we call "emulated mode cluster". It means that Dragonfly implements (most of) the Redis Cluster commands (i.e. `CLUSTER ...`), but does so with a single process.
The reason why this might be useful, is that Dragonfly scales with your hardware. While it doesn't make sense to run a single instance of Redis on a big machine (for example with 16 CPUs), it makes perfect sense to do so with Dragonfly.

Having said that, we currently do not support a _real_ cluster, i.e. one that uses multiple machines for a logical single data store. However, your question implies that Redis supports round-robin - that is actually not the case. The way Redis Cluster works is by dividing the keyspace into the N nodes in the cluster, and uniquely allocating the keys between them. So round-robin simply won't work in that config. That is also how we will implement Dragonfly Cluster, once ready.

**Comment by romange** [comment]
@idesk2596  why do you use round robin ? do you keep the same data on all shards?

**Comment by idesk2596** [comment]
Nope, each node have diffrent data, shard nodes are not part of the round-robin address, only the redis cluster nodes.
redis know where a specific "shard" of data reside, and pulling it for a client.

I use round-robin mostly trying to increase bandwidth and prevent bottlenecks.
for that mattar, clients connected with 10-25Gbps speed,
redis cluster nodes are with 100Gbps and shard nodes with 25Gbps.

**Comment by chakaz** [comment]
Sorry, I'm not following. What is the difference between redis cluster nodes and shard nodes?
If you need some key X, how do you get it in a round-robin fashion?
