### ISSUE TITLE
MULTI EXEC slow and high cpu used

### ISSUE THREAD

**Issue by FJSDS** [dragonflydb/dragonfly#1586]
i run docker-compose in windows wsl ,and test with [go-redis](https://github.com/redis/go-redis)

```go
package main

import (
	"context"
	"fmt"
	"math/rand"
	"strconv"
	"sync/atomic"
	"time"

	"github.com/redis/go-redis/v9"
)

var ctx = context.Background()
var count int64

func main() {
	rdb := redis.NewClient(&redis.Options{
		Addr:     "127.0.0.1:6379",
		Password: "", // no password set
		DB:       0,  // use default DB
		PoolSize: 100,
	})
	for i := 0; i < 100; i++ {
		go func() {
			for {
				DoOnce(rdb)
				atomic.AddInt64(&count, 1)
			}
		}()
	}

	old := int64(0)
	for {
		time.Sleep(time.Second)
		n := atomic.LoadInt64(&count)
		fmt.Println(n-old, n)
		old = n
	}
}

func DoOnce(client *redis.Client) {
	k := strconv.FormatInt(rand.Int63(), 10)
	k1 := strconv.FormatInt(rand.Int63(), 10)
	k2 := strconv.FormatInt(rand.Int63(), 10)
	k3 := strconv.FormatInt(rand.Int63(), 10)
	_, err := client.TxPipelined(ctx, func(pp redis.Pipeliner) error {
		pp.Set(ctx, k, k, -1)
		pp.Set(ctx, k1, k, -1)
		pp.Set(ctx, k2, k, -1)
		pp.Set(ctx, k3, k, -1)

		return nil
	})
	//err := client.Set(ctx, k, k, -1).Err()
	if err != nil {
		panic(err)
	}
}

```

connect dragon (cpu used about 600%)output:
6478 6478
6942 13420
6648 20068
6944 27012
7059 34071
6997 41068
6358 47426

but connect redis(docker image redis:7.0)(cpu used about 180%) output:
30701 30701
33019 63720
33700 97420
34267 131687
32937 164624
32907 197531
31938 229469
31045 260514
31791 292305

_**Where is my configuration wrong? Why is the concurrency so low?**_
How do I configure it to provide concurrency. Actually I have tried various configuration situations

**Comment by FJSDS** [comment]
![image](https://github.com/dragonflydb/dragonfly/assets/10356979/3c4dc6a8-5a3c-42d7-afbc-ac42e790612e)

The concurrency of 30000 corresponds to 600% of the CPU. I personally feel that the CPU is a bit high. Is there any configuration that can reduce the CPU?

**Comment by adiholden** [comment]
you can use proactor_threads flag to set the number of threads that dragonfly will use, by default it uses all available cpus.

**Comment by FJSDS** [comment]
thanks
