### ISSUE TITLE
improve snapshot scheduling interface

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#1590]
`save_schedule` flag is a bit confusing and not flexible enough.

Instead, we should introduce  a more standard way of scheduling snapshots like cronjob expression.

this library can help with parsing and matching the events. 
https://github.com/mariusbancila/croncpp 

we should introduce a new flag (e.g. `snapshot_cron`?) and leave the old one to allow an easy transition before we deprecate it.

**Comment by eliskovets** [comment]
Hi @romange , 
Would it be possible to schedule saves only in case changes were made to the data? 
In our case, we have a huge cluster that's mostly read-only, and we would like "save" to be triggered only if changes were made to the data. 
The only possibility I see right now is to trigger `bgsave` when we finish writing data from the client code.

Thank you!

**Comment by kostasrim** [comment]
Hi @eliskovets,

> Would it be possible to schedule saves only in case changes were made to the data?

Currently you can either save a snapshot explicitly via `bgsave` or periodically via the `save_schedule` flag. 

Probably the best way would be to trigger it explicitly each time a client writes the data to the server.

Moreover, is there a specific reason why you would like snapshotting on write trigger?

**Comment by romange** [comment]
I agree with @kostasrim  here. It's a very narrow use case and it requires from us some additional tracking and wiring to implement. Seems that calling BGSAVE/SAVE is an adequate solution for this problem.

**Comment by dor132** [comment]
@romange This can be marked as closed now.

**Comment by romange** [comment]
That was quick 😀. Thank you!

**Comment by romange** [comment]
I would like to apply some changes.

**Comment by dor132** [comment]
What are the changes?

**Comment by romange** [comment]
@dor132  I see you already saw - I think  your proposal is good.
