### ISSUE TITLE
redundant check-fail bug 

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#1630]
`1186 dragonfly_connection.cc:53] Check failed: RedisParser::BAD_ARRAYLEN == pres (2 vs. 4)`

really bad reason to check-fail. we should solve this asap

**Comment by chakaz** [comment]
I can remove the `CHECK()`, that's easy :)
(also the unused local `res` variable, or was it supposed to be prepended to all errors?)
But.. should I replace it with something? Go over all of [`Result`](https://github.com/dragonflydb/dragonfly/blob/3edd5bff798948689915115bbef78b4c84a2d302/src/facade/redis_parser.h#L25) options?
Sorry, I'm lacking context here

ftr here's the line:
https://github.com/dragonflydb/dragonfly/blob/3edd5bff798948689915115bbef78b4c84a2d302/src/facade/dragonfly_connection.cc#L53C1-L53C1

**Comment by romange** [comment]
Whatever you think is best. This crashed on real traffic so we must handle
it somehow.
