### ISSUE TITLE
snapshot_cron causes an infinite loop when stopping the daemon

### ISSUE THREAD

**Issue by admtech** [dragonflydb/dragonfly#1636]
I have all startup parameters for our DragonflyDB in a config: "/etc/dragonfly/dragonfly.conf".
There I have the new parameter: 

`--snapshot_cron=*/5 * * * *`

added to e.g. permanently save the DB every 5 minutes (--dbfilename=database).

I start DragonflyDB in Ubuntu with: "service dragonfly start" and stop it with: "service dragonfly stop".

Now when I stop DragonflyDB, it does not exit and starts an infinite loop with a save of the DB:

```
I20230803 16:15:37.920915 47349 server_family.cc:1281] Saving "/var/lib/dragonfly/database-summary.dfs" finished after 1 ms
I20230803 16:15:37.922566 47349 server_family.cc:1281] Saving "/var/lib/dragonfly/database-summary.dfs" finished after 1 ms
I20230803 16:15:37.924258 47349 server_family.cc:1281] Saving "/var/lib/dragonfly/database-summary.dfs" finished after 1 ms
I20230803 16:15:37.925998 47349 server_family.cc:1281] Saving "/var/lib/dragonfly/database-summary.dfs" finished after 1 ms
I20230803 16:15:37.927918 47349 server_family.cc:1281] Saving "/var/lib/dragonfly/database-summary.dfs" finished after 1 ms
I20230803 16:15:37.929728 47349 server_family.cc:1281] Saving "/var/lib/dragonfly/database-summary.dfs" finished after 1 ms
I20230803 16:15:37.931648 47349 server_family.cc:1281] Saving "/var/lib/dragonfly/database-summary.dfs" finished after 1 ms
I20230803 16:15:37.933238 47349 server_family.cc:1281] Saving "/var/lib/dragonfly/database-summary.dfs" finished after 1 ms
I20230803 16:15:37.934872 47349 server_family.cc:1281] Saving "/var/lib/dragonfly/database-summary.dfs" finished after 1 ms
etc.
```
(Note: the 1ms is because there is only some test data in the DB).

I have to terminate the DragonflyDB then already with kill -9. Without the "snapshot_cron" parameter it works fine.

Here additionally another error came to bear, because if I terminate the DB with -9 and the write process is not yet complete, all data are lost! The "database-summary.dfs" is then empty.

**Environment:**
 - OS: ubuntu 22.04
 - Dragonfly Version: 1.7.1

**Comment by romange** [comment]
Sorry for that @admtech .

@dor132  can you please take a look? :) 
if not we will check it next week.

**Comment by admtech** [comment]
One addition from me: I wanted to go back to the old "--save_schedule=*:30" instead of "--snapshot_cron".
But again I get into the save loop. If I take it out of config dragonfly db works as usual.

I tried it several times. As soon as I have "--snapshot_cron" or "--save_schedule" in the config the dragonfly goes into a save loop and can't exit under Ubuntu as service. Only a "kill -9" including data loss stops the DB. This behavior was not observed in any previous version. The time control of 1.7.1 must have a bug.

**Comment by dor132** [comment]
Sorry @admtech.
@romange I can take a look during the weekend and I'll update if I find something. 
I ran it using the dragonfly executable and this bug did not occur, I'll try to reproduce it and investigate.

**Comment by romange** [comment]
try pressing ctrl-c to stop the process .Or send a sigterm using kill. I am pretty sure it's the snapshot fiber that does not finish for some reason.

**Comment by melroy89** [comment]
I installed Dragonfly via deb, and also using systemd to stop/start/restart. However for some reason Dragonfly doesn't want to stop (on a `stop-sigterm`) from systemd. It's 5 mins and the process is still not stopped:

```sh
● dragonfly.service - Modern and fast key-value store
     Loaded: loaded (/lib/systemd/system/dragonfly.service; enabled; vendor preset: enabled)
     Active: deactivating (stop-sigterm) since Mon 2024-03-25 20:55:52 CET; 5min ago
   Main PID: 1677706 (dragonfly)
      Tasks: 27 (limit: 77022)
     Memory: 1.7G
        CPU: 7h 23min 9.237s
     CGroup: /system.slice/dragonfly.service
             └─1677706 /usr/bin/dragonfly --flagfile=/etc/dragonfly/dragonfly.conf

Mar 21 15:42:35 ubuntu-server systemd[1]: Started Modern and fast key-value store.
Mar 21 15:42:35 ubuntu-server dragonfly[1677706]: * Logs will be written to the first available of the following paths:
Mar 21 15:42:35 ubuntu-server dragonfly[1677706]: /var/log/dragonfly/dragonfly.*
Mar 21 15:42:35 ubuntu-server dragonfly[1677706]: * For the available flags type dragonfly [--help | --helpfull]
Mar 21 15:42:35 ubuntu-server dragonfly[1677706]: * Documentation can be found at: https://www.dragonflydb.io/docs
Mar 25 20:55:52 ubuntu-server systemd[1]: Stopping Modern and fast key-value store...
```

I'm now considering killing the process manually, due to no better alternative here.

**Comment by romange** [comment]
@melroy89 does it reproduce consistently?

**Comment by melroy89** [comment]
> @melroy89 does it reproduce consistently?

No, too bad not.. That would be much easier  right.. but now  ;(
