### ISSUE TITLE
Implement support for {Y}-{m}-{d} expansions in dbfilename argument

### ISSUE THREAD

**Issue by admtech** [dragonflydb/dragonfly#1637]
The parameter "--dbfilename" can be used to specify the file name. The default is "--dbfilename dump-{timestamp}";

The idea of {timestamp} is good, but it would be nice if you could refine it a bit. 

For example, I would like to save the database for each day, so rather the value {date} or even finer {Y}-{m}-{d}. 

With {timestamp} the system runs full very fast, if you use the "save" function often or if you time it. But if you only have the current date, you would always have a backup of the previous days etc. automatically. The rest, i.e. the cleanup, can be done by a shell script (delete everything older than x days etc.). 

Here are a few example:

--dbfilename dump-{date}
--dbfilename dump-{Y}-{m}-{d}
--dbfilename dump_{Y}-{m}
--dbfilename dump-{Y}-{m}-{d}_{h}

thanks
greetings Frank

**Comment by romange** [comment]
with cron argument (assuming it works) if you save a database once a  day you will get a single fileset per day. Now sure how the format affects the the occupancy of the system

**Comment by admtech** [comment]
We save the snapshot every 30 minutes so that it is as up-to-date as possible. No problem for the system. We do that with the cron, but it would be more elegant to have the options described above instead of {timestamp}. Coupled with the security of knowing that if the save operation is aborted (e.g. by a kill -9), the database remains intact. 

I can't think of any scenario where the previous {timestamp} could be used. 

I understand what you mean though. You assume that the dump is only saved here and there. But since you don't support "Redis persistence" (according to the release note you just buried it) we need the dump as a kind of "fast" persistence. If all possibilities fail, i.e. replication or final saving of a dump fails, I need to have the possibility to restore the previous data as fast and up-to-date as possible. Very important for customers. It would also be important in the development environment, where you usually don't have replication turned on. 

Since compared to Redis you only need seconds for several gigabytes when saving, this is quite possible and not a problem for the system (which would otherwise be permanent under an ArangoDB, for example, with this load).

Greetings
Frank

**Comment by admtech** [comment]
Is there any news about this here? The macro {date} should be quick to implement and would help considerably with administration. Additional cronjobs means more administration. The admins would be grateful.

**Comment by romange** [comment]
I think the distinction is purely syntactic (not clear how the text format matters here) but if you really feel you needed feel free to send a PR :)

**Comment by admtech** [comment]
Sorry, I am not a C++ developer. I represent the admin side here. The macros {Y}-{m}-{d} or {date} would simply help the administration. {timestamp} makes no sense at all from my point of view, because it creates tons of snapshot that are not needed. Snapshot of data we do not only once a day, but several times (every hour). 

Currently without {timestamp} a snapshot is created, then a cronjob gets the data, creates a .tgz and copies this file to another directory (costly). With the additional macros and the internal cronjob of Dragonfly you could create a snapshot every hour with e.g. the name: snapshot-{date}-{hour} and you could do without the additional cronjobs. That's the idea behind it. Simplification. The effort on your side to do this should be very small.

**Comment by romange** [comment]
I am sorry. why do you have another job that copies data aside if it's already created once an hour? to have a clear snapshot date ?

**Comment by admtech** [comment]
> I am sorry. why do you have another job that copies data aside if it's already created once an hour? to have a clear filename ?

The difference between the snapshot_{timestamp} and a snapshot_{date} is the uniquely assigned name. No matter if by "internal cron" or by "pg_save" (which our developers also like to use uncontrolled). 

With {timestamp} a new snapshot is "always" created. With my suggestion, the snapshot is overwritten or created after the specified time in a controlled way.

Example: In our chat system we save the snapshot every 60 minutes, but we need a complete snapshot backup only once a day. So we set the internal cron of Dragonfly to 1 hour, so that the snapshot is overwritten with the newest content. Then create a completely new snapshot via "snapshot_{date}" once a day. 

So something more understandable?

**Comment by romange** [comment]
Yes, now I understood 😁.

I've updated the task, hopefully we will be able to do it during
hacktoberfest

**Comment by ant31** [comment]
is it available ? 
The issue is closed as completed but I I don't the matching PR

**Comment by BorysTheDev** [comment]
Hi @ant31 The PR is here: https://github.com/dragonflydb/dragonfly/pull/2118

**Comment by ant31** [comment]
Awesome, thank you
