### ISSUE TITLE
add tcp-backlog config

### ISSUE THREAD

**Issue by ice-cronus** [dragonflydb/dragonfly#1643]
**Is your feature request related to a problem? Please describe.**
Hi, guys! We're experiencing some issues with connectivity when running a lot of connections with high concurrency (using [golang redis v9 client](https://github.com/redis/go-redis)), errors like that
```
failed to get [...]: dial tcp 127.0.0.1:6379: i/o timeout
``` 
We're running high frequent queries with about ~800 concurrent connections.

I figured out that it seems issue is related to tcp buffer size, cuz when I run the same client code on default redis docker image with tuned [tcp-backlog](https://developer.redis.com/operate/redis-at-scale/talking-to-redis/initial-tuning/#:~:text=Set%20TCP%2DBACKLOG%E2%80%8B,s%2C%20int%20backlog) configuration I do not exprience such issues.

As I see in the code server is running using the default one of [128 buffer size](https://github.com/romange/helio/blob/5c7f994fc480732f21a915a33fce0a00f2c691a9/util/accept_server.h#L67), and lib has a [function to adjust it](https://github.com/romange/helio/blob/5c7f994fc480732f21a915a33fce0a00f2c691a9/util/accept_server.h#L50), but it is [never called](https://github.com/search?q=repo%3Adragonflydb%2Fdragonfly%20set_back_log&type=code) from dragonfly server side.
**Describe the solution you'd like**
Some flag / configuration parameter should be added to adjust the tcp-backlog parameter.

**Describe alternatives you've considered**
Or make the default behaviour to be unbounded.

**Additional context**
[Discord thread](https://discord.com/channels/981533931486724126/981533931960676364/1136915129766776962)

**Comment by kostasrim** [comment]
Thank you, @ice-cronus submitting an issue. @romange He would like to work on this, any reason why not? (I remember Roy was cooking something, but my memory deceive me)

**Comment by royjacobson** [comment]
What I was working on is auto configuration of `ulimit` for open files, it's unrelated to the network stack :)

**Comment by kostasrim** [comment]
@royjacobson Oh yes yes thanks for pointing out! 

@ice-cronus if @romange approves I can make a quick PR. It's a few lines change

**Comment by romange** [comment]
Wow, slow down cowboys :) `backlog` is ONLY relevant when a new connection is initiated. Once the connection is established it does not affect anything. @ice-cronus does your app constantly tries to connect and disconnect? Is it possible to reproduce it on our side?

**Comment by kostasrim** [comment]
You are late the party :partying_face: (I know it's a non working day in Israel -- I am joking)

@romange I think the use case is that they initiate more than 128 connections at the same time, so probably the case is this flag puts an upper bound on the number of connections. And ofc it should, because it will call `listen` which is defined as:

```
293 /* Prepare to accept connections on socket FD.
294    N connection requests will be queued before further requests are refused.
295    Returns 0 on success, -1 for errors.  */
296 extern int listen (int __fd, int __n) __THROW;
```
So when the limit is reached, `__n` it will reject the connections.

Am I missing something?

**Comment by romange** [comment]
It's almost accurate. This article provides what i think is the complete picture: http://veithen.io/2014/01/01/how-tcp-backlog-works-in-linux.html

basically, linux OS indeed maintains the backlog for the accept queue. But it does not mean that once the queue is full the incoming connections are rejected. In fact, you can hack `echo_server` to stop accepting the connections and see yourself. Linux OS in that case does not send back ACK and the client retries sending SYN packets again and again (usually upto 5min). 
If during that time the accept queue is unloaded then the next SYN will be ACKED and the connection will be accepted. 
this is why you can open with `memtier_benchmark`  thousands of connections - in the worst case it will take more time for some connections to open.

**Comment by kostasrim** [comment]
@romange it's your call :)

**Comment by romange** [comment]
@ice-cronus I am sorry but it's not recommended to tune tcp backlog for high load. In fact, it makes the backend more prone to connection storms.  It's recommended to tune it for HTTP backends (lb/proxies) that need to handle huge amounts of accepts. I do not wish that Dragonfly users would waste their time tuning irrelevant options  🍺

**Comment by romange** [comment]
@ice-cronus do you monitor dragonfly instances? if yes, could you share graphs of `total_connections_received` and `instantaneous_ops_per_sec`  around the time you experience those timeouts. Also, I am curious to see the CPU load of the instance during these incidents.

**Comment by romange** [comment]
Ok, sounds good. Do you know why you have these disconnects in the first place? Could you provide `INFO ALL` output from that instance?

**Comment by romange** [comment]
Some updates on the issue. in case hundreds or more connections are created at the same time, linux moves first `backlog`  established connections into the accept queue. All others are put into special SYN queue https://veithen.io/2014/01/01/how-tcp-backlog-works-in-linux.html   For these connections, the linux server does not send SYN-ACK responses (i.e. silently ignores them), which triggers the re-transmit flow on the client side. The re-transmit flow has exponential back-off with the initial value being hardcoded in linux to 1 second, see https://serverfault.com/questions/1043758/initial-syn-timeout-on-linux

So, if our backlog is 128 and more than 128 clients try to connect and Dragonfly has not immediately unloaded them from the accept queue, then some of the connections will find themselves in the SYN queue which will automatically prolong the connect time for them to at least 1 second.

**Comment by chakaz** [comment]
@romange do I read your last comment correctly in that you are OK with implementing `backlog` as a configurable flag?

**Comment by romange** [comment]
Yes :) now we understand the context and why this flag can be useful.

**Comment by chakaz** [comment]
You had me at "some of the connections will [...] prolong the connect time for them to at least 1 second" :rofl:
