### ISSUE TITLE
Do you support clustering?

### ISSUE THREAD

**Issue by codgo** [dragonflydb/dragonfly#165]
Do you support clustering?

**Comment by romange** [comment]
Not yet, and it will probably take a while. 

Having said that, unless you need to manage terrabytes of data, you may find a single instance Dragonfly sufficient for your needs.

**Comment by romange** [comment]
Closing. Feel free to continue in discussions if you have more questions

**Comment by codgo** [comment]
No need for Pb level microservices and multiple IDC

**Comment by marcusbooyah** [comment]
I wonder if [mcrouter](https://github.com/facebook/mcrouter) could work with Dragonfly as the backend.

**Comment by gohossein** [comment]
> Not yet, and it will probably take a while.
> 
> Having said that, unless you need to manage terrabytes of data, you may find a single instance Dragonfly sufficient for your needs.

How a single instance Dragonfly can ensure High-Availability?
Another question is that, Does anyone use it in production at scale?

**Comment by romange** [comment]
@gohossein  High-Availability by definition assumes that an instance crashed for some reason, it could be an AZ down or hardware failure. So a single instance can not provide "high availability".

Re - reliability - we run the test suite to ensure the correctness of the implementation, but Dragonfly is a rapidly growing project (we launched 2 months ago) so some unforeseen problems might rise. You can check in the issues how quickly we fix things once they are reported.
You are welcome to join the community, test your use-cases and if you see anything off - report it and helps us fixing it.

**Comment by romange** [comment]
Whats this pb level? What's this idc?

**Comment by shinebayar-g** [comment]
> Do you support clustering?

Looks like you're need to pay for it. https://dragonflydb.io/platform/

**Comment by romange** [comment]
Nobody needs to pay for anything. We want to understand the use cases for
clustering, this is why we ask to join the early access program
