### ISSUE TITLE
Allow unit-testing replication

### ISSUE THREAD

**Issue by chakaz** [dragonflydb/dragonfly#1659]
Currently there's no way to unit-test replication, only via e2e pytests. The reason for that is that the replication code is tightly coupled with ther network / protocol code.
My plan is to:
1. Break the dependency between `Replica` and `ProtocolClient`, i.e. instead of inheriting from it, hold it as a member which can be injected
2. Build a fake / mock `ProtocolClient` that will allow custom behavior (like connection failure / break, invalid results, etc)
3. Create the boilerplate needed for making tests easier to write
4. Do some refactoring where makes sense

**Comment by romange** [comment]
why e2e is not enough? :)

**Comment by chakaz** [comment]
Well, coverage :)
There are cases in which are challenging (or worse) to test via e2e, like disconnection in specific points, bad replies, etc.

**Comment by chakaz** [comment]
Not planned
