### ISSUE TITLE
Incorrect CGroup v1 Resource Detection

### ISSUE THREAD

**Issue by talbii** [dragonflydb/dragonfly#1683]
Let's assume that `cat /proc/1/cgroup` outputs:

```shell
...
5:cpu,cpuacct:/some_group
...
3:memory:/some_other_group
...
```

moreover, assume we are running under some container (e.g., Kube). Then it might be the case that the CGroup `/memory/some_group` doesn't exist, causing us to skip over reading memory values. On the other hand, the container's limits are *also* present in `/memory/memory.limit_in_bytes` (for v1 only!) (in fact, this is the system's memory limit so it applies globally).

The same thing of course can happen with CPU values.

---

This issue was raised by a Discord member, link [here](https://discord.com/channels/981533931486724126/1138402621389029419).

**Comment by talbii** [comment]
I already have a general idea of how to fix this. In this line we detect the memory cgroup path:

https://github.com/dragonflydb/dragonfly/blob/b9e8a2c0dafba761c451141b50dece8f841bc8af/src/server/dfly_main.cc#L538-L540

(using the example above, `memory = "/sys/fs/cgroup/memory/some_group"`)

And we later read that file, *on read failure, continue*:

https://github.com/dragonflydb/dragonfly/blob/b9e8a2c0dafba761c451141b50dece8f841bc8af/src/server/dfly_main.cc#L562-L568

which by itself is OK, since we might need to read a different file (the function handles v1 and v2 at the same time)

---

With this in mind, the fix would be to pre-load `mdata` with the contents of `/memory/memory.limit_in_bytes`.

**Comment by romange** [comment]
@talbii can you provide evidence that you need to concat paths like this:
`absl::StrCat("/sys/fs/cgroup/memory/", entry[2]); ` for cgroups v1 ?

**Comment by talbii** [comment]
In v1 each system resource (memory, CPU, IO, Network) has its own CGroup, which is at location `/sys/fs/cgroup/<resource>`. To access *my own* CGroup, you access `/sys/fs/cgroup/<resource>/my_cgroup`

An example for this is available here: https://docs.kernel.org/admin-guide/cgroup-v1/cgroups.html#how-do-i-use-cgroups

(`Charlie` is a CGroup which limits CPU resources)
