### ISSUE TITLE
Add support for distroless static Docker images

### ISSUE THREAD

**Issue by gaby** [dragonflydb/dragonfly#1686]
**Did you search GitHub Issues and GitHub Discussions First?**
Yes

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently dragonfly only has tags with Ubuntu and Alpine as base systems for the Docker image. Adding support for `distroless` will allow systems with high-security requirements not have to worry about unpatched packages in the base-image. 

More information about distroless-static can be found here: https://github.com/GoogleContainerTools/distroless/blob/main/base/README.md

List of images and examples here: https://github.com/GoogleContainerTools/distroless/tree/main#docker

**Describe alternatives you've considered**
Building my own image

**Comment by romange** [comment]
@gaby Seems you know about this much more than us. Could you provide build files for such images and we will continue maintaining them?

**Comment by gaby** [comment]
@romange Yeah, I can def take a look. It was confused a bit with the alpine/ubuntu images. Is there a way to compile Dragonfly completely static? 

Both current production images are adding dependencies in the final stage as seen here https://github.com/dragonflydb/dragonfly/blob/main/tools/docker/Dockerfile.alpine-prod.wip#L17 and here https://github.com/dragonflydb/dragonfly/blob/main/tools/docker/Dockerfile.ubuntu-prod#L24

I tried using the binary from the ubuntu imagea, in a new clean ubuntu image and it fails to start because `libxml` is missing.

Very basic static example:

```
# Base image for dragonfly
FROM ghcr.io/dragonflydb/dragonfly:v1.8.0 as dragonfly

# Final release image
FROM ubuntu:latest

COPY --from=dragonfly /usr/local/bin/dragonfly /usr/local/bin/dragonfly

EXPOSE 6379

CMD ["/usr/local/bin/dragonfly", "--logtostderr"]
```

**Comment by romange** [comment]
Dragonfly indeed uses several 3rd party libraries. We are open to accept PRs that will be able to change libraries linking to static.

**Comment by gaby** [comment]
I will try to take a look this week.

**Comment by Abhra303** [comment]
Hi @gaby, any update?

**Comment by gaby** [comment]
@Abhra303 Not really, I got caught up with other things then went on vacation for 3 weeks just got back.

I also stopped using Dragonfly and went back to Redis, so not sure if its worth for me to even look into it.

**Comment by romange** [comment]
@gaby  what was the reason that you decided to switch back to Redis?

**Comment by gaby** [comment]
@romange Mostly lack of arm64 support and how different the CLI arguments are compared to Redis. At least for our use-case Redis was enough.

In the future I have another service which may require higher throughput, which we may use `dragonfly` for.
