### ISSUE TITLE
QUIT does not disconnect once subscribed

### ISSUE THREAD

**Issue by pascaldekloe** [dragonflydb/dragonfly#170]
`QUIT` terminates the connection.

```
% nc localhost 6379
PING
+PONG
QUIT
+OK
%
```

`QUIT` does not terminate the connection anymore after a `SUBSCRIBE`. Instead, it waits for another line/command, and then the connection gets terminated.

```
% nc localhost 6379
PING
+PONG
SUBSCRIBE foo
*3
$9
subscribe
$3
foo
:1
QUIT
+OK
PING
%
```

The issue was detected with by https://github.com/pascaldekloe/redis/issues/4.

**Comment by romange** [comment]
@dranikpg it's a very easy bug once you know what to fix and it's very complicated because it requires from you to understand how DF connection management works. It's not urgent and serves more as an education task to learn the code in that area...

**Comment by dranikpg** [comment]
Is it really an easy bug to fix?
So, what is causing this bug:
1. After subscribe, `IoLoop...ParseRedis()` is choosing the slow path to dispatch `QUIT` via the dispatch fiber
2. The `IoLoop` blocks on `peer->Recv(append_buf);` waiting for more data
3. The dispatch fiber stops after processing QUIT (as expected) by checking the builder error
4. `ConnectionFlow` blocks on `IoLoop`

It makes sense for `IoLoop` to block on new data as soon as possible - for faster reading. By the time QUIT is processed, the only way to unblock `IoLoop` is by closing the `peer` manually. 

So we either:
1. Run QUIT always in sync
2. Close manually (and move cleanup)
3. Invent something else...
