### ISSUE TITLE
config get command support

### ISSUE THREAD

**Issue by boomballa** [dragonflydb/dragonfly#1700]
Due to the difference from the underlying architecture of redis, some previous config commands may not be fully supported, but can you have a complete display of the configurable items of dragonfly, similar to the function of `config get *`. From the user's point of view, I just don't know which configs can be configured and which ones can't. After all, I have transitioned from redis before, and some usage habits need to be adapted. 

I hope there will be a clear display of our configurable config items.
<img width="530" alt="image" src="https://github.com/dragonflydb/dragonfly/assets/8543659/69a69fc8-518c-4e5a-9bae-949c8e1d6ff2">

**Comment by romange** [comment]
@boomballa  why did you close it?

**Comment by boomballa** [comment]
@romange  Thanks for reopening.
I heard it said yesterday that for the monitoring level of dragonfly, the monitoring items should be as streamlined as possible, and some important indicators should be kept. I don't know if there is something wrong with my understanding
,I thought we had no plans to build this, so i closed it first.  😬

In fact, our current requirement is that if we want to use dragonfly, we need to modify it according to the python script monitored by redis before. If there are some important indicators in config get, it may be relatively troublesome to modify. So if we don't have a plan, we plan to try the grafana way first. The reason why we do not give priority to using grafana to collect monitoring information is that we have our own monitoring system. If we use grafana, there will be two sets of monitoring and alarm systems. The monitoring data collection caliber is not uniform, which will cause this problem.
