### ISSUE TITLE
Redisson and Dragonfly

### ISSUE THREAD

**Issue by Cloud-Yao** [dragonflydb/dragonfly#1704]
1. My project uses the Redisson client, connecting to Redis (version 6.x). Can I seamlessly switch Redis to DragonFly?

**Comment by kostasrim** [comment]
Hi `@Cloud-Yao` thank you for your question. Yes you can seamlessly replace `Redis` with `Dragonfly`. Under the hood, we use the same protocol as redis (and API) so any of the existing libraries should work with us as well.

We don't support all of the commands yet, but we are close. Let us know if you find something that did not work for you :)

Some reference materials can be found at https://www.dragonflydb.io/docs
