### ISSUE TITLE
CI: Use sccache with a cloud storage

### ISSUE THREAD

**Issue by royjacobson** [dragonflydb/dragonfly#1719]
We currently use `ccache` to speed up compilation but it's limited by the fact that we cannot share artifacts between different PRs.

We should switch to `sccache` and set up a bucket backend on GCS.
See https://github.com/mozilla/sccache/blob/main/docs/Gcs.md for details.

We'd need to set up either a TTL or a size limit on the bucket. 40GB sounds reasonable if we put a size limit.

**Comment by romange** [comment]
fixed by #1738
