### ISSUE TITLE
Add Lua Scripts without loading them in via the console

### ISSUE THREAD

**Issue by guyinatuxedo** [dragonflydb/dragonfly#172]
Unsure of the severity of this, I just wanted to point out that it can be done. I know that via editing the Database dump file, you can add saved lua scripts that can be executed when the server starts back up again. Unsure of the severity of this because there is no ACL, and you can load in scripts from the client.

**Comment by romange** [comment]
I did not understand the problem. Are you saying that the ability to load scripts from an rdb file is a bug?

**Comment by guyinatuxedo** [comment]
Not exactly, I made a mistake with a submission. I just wanted to let you
know that it could be done, since looking through the code/docs, it looks
like there are plans to implement an ACL later. Feel free to close the
issue.
