### ISSUE TITLE
proactor.cc:432] Error initializing io_uring: (1) Operation not permitted

### ISSUE THREAD

**Issue by liaoweiguo** [dragonflydb/dragonfly#174]
Docker install fail to load, ubuntu 20.04, kernel 5.18.4
Linux ??-ubuntu 5.18.4-051804-generic #202206141755 SMP PREEMPT_DYNAMIC Tue Jun 14 18:09:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Status: Downloaded newer image for docker.dragonflydb.io/dragonflydb/dragonfly:latest
I20220624 06:36:54.916532     1 init.cc:56] dragonfly running in opt mode.
I20220624 06:36:54.916580     1 dfly_main.cc:179] maxmemory has not been specified. Deciding myself....
I20220624 06:36:54.916622     1 dfly_main.cc:184] Found 24.54GiB available memory. Setting maxmemory to 19.63GiB
F20220624 06:36:54.917619     8 proactor.cc:432] Error initializing io_uring: (1) Operation not permitted
*** Check failure stack trace: ***
F20220624 06:36:54.917665     9 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.917739    10 proactor.cc:432] Error initializing io_uring: (1) Operation not permitted
*** Check failure stack trace: ***
F20220624 06:36:54.917665     9 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.917739    10 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedOperation not permitted
*** Check failure stack trace: ***
F20220624 06:36:54.917665     9 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.917739    10 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedOperation not permittedF20220624 06:36:54.917979    11 proactor.cc:432] Error initializing io_uring: (1) Operation not permitted
*** Check failure stack trace: ***
F20220624 06:36:54.917665     9 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.917739    10 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedOperation not permittedF20220624 06:36:54.917979    11 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedF20220624 06:36:54.918125    12 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.918238    13 proactor.cc:432] Error initializing io_uring: (1) Operation not permitted
*** Check failure stack trace: ***
F20220624 06:36:54.917665     9 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.917739    10 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedOperation not permittedF20220624 06:36:54.917979    11 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedF20220624 06:36:54.918125    12 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.918238    13 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedF20220624 06:36:54.918346    14 proactor.cc:432] Error initializing io_uring: (1) Operation not permitted
*** Check failure stack trace: ***
F20220624 06:36:54.917665     9 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.917739    10 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedOperation not permittedF20220624 06:36:54.917979    11 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedF20220624 06:36:54.918125    12 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.918238    13 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedF20220624 06:36:54.918346    14 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedOperation not permitted
*** Check failure stack trace: ***
    @     0x55e19c37ec53  google::LogMessage::SendToLog()
    @     0x55e19c37ec53  google::LogMessage::SendToLog()
    @     0x55e19c37ec53  google::LogMessage::SendToLog()
F20220624 06:36:54.917665     9 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.917739    10 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedOperation not permittedF20220624 06:36:54.917979    11 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedF20220624 06:36:54.918125    12 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.918238    13 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedF20220624 06:36:54.918346    14 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedOperation not permittedF20220624 06:36:54.918597    16 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.918617    15 proactor.cc:432] Error initializing io_uring: (1) Operation not permitted
*** Check failure stack trace: ***
F20220624 06:36:54.917665     9 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.917739    10 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedOperation not permittedF20220624 06:36:54.917979    11 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedF20220624 06:36:54.918125    12 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.918238    13 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedF20220624 06:36:54.918346    14 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedOperation not permittedF20220624 06:36:54.918597    16 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.918617    15 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedF20220624 06:36:54.918764    17 proactor.cc:432] Error initializing io_uring: (1) Operation not permitted
*** Check failure stack trace: ***
    @     0x55e19c37ec53  google::LogMessage::SendToLog()
F20220624 06:36:54.917665     9 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.917739    10 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedOperation not permittedF20220624 06:36:54.917979    11 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedF20220624 06:36:54.918125    12 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.918238    13 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedF20220624 06:36:54.918346    14 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedOperation not permittedF20220624 06:36:54.918597    16 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.918617    15 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedF20220624 06:36:54.918764    17 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedOperation not permitted
*** Check failure stack trace: ***
    @     0x55e19c37ec53  google::LogMessage::SendToLog()
    @     0x55e19c37ec53  google::LogMessage::SendToLog()
F20220624 06:36:54.917665     9 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.917739    10 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedOperation not permittedF20220624 06:36:54.917979    11 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedF20220624 06:36:54.918125    12 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.918238    13 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedF20220624 06:36:54.918346    14 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedOperation not permittedF20220624 06:36:54.918597    16 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.918617    15 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedF20220624 06:36:54.918764    17 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedOperation not permittedF20220624 06:36:54.919034    19 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.919082    18 proactor.cc:432] Error initializing io_uring: (1) Operation not permitted
*** Check failure stack trace: ***
    @     0x55e19c37ec53  google::LogMessage::SendToLog()
F20220624 06:36:54.917665     9 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.917739    10 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedOperation not permittedF20220624 06:36:54.917979    11 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedF20220624 06:36:54.918125    12 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.918238    13 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedF20220624 06:36:54.918346    14 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedOperation not permittedF20220624 06:36:54.918597    16 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.918617    15 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedF20220624 06:36:54.918764    17 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedOperation not permittedF20220624 06:36:54.919034    19 proactor.cc:432] Error initializing io_uring: (1) F20220624 06:36:54.919082    18 proactor.cc:432] Error initializing io_uring: (1) Operation not permittedOperation not permitted
*** Check failure stack trace: ***
    @     0x55e19c377417  google::LogMessage::Flush()
    @     0x55e19c377417  google::LogMessage::Flush()
    @     0x55e19c377417  google::LogMessage::Flush()
    @     0x55e19c37ec53  google::LogMessage::SendToLog()
    @     0x55e19c377417  google::LogMessage::Flush()
    @     0x55e19c37ec53  google::LogMessage::SendToLog()
    @     0x55e19c37ec53  google::LogMessage::SendToLog()
    @     0x55e19c377417  google::LogMessage::Flush()
    @     0x55e19c377417  google::LogMessage::Flush()
    @     0x55e19c37ec53  google::LogMessage::SendToLog()
    @     0x55e19c377417  google::LogMessage::Flush()
    @     0x55e19c378d9f  google::LogMessageFatal::~LogMessageFatal()
    @     0x55e19c378d9f  google::LogMessageFatal::~LogMessageFatal()
    @     0x55e19c377417  google::LogMessage::Flush()
    @     0x55e19c378d9f  google::LogMessageFatal::~LogMessageFatal()
    @     0x55e19c378d9f  google::LogMessageFatal::~LogMessageFatal()
    @     0x55e19c377417  google::LogMessage::Flush()
    @     0x55e19c377417  google::LogMessage::Flush()
    @     0x55e19c378d9f  google::LogMessageFatal::~LogMessageFatal()
    @     0x55e19c37ec53  google::LogMessage::SendToLog()
    @     0x55e19c378d9f  google::LogMessageFatal::~LogMessageFatal()
    @     0x55e19c377417  google::LogMessage::Flush()
    @     0x55e19c378d9f  google::LogMessageFatal::~LogMessageFatal()
    @     0x55e19c025e40  util::uring::Proactor::Init()
    @     0x55e19c378d9f  google::LogMessageFatal::~LogMessageFatal()
    @     0x55e19c025e40  util::uring::Proactor::Init()
    @     0x55e19c025e40  util::uring::Proactor::Init()
    @     0x55e19c378d9f  google::LogMessageFatal::~LogMessageFatal()
    @     0x55e19c025e40  util::uring::Proactor::Init()
    @     0x55e19c378d9f  google::LogMessageFatal::~LogMessageFatal()
    @     0x55e19c377417  google::LogMessage::Flush()
    @     0x55e19c025e40  util::uring::Proactor::Init()
    @     0x55e19c378d9f  google::LogMessageFatal::~LogMessageFatal()
    @     0x55e19c025e40  util::uring::Proactor::Init()
    @     0x55e19c0345b0  _ZNSt17_Function_handlerIFvvEZN4util12ProactorPool14SetupProactorsEvEUlvE_E9_M_invokeERKSt9_Any_data.lto_priv.0
    @     0x55e19c025e40  util::uring::Proactor::Init()
    @     0x55e19c025e40  util::uring::Proactor::Init()
    @     0x55e19c025e40  util::uring::Proactor::Init()
    @     0x55e19c0345b0  _ZNSt17_Function_handlerIFvvEZN4util12ProactorPool14SetupProactorsEvEUlvE_E9_M_invokeERKSt9_Any_data.lto_priv.0
    @     0x55e19c0345b0  _ZNSt17_Function_handlerIFvvEZN4util12ProactorPool14SetupProactorsEvEUlvE_E9_M_invokeERKSt9_Any_data.lto_priv.0
    @     0x55e19c025e40  util::uring::Proactor::Init()
    @     0x55e19c378d9f  google::LogMessageFatal::~LogMessageFatal()
    @     0x55e19c0345b0  _ZNSt17_Function_handlerIFvvEZN4util12ProactorPool14SetupProactorsEvEUlvE_E9_M_invokeERKSt9_Any_data.lto_priv.0
    @     0x55e19c0345b0  _ZNSt17_Function_handlerIFvvEZN4util12ProactorPool14SetupProactorsEvEUlvE_E9_M_invokeERKSt9_Any_data.lto_priv.0
    @     0x55e19c0345b0  _ZNSt17_Function_handlerIFvvEZN4util12ProactorPool14SetupProactorsEvEUlvE_E9_M_invokeERKSt9_Any_data.lto_priv.0
    @     0x55e19c025e40  util::uring::Proactor::Init()
    @     0x55e19c0345b0  _ZNSt17_Function_handlerIFvvEZN4util12ProactorPool14SetupProactorsEvEUlvE_E9_M_invokeERKSt9_Any_data.lto_priv.0
    @     0x55e19c019bca  _ZN4baseL18start_cpp_functionEPv.lto_priv.0
    @     0x55e19c025e40  util::uring::Proactor::Init()
    @     0x55e19c0345b0  _ZNSt17_Function_handlerIFvvEZN4util12ProactorPool14SetupProactorsEvEUlvE_E9_M_invokeERKSt9_Any_data.lto_priv.0
    @     0x55e19c0345b0  _ZNSt17_Function_handlerIFvvEZN4util12ProactorPool14SetupProactorsEvEUlvE_E9_M_invokeERKSt9_Any_data.lto_priv.0
    @     0x55e19c019bca  _ZN4baseL18start_cpp_functionEPv.lto_priv.0
    @     0x55e19c019bca  _ZN4baseL18start_cpp_functionEPv.lto_priv.0
    @     0x7f8bc4ea3609  start_thread
    @     0x55e19c019bca  _ZN4baseL18start_cpp_functionEPv.lto_priv.0
    @     0x55e19c0345b0  _ZNSt17_Function_handlerIFvvEZN4util12ProactorPool14SetupProactorsEvEUlvE_E9_M_invokeERKSt9_Any_data.lto_priv.0
    @     0x7f8bc4a7c133  clone
    @     0x7f8bc4ea3609  start_thread
    @     0x7f8bc4ea3609  start_thread
    @     0x55e19c019bca  _ZN4baseL18start_cpp_functionEPv.lto_priv.0
    @     0x7f8bc4ea3609  start_thread
    @     0x7f8bc4a7c133  clone
    @              (nil)  (unknown)
*** SIGABRT received at time=1656052614 on cpu 0 ***
    @     0x7f8bc4ea3609  start_thread
    @     0x7f8bc4a7c133  clone
    @     0x7f8bc4a7c133  clone
    @     0x55e19c019bca  _ZN4baseL18start_cpp_functionEPv.lto_priv.0
    @     0x7f8bc4a7c133  clone
    @     0x55e19c019bca  _ZN4baseL18start_cpp_functionEPv.lto_priv.0
    @              (nil)  (unknown)
    @              (nil)  (unknown)
[failure_signal_handler.cc : 331] RAW: Signal 6 raised at PC=0x7f8bc49a000b while already in AbslFailureSignalHandler()
    @              (nil)  (unknown)
[failure_signal_handler.cc : 331] RAW: Signal 6 raised at PC=0x7f8bc49a000b while already in AbslFailureSignalHandler()
PC: @     0x7f8bc49a000b  (unknown)  raise
    @ ... and at least 1 more frames
[failure_signal_handler.cc : 331] RAW: Signal 6 raised at PC=0x7f8bc49a000b while already in AbslFailureSignalHandler()
    @     0x55e19c0345b0  _ZNSt17_Function_handlerIFvvEZN4util12ProactorPool14SetupProactorsEvEUlvE_E9_M_invokeERKSt9_Any_data.lto_priv.0
[failure_signal_handler.cc : 331] RAW: Signal 11 raised at PC=0x7f8bc497f941 while already in AbslFailureSignalHandler()
*** SIGSEGV received at time=1656052614 on cpu 0 ***
    @     0x7f8bc4ea3609  start_thread
    @     0x55e19c019bca  _ZN4baseL18start_cpp_functionEPv.lto_priv.0
    @     0x55e19c019bca  _ZN4baseL18start_cpp_functionEPv.lto_priv.0
PC: @     0x7f8bc497f941  (unknown)  abort
    @ ... and at least 1 more frames

**Comment by liaoweiguo** [comment]
solved with --privileged

**Comment by romange** [comment]
Opened https://github.com/dragonflydb/dragonfly/issues/181 to help with this.
