### ISSUE TITLE
Add Support for more fields in CLIENT LIST

### ISSUE THREAD

**Issue by yelinaung** [dragonflydb/dragonfly#1767]
**Did you search GitHub Issues and GitHub Discussions First?**
Yes

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I've looked at Dragonfly's [CLIENT LIST](https://www.dragonflydb.io/docs/command-reference/server-management/client-list) command reference.

I would like to see more information in `CLIENT LIST` output, similar to Redis's [`CLIENT LIST`](https://redis.io/commands/client-list/), especially the DB number that the clients are connecting to.
Subsequently, I think this will also be helpful for `dragonfly_connected_clients` metrics.

**Describe alternatives you've considered**
There is no other alternative.

**Additional context**

**Comment by romange** [comment]
Can you expand about `dragonfly_connected_clients` part? We do have `connected_clients` metric in `INFO` output.

**Comment by romange** [comment]
Also, this is how the redis line looks like `name= age=3 idle=0 flags=N db=0 sub=0 psub=0 ssub=0 multi=-1 qbuf=26 qbuf-free=20448 argv-mem=10 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=22298 events=r cmd=client|list user=default redir=-1 resp=2` Do you need anything else besides db?
