### ISSUE TITLE
Error: Multi bulk len is too big  245002

### ISSUE THREAD

**Issue by boomballa** [dragonflydb/dragonfly#1771]
**Describe the bug**
When I use the synchronization tool to synchronize redis data to dragonfly, dragonfly reports an error `"Multi bulk len is too big 245002"`, and the synchronization tool client reports an error `"I/O error read from target server[xx.xx.xx.xx" :6379]: lost connect"`，cause data synchronization interruption.

**To Reproduce**
1. Parse the redis rdb file.
2. insert the parsed data into dragonfly in batches

**Screenshots**
1、 dragonfly error report：
<img width="1272" alt="image" src="https://github.com/dragonflydb/dragonfly/assets/8543659/c9571503-99e3-4b18-a400-0b23a061522e">
2、Synchronization tool reports an error：
<img width="1247" alt="image" src="https://github.com/dragonflydb/dragonfly/assets/8543659/bb4d666b-8933-4751-a4e7-f0f769a9e8f4">
3、dragonfly monitor
<img width="1893" alt="image" src="https://github.com/dragonflydb/dragonfly/assets/8543659/d3ee36f1-f24f-47f8-b355-afa2a6c6a4b5">

**Environment (please complete the following information):**
 - OS: [Debian GNU/Linux 11 ]
 - Kernel:   5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux
 - Dragonfly Version: [dragonfly  v1.8.0-7c99d2d1111e2636556ad8c2afad43c396906d01]

**Additional context**
    The migration tool I use is [redis-migrate-tool](https://github.com/vipshop/redis-migrate-tool). This tool is reliable and we use it frequently every day. I have 
    An idea for this problem. Is this problem related to the client buffer setting being too small? Here you can refer to the redis parameter` client-output-buffer-limit`. When the buffer is full, the client cannot perform write operations. I have encountered a similar problem when using redis before, and it is solved by setting the `normal `part in the` client-output-buffer-limit` parameter to not limit the client's buffer.
    Or whether we have parameters to solve this problem, in fact, I have filtered the parameter list we gave before asking the question, and found nothing helpful.
    In addition, I also want to raise a little question. Can our parameter modification be solved only by modifying the configuration file and restarting the dragonfly service?
Although dragonfly has the characteristics of multi-threading, when dragonfly uses a large enough memory, the impact on the business will be caused by modifying individual configurations and restarting the service. I feel that it is not cost-effective. 
    Functional requirements similar to `config get`, `config set `and `config rewrite` have been proposed before. Hope it can be improved in the next version,I hope this opinion can be adopted.

**Comment by romange** [comment]
we have a hardcoded limit for parsing arrays of elements - 64K and we reject array longer than that. 
we do not have ` client-output-buffer-limit` parameter in the system

**Comment by boomballa** [comment]
> we have a hardcoded limit for parsing arrays of elements - 64K and we reject array longer than that. we do not have ` client-output-buffer-limit` parameter in the system
<img width="922" alt="image" src="https://github.com/dragonflydb/dragonfly/assets/8543659/a8414241-8931-46f0-8795-110255612d71">

@romange  Is it caused by this key?

**Comment by boomballa** [comment]
> yes

@romange 
OK，Let's handle this unconventional Key by ourselves.

1、In addition, I would like to ask, similar to the `client-output-buffer-limit` parameter, does it mean that we do not impose buffer-level restrictions on the operations of the client and slave?
2、Regarding the question I asked above, do we have any plans to support `config `related commands?
