### ISSUE TITLE
allow setting flags via environment

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#1784]
absl c++ flags  ignore the environment variables, 
but sometimes it's more convenient to configure a process via environment (especially in development) 
like this `export FLAGS_dbfilename=''` so that all future invocations of dragonfly won't use snapshotting.

I suggest introducing a routine that will be called early in dfly_main.cc that will go over all the flags and will check if there is an env var with the appropriate name defined and will try to override that flag value.

**Comment by chakaz** [comment]
Note that we have something very similar for tests: https://github.com/dragonflydb/dragonfly/blob/7c16329ef3568dce68a77c568b6cf5db29fb9b36/src/server/test_utils.cc#L148-L159

And also note that absl has `--tryfromenv` and `--fromenv`, but they are opt in (no wildcard/regex) so it's not really helpful

**Comment by aidarbek** [comment]
@romange do you mind if I pick this?

**Comment by romange** [comment]
Sure, please do :)
