### ISSUE TITLE
Symfony PHP framework - cache mode failure

### ISSUE THREAD

**Issue by adrianmarcu18** [dragonflydb/dragonfly#1800]
**Describe the bug**
Dragonfly doesn't work with Symfony PHP framework when cache_mode:true.

The reason is the maxmemory_policy is used for validating the redis setup in their Redis Adapter:

https://github.com/symfony/symfony/blob/fcb754a1c08ef0b283f1f0caf0c8666098cb7fb6/src/Symfony/Component/Cache/Adapter/RedisTagAwareAdapter.php#L298

When cache_mode: store in Dragonfly, the policy is set to noeviction and connection to Dragonfly works as expected.
When cache_mode: true, maxmmemory_policy is removed entirely, which could make sense, but than, the connection from Symfony breaks, as it doesn't allow NULL values for maxmemory_policy.

Can we workaround this in any way? Maybe, the maxmemory_policy should always be appended to redis INFO and set as noeviction or give the possibility of adding a custom value for it.

**To Reproduce**
Probably not needed in this case. As the issue is clear.

**Expected behavior**
cache_mode: true to work for all frameworks which are using redis adapters

**Screenshots**

**Environment (please complete the following information):**
 - OS: [ubuntu 20.04]
 - Kernel: # Command: `uname -a`
 - Containerized?: Docker
 - Dragonfly Version: v1.6.2

**Reproducible Code Snippet**
```
# Minimal code snippet to reproduce this bug
```

**Additional context**

**Comment by romange** [comment]
What exactly symphony expects to see in this field? I still wish we have a minimal code snippet to reproduce this bug

**Comment by adrianmarcu18** [comment]
https://github.com/symfony/symfony/blob/fcb754a1c08ef0b283f1f0caf0c8666098cb7fb6/src/Symfony/Component/Cache/Adapter/RedisTagAwareAdapter.php#L95

Here is what Symphony expects:         
if ('noeviction' !== $eviction && !str_starts_with($eviction, 'volatile-')) {

So it needs either noeviction, either volatile-*

From what I see, this is just a check, and haven’t seen it used anywhere else. 

The actual error we get, though, is way calling the function to get the police, as it has a constraint to be of type string, and fails because NULL is not a string. 

private function getRedisEvictionPolicy(): string

**Comment by romange** [comment]
Does not it check that it's NOT `noeviction` and NOT `volatile-*`.  In other words, it needs `allkeys-*` ?

**Comment by adrianmarcu18** [comment]
https://symfony.com/doc/current/components/cache/adapters/redis_adapter.html

Here is a link also to their documentation. 
![image](https://github.com/dragonflydb/dragonfly/assets/48454135/299841bb-b1e6-4a42-b79c-85406235d897)

I might of sent incomplete code snippet. So if it is not one of them, it throws an exception. So thats why got you confused.

`        $eviction = $this->getRedisEvictionPolicy();
        if ('noeviction' !== $eviction && !str_starts_with($eviction, 'volatile-')) {
            throw new LogicException(sprintf('Redis maxmemory-policy setting "%s" is *not* supported by RedisTagAwareAdapter, use "noeviction" or "volatile-*" eviction policies.', $eviction));
        }`

**Comment by adrianmarcu18** [comment]
@romange Thanks prioritizing this and create the fix. I do have one comment though. By setting the policy to "eviction", it will still fail, as you can see above, an exception will be thrown when policy is not exactly "noeviction" or starts with "volatile". If set to eviction it will throw a different error, stating that the policy "eviction" is not supported by RedisTagAwareAdapter.

Now, after I studied a little bit how the Dragonfly Cache works, if that is compatible at all with this RedisTagAwareAdapter, even if we do set the cache policy to a keyword they validate against.

` * Stores tag id <> cache id relationship as a Redis Set.
 *
 * Set (tag relation info) is stored without expiry (non-volatile), while cache always gets an expiry (volatile) even
 * if not set by caller. Thus if you configure redis with the right eviction policy you can be safe this tag <> cache
 * relationship survives eviction (cache cleanup when Redis runs out of memory).
 *
 * Redis server 2.8+ with any `volatile-*` eviction policy, OR `noeviction` if you're sure memory will NEVER fill up
 *`
 
Now, in dragonfly, I am not sure if cache even gets an expiry and/or if it is taken into consideration when doing evictions.

**Comment by romange** [comment]
oh, that sucks. In Dragonfly we implemented the `STICK` command that prevents from specific items to be evicted. We find this volatile eviction based on ttl is pretty arbitrary. But yeah, this would require changing the framework code to work with Dragonfly specifically.
