### ISSUE TITLE
introduce graceful exit when io_uring is not present

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#181]
Currently DF crashes with ugly stack-trace when `io_uring_queue_init_params` exits with error 38.

We should provide a nice explanation of what can cause this. Currently there are two reasons:
someone run it on WSL2 on version smaller than `5.10.60.1` or DF was run via docker with `--priveleged` flag. The core reason for latter is not known to me. In any case, we should provide an explanation for both cases before exiting nicely via `exit(1)`.

**Comment by romgrk** [comment]
> or DF was run via docker with --priveleged flag

I'm also getting this issue when `--privileged` is *not* present (Amazon Linux 2, kernel 5.15). The issue disappears by adding that flag. Could be nice to mention in the Getting Started page.

**Comment by romange** [comment]
Thanks for the suggestion. Why would not you send a pr that implements this
advice?

**Comment by romgrk** [comment]
Sure, where are the website files?

**Comment by romange** [comment]
I meant this file: https://github.com/dragonflydb/dragonfly/blob/main/docs/quick-start/README.md

**Comment by romgrk** [comment]
Done, but you might want to update the website, I followed the instructions there to setup a test instance.

**Comment by iko1** [comment]
I've sent a [PR](https://github.com/romange/helio/pull/4) that implements a way to check whether io_uring is supported.

**Comment by romange** [comment]
@iko1 why not just try creating iouring on server bootstrap just to see it could be done?

**Comment by iko1** [comment]
@romange  Agree, the trivial solution is checking `io_uring_queue_init_params ` result code is equal to ENOSYS (Function not implemented)
This PR can be a solution: https://github.com/romange/helio/pull/5

**Comment by romange** [comment]
#197 fixes this
