### ISSUE TITLE
Unable start dragonfly 1.9.0 on ubuntu 22.04

### ISSUE THREAD

**Issue by fernandomacho** [dragonflydb/dragonfly#1823]
**Describe the bug**
After install dragonfly 1.9.0 on Ubuntu 22.04 dragon fly not start

**To Reproduce**
1. Download https://github.com/dragonflydb/dragonfly/releases/download/v1.9.0/dragonfly_amd64.deb
2. dpkg -i dragonfly_amd64.deb
3. run sudo -u dfly /usr/bin/dragonfly --flagfile=/etc/dragonfly/dragonfly.conf
4. Get this error: /usr/bin/dragonfly: error while loading shared libraries: libicuuc.so.66: cannot open shared object file: No such file or directory

**Environment (please complete the following information):**
 - OS: [ubuntu 22.04]
 - Kernel: # 5.15.0-73-generic
 - Containerized?: Bare Metal
 - Dragonfly Version: 1.9.0

**Additional context**
The library libicu version 6.6 is not available on ubuntu 22.04 the libicu library version is 7.7

**Comment by romange** [comment]
Thanks for reporting this. We will fix this in our next release 1.10 next week. We plan on dropping the dependency on icu.
Btw, you may workaround the issue by creating a softlink to sharedlib 7.7 - the regular code path does not really call icu functions anyway.

**Comment by fernandomacho** [comment]
I execute: 
ln -s /usr/lib/x86_64-linux-gnu/libicuuc.so.70 /usr/lib/x86_64-linux-gnu/libicuuc.so.66

install 1.9.0 and on start get this error:
/usr/bin/dragonfly: symbol lookup error: /usr/bin/dragonfly: undefined symbol: _ZTIN6icu_668ByteSinkE

And dragonfly not start

Revert to 1.8.0 version

**Comment by rickytato** [comment]
Same error here with Debian 11

**Comment by Gl00mY-ZeiZ** [comment]
Same error at Ubuntu 22.04.3 LTS

**Comment by supakaity** [comment]
You can download a dpkg file for icu66 from the following URLs (pick either amd64 or arm64):
 - http://archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu66_66.1-2ubuntu2.1_amd64.deb
 - http://ports.ubuntu.com/pool/main/i/icu/libicu66_66.1-2ubuntu2.1_arm64.deb

Once downloaded, you can install it with dpkg, e.g:
```
dpkg -i libicu66_66.1-2ubuntu2.1_amd64.deb
```

**Comment by dfernandesbsolus** [comment]
I have the same problem, but on Rocky Linux (centos).

**Comment by romange** [comment]
should be fixed in 1.10
