### ISSUE TITLE
Generic Result Type

### ISSUE THREAD

**Issue by dranikpg** [dragonflydb/dragonfly#1828]
New code has a small problem with returning results.

1. OpResult can only hold an OpStatus, which is neither a std::error_code nor a full blown generic error
2. io::Result<T, GenericError> is a little alienating and doesn't adhere to our code style / is somewhat inconvenient to use

What I've seen has been used instead

1. std::variant<T, GenericError> -> requires holds_alternative, get(move()), visit, etc all that manual you shouldn't been doing
2. Mutable pointer out arguments
3. io::Result<T, GenericError>, see p2

I'd propose adding a new Result type

```c++
template <typename V, typename E> class Result {
 public:
  Result(V&& value) : value_{std::move(value)} {
  }

  Result(E&& error) : value_{std::move(error)} {
  }

  template <typename... Args,
            typename = typename std::enable_if_t<std::is_constructible_v<V, Args...>>>
  Result(Args&&... args) : value_{T(std::forward<Args>(args)...)} {
  }

  bool HasValue() const {
    return std::holds_alternative<V>(value_);
  }

  bool HasError() const {
    return std::holds_alternative<E>(value_);
  }

  V TakeValue() {
    return std::move(std::get<V>(value_));
  }

  E TakeError() {
    return std::move(std::get<E>(value_));
  }

 protected:
  std::variant<V, E> value_;
};

template <typename T> struct GenericResult : public Result<T, GenericError> {
  GenericResult(facade::OpResult<T> res) {
    if (res.ok())
      value_ = std::move(res.value());
    else
      value_ = GenericError(res.status());
  }

  GenericResult(io::Result<T, GenericError> res) {
    if (res.has_value())
      value_ = std::move(res.value());
    else
      value_ = std::move(res.error());
  }
};
```

and a conversion function from GenericError to facade::ErrorReply (or optional<ErrorReply>) 🤔 

So at the end it becomes

```

                         facade::ErrorReply  ◄────   OpStatus

                                 ▲
                                 │                      ▲
                                                        │
  std::error_code  ──────►  GenericError                │
                                                        │
        ▲                        ▲                      │
        │                        │
                                 │
    io::Result                   │                   OpResult
         │              ┌────────┴─────────┐            │
         │              │                  │            │
         └─────────────►│   GenericResult  │◄───────────┘
                        │                  │
                        └──────────────────┘

                   New conversion to single type

```

![image](https://github.com/dragonflydb/dragonfly/assets/20553775/0b59a67e-2ff8-4efb-9a64-2dc7b8606a0f)

**Comment by dranikpg** [comment]
@chakaz @kostasrim 

What do you think of my idea?

**Comment by romange** [comment]
1. This templated class should replace the old `OpResult` ? 
2. Why io::Result does not adhere to our coding style? What's alienating in it?

**Comment by dranikpg** [comment]
🤷🏻 Just thoughts. Looking for ways to unify parts that use different mechanisms as well as using one where both are inconvenient 

1. I'm not sure how specifically, because op status can't be turned into a generic error now, but this can be added
2. reference type accessors, no implicit conversion for error types

**Comment by dranikpg** [comment]
On a second thought I guess unifying the system it is not worth given that not much new code will actually be added in the future that can make use of those

**Comment by chakaz** [comment]
Don't forget `unexpected` that's used in RDB/replication :rofl: 
Yeah, I can see a value for unifying them. What makes you say not much new code will use them in the future?

**Comment by royjacobson** [comment]
Aren't `unexpected` and `io::Result` the same type?

**Comment by chakaz** [comment]
You're right, I didn't know that.
