### ISSUE TITLE
Unable to set eviction-policy to noeviction

### ISSUE THREAD

**Issue by antarr** [dragonflydb/dragonfly#1840]
**Describe the bug**
I'm trying to set the eviction policy to `noeviction` I'm getting the error `ERR CONFIG SET failed (possibly related to argument 'maxmemory-policy').`

**To Reproduce**
1. `redis-cli --pass mypassword config set maxmemory-policy noeviction`

**Expected behavior**
Successful reponse

**Screenshots**
![image](https://github.com/dragonflydb/dragonfly/assets/974295/7a85b802-0aec-4165-97ed-3dbbd0ed417f)

**Environment (please complete the following information):**
 - OS: [Ubuntu 22.04.2 LTS]
 - Containerized?: Bare Metal
 - Dragonfly Version: [1.9.0]

### /data/app/dragonfly-start.sh 
```
#!/bin/bash
cd /data/app/
/data/app/dragonfly-x86_64 --logtostderr  --requirepass=somepassword --dbnum 16 --bind 0.0.0.0 --port 6379 --save_schedule *:30 --maxmemory=230g --keys_output_limit=12288 --dir /data/app/   >> /data/app/dragonfly.log 2>&1 &

echo $! > /run/dragonfly.pid
```

**Comment by romange** [comment]
it's not a bug though I agree we do not have clear documentation about this.
Dragonfly by default starts with "noeviction". If you want to have eviction (we call it cache mode), 
you need to pass `--cache_mode=true`.

You can verify the mode by running "redis-cli INFO MEMORY" - you should see `cache_mode:store` and 
`maxmemory_policy:noeviction` lines
