### ISSUE TITLE
Error on Command CONFIG GET databases

### ISSUE THREAD

**Issue by fernandomacho** [dragonflydb/dragonfly#1842]
Describe the bug
dragonfly 1.9.0 no report number of databases

To Reproduce

redis-cli -p xxxx CONFIG GET databases
Get empty array
On other versions this command return:
1) "databases"
2) "24"

Environment (please complete the following information):

OS: [ubuntu 22.04]
Kernel: # 5.15.0-73-generic
Containerized?: Bare Metal
Dragonfly Version: 1.9.0

**Comment by fernandomacho** [comment]
Other commands, for example:
config get maxmemory
config get maxclients

works fine

**Comment by royjacobson** [comment]
Changed in #1751. Dragonfly was using the `--dbnum` flag for this so `config get dbnum` still works. @romange was the alias removed intentionally?

**Comment by romange** [comment]
@fernandomacho does "config get/set dbnum" works for your use-case?

**Comment by fernandomacho** [comment]
In my case use flagfile config:
--dbnum=24

**Comment by fernandomacho** [comment]
The command:

config get dbnum

Works fine.
But all visual clients for example "Another Redis desktop manager" or redisinsight read the param:
CONFIG GET databases

**Comment by fernandomacho** [comment]
Hi, this fix is include on version 1.10.0?

**Comment by romange** [comment]
No, it was added afterwards
