### ISSUE TITLE
Any plans for persistency (i.e. send reply to client only after fsync() returned on all involved shards)

### ISSUE THREAD

**Issue by dumblob** [dragonflydb/dragonfly#186]
**Did you search GitHub Issues and GitHub Discussions First?**
Yes.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated looking for a fast DB with key-value **transactional** semantics which scales dynamically. I can not find one. Redis does not offer fine-grained (i.e. [**per client request**](https://github.com/redis/redis/issues/6200 )) persistency guarrantees.

**Describe the solution you'd like**
I wish I had something like Redis but with the per client request persistency guarantees as linked above. Or perhaps a way to efficiently mimic something like transactionally streaming data as [Pravega](https://github.com/pravega/pravega ) kind of does? IDK

**Describe alternatives you've considered**
Using (very) special HW (imagine Intel Optane or some low-level supercomputer-like virtualization of HW storage) and use basically any of those hundreds of DBs out there in a fully synchronous regime.

But I do not want to constrain my app(s) to such a very special (and super expensive!) HW setup.

**Additional context**
N/A

**Comment by romange** [comment]
Have you looked at MemoryDB from AWS? This is what they do, imho.
As to Dragonfly, we do not have yet concrete plans regarding full durability guarantees. I think that what you ask for will require many steps from where we are right now. We will start with H/A and we will see how we proceed from there.
Btw, we also consider supporting more sophisticated protocols than RESP (i.e. http). This will allow providing command modifiers like what you asked for. Doing it with RESP is a bit messy.

**Comment by romange** [comment]
Closing. Feel free to continue the discussion in "Discussions"

**Comment by dumblob** [comment]
> Have you looked at MemoryDB from AWS? This is what they do, imho.

Last time I took a look was when they announced the fork some years ago as reaction to Redis becoming more commercially-focused. But I did not notice anything different from Redis back then. I will look into it now if anything changed - thanks for the pointer!

>As to Dragonfly, we do not have yet concrete plans regarding full durability guarantees. I think that what you ask for will require many steps from where we are right now. We will start with H/A and we will see how we proceed from there.

Will keep an eye on it! Is it enough if I follow this issue tracker?

>Btw, we also consider supporting more sophisticated protocols than RESP (i.e. http). This will allow providing command modifiers like what you asked for.

Perfect! Looking forward to what you will choose as the next step in that direction.

**Comment by ashotland** [comment]
Hi @dumblob, Dragonfly supports replication and is compatible with Redis sentinel which should provide an HA solution. 
Hope it helps.
