### ISSUE TITLE
XREADGROUP issues: DF consumes from non-existing stream and does not block on newly created stream

### ISSUE THREAD

**Issue by FZambia** [dragonflydb/dragonfly#1860]
**Describe the bug**

Hello again! Continue trying DragonflyDB, now came across a couple of inconsistencies with Redis – preventing my queue based on Redis streams working fine with DragonflyDB:

## 1. Dragonfly tries to group consume from non-existing stream

Redis (7.0.12):

```
127.0.0.1:6379> flushdb
OK
127.0.0.1:6379> "XREADGROUP" "GROUP" group consumer COUNT 10 BLOCK 5000 STREAMS stream >
(error) NOGROUP No such key 'stream' or consumer group 'group' in XREADGROUP with GROUP option
```

DragonflyDB (1.10.0):

```
127.0.0.1:6379> flushdb
OK
127.0.0.1:6379> "XREADGROUP" "GROUP" group consumer COUNT 10 BLOCK 5000 STREAMS stream >
(nil)
(5.01s)
```

So DragonflyDB does not return `NOGROUP` error, instead it blocks for 5 secs.

## 2. Does not block on existing empty stream after creation

Redis (7.0.12):

```
127.0.0.1:6379> flushdb
OK
127.0.0.1:6379> "XGROUP" "CREATE" stream group "0" MKSTREAM
OK
127.0.0.1:6379> keys *
1) "stream"
127.0.0.1:6379> "XREADGROUP" "GROUP" group consumer COUNT 10 BLOCK 5000 STREAMS stream >
(nil)
(5.02s)
```

Redis blocks for 5 seconds.

DragonflyDB (1.10.0):

```
127.0.0.1:6379> flushdb
OK
127.0.0.1:6379> "XGROUP" "CREATE" stream group "0" MKSTREAM
OK
127.0.0.1:6379> keys *
1) "stream"
127.0.0.1:6379> "XREADGROUP" "GROUP" group consumer COUNT 10 BLOCK 5000 STREAMS stream >
(empty array)
```

Dragonfly returns immediately - which in my case results into busy loop while stream is empty.

**Environment (please complete the following information):**
 - OS: Macos, M1 PRO
 - Containerized: Yes, running in Docker
 - Dragonfly Version: v1.10.0

**Comment by theyueli** [comment]
hi @FZambia , we have fixed this issue, and it is now available through our weekly built container image:

```
sudo docker pull ghcr.io/dragonflydb/dragonfly-weekly:latest
docker run --network=host --ulimit memlock=-1 ghcr.io/dragonflydb/dragonfly-weekly
```

Would you like to have a quick test to see if that satisfies your need? Thanks!

**Comment by FZambia** [comment]
@theyueli thanks a lot! I'll definitely test it out very soon. Also waiting for other stream-related commands to be merged.

**Comment by theyueli** [comment]
@FZambia sounds good, we have just implemented XACK, and it shall get merged this week. 

Currently, the only command that is missing is XAUTOCLAIM, do you need this as well in your use case?

**Comment by FZambia** [comment]
@theyueli ideally yes since `XAUTOCLAIM` simplifies app code and does the work in one RTT - but I also have fallback to use `XPENDING` and then `XCLAIM`.

`Xack` is no doubt required for my use case.

**Comment by FZambia** [comment]
@theyueli I just tried weekly build with two scenarios above - works fine, many thanks!

A couple of things which block me from moving forward:

* XACK
* Also just noticed there is an issue with XCLAIM: https://github.com/dragonflydb/dragonfly/issues/1944
* Less blocker but still important: `XINFO GROUPS stream` does not return some fields which are available in Redis:

Redis (7.0.12):

```
127.0.0.1:6379> "XGROUP" "CREATE" stream group "0" MKSTREAM
OK
127.0.0.1:6379> XINFO GROUPS stream
1)  1) "name"
    2) "group"
    3) "consumers"
    4) (integer) 0
    5) "pending"
    6) (integer) 0
    7) "last-delivered-id"
    8) "0-0"
    9) "entries-read"
   10) (nil)
   11) "lag"
   12) (integer) 0
```

DF:

```
127.0.0.1:6379> "XGROUP" "CREATE" stream group "0" MKSTREAM
OK
127.0.0.1:6379> XINFO GROUPS stream
1) 1) "name"
   2) "group"
   3) "consumers"
   4) (integer) 0
   5) "pending"
   6) (integer) 0
   7) "last-delivered-id"
   8) "0-0"
```

So `entries-read` and `lag` are missing. I am using `lag` value for monitoring the queue.

Should I create a separate issue for this?

**Comment by theyueli** [comment]
Thanks a lot @FZambia for the update!

https://github.com/dragonflydb/dragonfly/pull/1923 has just been merged, it shall be available on this Sunday's weekly build
https://github.com/dragonflydb/dragonfly/issues/1944 is being worked on right now. 

Yes, please create a separate ticket, and we will look into this asap. Indeed XINFO is also a work-in-progress (especially XINFO STREAM):
https://github.com/dragonflydb/dragonfly/pull/1533

**Comment by FZambia** [comment]
Thanks, done - https://github.com/dragonflydb/dragonfly/issues/1948

**Comment by theyueli** [comment]
thanks!
