### ISSUE TITLE
Dragonfly does not accept all connections if requirepass is blank (default)

### ISSUE THREAD

**Issue by girlbossceo** [dragonflydb/dragonfly#1862]
**Describe the bug**

Dragonfly seems to require authentication for all connections, even if `requirepass` is blank which is the default behaviour for Dragonfly. Attempting to connect will throw an error, at least with ioredis.

<hr>

**To Reproduce**

1. Run Dragonfly v1.10.0 with no password defined (no `--requirepass`)
2. Attempt to connect to Dragonfly using something like ioredis
3. See that it errors on failing to authorize the "default" user

<hr>

**Expected behavior**

 If `--requirepass` is blank, the default, it should match Redis's behaviour where it accepts all connections.

https://redis.io/docs/management/security/acl/

> Redis can be configured so that new connections are already authenticated with a "default" user (this is the default configuration).

redis.conf (SECURITY section):

```
# The special username "default" is used for new connections. If this user
# has the "nopass" rule, then new connections will be immediately authenticated
# as the "default" user without the need of any password provided via the
# AUTH command. Otherwise if the "default" user is not flagged with "nopass"
# the connections will start in not authenticated state, and will require
# AUTH (or the HELLO command AUTH option) in order to be authenticated and
# start to work.
```

<hr>

**Screenshots (node logs)**

```
Sep 15 01:40:43 plus.st pnpm[35092]: [ioredis] Unhandled error event: ReplyError: ERR Could not authorize user: default
Sep 15 01:40:43 plus.st pnpm[35092]:     at parseError (/opt/firefish/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:179:12)
Sep 15 01:40:43 plus.st pnpm[35092]:     at parseType (/opt/firefish/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:302:14)

```

<hr>

**Environment (please complete the following information):**

 - OS: Arch Linux
 - Kernel: `Linux plus.st 6.4.16-hardened1-1-hardened #1 SMP PREEMPT_DYNAMIC Thu, 14 Sep 2023 23:48:30 +0000 x86_64 GNU/Linux`
 - Containerized?: Bare Metal
 - Dragonfly Version: 1.10.0 (currently downgraded to 1.8.0 though)

<hr>

**Reproducible Code Snippet**

N/A

<hr>

**Additional context**

Another user of Firefish (Fediverse software which uses and recommends Dragonfly) reported this same issue and confirmed downgrading to 1.8.0 fixed it, using TCP instead of UNIX sockets: https://git.joinfirefish.org/firefish/firefish/-/issues/10734
This user also provided error logs from ioredis.

systemd ExecStart for our Dragonfly service: `ExecStart=/dragonfly --logtostderr --cache_mode=true --maxmemory=15gb --hz=200 --unixsocketperm=0660 --unixsocket=/run/dragonfly/dfly.sock --pidfile=/run/dragonfly/dragonfly.pid --port=6379 --dir=/dragonfly-dir --primary_port_http_enabled=false --bind=127.0.0.1 --version_check=false`

systemd Environment variable for Firefish (our `CACHE_URL` which is what we are using to connect ioredis with): `Environment=CACHE_URL=unix:///run/dragonfly/dfly.sock`

Usage of this^: `return new Redis(process.env.CACHE_URL);`

**Comment by royjacobson** [comment]
The only difference I can observe is that unlike redis we reject `auth default ""`. This should probably be fixed but I'm not sure if that's the actual issue here, as it was rejected with a different error even in 1.8 (cc @kostasrim)

@girlbossceo do you have any way to get the actual `AUTH` command that is executed by the redis client or a simple way to reproduce the issue with node?

I've tried to connect to current trunk dragonfly with `ioredis` and couldn't reproduce the issue:
```
[user@fedora work]$ node
Welcome to Node.js v18.17.1.
Type ".help" for more information.
> const Redis = require('ioredis');
undefined
> const redis = new Redis();
undefined
> await redis.set("key", "value")
'OK'
> 
```

**Comment by kostasrim** [comment]
@royjacobson I opted in to explicitly use `nopass` on default. So:

`AUTH default nothing` will fail for us and not on redis.

Maybe we should be on par with redis, but I believe having `nopass` roughly meaning `anypass` is as misleading UX experience

**Comment by royjacobson** [comment]
> Maybe we should be on par with redis, but I believe having `nopass` roughly meaning `anypass` is as misleading UX experience.

If it's causing problems with current redis clients we should align with redis.

**Comment by kostasrim** [comment]
> If it's causing problems with current redis clients we should align with redis.

100% but let's first reproduce...

**Comment by girlbossceo** [comment]
Hi @kostasrim, I do like the idea of a more clear behaviour with `nopass`, but this is one of those breaking changes that should have been more clearly announced. I didn't really see anywhere in the release notes of 1.9.0 or 1.10.0 that this was going to be a differing behaviour with ACLs and Redis. I assumed that the implementation of ACLs was not going to impact anything I have running existing because I don't have ACLs setup, Redis just accepts all the connections and assumed that was the case here too.

I believe ioredis uses this AUTH command by default if no password is supplied:
`firefish              |   command: { name: 'auth', args: [ 'default', '' ] }`

https://github.com/redis/ioredis/blob/ec42c82ceab1957db00c5175dfe37348f1856a93/lib/redis/RedisOptions.ts#L38-L54

As I cannot find any code in Firefish that uses its own AUTH command for ioredis which is a problem in itself as the default behaviour of ioredis is to use `AUTH default` with no arguments if no password is supplied.

Dragonfly intends on being a drop-in replacement of Redis, and while I do understand that results will vary, matching Redis's behaviour of default/no ACLs just makes sense to do.

**Comment by kostasrim** [comment]
@girlbossceo 100% for sure I agree if this change breaks client code. 

I will take care of this. 

p.s. I still don;t understand why it calls `auth default`, since it's redundant because once you connect to redis or dragonfly, you are basically connected as default....

**Comment by kostasrim** [comment]
@girlbossceo fixed :)
