### ISSUE TITLE
implement BITFIELD_RO

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#1876]
See https://redis.io/commands/bitfield_ro/ for more details

**Comment by 0xedl** [comment]
Hi, I'd like to work on this!

**Comment by romange** [comment]
Sure, go ahead.

**Comment by chakaz** [comment]
Hi @0xedl, please note that there's also `BITFIELD` command which is missing:
https://github.com/dragonflydb/dragonfly/issues/213
It might be worth to keep that in mind when implementing, for supporting that as well :pray:

**Comment by romange** [comment]
@chakaz  actually BITFIELD is more complicated therefore I actually suggest to start with BITFIELD_RO first and do the refactoring (code reuse) later.

**Comment by chakaz** [comment]
Agreed, just something to keep in mind that's all :)

**Comment by Abhra303** [comment]
Hi @0xedl , are you working on the issue? If you are, consider opening a draft PR so that other could see and comment on the approach :)

**Comment by 0xedl** [comment]
Hi! I will have something ready soon!
