### ISSUE TITLE
HTTP authentication should work with ACLs

### ISSUE THREAD

**Issue by chakaz** [dragonflydb/dragonfly#1889]
Currently, HTTP auth only works with `--requirepass`. With ACLs now supported, we should make it work with them as well.
Note that currently we might actually allow unauthenticated traffic to run commands, although I have not tested it.

Some quotes from @royjacobson:

> We need to allow overriding the authentication in helio
> Probably make the password check a virtual method is good enough
> Then override in dfly

Thanks @royjacobson for agreeing to look into this!

**Comment by kostasrim** [comment]
@chakaz Let me take this :stuck_out_tongue:

**Comment by kostasrim** [comment]
As agreed internally, we decided to only change the authed username in HTTP from `user` to `default`. 

#1950 partially address this and include the functionality required to bake in ACL's in HTTP if desired.
