### ISSUE TITLE
feat (Streams): Support LASTID option for XCLAIM command

### ISSUE THREAD

**Issue by theyueli** [dragonflydb/dragonfly#1898]
From `t_stream.c` of Redis:

```
 * 
 * 
 *  * 6. LASTID <id>:
 *      Update the consumer group last ID with the specified ID if the
 *      current last ID is smaller than the provided one.
 *      This is used for replication / AOF, so that when we read from a
 *      consumer group, the XCLAIM that gets propagated to give ownership
 *      to the consumer, is also used in order to update the group current
 *      ID.
```

**Comment by chakaz** [comment]
I was under the impression that `XCLAIM` is already implemented, what's missing?
@Abhra303

**Comment by theyueli** [comment]
@chakaz it gave me the following error:

```
127.0.0.1:6379> XCLAIM                                                       
(error) ERR unknown command `XCLAIM`  
```

**Comment by chakaz** [comment]
This is odd, we definitely have support for that: https://github.com/dragonflydb/dragonfly/blob/f652e09a4a3281dd16339ce3ceaa608ec426d1bb/src/server/stream_family.cc#L2547

Which Dragonfly version are you using?

**Comment by theyueli** [comment]
i was using an older codebase from my fork (09/02), which did not have the command:

commit 9a8e5208d70114f57be9536d90cf0acafa0c589e 

https://github.com/dragonflydb/dragonfly/commit/9a8e5208d70114f57be9536d90cf0acafa0c589e

I guess the command probably is implemented very recently...

**Comment by theyueli** [comment]
> Only one flag is missing (with a todo comment). So we can close this issue as completed

thanks @Abhra303! maybe you could help modify the ticket to add the details on the option that is missing, if you are working on that, I will change the ticket to be assigned to you...

**Comment by Abhra303** [comment]
Sure @theyueli, the option is `lastid` https://github.com/dragonflydb/dragonfly/blob/f652e09a4a3281dd16339ce3ceaa608ec426d1bb/src/server/stream_family.cc#L1703. I think we can close this one and create a new issue for `lastid`

**Comment by Abhra303** [comment]
I can't modify the issue title. Can you please modify it?

**Comment by theyueli** [comment]
> I can't modify the issue title. Can you please modify it?

Thanks, done!

**Comment by theyueli** [comment]
hi @Abhra303 i'm wondering do you know where I can find a formal spec for this lastID option? I couldn't locate it on Redis' doc explaining its usage.

**Comment by theyueli** [comment]
I just founded in `t_stream.c`... updated the ticket
