### ISSUE TITLE
Add config set for aclfile

### ISSUE THREAD

**Issue by kostasrim** [dragonflydb/dragonfly#1901]
Currently, we can only configure the ACL file on DF bootstrap via the parameter `--aclfile`. 

It would be nice for df to configure it at runtime, via `CONFIG SET` command.

**Comment by Saket009** [comment]
Can you please assign this issue to me ? it will be much appreciated !!

**Comment by kostasrim** [comment]
Hi @Saket009! Welcome to the community! 

It's all yours

**Comment by romange** [comment]
Hi @Saket009 we do not assign issues to first time contributors due to our past experience. Feel free to send a PR and then we will put the issue on you.
