### ISSUE TITLE
Add config set for acllog_max_len

### ISSUE THREAD

**Issue by kostasrim** [dragonflydb/dragonfly#1902]
Currently, we can only configure the size of the `ACL LOG` on DF bootstrap via the parameter `--acllog_max_len`.

It would be nice for DF to be able to configure it at runtime, via CONFIG SET command.

**Comment by amansharma612** [comment]
Hi, I would love to work on this issue as part of Hacktoberfest. Could you please assign me this issue, and describe how should I go about working on it?

**Comment by kostasrim** [comment]
Hi @amansharma612! Unfortunately, somebody opened a PR for this. I haven't checked it yet but I assume they will complete it soon. 

I would highly consider to go over our open issues with label `hacktoberfest` and pick another task :)
