### ISSUE TITLE
Add number of threads to INFO

### ISSUE THREAD

**Issue by royjacobson** [dragonflydb/dragonfly#1904]
We sometimes ask people to post output of `INFO`, would be nice to have the number of shards and number of threads somewhere in there.

**Comment by sourav091** [comment]
can you guide me through this, I wanted to do this

**Comment by chakaz** [comment]
@sourav091 thanks for offering your help!
Generally you'd like to look into `Info()` method: https://github.com/dragonflydb/dragonfly/blob/65fbbdfe077a3453c09be0679f086dbee8e052f1/src/server/server_family.cc#L1263
And add `shard_set->size()` and `service_.proactor_pool().size()`

**Comment by Nithin-532** [comment]
Can I contribute to this

**Comment by chakaz** [comment]
@Nithin-532 Feel free to, it should only be a few lines of code really :)

**Comment by chakaz** [comment]
I haven't heard anything from others on this issue, so @unclebinary1001 feel free to try it out, thanks!

**Comment by romange** [comment]
We can add number of threads only.

**Comment by unclebinary1001** [comment]
> I haven't heard anything from others on this issue, so @unclebinary1001 feel free to try it out, thanks!

Will do!
