### ISSUE TITLE
entries_read is not updated on xreadgroup command

### ISSUE THREAD

**Issue by rounaknandanwar** [dragonflydb/dragonfly#1945]
**Describe the bug**

**To Reproduce**
```shell
xgroup create mystream mygroup $ MKSTREAM

xgroup createconsumer mystream mygroup consumer1
xgroup createconsumer mystream mygroup consumer2

xadd mystream 1-0 test-field-1 test-value-1
xadd mystream 2-0 test-field-2 test-value-2

xreadgroup group mygroup consumer1 STREAMS mystream >

xinfo groups mystream
``` 

Output : 
```
127.0.0.1:6379[1]> xinfo groups mystream
1)  1) "name"
    2) "mygroup"
    3) "consumers"
    4) (integer) 2
    5) "pending"
    6) (integer) 2
    7) "last-delivered-id"
    8) "2-0"
    9) "entries-read"
   10) (integer) 0
   11) "lag"
   12) (integer) 2
``` 

**Expected behavior**
```
127.0.0.1:6379> xinfo groups mystream
1)  1) "name"
    2) "mygroup"
    3) "consumers"
    4) (integer) 2
    5) "pending"
    6) (integer) 0
    7) "last-delivered-id"
    8) "2-0"
    9) "entries-read"
   10) (integer) 2
   11) "lag"
   12) (integer) 0

Notice the difference in entries-read and lag. Both are related and lag is derived from entries-read
```

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS
 - Kernel: Linux 327ea1247755 6.1.29-0-virt # 1-Alpine SMP Wed, 17 May 2023 14:22:15 +0000 aarch64 aarch64 aarch64 GNU/Linux
 - Containerized: Docker
 - Dragonfly Version: Latest, I am using the build version.

**Additional context**
The bug is only reproducible after implementing xinfo command https://github.com/dragonflydb/dragonfly/pull/1533.
This is related to https://github.com/dragonflydb/dragonfly/pull/1533#discussion_r1314938024.
Possible solution - 

- OpRead function makes use of OpRangeFromConsumerPEL & OpRange. Both should not modify the entries_read field for a group.
- It would make sense to update entries_read after these calls are made within the OpRead function.

After this is fixed, xinfo also needs to be fixed for entries-read and lag fields.

**Comment by theyueli** [comment]
hi @rounaknandanwar 

Could you try to see if this patch resolves the problem? thanks!

https://github.com/dragonflydb/dragonfly/pull/1946

**Comment by rounaknandanwar** [comment]
Hi @theyueli ,

This looks good! I pulled your branch and tried it with my code.
Thanks for the fix :)
Please feel free to close the issue once your change is merged.

**Comment by theyueli** [comment]
Excellent! thank you for the fast response!
