### ISSUE TITLE
feat (Streams): Support entries-read and lag fields in XINFO GROUPS command output

### ISSUE THREAD

**Issue by FZambia** [dragonflydb/dragonfly#1948]
Hello! One more desired improvement for streams API:  currently`XINFO GROUPS` does not return some fields which are available in Redis:

Redis (7.2.1):

```
127.0.0.1:6379> "XGROUP" "CREATE" stream group "0" MKSTREAM
OK
127.0.0.1:6379> XINFO GROUPS stream
1)  1) "name"
    2) "group"
    3) "consumers"
    4) (integer) 0
    5) "pending"
    6) (integer) 0
    7) "last-delivered-id"
    8) "0-0"
    9) "entries-read"
   10) (nil)
   11) "lag"
   12) (integer) 0
```

DF (latest weekly):

```
127.0.0.1:6379> "XGROUP" "CREATE" stream group "0" MKSTREAM
OK
127.0.0.1:6379> XINFO GROUPS stream
1) 1) "name"
   2) "group"
   3) "consumers"
   4) (integer) 0
   5) "pending"
   6) (integer) 0
   7) "last-delivered-id"
   8) "0-0"
```

So `entries-read` and `lag` are missing. I am using `lag` value for monitoring the queue.

**Comment by theyueli** [comment]
thanks @FZambia for reporting. It turned out these two are newly added to Redis 7.0. We shall also have this available in the next week's weekly build.

Fixed in:
https://github.com/dragonflydb/dragonfly/pull/1952

**Comment by theyueli** [comment]
hi @FZambia, just want to provide a quick update, at the moment, all the Redis STREAM API has now been supported (e.g. XACK, XAUTOCLAIM ...)

XAUTOCLAIM should be available in the next week's weekly build. Please just let us know if any issue is found. Thanks!

**Comment by romange** [comment]
@theyueli @FZambia for the reference, our weekly builds can be pulled via 
`docker pull ghcr.io/dragonflydb/dragonfly-weekly`
