### ISSUE TITLE
Parameter modification not effective(snapshot_cron)

### ISSUE THREAD

**Issue by kissingtiger** [dragonflydb/dragonfly#1962]
**Describe the bug**
curl  -u user:xxxxx  '172.xxx.xxx.xxx:6379/flagz?flag=snapshot_cron&value=0 1 * * 1'
I am using this method to adjust parameters but it is not effective. Is there a way to remove or adjust this parameter without restarting the service?

**Environment (please complete the following information):**
 - OS: [Alibaba Cloud Linux release 3 (Soaring Falcon) ]
 - Kernel: 5.10.134-14.al8.x86_64 #1 SMP Thu Apr 27 16:46:29 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
 - Containerized?: [Bare Metal]
 - Dragonfly Version: [v1.10.0]

**Comment by UkuLoskit** [comment]
duplicates https://github.com/dragonflydb/dragonfly/issues/1762
