### ISSUE TITLE
Crash during connection migrate

### ISSUE THREAD

**Issue by Ronaknayak01** [dragonflydb/dragonfly#1976]
**Describe the bug**

**To Reproduce**
1. Insert records using `command`
2. Query records using `command`

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [ubuntu 20.04]
 - Kernel: # Command: `uname -a`
 - Containerized?: [Bare Metal, Docker, Docker Compose, Docker Swarm, Kubernetes, Other]
 - Dragonfly Version: [e.g. 0.3.0]

**Reproducible Code Snippet**
```
# Minimal code snippet to reproduce this bug
```

**Additional context**

**Comment by dranikpg** [comment]
@Ronaknayak01 It seems like you submitted a blank issue with a copied title(?). If you experience any issues with Dragonfly, please re-submit your issue with a description of the accident
