### ISSUE TITLE
ACL Load does not evict open connections

### ISSUE THREAD

**Issue by kostasrim** [dragonflydb/dragonfly#2003]
`ACL LOAD` is used to load the contents of an ACL file into DF.

The issue is that some of the previously existed users might not exist anymore. These users, might already have open connections with DF, creating a security hole in the system. 

The fix should be simple/straightforward, use `EvictOpenConnectionsOnAllProactors` to evict all open connections from users that no longer exist in the newly loaded ACL file.

For example:

Users before new ACL file loaded:
1. default
2. mike
3. ada

Users after new ACL file loaded:
1. default
2. ada

Therefore, we should evict all open connections from the user `mike`.

**Comment by azuredream** [comment]
Hi @kostasrim,

I've created PR#2018 to fix this.
Could you assign this issue to me if my fix makes sense?
I'm a beginner to dragonflydb, trying to start with small changes.

Thanks!
