### ISSUE TITLE
High CPU usage when running in epoll mode

### ISSUE THREAD

**Issue by kurtisane** [dragonflydb/dragonfly#2014]
Running DragonflyDB in Docker via Docker-Compose like this :
` 
dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: 2000000
    ports:
      - "6379:6379"
`
After starting the log shows:
![image](https://github.com/dragonflydb/dragonfly/assets/22451592/56a4d292-687d-45ad-a8e3-309a5d15d480)

![image](https://github.com/dragonflydb/dragonfly/assets/22451592/02880657-a960-4c25-bc30-2a4311b63963)

And docker stats is telling me this :
![image](https://github.com/dragonflydb/dragonfly/assets/22451592/77b6a3f9-84e4-459a-aada-baf8b45c6b60)

How can it be that it is using 25% CPU usage by just sitting there in idle ? The Memory usage aside. 
Is my configuration "wrong" ?

**Comment by romange** [comment]
The reason is - you are running in epoll_mode (see the logs, iouring is not supported for some reason). On my machine:
`docker run --network=host ghcr.io/dragonflydb/dragonfly  --force_epoll`  - takes 200% CPU, while with iouring it goes down to 7%.

**Comment by UkuLoskit** [comment]
My two cents as well:

<img width="1085" alt="Screenshot 2023-10-14 at 21 52 42" src="https://github.com/dragonflydb/dragonfly/assets/920770/6e3278a6-c4d4-4fc8-8575-a891fb74a89a">

```
processor	: 63
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 49
model name	: AMD EPYC 7502P 32-Core Processor
stepping	: 0
microcode	: 0x8301055
cpu MHz		: 1497.088
cache size	: 512 KB
physical id	: 0
siblings	: 64
core id		: 31
cpu cores	: 32
apicid		: 63
initial apicid	: 63
fpu		: yes
fpu_exception	: yes
cpuid level	: 16
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd mba sev ibrs ibpb stibp vmmcall sev_es fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca
bugs		: sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass retbleed
bogomips	: 4990.62
TLB size	: 3072 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]
```


![dragonfly_debug_14102023_164956 prof](https://github.com/dragonflydb/dragonfly/assets/920770/da4c04ed-c7e6-4b6f-aa10-b228d20e37c5)
