### ISSUE TITLE
Renaming commands does not work for ACL commands

### ISSUE THREAD

**Issue by bogdanp05** [dragonflydb/dragonfly#2036]
**Describe the bug**
Renaming commands does not work for ACL commands e.g. `acl list`

**To Reproduce**
1. Start Dragonfly with `./dragonfly --logtostderr --rename_command "acl=foo"`
2.  Connect to Dragonfly using `redis-cli`
3. Type `foo list`
4. `(error) ERR Wrong number of arguments for acl command`

**Expected behavior**
See a list of users.

**Environment (please complete the following information):**
 - OS: Fedora 38
 - Kernel: Linux toolbox 6.3.8-100.fc37.x86_64
 - Containerized?: running in a Fedora toolbox container
 - Dragonfly Version: 1.11.0

**Additional context**
Renaming seems to work for other commands e.g. starting Dragonfly with
`./dragonfly --logtostderr --rename_command "save=foo"` and running `> foo` in the cli will correctly execute the save command.

**Comment by kostasrim** [comment]
Hi @bogdanp05 , thank you for reporting this :rocket: . I confirm it's a bug -- we will take care of it!

**Comment by chakaz** [comment]
It seems to be related to `ACL` itself, I just tested with renaming `SET` and it works fine

**Comment by chakaz** [comment]
Oh, I see the edit now, you already mentioned that :)

**Comment by bogdanp05** [comment]
@chakaz yeah sorry about the initial title, I was confused myself. But it seems to work with other commands e.g. `config`.
