### ISSUE TITLE
dragonflydb support unix socket connection like redis

### ISSUE THREAD

**Issue by hnimminh** [dragonflydb/dragonfly#206]
### Discussed in https://github.com/dragonflydb/dragonfly/discussions/168

<div type='discussions-op-text'>

<sup>Originally posted by **hnimminh** June 22, 2022</sup>
Interesting project, Does dragonflydb support unix socket connection like Redis?</div>

**Comment by romange** [comment]
@hnimminh  if you build from main, you can use `unixsocket` flag for this.
