### ISSUE TITLE
`--tls_ca_cert_dir` doesn't work

### ISSUE THREAD

**Issue by Pothulapati** [dragonflydb/dragonfly#2081]
**Describe the bug**

Just passing a dir with certificates to this argument does not work in Dragonfly while `--tls_ca_cert_file` works fine
with the same file. I get the following error message

```
Error accepting a client connection: certificate verify failed
````

This seems similar to similar issues in Redis https://github.com/bitnami/charts/issues/8854, https://github.com/redis/redis/issues/7392

**To Reproduce**
1. Insert records using `command`
2. Query records using `command`

**Expected behavior**

Expect it to work as expected or have requirements in the flag help section mentioined.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [ubuntu 20.04]
 - Kernel: # Command: `uname -a`
 - Containerized?: [Bare Metal, Docker, Docker Compose, Docker Swarm, Kubernetes, Other]
 - Dragonfly Version: [e.g. 0.3.0]

**Reproducible Code Snippet**
```
# Minimal code snippet to reproduce this bug
```

**Additional context**

**Comment by adiholden** [comment]
@kostasrim was this added to documentation? can we close the issue?

**Comment by kostasrim** [comment]
@adiholden now it is :)
