### ISSUE TITLE
--pidfile parameter for the dragonflydb binary

### ISSUE THREAD

**Issue by anosulchik** [dragonflydb/dragonfly#209]
`--pidfile=</path/to/dragonflybd.pid>` would make it easier to integrate it with [monit](https://mmonit.com/monit/). When this param is specified, dragonflydb would write its pid into specified file or fail if it's possible e.g. due to permission.

**Comment by iko1** [comment]
@romange, I'd like to implement a function that creates `pidfile `file, where is the suitable place to place that function?
I think the file `proc_util.c` within helio can be an option. 
The function will be called from server bootstrap in `dfly_main.cc`

**Comment by romange** [comment]
Thanks @iko1 .  Let's just implement everything inside dfly_main.cc.
