### ISSUE TITLE
PEXPIRE in 1.11.0 breaks TTL in some cases

### ISSUE THREAD

**Issue by Letfdsada** [dragonflydb/dragonfly#2105]
**Describe the bug**
I'm using code that updates keys TTL in the background using a Lua script. With update 1.11.0 i noticed that keys ttl has become huge.
Behaviour is normal in 1.10.0.

**To Reproduce**
1. Create string: `set key value`
2. Execute lua script: `eval "redis.call('pexpire', KEYS[1], ARGV[1])" 1 key`
3. See huge ttl: `ttl key`

**Expected behavior**
I expect that when using PEXPIRE 60000, keys ttl will become 60 seconds.

**Screenshots**

https://youtu.be/V-pEatTKB6A

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS
 - Kernel: Linux ***** 5.15.90.1-microsoft-standard-WSL2 `#1 SMP` Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux, Linux ***** 5.4.0-155-generic `#172-Ubuntu SMP` Fri Jul 7 16:10:02 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 - Containerized?: Yes (Docker, Kubernetes)
 - Dragonfly Version: 1.11.0 (does not appear in 1.10.0)

**Reproducible Code Snippet**
```
redis-cli
set key value px 60000
eval "redis.call('pexpire', KEYS[1], ARGV[1])" 1 key 60000
ttl key
```

**Additional context**

**Comment by Letfdsada** [comment]
Perhaps you know [something](https://github.com/dragonflydb/dragonfly/pull/1724)? @dranikpg @kostasrim

**Comment by dranikpg** [comment]
Yes, I do know _something_ 😄  Unfortunately it did break indeed... 😢 The issue is already fixed: https://github.com/dragonflydb/dragonfly/pull/2080

We are most likely planning to release a patch version by the end of this week / next week that will include this fix, so please stay tuned
