### ISSUE TITLE
Dragonfly 1.12.0 does not accept renamed commands longer than 15 chars

### ISSUE THREAD

**Issue by bogdanp05** [dragonflydb/dragonfly#2131]
**Describe the bug**
Title. This is a regression from Dragonfly 1.11.0, where it used to work.

**To Reproduce**
1. `./dragonfly  --logtostderr --rename_command save=abcdefghijklmnop`
2. In a different terminal: 
```
redis-cli
127.0.0.1:6379> abcdefghijklmnop
(error) ERR unknown command `ABCDEFGHIJKLMNOP
```

3. `./dragonfly  --logtostderr --rename_command save=abcdefghijklmno`
4. In a different terminal: 
```
redis-cli
127.0.0.1:6379> abcdefghijklmno
OK
```

**Expected behavior**
Command renames should work when they're longer than 15 chars. I think it's ok to have a sane length limit, but 15 seems too short, I guess there's a "2 bytes" bug somewhere.

**Environment (please complete the following information):**
 - OS: Fedora 38
 - Kernel: Linux toolbox 6.5.8-100.fc37.x86_64
 - Containerized?: Fedora toolbox container
 - Dragonfly Version: 1.12.0

**Comment by chakaz** [comment]
It might be small string optimization, capped at 16 bytes

**Comment by romange** [comment]
@bogdanp05  we will release 1.12.1 with the fix shortly

**Comment by bogdanp05** [comment]
awesome!

**Comment by romange** [comment]
https://github.com/dragonflydb/dragonfly/releases/tag/v1.12.1 was released
