### ISSUE TITLE
Scripts should return error on non-conventional (global, nokey) commands

### ISSUE THREAD

**Issue by dranikpg** [dragonflydb/dragonfly#2134]
```
redis.call('FLUSHALL')
```

crashes DF in the regular mode, it should return an error instead, that any of those two should be used:

```
#!lua flags=disable-atomicity
redis.call('FLUSHALL')
```

```
#!lua flags=allow-undeclared-keys
redis.call('FLUSHALL')
```

or even add a new flag...? like management which implicitly means = allow-undeclared-keys?

**Comment by romange** [comment]
lets reject it from lua scripts as a first step.

**Comment by dranikpg** [comment]
> lets reject it from lua scripts as a first step.

That's what I mean by returning an error 🙂
