### ISSUE TITLE
MODULE LIST Support

### ISSUE THREAD

**Issue by admtech** [dragonflydb/dragonfly#2135]
RedisInsight and other Redis GUIs query the available modules to recognize the feature set. Since DragonflyDB supports JSON and now also the Search (FT.SEARCH (beta)), it would make sense to display these features as activated under "MODULE LIST" so that they can be used in the GUIs. 

For example, the following message appears under RedisInsight and "Workbench" when using the Json commands: "RedisJSON is not available for this database".

![Bildschirmfoto 2023-11-06 um 13 19 40](https://github.com/dragonflydb/dragonfly/assets/5912839/edae2179-f774-4757-9354-e94d31d962db)

I have activated the Json module and also the Search module under redis (7.2.2) and this is what it looks like (please ignore the timeseries module):

```
127.0.0.1:6479> MODULE LIST
1) 1) "name"
   2) "timeseries"
   3) "ver"
   4) (integer) 11006
   5) "path"
   6) "/opt/redis-stack/lib/redistimeseries.so"
   7) "args"
   8) (empty array)
2) 1) "name"
   2) "ReJSON"
   3) "ver"
   4) (integer) 20606
   5) "path"
   6) "/opt/redis-stack/lib/rejson.so"
   7) "args"
   8) (empty array)
3) 1) "name"
   2) "search"
   3) "ver"
   4) (integer) 20808
   5) "path"
   6) "/opt/redis-stack/lib/redisearch.so"
   7) "args"
   8) (empty array)

```

Thank you :-)

**Comment by romange** [comment]
yes, that's easy to fix.

**Comment by dranikpg** [comment]
What version of redis insight are you using? Mine (2.34) detects search by looking for available commands 

![image](https://github.com/dragonflydb/dragonfly/assets/20553775/9ca0d706-23a9-4333-b9a7-2a9c0a838709)

PS: will still add module list, just mentioning that the discovery way likely changed

**Comment by admtech** [comment]
That's right, "RediSearch" and also "RedisJson" is recognized as a module in RedisInsight-v2 (2.32.0) since Dragonfly 1.12. I hadn't even noticed that. This was not the case in Dragonfly 1.11. Since the message above was displayed in the Workbench (see screenshot), I thought it was due to the lack of module support. It looks like RedisInsight is getting the information from somewhere else, you're right.

However, I still think that it makes sense to read out the information under "Module List" (e.g. for other GUIs or IDEs).

**Comment by romange** [comment]
@admtech do you know which GUI/IDE requires this (so we could test it) ? What's Workbench?

**Comment by admtech** [comment]
> What's Workbench?

This is the third icon in RedisInsight (left-hand side). This switches to a kind of graphical redis-cli mode.

> do you know which GUI/IDE requires this (so we could test it) 

Currently no, unfortunately. We use the IDEs from jetbrains, they have a Redis driver but they don't have Json support yet (but another error https://github.com/dragonflydb/dragonfly/issues/2137). I still know the GUI from Navicat Redis, which I will install and test in the next few days.
