### ISSUE TITLE
Search support

### ISSUE THREAD

**Issue by Delicious-Bacon** [dragonflydb/dragonfly#214]
I've seen JSON is in plans: https://github.com/dragonflydb/dragonfly/issues/104

What about Search (RediSearch)?

It's part of [Redis Stack](https://redis.io/docs/stack/), and is one of the pain points when doing concurrent index searching—latency spikes up when concurrently searching/aggregating an index with a lot of documents.

**Describe the solution you'd like**
Redis-like support for Search commands.

**Additional context**
A list of RediSearch commands: https://redis.io/commands/?name=FT.

**Comment by romange** [comment]
Designing RedisSearch from scratch is a huge project (unlike JSON). I won't think we can pursue it realistically speaking within the next 2 years. Sorry.

**Comment by Delicious-Bacon** [comment]
Thanks for the reply!

Well, maybe in the next 2 years, then! 😄 👍

**Comment by romange** [comment]
@Delicious-Bacon, I was over-pessimistic. We wilill have an experimental version of FT.SEARCH in v1.10 (next release).
Would you like to try it out?

**Comment by Delicious-Bacon** [comment]
@romange I took a U-turn away from the DragonflyDB and implemented a different DB for the cache.

It's great to hear it's getting a search implementation, but I don't have an active implementation of it to experiment with it.

Good luck with the stable implementation!

**Comment by romange** [comment]
Cool, closing the issue.
