### ISSUE TITLE
Allow binding to all available network interfaces

### ISSUE THREAD

**Issue by bogdanp05** [dragonflydb/dragonfly#2142]
**Did you search GitHub Issues and GitHub Discussions First?**
Yes.

**Is your feature request related to a problem? Please describe.**
In Redis, not adding any `bind` line in `redis.conf` means that Redis will listen to all available network interfaces. So you can connect from the same machine by either passing localhost or the IP of the machine. 

It would be nice to have the same option in Dragonfly. As far as I can tell (+plus checking the README), you can only specify 1 bind interface. I tried using `--bind "*"`, `--bind "::*"`, and `--bind ""`, but they all meant that Dragonfly was binding to localhost, not all interfaces. 

**Describe the solution you'd like**
Dragonfly should be able to bind to all interfaces by passing something like `--bind "*"`. A client from the same machine should be able to connect to it by using `-h localhost` or `-h <machine_IP>`.

**Describe alternatives you've considered**
It would also work for my use case to simply allow passing multiple interfaces to bind to e.g. `--bind IP1 IP2` or `--bind IP1 --bind IP2`, but you'll still probably to allow binding to all in the future.

**Additional context**
I tried this with Dragonfly 1.11 and 1.12.

**Comment by romange** [comment]
@bogdanp05 have you tried `--bind "0.0.0.0" ` ?

**Comment by bogdanp05** [comment]
Yeah this works, wish I'd tried it sooner! Thanks a lot @romange! Closing.
