### ISSUE TITLE
ZINTER command is absent

### ISSUE THREAD

**Issue by BorysTheDev** [dragonflydb/dragonfly#2147]

**Comment by highpon** [comment]
Hi, I'd like to work on this!

**Comment by romange** [comment]
cool, send a pr :)

**Comment by highpon** [comment]
@romange 
Thanks for your response.
I implement ZINTER command and create draft PR.

My added test fails in the local development environment. I am currently investigating this problem.

If this problem is solved, I will open https://github.com/dragonflydb/dragonfly/pull/2164 .

**Comment by romange** [comment]
Do you know how to check/control debug logs? I.e how to use vmodule flag?

**Comment by highpon** [comment]
This is the first time I have heard the term vmodule.
I would like to know if it is possible.

By the way, I have been debugging with VSCode, using breakpoints.

**Comment by highpon** [comment]
I modified #2164 so that the test succeeds.
I opened #2164 .

**Comment by romange** [comment]
if using debugger worked for you, it's great. you can run `zset_family_test --vmodule=zset_family=1` and then check `/tmp/zset_family_test.INFO` log for example with all the VLOG/DVLOG statements.
