### ISSUE TITLE
ACL does not work with flag `restricted_commands`

### ISSUE THREAD

**Issue by kostasrim** [dragonflydb/dragonfly#2154]
**Describe the bug**

ACL family is not working with `restricted_commands`. 

Thanks @adiholden for catching this.

**Comment by andydunstall** [comment]
@kostasrim On the control plane we're using `--restricted_commands="acl setuser, ..."` which works ok. We don't want to block all ACL commands so its useful to be able to specify a subset. Let us know if this behaviour changes and we need to update

**Comment by kostasrim** [comment]
@andydunstall What I had in mind was to match the behaviour with the other family of commands. For example:
`--restricted_commands=config`. If I use, `config set` or `config get` both will be restricted. On the other hand, if I do `--restricted_commands="config set"` none of them will be restricted.

`ACL's` are the only family of commands that do not have this behaviour and I wanted them to be on par with the rest of commands.

Is there a specific reason you are restricting a subset of the ACL commands?

**Comment by andydunstall** [comment]
Ok so will blocking a subset of ACL commands still work?

> Is there a specific reason you are restricting a subset of the ACL commands?

Its not a big issue yet as we don't have any ACL management on the control plane, so far we've just copied the blocked ACL commands from https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/RestrictedCommands.html

So customers can't update ACL - but can still get info like `whoami` and `getuser`

**Comment by kostasrim** [comment]
> Ok so will blocking a subset of ACL commands still work?

With what I had in mind, no not really -- it would't as it would bring ACL's on par with the rest of commands.

However, after this discussion I think it's more sensible to keep them as is for now. In fact, the rest of the subcommands should be implemented that way such that you can finely restrict them (that is `CONFIG SET, CONFIG GET etc`

**Comment by andydunstall** [comment]
> However, after this discussion I think it's more sensible to keep them as is for now

Up to you - as mentioned we don't have any ACL setup on the control plane yet so it doesn't matter if we block all ACL commands for now - then we can revisit the issue when we add control plane ACL

> the rest of the subcommands should be implemented that way such that you can finely restrict them

Yeah that would be nice - especially if you could either block all subcommands (eg `CONFIG`) or just a subset
