### ISSUE TITLE
improper handling of JSON path "."

### ISSUE THREAD

**Issue by consortium-frank** [dragonflydb/dragonfly#2175]
**Describe the bug**
The current behavior is to treat a JSON path of "." as "$" for compatibility with tools like RedisInsight and official Redis libraries; however, this is different from the way Redis itself handles the legacy path ".".

**To Reproduce**

**Redis**

> 127.0.0.1:6379> JSON.SET doc $ '{"a":2}'
> OK
> 127.0.0.1:6379> JSON.GET doc
> {"a":2}
> 127.0.0.1:6379> JSON.GET doc $
> [{"a":2}]
> 127.0.0.1:6379> JSON.GET doc .
> {"a":2}

**Dragonfly**

> 127.0.0.1:6379> JSON.SET doc $ '{"a":2}'
> OK
> 127.0.0.1:6379> JSON.GET doc
> {"a":2}
> 127.0.0.1:6379> JSON.GET doc $
> [{"a":2}]
> 127.0.0.1:6379> JSON.GET doc .
> [{"a":2}]

**Expected behavior**
Providing a path of "." should give the same output as not providing a path at all. This would increase compatibility with RedisInsight and official Redis libraries.

I'm not as intimately familiar with other Redis libraries but redis-py automatically adds a path of "." if no path is provided. This is causing compatibility issues with using Dragonfly as a drop-in replacement since `redis.json().get("key")` is always returning a list due to the implied "." path.

**Comment by romange** [comment]
thank you for describing the issue in such detail! :)
we will fix it before the next release.

**Comment by consortium-frank** [comment]
Excellent! Thanks for the quick response and resolution, Roman.

**Comment by admtech** [comment]
This is the same error as in https://github.com/dragonflydb/dragonfly/issues/1523 and https://github.com/dragonflydb/dragonfly/issues/2053

As I understand it, it has to do with json path v1 and v2 syntax.

**Comment by consortium-frank** [comment]
Before making this, I searched for issues related to JSON and didn't see either issue. You are correct in that it relates to legacy v2 syntax but, more importantly in my case, it is altering the way the official Redis python library returns results. To give a python specific example that shows the behavior:

**Redis:**
> db.json().set("doc", "$", {"a":2})
> True
> db.json().get("doc", "$")
> [{'a': 2}]
> db.json().get("doc", ".")
> {'a': 2}
> db.json().get("doc")
> {'a': 2}

**Dragonfly:**
> db.json().set("doc", "$", {"a":2})
> True
> db.json().get("doc", "$")
> [{'a': 2}]
> db.json().get("doc", ".")
> [{'a': 2}]
> db.json().get("doc")
> [{'a': 2}]

This behavior difference is preventing me from implementing Dragonfly in our environment currently. We use `get` in most places without a supplied path because we want the entire JSON structure, but the code is expecting the original element instead of a list containing the element.

I'm not asking for JSON path v1 support right now, but it should eventually be implemented if Dragonfly wants to be considered a genuine drop-in replacement for Redis. All I need is for "." not to be handled like "$" and instead be handled like no path was provided because this is an unexpected significant difference to the output.

I haven't tested it or created a PR because my C++ is a bit rusty, but I'm pretty sure all that needs to change is line 92 of json_family.cc from `path = "$"sv;` to `path = ""sv;`

**Comment by admtech** [comment]
Oh, that wasn't meant to be a criticism, I just wanted to summarize the issues.
For example, RedisInsight also uses the legacy path, so json is currently not displayed correctly (in an array see https://github.com/dragonflydb/dragonfly/issues/2053). Therefore you cannot edit or delete json entries.
