### ISSUE TITLE
Support RESP3 protocol

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#218]
RESP3 is an enhancement of RESP2. Specifically, it encodes response types as part of the protocol. It's much easier to build client libraries with RESP3 because a client library does not need to know the semantics of the command in order to parse them. 

Relates to #129 #180 and #102

**Comment by heri16** [comment]
Also "CLIENT TRACKING" support is missing from: https://github.com/dragonflydb/dragonfly/blob/main/docs/api_status.md

https://redis.io/commands/client-tracking/

https://redis.io/docs/manual/client-side-caching/

**Comment by ashotland** [comment]
Sidekiq >= 7 uses a RESP3 redis client by default:
https://github.com/sidekiq/sidekiq/blob/4c101d243e9589cd3d1a81060dac602beb1652a1/docs/7.0-Upgrade.md#redis-client

**Comment by ashotland** [comment]
In progress - have a working draft 

Need to fix rendering of zrange withscores
And organise the code and tests for PRs
