### ISSUE TITLE
High IOWAIT usage

### ISSUE THREAD

**Issue by Jeglerjeg** [dragonflydb/dragonfly#2181]
**Describe the bug**
While dragonfly is running, all free CPU time is used as IOWAIT even when idle and with no keys stored

**To Reproduce**
1. Run dragonflydb
2. Check CPU usage through a tool like top
3. See high IOWAIT

**Expected behavior**
IOWAIT is only consumed when IO operations happen.

**Environment (please complete the following information):**
```
 - OS: Debian 12.2
 - Kernel: 6.1.0-13-arm64 #1 SMP Debian 6.1.55-1 (2023-09-29) aarch64 GNU/Linux
 - Containerized?: Docker
 - Dragonfly Version: 1.12.1
```

**Comment by romange** [comment]
Seems that it's caused by iouring API treating pending io requets as iowait even for networking. therefore it's a behavior change on kernel side. See https://github.com/axboe/liburing/issues/943  for more info.
