### ISSUE TITLE
introduce STICK command

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#219]
DF (similarly to Redis OSS) allows process-wide configuration (`cache_mode`) of whether to support records eviction or not.

The community asked on multiple occasions for a feature that allows whitelisting keys, so that the eviction policy won't kick them out. 
Sometimes it's useful when the datastore is mostly cache but has some metadata keys that store the cache state.

I suggest introducing a new command, something like STICK or BIND or GLUE. 
Say, `STICK key1 key2 key3` will mark those keys (only those that already exist) as non-evictable. Of course, explicit DEL or TTL will still work on them as expected.

**Comment by dranikpg** [comment]
* What should the updated eviction process look like? Currently it just pops from a random stash bucket. But what if all its values are sticky? Probably scan the whole segment? Or is that too costly in case of repeated failure?

* Stickyness shoud just be a `MaskBit` is `CompactObj`, right?

**Comment by romange** [comment]
Good questions, @dranikpg .

1. You are considering a corner case where STICK keys are the majority. Since this feature is experimental, I would first implement the simplest fallback solution - return "out of memory" error. This path already exists for non-caching mode. Then we could improve it IF there will be a customer adoption for this feature. 

2. Yes, the code there is a bit messy, and some things are experimental, but that's what I would do 💯

**Comment by dranikpg** [comment]
Great, I'll try this out then if its free to take up

**Comment by romange** [comment]
Go for it!

**Comment by romange** [comment]
Fixed by #245
