### ISSUE TITLE
Build issue. Linker looking in wrong dir

### ISSUE THREAD

**Issue by Forza-tng** [dragonflydb/dragonfly#220]
**Describe the bug**
It seems that the linker is looking in the wrong path for the third_party `.a` files. For example `third_party/libs/dconv/lib/libdouble-conversion.a` is actually available at `third_party/libs/dconv/libdouble-conversion.a`. The same goes for all of the files in the output below. 

**To Reproduce**
1.  `git clone --recursive https://github.com/dragonflydb/dragonfly && cd dragonfly`
2. `helio/blaze.sh -release`
3. `cd build-opt`
4. `ninja dragonfly`

**Expected behavior**
Clean build. 

**Screenshots**
```
/usr/lib/gcc/x86_64-pc-linux-gnu/12.1.1/../../../../x86_64-pc-linux-gnu/bin/ld: cannot
find third_party/libs/dconv/lib/libdouble-conversion.a: No such file or directory
/usr/lib/gcc/x86_64-pc-linux-gnu/12.1.1/../../../../x86_64-pc-linux-gnu/bin/ld: cannot
find third_party/libs/mimalloc/lib/libmimalloc.a: No such file or directory
/usr/lib/gcc/x86_64-pc-linux-gnu/12.1.1/../../../../x86_64-pc-linux-gnu/bin/ld: cannot
find third_party/libs/xxhash/lib/libxxhash.a: No such file or directory
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Desktop (please complete the following information):**
 - OS: Gentoo Linux
 - Kernel: 5.17.15-gentoo 
 - Containerized?: No. Bare metal
  - Version 2.8

**Additional context**

I've tried with GCC 11.3.0 and 12.1.1 with the same results. GCC 12 produced some additional warnings, but it compiled fine if I moved the `.a` files to the correct dirs.

**Comment by romange** [comment]
Weird. Maybe it's related to newer cmake? 
1. Where did it put  `libdouble-conversion.a` before you moved it?
2. What's your cmake version?

**Comment by Forza-tng** [comment]
I'm using cmake 3.22.4.

**Comment by romange** [comment]
I succeeded to reproduce on Gentoo with cmake 3.22.2.
Submitted https://github.com/romange/helio/commit/a2fffa3132683fa61f53f9e80caa57e4f714f0bc 
will fix dragonfly tomorrow.

**Comment by Forza-tng** [comment]
Amazing :) I'll try it later tonight again.

Thank you 🙏
