### ISSUE TITLE
improve MGET performance bottlenecks 

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#2203]
Seems that MGET is quite cpu intensive:

1. SendMGetResponse is pretty naive, copies everything into a single blob and one can see it shows on the flamegraph.
we have SendStringArrInternal but it does not fit `OptResp` case. Can something be done here? 
2. we use `vector<string>` to fetch multiple strings from shard threads into the coordinator thread.  And we reallocate it again and again. Seems like a more complicated effort to fix. what can be done here? The challenge here is that strings are allocated in shard threads and then deallocated in the coordinator threads. 

![image](https://github.com/dragonflydb/dragonfly/assets/3674760/60f0c274-5c0a-43f4-8eb8-ee2cbfeb9a87)

**Comment by romange** [comment]
@dranikpg regarding (1) - do you have any advice?

**Comment by dranikpg** [comment]
about (1)? It seems pretty straightforward... Just remove the intermediate copy by using SendArray and then SendString to write directly into buf_

**Comment by dranikpg** [comment]
We also have some places that use `vector<T> shard_results` to capture per-shard results. A solution would be to implement result capture by the transaction. Remember we have 46 bytes of cacheline padding inside PerShardData that can be used for it - let's use it, so we don't have to allocate vectors

What I actually notice by looking at it: We never set the PerShardData's alignment to make the start address to reside on the cacheline start 😨

**Comment by dranikpg** [comment]
about (2): vector<string> is double indirection, always bad... let's just calculate ahead the total string sizes (and keep the dashtable iterators) and then slap them together into a single string + sizes array with SOO (.e.g absl fixed-array) - We actually use the same for PipelineMessage!

**Comment by romange** [comment]
(1) you mean using StartArray method?

**Comment by dranikpg** [comment]
Yes, from what I understood from the code its `*arr-len $v-1-len v1 ...`, so StartArray + SendBulkString. Maybe something needs to be tweaked for nulls - doesn't matter, we can always just write directly into buf_ in any plausible way 🙂

**Comment by romange** [comment]
Improved MGET code (#2212). Closing
