### ISSUE TITLE
random crash

### ISSUE THREAD

**Issue by yovanoc** [dragonflydb/dragonfly#2204]
sorry I can't help more I experienced a random crash yesterday didn't see it right away and know what I was doing but not something special I guess.

![CleanShot 2023-11-23 at 07 56 13](https://github.com/dragonflydb/dragonfly/assets/7302317/20bee238-8141-40e1-a433-5b72f93936e5)

**Comment by romange** [comment]
@yovanoc what container version do you run?

**Comment by yovanoc** [comment]
We can see it in the screen: 1.12.1

**Comment by dranikpg** [comment]
v 1.12.1, from the logs

Please use --pipeline_squash=0 for now, we know this regression 😢

**Comment by yovanoc** [comment]
> v 1.12.1, from the logs
> 
> 
> 
> Please use --pipeline_squash=0 for now, we know this regression 😢

Ahah no problems! Thanks for your hard work

**Comment by romange** [comment]
@dranikpg can we close this one?
