### ISSUE TITLE
Prometheus metric dragonfly_commands_duration_seconds_total is wrong (milliseconds instead of seconds)

### ISSUE THREAD

**Issue by euanhunteratom** [dragonflydb/dragonfly#2213]
**Describe the bug**
The Prometheus metric `dragonfly_commands_duration_seconds_total` from `/metrics` is wrong; it's off by a factor of 1000, meaning it is effectively recording milliseconds rather than seconds as the name implies.

**To Reproduce**
1. Call `/metrics` and observe `dragonfly_commands_duration_seconds_total` metric
2. Issue `INFO commandstats` with a client
3. Divide `usec` in INFO output by 1x10^6 to get seconds
4. Compare for same command in `/metrics` output. Notice different by factor of 1000

**Example**
Output from `/metrics`
```
dragonfly_commands_duration_seconds_total{cmd="AUTH"} 0.264
dragonfly_commands_duration_seconds_total{cmd="CLIENT"} 0.805
...
```

Output from `INFO commandstats`
```
cmdstat_AUTH:calls=304,usec=264,usec_per_call=0.868421
cmdstat_CLIENT:calls=28,usec=805,usec_per_call=28.75
...
```

Compare metrics value to INFO usec
* AUTH - 0.264s != 264µs
* CLIENT - 0.805s != 805µs

**Expected behavior**
`dragonfly_commands_duration_seconds_total` should be in seconds as the name implies rather than milliseconds.

**Environment (please complete the following information):**
 - Containerized?: Kubernetes
 - Dragonfly Version: df-v1.10.0

**Additional context**
I think the issue is in `server_family.cc` https://github.com/dragonflydb/dragonfly/blob/cade6850bf51e515d308e1e9ee4ce88f4fff866e/src/server/server_family.cc#L919C59
This line should probably multiple by 0.000001 (1x10^-6) instead of 0.001 (1x10^-3) to convert the microseconds (?) value to seconds.

**Comment by romange** [comment]
Well, good that we are not sending dragonfly to mars 🚀  (yet).
