### ISSUE TITLE
Support S3 using HTTPS

### ISSUE THREAD

**Issue by tekumara** [dragonflydb/dragonfly#2216]
**Is your feature request related to a problem? Please describe.**

S3 snapshotting currently uses HTTP.

**Describe the solution you'd like**

Use HTTPS for S3 snapshots.

**Describe alternatives you've considered**

Using disk based snapshots for now.

**Additional context**

Required for security compliance.

**Comment by andydunstall** [comment]
Hi @tekumara, we added S3 HTTPS support in [v1.12.0](https://github.com/dragonflydb/dragonfly/releases/tag/v1.12.0) - does that work for you? (Uses HTTPS by default)

(Sorry I forgot to update the [docs](https://www.dragonflydb.io/docs/managing-dragonfly/backups#cloud-storage), will update)

**Comment by tekumara** [comment]
Fantastic! Sorry I didn't realise and was going off the docs. I'll give it a go.
