### ISSUE TITLE
bug: version bump markup alignment

### ISSUE THREAD

**Issue by ryanrussell** [dragonflydb/dragonfly#223]
**Describe the bug**
There's something wrong with the markdown making the feedback on version bumps not accessible...

**To Reproduce**
1. Try to leave a thumbs up or a rocket or a heart.

**Expected behavior**
You can get the the div, but you can't!

**Screenshots**
<img width="874" alt="image" src="https://user-images.githubusercontent.com/523300/181926383-d8722635-4e29-43fc-95d8-20ee2bf8aa9a.png">

**Additional context**
I'd give it a thumbs up if I could :)

**Comment by odedponcz** [comment]
Works for me. Can  you try again?

**Comment by ryanrussell** [comment]
This is probably so evident because I'm traveling and on cell/laptop... Couldn't give feedback on mobile, tried again on low width laptop browser and couldn't either access the div easily.

For example, here's the Mobile version ...
<img width="354" alt="image" src="https://user-images.githubusercontent.com/523300/182026374-9c5c5b82-b52a-48a7-91b8-45191b418309.png">

If there are 0 reactions, it's really tricky to leave the first...

Probably not exclusive to this repo or something you'd ever notice otherwise.

Ultimately this is minutiae... The popup goes left, I'll see if there's a right align quickfix and if so send a PR to move it over. If not, I'll just close it back out.

**Comment by ryanrussell** [comment]
This is not a distinct issue to DF. Closing for housekeeping.
