### ISSUE TITLE
bug: QUIT command should not be tagged as CO::READONLY

### ISSUE THREAD

**Issue by theyueli** [dragonflydb/dragonfly#2259]
There are at least two reasons:

QUIT itself doesn't read any key, doesn't justify the tag, and doesn't agree with Redis' ACL tag either https://redis.io/commands/quit/
tagging quit read only would confuse client tracking. Client tracking expect to track all the keys accessed by a readonly command.

**Comment by romange** [comment]
why it's a bug?
please provide a context

**Comment by theyueli** [comment]
There are at least two reasons:

1. quit itself doesn't read any key, doesn't justify the tag, and doesn't agree with Redis' ACL tag either https://redis.io/commands/quit/
2. tagging quit read only would confuse client tracking. Client tracking expect to track all the keys accessed by a readonly command.
