### ISSUE TITLE
FT.CREATE fields with dash errors with "Bad json path"

### ISSUE THREAD

**Issue by chkp-omris** [dragonflydb/dragonfly#2265]
**Describe the bug**
I'm trying to create an index on json objects which have some fields with dashes in their name.

**To Reproduce**
1. Try to create an index `FT.CREATE idx ON JSON SCHEMA $.some-text AS some-text TEXT $.some-tag AS some-tag TAG`
2. See error `(error) ERR Bad json path: $.some-text`

**Expected behavior**
I expect that the index will be created successfully as it does in RediSearch, and correctly index and find objects with such fields.

**Environment (please complete the following information):**
 - OS: [ubuntu 20.04]
 - Kernel: `5.15.0-47-generic`
 - Containerized: Docker
 - Dragonfly Version: 1.13.0

**Reproducible Code Snippet**
```
docker run -d --network=host --ulimit memlock=-1 docker.dragonflydb.io/dragonflydb/dragonfly
redis-cli
FT.CREATE idx ON JSON SCHEMA $.some-text AS some-text TEXT $.some-tag AS some-tag TAG
```

**Additional context**
This does work on RediSearch, I tried digging a bit and I think it might be related to the implementation of [`jsoncons`](https://github.com/danielaparker/jsoncons/blob/master/include/jsoncons_ext/jmespath/jmespath.hpp#L3433) and its usage in dragonfly in [`IsValidJsonPath`](https://github.com/dragonflydb/dragonfly/blob/main/src/server/search/search_family.cc#L42)

**Comment by romange** [comment]
Thank you @chkp-omris .
A minimal reproducible example is `FT.CREATE idx ON JSON SCHEMA $.text-d TEXT` where it rejects `-` field.
while we are at it, `FT.CREATE idx ON JSON SCHEMA $.text` responds with a bit confusing error, imho - `ERR Invalid field type:` instead of something like `missing type specifier for field $.text`

**Comment by romange** [comment]
The workaround @chkp-omris  is to use `FT.CREATE idx ON JSON SCHEMA "$.'text-d'" TEXT`.

Does it work for you?
