### ISSUE TITLE
keeping 100% iowait CPU utilization on kernel 6.5

### ISSUE THREAD

**Issue by soukichi** [dragonflydb/dragonfly#2287]
**Describe the bug**
when running dragonflydb on kernel 6.5, io threads consume all CPU in idle state.
if set proactor_threads=1, it keep 100% iowait utilization on 1 core.

**To Reproduce**
start dragonfly.service on kernel 6.5

**Expected behavior**
don't consume cpu cycles in idle state

**Screenshots**
![image](https://github.com/dragonflydb/dragonfly/assets/1485294/f5c4e2d4-5626-447a-8e79-641cba407502)

**Environment (please complete the following information):**
 - OS: [ubuntu 22.04.1] with HWE kernel 6.5
 - Kernel: Linux 6.5.0-14-generic 14~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov 20 18:15:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
 - Containerized?: Bare Metal
 - Dragonfly Version: 1.13.0, 1.3.0

** config
```
--admin_bind=10.10.10.20
--admin_nopass=true
--admin_port=16379
--compression_mode=2
--conn_io_threads=8
--conn_use_incoming_cpu=true
--dbfilename=dump
--dbnum=1024
--dir=/var/data/dragonfly
--keys_output_limit=9000
--list_compress_depth=2
--log_dir=/var/log/dragonfly
--logtostderr
--maxmemory=100G
--pidfile=/run/dragonfly/dragonfly.pid
--port=0
--primary_port_http_enabled=false
--proactor_threads=0
--save_schedule="18:00"
--unixsocket=/run/dragonfly/dragonfly.sock
--version_check=false
```

**Comment by chakaz** [comment]
Hi @soukichi 
Please see https://github.com/dragonflydb/dragonfly/issues/2270#issuecomment-1845188470

**Comment by chakaz** [comment]
Working as intended :)
