### ISSUE TITLE
Redis STREAM consumer group have duplicates

### ISSUE THREAD

**Issue by kirinnee** [dragonflydb/dragonfly#2294]
**Describe the bug**
Redis STREAM Consumer groups have duplicates

**To Reproduce**
1. Start `dragonflydb` with docker
2. Run 3 separate session of docker exec, `docker exec -ti <container> redis-cli -a <password>`
3. In session 1: `XGROUP CREATE pokenews pokenews-group 0 MKSTREAM`
4. In session 2: `XREADGROUP GROUP pokenews-group ash COUNT 1 BLOCK 0 STREAMS pokenews >`
5. In session 3: `XREADGROUP GROUP pokenews-group ash COUNT 1 BLOCK 0 STREAMS pokenews >`
6. In session 1: `XADD pokenews * pokemon entei`

both session 2 and session 3 receives the message.

**Expected behavior**
Only session 2 OR session 3 should receive the message, both of them are in the same consumer group

**Environment (please complete the following information):**
- Host OS: MacOS `13.4.1`
 - OS: ubuntu docker image
 - Containerized?: Docker, `ghcr.io/dragonflydb/dragonfly:v1.13.0-ubuntu`
 - Dragonfly Version: `1.13.0`

**Additional context**
None

**Comment by BorysTheDev** [comment]
@kirinnee thx for reporting the bug, I've already reproduced it and will fix it soon.
