### ISSUE TITLE
`OpStick` does not remove from expiry table

### ISSUE THREAD

**Issue by chakaz** [dragonflydb/dragonfly#2315]

**Comment by chakaz** [comment]
Just to make sure I'm on the right page:
Redis doesn't have a `STICK` command (right?), and so we need to define our own semantics to it.
From looking at the code, it seems that by setting the `STICKY` bit to a key we never evict it. As a user, I'd assume that by specifying that a key is sticky - it will also imply that the key will never expire. That's why I filed this issue. @adiholden do you agree?

**Comment by romange** [comment]
I do not agree :) 
expiry and eviction is different. STICKY keys should expire as requested by a user. 
eviction is decided by a server so STICK protects agains deletion of keys that user does not want to be evicted.

**Comment by chakaz** [comment]
My question here is this: if a user issued `STICK key1`, does that mean we should keep the previous expiration as was set before?
If the answer is 'yes', which I think this is what you're saying, then no action is required :)
Please reopen if you think otherwise.
