### ISSUE TITLE
Can not load older posts in the mastodon timeline

### ISSUE THREAD

**Issue by Morethanevil** [dragonflydb/dragonfly#2320]
**Describe the bug**

I wanted to replace Redis with Dragonfly in Mastodon (Docker). It started well, but it could not load any posts in the past, only new postings in the timeline.

**To Reproduce**
1. Replace Redis with Dragonfly in docker-compose.yml
2. Start Mastodon
3. Scroll down to old postings in the timeline (personal feed)
4. See error in the logs

**Expected behavior**
It should load old postings :)

**Logs**
Appended as TXT-File
[error.txt](https://github.com/dragonflydb/dragonfly/files/13727982/error.txt)
[docker-compose.txt](https://github.com/dragonflydb/dragonfly/files/13728038/compose.txt)

**Environment (please complete the following information):**
 - OS: ubuntu server 22.04
 - Kernel: 6.2.0-39-generic (ubuntu hwe)
 - Containerized?: Docker Compose
 - Dragonfly Version: latest

**Comment by romange** [comment]
I am sorry, we won't be able to debug it at this time. 
If you want to help us, please narrow down the issue to where Dragonfly behaves differently. Could it be that mastodon logs have some errors related to accessing dragonfly?
