### ISSUE TITLE
Cannot run docker on local machine

### ISSUE THREAD

**Issue by zakevich** [dragonflydb/dragonfly#234]
**Describe the bug**
Cannot do first step to start using DragonFlyDB. Will be appreciated for any assistance.

**To Reproduce**
1. UE01RD@APM3LC02X60VDJGH8 dragonfly_test % docker run --privileged --network=host --ulimit memlock=-1 docker.dragonflydb.io/dragonflydb/dragonfly
I20220811 08:54:19.962579     1 init.cc:56] dragonfly running in opt mode.
I20220811 08:54:19.962651     1 dfly_main.cc:196] Starting dragonfly df-v0.6.0-e8cbd41719843019893f3d8f93deff41446caf28
I20220811 08:54:19.963207     1 dfly_main.cc:237] maxmemory has not been specified. Deciding myself....
I20220811 08:54:19.963382     1 dfly_main.cc:242] Found 1.12GiB available memory. Setting maxmemory to 918.47MiB
I20220811 08:54:19.974982    13 proactor.cc:459] IORing with 1024 entries, allocated 102720 bytes, cq_entries is 2048
I20220811 08:54:19.977383     1 proactor_pool.cc:66] Running 6 io threads
E20220811 08:54:19.977528     1 dfly_main.cc:108] Max memory is less than 256MB per thread. Exiting...
UE01RD@APM3LC02X60VDJGH8 dragonfly_test % docker run --privileged --network=host --ulimit memlock=-1 docker.dragonflydb.io/dragonflydb/dragonfly
I20220811 08:56:00.462661     1 init.cc:56] dragonfly running in opt mode.
I20220811 08:56:00.463068     1 dfly_main.cc:196] Starting dragonfly df-v0.6.0-e8cbd41719843019893f3d8f93deff41446caf28
I20220811 08:56:00.463097     1 dfly_main.cc:237] maxmemory has not been specified. Deciding myself....
I20220811 08:56:00.463663     1 dfly_main.cc:242] Found 2.60GiB available memory. Setting maxmemory to 2.08GiB
I20220811 08:56:00.470533     9 proactor.cc:459] IORing with 1024 entries, allocated 102720 bytes, cq_entries is 2048
I20220811 08:56:00.473616     1 proactor_pool.cc:66] Running 6 io threads
I20220811 08:56:00.478246     1 server_family.cc:197] Data directory is "/data"
I20220811 08:56:00.478387     1 server_family.cc:119] Checking "/data/dump"
I20220811 08:56:00.478525    11 listener_interface.cc:79] sock[21] AcceptServer - listening on port 6379
2. Cannot reach out the http://localhost:6379 

If try to execute without --privileged 

docker run --network=host --ulimit memlock=-1 docker.dragonflydb.io/dragonflydb/dragonfly
I20220811 09:05:52.779424     1 init.cc:56] dragonfly running in opt mode.
I20220811 09:05:52.779520     1 dfly_main.cc:196] Starting dragonfly df-v0.6.0-e8cbd41719843019893f3d8f93deff41446caf28
E20220811 09:05:52.779536     1 dfly_main.cc:216] iouring system call interface is not supported. Exiting...

**Environment (please complete the following information):**
Mac OS Big Sur 11.6.1
Docker version 3.6.0

**Comment by ryanrussell** [comment]
> iouring system call interface is not supported. Exiting...

Your system is does not meet the minimum kernel requirements. 

From https://github.com/dragonflydb/dragonfly/

Dragonfly runs on linux. It uses relatively new linux specific [io-uring API](https://github.com/axboe/liburing) for I/O, hence it requires Linux version 5.10 or later. Debian/Bullseye, Ubuntu 20.04.4 or later fit these requirements.

**Comment by romange** [comment]
What Ryan said. Closing.
