### ISSUE TITLE
Change to an open-source friendly license to permit Linux distro packaging

### ISSUE THREAD

**Issue by jonathanspw** [dragonflydb/dragonfly#235]
Currently DragonflyDB cannot be packaged into most Linux distributions because of the license in use.

I was planning to package it for Fedora/EPEL but that was shot down by the legal team based on the license.

https://gitlab.com/fedora/legal/fedora-license-data/-/issues/55#note_1059203371

**Comment by romange** [comment]
@jonathanspw The solution is to provide our own hosted repo for the dragonfly package. 
We can provide the hosting if you can guide us on how to build the package (and setup the public repo).

**Comment by romange** [comment]
Opened #237 for this. closing this issue.
