### ISSUE TITLE
Windows Server Support

### ISSUE THREAD

**Issue by steskalja** [dragonflydb/dragonfly#236]
Are there any plans to support Windows Server? This would be a great feature to add.

**Comment by iko1** [comment]
It can't be run natively, because io_uring isn't supported under Windows.
You can run it within WSL version 2, make sure you install the latest WSL kernel with io_uring support.

**Comment by romange** [comment]
Windows? What's this? I have not heard about this Linux distro.

**Comment by deadcoder0904** [comment]
@iko1 how about now? https://windows-internals.com/ioring-vs-io_uring-a-comparison-of-windows-and-linux-implementations/ & https://github.com/CarterLi/libwinring
