### ISSUE TITLE
Replication info master_repl_offset or equivalent for Dragonfly

### ISSUE THREAD

**Issue by safa-topal** [dragonflydb/dragonfly#2362]
**Is your feature request related to a problem? Please describe.**
I would like to know when a Dragonfly replica has the most up-to-date information and for Redis this is usually done via `master_repl_offset` information on `INFO replication` output by keeping track of this number and comparing it with the masters value.

**Describe the solution you'd like**
The same replication information field called `master_repl_offset` would be a good one.

**Describe alternatives you've considered**
Using `full_sync_done` instead of `master_repl_offset` however not quite sure if `true` for this field really means replica has caught up with the master completely as Dragonfly has a different replication implementation than Redis.

**Comment by adiholden** [comment]
Hi @safa-topal 
As dragonfly is doing replication on multiple shards there is no one offset that we can send like master_repl_offset
Today we have the commands `DFLY REPLICAOFFSET` on master side and `DEBUG REPLICA OFFSET` on replica side which returns a string that represents the lag on each replication shard connection. So if both outputs from master and replica are the same you can know the replica has the most up-to-date information.

**Comment by safa-topal** [comment]
Hi @adiholden, thanks for the useful information.
