### ISSUE TITLE
not all calls to AddOrFind are inside try catch

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#2379]
**Describe the bug**
dbslice AddOrFind can throw bad alloc but not all places in code that call it wrap it in try catch

**Comment by adiholden** [comment]
@chakaz I believe @kostasrim is already fixing this in his PR https://github.com/dragonflydb/dragonfly/pull/2411. please dont wrok on this bug

**Comment by chakaz** [comment]
Sure thing.
I'd actually go about it differently. If all calls to `AddOrFind()` might throw an exception, perhaps an exception is not the best mechanism, and an `OpResult` is more appropriate. This will force callers to check for error before proceeding.
But @kostasrim your call :)

**Comment by kostasrim** [comment]
Had I seen this earlier, I would have moved forward with this but I merged earlier today :( 

Happy to patch this though
