### ISSUE TITLE
Dragonfly replica inconsistent with master data

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#2381]
**Describe the bug**
When master executes a write command the command is send to replica (journal change). If the callback on master side returns error we still send it to replica which can result in inconsistency between master and replica. f.e if master returned with oom when executing the command replica will still execute the command. 

**To Reproduce**
```python
@pytest.mark.asyncio
async def test_policy_based_eviction_propagation(df_local_factory, df_seeder_factory):
    master = df_local_factory.create(
        proactor_threads=1,
        cache_mode="true",
        maxmemory="256mb",
        enable_heartbeat_eviction="false"
    )
    replica = df_local_factory.create(proactor_threads=1)
    df_local_factory.start_all([master, replica])
    df_local_factory.start_all([master])

    c_master = master.client()
    c_replica = replica.client()

    await c_master.execute_command("DEBUG POPULATE 6000 size 44000")

    await c_replica.execute_command(f"REPLICAOF localhost {master.port}")
    await wait_available_async(c_replica)

    seeder = df_seeder_factory.create(port=master.port, keys=500, val_size=1000, stop_on_failure=False)
    await seeder.run(target_deviation=0.1)

    info = await c_master.info("stats")
    assert info["evicted_keys"] > 0, "Weak testcase: policy based eviction was not triggered."

    await check_all_replicas_finished([c_replica], c_master)
    keys_master = await c_master.execute_command("keys *")
    keys_replica = await c_replica.execute_command("keys *")
    
    assert set(keys_master) != set(keys_replica):
    await disconnect_clients(c_master, *[c_replica])
```

**Expected behavior**
master will not replicate a command that returned error on callback execution

**Comment by chakaz** [comment]
I looked into this issue for most of today.
It's quite easy to add an early return inside `LogAutoJournalOnShard()` in case `local_result_` is not `OK`. After some debugging I figured out a place to patch to fix a bug with that, so that's pretty easy, and it solves the cases where the master sends to the replica commands that it did not execute.
There is a challenge, though: partial success.
For example, think of the case of `MSET k1 ... k2 ... k3 ...`, where the OOM was thrown for k3, i.e. k1 and k2 *were* set. In this case (assume all are in the same shard), what do we send to the replica? We need some intimate details of the command and what exactly failed within it.
It's a much more rare failure, but I can catch it with Adi's test every few (many) runs.
Unfortunately, I'm not sure how to address it. I thought that, in the case of an error, we can simply serialize all relevant keys, maybe in the format of a `RESTORE` command like we do for slot migration, unless anyone else can think of a better idea?

**Comment by romange** [comment]
We are not a database. Redis, for example, crashes in some cases of OOM.
I think we should do a reasonable effort of replicating correct results but in case of OOM we do not guarantee atomicity of MULTI/EXEC transactions, lua scripts and we can not guarantee correctness of replication.
For this we would need a transaction log and being able to rollback. We can not afford it for in-memory store.

**Comment by chakaz** [comment]
So you don't even want the `RESTORE` solution?
Note that it's not about MULTI/EXEC atomicity. Even in the case of a simple `MSET` with 2 values, that atomicity is not guaranteed (not in the master / standalone, nor in the replica)

**Comment by adiholden** [comment]
In case of OOM we do not guarantee the atomicity of multi transactions and lua scripts, but with shahar fix we should be able to replicate only the commands that where executed successfully and we will be able to guarantee correctness of replication.
For MSET command (or other write multi key commands if there are any) we can do the following change which can ensure the execution of mset command for all keys in shard which will guarantee correctness of replication:
Today in mset we do a for loop on all keys insert key and value one by one, to make sure we dont get bad_alloc for one of the keys in the mset we can do first insert all keys, only if all keys are inserted we can do the value setting. Note that this flow is not so trivial because once we insert a key it can invalidate the iterators of the other inserted keys.

**Comment by chakaz** [comment]
I sent https://github.com/dragonflydb/dragonfly/pull/2416 for review, which fixes command failures except for partial failures.

> For MSET command (or other write multi key commands if there are any) we can do the following (...)

There are a few downsides to this approach:
1. It requires changes to all mutating multi-key commands, present and future
2. As you said, implementing this is not trivial (and I'd even say that it's not guaranteed to work, for example pushing an item to an existing list can also OOM no?)

The proposal of automatically sending a `RESTORE` command for all relevant keys is a one place change, which doesn't sound too hard to implement, and is also future proof..

**Comment by chakaz** [comment]
@adiholden and I discussed this and came to the following conclusions:
1. The only command that can create multiple keys is `MSET` (note that other commands that "touch" multiple keys, like `LMOVE` or `SUNIONSTORE` can only create at most 1 key)
2. For all commands _except for `MSET`_, we'll simply send a `NOOP` opcode on shard callback failure. This will be sent also for non auto journal commands.
3. For `MSET` (and potentially future commands which we do not currently support) we will use non-auto journal, where the callback will always return `Status::OK` (to force not sending `NOOP` from transaction, see (2) above), and we will custom handle sending the subset of the command that succeeded:

```cpp
atomic_bool success = true;

ScheduleSingleHop([&]() {
  int i = 0;
  for (i = 0; i < args.count(); ++i) {
    if (!sg.Set(...)) {
      success = false;
      break;
    }
  }
   
  if (i == 0) {
    journal no-op
  } else {
    journal: MSET [0, i)
  }

  return OK;
});

if (!success) {
  send error
}
```
