### ISSUE TITLE
info.persistence information

### ISSUE THREAD

**Issue by safa-topal** [dragonflydb/dragonfly#2386]
**Did you search GitHub Issues and GitHub Discussions First?**
Yes

**Is your feature request related to a problem? Please describe.**
Problem is to be able to keep track of backup progress while taking regular backups on a managed platform, we need persistence related progress info such as `rdb_bgsave_in_progress` and `rdb_last_bgsave_status` under `persistence` section of `INFO` output.

**Describe the solution you'd like**
Fields namely `rdb_bgsave_in_progress` and `rdb_last_bgsave_status` being present under `persistence` section of `INFO` output of a Dragonfly process.

**Additional context**
Example list with desired fields:

```
rdb_bgsave_in_progress:0
rdb_last_save_time:1704709182
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
```

Most important fields in the context of this problem are: `rdb_bgsave_in_progress` and `rdb_last_save_time`

**Comment by BorysTheDev** [comment]
@safa-topal I've implemented a little different approach but it should be more flexible and cover your use case

**Comment by BorysTheDev** [comment]
Hi @safa-topal  we have now last_success_save and last_failed_save, so if you need last attempt with any result it's max(last_success_save, last_failed_save)

**Comment by safa-topal** [comment]
Awesome, thanks @BorysTheDev
