### ISSUE TITLE
error: uring_socket.cc:388] Error canceling error cb 2

### ISSUE THREAD

**Issue by hgdhfq** [dragonflydb/dragonfly#2388]
**Describe the bug**
Using dragonfly operator, master error log

**Expected behavior**
Don‘t produce the error

**Screenshots**
<img width="1197" alt="image" src="https://github.com/dragonflydb/dragonfly/assets/24693592/4ba3f417-792b-4c02-ae93-e9e84f5e08b7">

**Environment (please complete the following information):**
 - OS: [AWS AL2]
 - Kernel: ..
 - Containerized?: [EKS v1.28.3-eks-e71965b]
 - Dragonfly Version: [1.13.0](1.12.0 also has the error)

**Reproducible Code Snippet**
It's the prod env, can't find Code Snippet。Maybe high concurrency Lputh Ltrim and HIncrBy

**Additional context**
dragonfly-deploy.yaml
```
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  labels:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: dragonfly
    app.kubernetes.io/part-of: dragonfly-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dragonfly-operator
  name: dragonfly
  namespace: drf
spec:
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.13.0
  replicas: 2
  args:
    - "--requirepass=****"
  serviceAccountName: dragonfly-prod-backup
  snapshot:
    dir: "s3://prod-df-s3"
    cron: "*/30 * * * *"
  resources:
    limits:
      cpu: 5000m
      memory: 20Gi

**Comment by romange** [comment]
yeah, it's gonna be fixed in the future, feel free to ignore this error message, it's harmless by itself.

**Comment by hgdhfq** [comment]
Okay, understood.
