### ISSUE TITLE
high latency when saving snapshots

### ISSUE THREAD

**Issue by liusf1993** [dragonflydb/dragonfly#2389]
**Describe the bug**
Cpu is high while saving snapshots

**To Reproduce**
1. Memory usage
```

127.0.0.1:6379> info memory
# Memory
used_memory:30743621312
used_memory_human:28.63GiB
used_memory_peak:35570662920
used_memory_rss:40014254080
used_memory_rss_human:37.27GiB
used_memory_peak_rss:40043327488
comitted_memory:42948165632
maxmemory:57982058496
maxmemory_human:54.00GiB
object_used_memory:93229633565950
table_used_memory:5744927384
num_buckets:110960640
num_entries:60395994
inline_keys:1798
strval_bytes:1250498936
updateval_amount:169201443953250
listpack_blobs:18446744073708746597
listpack_bytes:2458150178
small_string_bytes:2051391408
pipeline_cache_bytes:18446744073709497990
dispatch_queue_bytes:18446744073708585533
dispatch_queue_peak_bytes:18446744073709172904
client_read_buffer_peak_bytes:4315136
cache_mode:store
maxmemory_policy:noeviction

```
2. Execute `bgsave` 
3. View cpu usage, `mpstat -P ALL 1 100` , all core's cpu is very high, nearly 95%, and results in many slow query

**Expected behavior**
   CPU is at at a reasonable level,  online business shouldn't be affected.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Anolis OS 8.8 ANCK 64
 - Kernel: Linux dongni-nginxjump 5.10.134-15.an8.x86_64
 - Containerized?: Docker Swarm
 - Dragonfly Version: v1.12.1

**Reproducible Code Snippet**
```
bgsave
```

**Additional context**
8C64G 
startup command: dragonfly --requirepass [PASSWORD] --max_multi_bulk_len 1000000 --logtostderr --snapshot

**Comment by romange** [comment]
high CPU by itself is not a problem - it's a design choice. high latency is. 
in any case we do not have enough data to comment on the issue, we would need to see continuous monitoring metrics from our latest version v1.13 and that's not something we can do effectively on github.

**Comment by chakaz** [comment]
@liusf1993 are you able to share an RDB file with which this is reproducible? Or maybe reproduce this issue with a script or another mean?

**Comment by romange** [comment]
I kicked off our weekly build now. Check this out: 
https://github.com/dragonflydb/dragonfly/actions/runs/7472965174
should update https://github.com/dragonflydb/dragonfly/pkgs/container/dragonfly-weekly

**Comment by chakaz** [comment]
Please ignore Roman's comment above, it was supposed to go to another issue :)

**Comment by liusf1993** [comment]
I need some time to complete the data desensitization, and I will provide the file rdb file later

**Comment by chakaz** [comment]
that would be MUCH appreciated, thank you!

**Comment by liusf1993** [comment]
> @liusf1993 are you able to share an RDB file with which this is reproducible? Or maybe reproduce this issue with a script or another mean?
Dump file is here, the file server is in china, may be a litter slow. 
https://snapshot2-tmp.oss-cn-shenzhen.aliyuncs.com/01-11/dragonfly_dfs.tgz?Expires=1704999873&OSSAccessKeyId=TMP.3Kjy1qQBa9rCRfN5yTeYecfWeKPS418arJkCiLWMvYDXDz8ySJHXvvuLALNRiBg2Z3W7adJfdxxhqznrHqVZfH6UBU1Bko&Signature=H6rmKerfFt1coVhRUE4n%2BqQhtVk%3D

**Comment by chakaz** [comment]
thanks!
and how can I inspect whether the traffic is slower?
can you please reach out on Discord (I'm shahar5696) so we can discuss this faster? thanks!

**Comment by liusf1993** [comment]
We are using sywalking as performance monitor, and I watched that some slow query in skywalking panel.

**Comment by liusf1993** [comment]
> Discord

I don't have a Discord account, let me see how to register an account.

**Comment by liusf1993** [comment]
> I used a clumsy means to watch the result. In shell,I executed `for i in {1..100}; do time redis-cli -a [PASSWORD] dbsize ; sleep 2; done` to see the execution time. And result is like this While bgsave is in progress
> 
> ```
> (integer) 51169005
> real	0m0.039s
> user	0m0.003s
> sys	0m0.002s
> ```
> 
> After `gbsave` finished
> 
> ```
> (integer) 51169005
> real	0m0.021s
> user	0m0.002s
> sys	0m0.002s
> ```

To add, the slow query  was, many query within 1ms was changed to 4ms to 15ms while bgsave was in progress. The result was observed using a performance monitoring tool named skywalking.

**Comment by romange** [comment]
@liusf1993  sorry I did not get it in time. is it possible to share it again?

**Comment by liusf1993** [comment]
> @liusf1993 sorry I did not get it in time. is it possible to share it again?

My VPN is not very stable, and currently I am unable to connect to Discord, so can we communicate via email? My email is `liusifan1182@dingtalk.com`.

**Comment by liusf1993** [comment]
https://snapshot2-tmp.oss-cn-shenzhen.aliyuncs.com/01-11/dragonfly_dfs.tgz?Expires=1705319537&OSSAccessKeyId=TMP.3KeUe7zUieomB7EXjA9JEG6dd1b6bjL1eJDUTTxJms81NtmNFP7ZF9Fgg5nqkkd2TRAEvx137VzGZ9FCDZtfF7BqkuaaL5&Signature=S8lZ%2FXhpwq1nX%2Fv4CT%2BcWYL%2BSSY%3D

**Comment by Qubitium** [comment]
Coming from Redis v6.0, 200GB rdb with default compression enabled takes  around 20+ minutes with single cpu at 100%. Dragonly on same db also with default compression enabled takes only 1.1 minute with high/100% cpu usage.

**Comment by romange** [comment]
@liusf1993 thank you, I copied it 👍🏼
