### ISSUE TITLE
Difference in behaviour in dfly vs redis for MEMORY USAGE Command for nonexistent key

### ISSUE THREAD

**Issue by Flo4604** [dragonflydb/dragonfly#2399]
**Describe the bug**
When using dragonfly, there is a different behaviour when running the MEMORY USAGE command on a key that does not exists vs when you do the same in redis. 

It will throw an err no such key instead of just returning nil
 
**To Reproduce**
1. Query nonexistent key via memory usage key in redis
2. Query nonexistent key via memory usage key in dragonfly
4. See the difference in behaviour

**Expected behavior**
```bash
127.0.0.1:6379> memory usage 123
(nil)
```

**Current behavior**
```bash
127.0.0.1:6379> memory usage 123
(error) ERR no such key
```

**Environment (please complete the following information):**
 - OS: MacOs 14.2.1 (23C71)
 - Kernel: Darwin mbp.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:51 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6030 arm64
 - Containerized?:Docker
 - Dragonfly Version: df-014a86f
 - Redis Version: 7.2.3

**Reproducible Code Snippet**
```
memory usage 123
```

**Comment by romange** [comment]
right. why does it matter to you?

**Comment by Flo4604** [comment]
> right. why does it matter to you?

Because it breaks a webui I would like to use https://github.com/hibiken/asynqmon for https://github.com/hibiken/asynq. 

In there is a script that checks for memory usage of keys which errors out due to the above error. 

Should this be rather fixed in the script itself?

**Comment by romange** [comment]
no, I will fix it - just wanted to understand the context.
