### ISSUE TITLE
implement json.numincrby

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#240]
implement json.numincrby 
spec: https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/json-numincrby.html

specifically:
```
json.set foo $ '{ "e": 1.5 , "a": 1 }' 
json.NUMINCRBY foo $.a 1.1
```
returns `"[2.1]"`

and `json.NUMINCRBY foo $.e 1` returns  `"[2.5]"`
and `json.NUMINCRBY foo $.e 1e10` returns  `"[1e+10]"`

moreover,
`json.NUMINCRBY foo $.e inf` returns `(error) OVERFLOW Addition would overflow`

**Comment by romange** [comment]
```
json.set foo $ '{ "e": 1.5 , "a": 1 }' 
json.NUMINCRBY foo $.e 1.7e308
```
returns `"[1.7e+308]"`
but then if we call `json.NUMINCRBY foo $.e 1.7e308` again we get 
`(error) OVERFLOW Addition would overflow` because max double is ~ `1.8e308`

**Comment by iko1** [comment]
This issue can be closed

**Comment by romange** [comment]
🚀
