### ISSUE TITLE
CONFIG RESETSTAT not working

### ISSUE THREAD

**Issue by Qubitium** [dragonflydb/dragonfly#2420]
CONFIG RESETSTAT does not reset the INFO stats such as keyspace hit/miss data columns. 

```
dragonfly <- CONFIG RESETSTAT
dragonfly ->  ok
```

Using latest binary build of dragonflydb

```
redis_version:6.2.11
dragonfly_version:df-v1.13.0
redis_mode:standalone
arch_bits:64
multiplexing_api:iouring
tcp_port:6379
thread_count:8
uptime_in_seconds:43909
uptime_in_days:0
```

**Comment by kostasrim** [comment]
Hi @Qubitium, 

thank you for the report. This should not be the case since, I quote:

> The following is a non-exhaustive list of values that are reset:
Keyspace hits and misses 
....

I will take care of this
