### ISSUE TITLE
introduce redis.replicate_commands() in lua

### ISSUE THREAD

**Issue by EvertonSA** [dragonflydb/dragonfly#2468]
Hi, 

I'm a heavy user of https://github.com/mvisonneau/gitlab-ci-pipelines-exporter and I have been looking to migrate it's redis dependency to dragonflydb.

On Dragonfly 1.10, I was blocked due to missing XACK. Now, i'm trying with version 1.13 and I'm one step further. Now it gives me:

{"error":"ERR Error running script (call to f52a5b566060d79fd321d695df55bc918339c4aa): @user_script:4: user_script:4: attempt to call a nil value (field 'replicate_commands')","level":"fatal","msg":"","time":"2024-01-24T18:16:39Z"}

I googled quickly and it looks like a redis command. I will dive more but if someone knows about it and want to save my time it would be great. 

thanks! btw, great project.

**Comment by romange** [comment]
see https://redis.io/docs/interact/programmability/lua-api/ for more info.

Dragonfly already replicates the effect of lua scripting therefore this command should be a noop.

**Comment by EvertonSA** [comment]
Thanks, I can test at any time. I'm very bad at c++, and I was not able to proceed on my fork.

Let me know if you need input from me.
