### ISSUE TITLE
implement creation of deb package

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#249]
part of much bigger #237 

a pretty extensive [blog post](https://decovar.dev/blog/2021/09/23/cmake-cpack-package-deb-apt/) guides on how to build debian packages. Also  https://earthly.dev/blog/creating-and-hosting-your-own-deb-packages-and-apt-repo/ but it does not use cmake.

no need to host or build a repo, just to make sure we can build the deb using `cpack -G DEB`. 
The goal at this point is to release `deb` via our release pipeline on github.
cmake is just one challenge. another (minor) one - installing the dragonfly will require a systemd service script.

**Comment by acheevbhagat** [comment]
I can take a crack at this one, but I won't have time to start on it for the next 3 or 4 days

**Comment by romange** [comment]
thanks Acheev, much appreciated. and it's not urgent at all.

**Comment by romange** [comment]
hi @acheevbhagat, are you planning on working on this?

**Comment by acheevbhagat** [comment]
Ah yes I am. 
Truthfully, I forgot I had put my name on this issue. Thank you for reminding me, I am still planning on doing this.

**Comment by romange** [comment]
Well, now you are officially assigned 😆 
I will keep reminding you from time to time ;)

**Comment by acheevbhagat** [comment]
Just wanted to drop a small update
I have created a packing.cmake file to generate the deb package, and it seemingly works installing to my vm, but I want to do some more testing and make sure it's actually working properly + learn some more about cpack to make sure I'm doing things right. 
I have the changes on my fork if you care to check them out, and if you want me to put up a wip pr I can do that too

**Comment by romange** [comment]
Thanks, Acheev. I actually do not know myself how to generate the deb package, so at this point you already know better than me.
I trust you do the necessary checks. Shoot the PR afterwards! :)

**Comment by romange** [comment]
I do not know enough to say why either option is better. Currently, I just do not have time to learn the domain, waiting for the team to grow and then the task owner will decide.

**Comment by antonffeksdnu** [comment]
Hey,i starting fix this issue

**Comment by boazsade** [comment]
The first PR will only include the required files/scripts to generate the packages.
The second PR  will include the changes to the git workflow so that we would generate a version automatically from git actions.

**Comment by boazsade** [comment]
We now have deb packages for x86 as well as ARM
