### ISSUE TITLE
Investigate why `test_policy_based_eviction_propagation` is flaky

### ISSUE THREAD

**Issue by chakaz** [dragonflydb/dragonfly#2506]
It was flaky, and so I disabled it in #2505

Example failure: https://github.com/dragonflydb/dragonfly/actions/runs/7665188813/job/20890653630?pr=2483#step:11:1740

From the small set of failures that I saw, it seems like the replica always has *more* keys.

See original PR #2428 and issue #2381

**Comment by kostasrim** [comment]
Closing this. Inactive.
