### ISSUE TITLE
Dragonfly crashes when setting empty string in transaction

### ISSUE THREAD

**Issue by cklossek** [dragonflydb/dragonfly#2509]
**Dragonfly version**
```
$ dragonfly --version
dragonfly v1.14.1-25b2713d3a46ba76bf492f93e5f34c4f647855bf
build time: 2024-01-25 10:01:17
```

**Description**
I opened a transaction und tried to set an empty string as the value of a key. Then dragonfly crashed with an error message:
```
*** SIGSEGV received at time=1706708997 on cpu 0 ***
PC: @     0x7fce6393597c  (unknown)  (unknown)
```

**Steps to reproduce**
```
redis-cli
127.0.0.1:6379> MULTI
OK
127.0.0.1:6379(TX)> SET test ''
Error: Server closed the connection
```

**Comment by romange** [comment]
OMG, this is the most embarrassing bug I saw in dragonfly in the past year! Thank you for reporting this! 
Can I buy you a beer? :)
