### ISSUE TITLE
Support CONFIG subcommands

### ISSUE THREAD

**Issue by highpon** [dragonflydb/dragonfly#2511]
CONFIG REWRITE

**Comment by romange** [comment]
Hello @highpon . What is the reason you need this command?

**Comment by highpon** [comment]
Hello @romange.
I believe DragonflyDB aims for full compatibility with Redis commands.
I found a command implemented in Redis that is not yet implemented in DragonflyDB, so I have raised it as an Issue.

I am not troubled by the lack of this command in my actual use of DragonflyDB.

**Comment by romange** [comment]
Full compatibility with Redis is not a goal by itself, but a means to allow smooth migration to Dragonfly. 
I strive to understand the reason behind each command before implementing it.

**Comment by highpon** [comment]
@romange 
Thanks for the reply! I have solved my misunderstanding....

This time, I don't have a concrete use case, and I don't have enough material for discussion. So, I'm going to close the issue.
