### ISSUE TITLE
Eval on a single shard does not log exec to journal

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#2519]
When running eval on a single shard we have an optimisation for a single hop
inside Service::EvalInternal  if (CanRunSingleShardMulti(sid, *params, *tx)
When this optimisation is taking place we log to journal all the executed commands in the script with MULTI opcode but when finishing running the script we do not journal EXEC opcode.
This bug is causing replica to get stuck on execution and memory continues to grow untill oom occurs.

**Comment by dranikpg** [comment]
Will follow up with a separate quick PR, but generally #2376 will be a proper solution

**Comment by romange** [comment]
@dranikpg  how long do you think it will take to implement #2376? Maybe it's worth just wait for this PR to land?

**Comment by dranikpg** [comment]
Okay, let's merge it before the remaining refactoring, it doesn't rely much on the parts left. I'll polish it and it's ready for review

**Comment by dranikpg** [comment]
@romange PTAL at the PR if you want this issue closed 🙄
