### ISSUE TITLE
Check code with static analyzers

### ISSUE THREAD

**Issue by BorysTheDev** [dragonflydb/dragonfly#2580]
I will add here bugs that I found with static analysis

**Comment by BorysTheDev** [comment]
`void Scheduler::ScheduleFromRemote(FiberInterface* cntx) {
  // This function is called from FiberInterface::ActivateOther from a remote scheduler.
  // But the fiber belongs to this scheduler.
  DCHECK(cntx->scheduler_ == this);

  // If someone else holds the bit - give up on scheduling by this call.
  // This should not happen as ScheduleFromRemote should be called under a WaitQueue lock.
  if ((cntx->flags_.fetch_or(FiberInterface::kScheduleRemote, memory_order_acquire) &
       FiberInterface::kScheduleRemote) == 1) {
    LOG(DFATAL) << "Already scheduled remotely " << cntx->name();
    return;
  }`

`  if ((cntx->flags_.fetch_or(FiberInterface::kScheduleRemote, memory_order_acquire) &
       FiberInterface::kScheduleRemote) == 1)` is always false

**Comment by BorysTheDev** [comment]
`  optional<Transaction::MultiMode> multi_mode = DeduceExecMode(state, exec_info, *script_mgr());
  if (!multi_mode) 															// always false
    return rb->SendError(
        "Dragonfly does not allow execution of a server-side Lua in Multi transaction");`

condition is always false

**Comment by romange** [comment]
@BorysTheDev  we should integrate it into our codebase and our test runs :)

**Comment by BorysTheDev** [comment]
`OpStatus OpSetId2(const OpArgs& op_args, string_view key, const streamID& sid) {
....
long long entries_added = -1;
....
if (entries_added != -1)
`

**Comment by BorysTheDev** [comment]
size_t node_max_bytes = kStreamNodeMaxBytes;
    if (node_max_bytes == 0 || node_max_bytes > STREAM_LISTPACK_MAX_SIZE)
      node_max_bytes = STREAM_LISTPACK_MAX_SIZE;

**Comment by BorysTheDev** [comment]
unsigned int ziplistRandomPairsUnique(unsigned char *zl, unsigned int count, ziplistEntry *keys, ziplistEntry *vals) {
    unsigned char *p, *key;
   ....
            assert(ziplistGet(p, &key, &klen, &klval));
            ziplistSaveValue(key, klen, klval, &keys[picked]);

**Comment by BorysTheDev** [comment]
assert(ziplistGet(p, &value, &vlen, &vlval));
        while (pickindex < count && zipindex == picks[pickindex].index) {
            int storeorder = picks[pickindex].order;
            ziplistSaveValue(key, klen, klval, &keys[storeorder]);
            if (vals)
                ziplistSaveValue(value, vlen, vlval, &vals[storeorder]);
             pickindex++;


It looks that we get values under ASSERT and it works only in debug

**Comment by BorysTheDev** [comment]
DCHECK(it == blocks_.begin() || it == blocks_.begin() || it->Size() * 2 >= block_size_);

duplication check, maybe a bug

**Comment by dranikpg** [comment]
>```if (conn_state.subscribe_info) {  // Clean-ups related to PUBSUB
>    if (!conn_state.subscribe_info->channels.empty()) {
>      server_cntx->UnsubscribeAll(false);
>    }
>
>    if (conn_state.subscribe_info) { // always true
>      DCHECK(!conn_state.subscribe_info->patterns.empty());
>      server_cntx->PUnsubscribeAll(false);
>    }
>
>    DCHECK(!conn_state.subscribe_info);
>  }
>```

UnsubscribeAll can call conn_state.reset(), so how is it always true? 🤔

**Comment by BorysTheDev** [comment]
I think it's a false positive, I haven't dived deep when I analyzed the static analysis results. You can hide the comment and I will know that I was wrong regarding it
