### ISSUE TITLE
add a pytest test that checks redis/df replication

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#261]
it should: 

1. Start a redis server
2. Start a DF server
3. Populate Redis with data, and DF with data. Continue with adding data to redis.
4. set DF as a secondary replica of Redis server.
5. Validate that DF is synchronized with Redis. DF should disappear, Redis data should by synced.
6. use "DEBUG REPLICATE PAUSE" to pause replication negotiation in case of disconnect
7. kill DF replication connection on redis server using `client kill type replica`.
8. continue adding data to redis for a few seconds.
9. Resume replication on DF and validate that it's been synced with Redis.

**Comment by nmathew98** [comment]
Hi if this is not urgent could I be assigned to this?

**Comment by romange** [comment]
You need knowledge of pytest framework in order to do this. Specifically how to work with fixtures. 
Current pytest code is located here under "tests/dragonfly"
