### ISSUE TITLE
Flake on pytest df instance that times-out after 5seconds instead of properly shut down

### ISSUE THREAD

**Issue by kostasrim** [dragonflydb/dragonfly#2624]
This happen from time to time in our regression tests. Maybe it's worth looking on why: https://github.com/dragonflydb/dragonfly/actions/runs/7923846274 

(not critical happens rarely)

**Comment by romange** [comment]
Fiber "Dispatched" looks suspicious: https://github.com/dragonflydb/dragonfly/actions/runs/7923846274/job/21634391807#step:6:1521

This is the default name of a fiber that is run via `ProactorBase::Dispatch` method.
This seems to be called only  via `RunBlockingInParallel` function or inside `load_join_fiber`.
The first step would be to go over all the cases there and override the fiber name with a specific name using `ThisFiber::SetName` function at the beginning of each fiber function.

**Comment by kostasrim** [comment]
Closing this. It was related to Shutdown we don't even have logs for this
