### ISSUE TITLE
master_id (runid) should protect from accidental master restarts

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#2636]
Currently we use master_id for two purposes: cluster node id generation and as "master id" during the replication.

1. Similarly to Redis, we do not protect slave from accidental data flushes during full sync (see http://antirez.com/news/80 for context)
2. Unlike Redis we currently do not employ partial sync where such protection exists

Not directly related to this issue but important for providing additional context - using master_id as nodeid for cluster management is cumbersome and confusing.

I suggest we implement master_id protection so that replica that had been synced already and reached SSR with the master id A, won't reconnect automatically with master under the same address with master id B.  Specifically, one would need to reissue "replicaof .." command again to bootstrap the replication again.

This behavior change on replica side should be under flag with default to preserve the current behaviour.

**Comment by ashotland** [comment]
Also consider the case where master is restarted during takeover

**Comment by romange** [comment]
@ashotland  it's done
