### ISSUE TITLE
race condition on `INFO ALL` && `BGSAVE` 

### ISSUE THREAD

**Issue by kostasrim** [dragonflydb/dragonfly#2644]
We have a race condition when `INFO ALL` && `BGSAVE` is called concurrently. The problem is within `BGSAVE` command:

`ServerFamily::DoSave` :

```
    {
      std::lock_guard lk(save_mu_);
      if (save_controller_) {
        return GenericError{make_error_code(errc::operation_in_progress),
                            "SAVING - can not save database"};
      }    
      save_controller_ = make_unique<SaveStagesController>(detail::SaveStagesInputs{
          new_version, basename, trans, &service_, fq_threadpool_.get(), snapshot_storage_});
    }
  
    detail::SaveInfo save_info = save_controller_->Save();
```

and in `INFO ALL`: 

```
      lock_guard lk{save_mu_};
      if (save_controller_) {
        save_buffer_bytes = save_controller_->GetSaveBuffersSize();
```

The issue is that the initialization of the object `SaveController` is done within `save_controller_->Save()` which no longer holds a lock to the mutex. Therefore `GetSaveBufferSize()` access to local `snapshot_` is a race condition, because there is a modify read/write operation concurrently (INFO ALL is trying to access the member variable snapshots while save_controller is trying to initialize it). 

I think there other similar races in this path, so it should be checked as well.

**Comment by romange** [comment]
Indeed, good catch, Kostas!
SaveStagesController::InitResources and SaveStagesController::GetSaveBuffersSize race with each other. 🤦🏼‍♂️ 

I think it justifies 1.14.6.

**Comment by kostasrim** [comment]
I will push a fix! Cheers!

**Comment by dranikpg** [comment]
We have even one more reace condition, namely ` RdbSnapshot::StartInShard()` does `started_ = true` from multiple shards. In general, this code is quite old and likely has many bugs 😈

**Comment by kostasrim** [comment]
I know and in the cleanup. I fixed both. I wanted to push a refactor but I also want to get my other PR merged so I am moving forward with the small changes/fixes. I will push another PR sometime soon that I will refactor some parts out.
