### ISSUE TITLE
docker image does not perform a proper health checking with custom ports

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#2650]
when running `docker run docker.dragonflydb.io/dragonflydb/dragonfly --port=8888` for example,
our healthcheck.sh fails because it's hardcoded to check :6379 port locally.

To fix it - we should add `netstat` to our docker image in `tools/packaging/Dockerfile.*" files and then find the listening port in `tools/docker/healthcheck.sh`

**Comment by manojks1999** [comment]
Hi @romange ,
Pls check this PR https://github.com/dragonflydb/dragonfly/pull/2659

I have made changes.
