### ISSUE TITLE
set masteruser support on replicas

### ISSUE THREAD

**Issue by safa-topal** [dragonflydb/dragonfly#2668]
**Did you search GitHub Issues and GitHub Discussions First?**
Yes.

**Is your feature request related to a problem? Please describe.**
Setting another masteruser than "default" on replicas seems impossible right now. Ideally I would like to use a custom masteruser for admin operations so `set masteruser` is needed on this case.

**Describe the solution you'd like**
configuration option available on replicas called `masteruser`  as it's called in Redis would suffice.

**Comment by kostasrim** [comment]
Hi @safa-topal, thank you for reporting this. I will take care of this :)

**Comment by romange** [comment]
@safa-topal  FYI, we also have `admin_nopass` flag so that in case you open an admin interface bound to management internal network you can access nodes via this port without any authentication.

**Comment by safa-topal** [comment]
Thanks @kostasrim, @romange. Good to know, though on this case `admin_nopass` won't help because requirement is to define a different user for replication than `default` user.
