### ISSUE TITLE
Wrong DF version displied in info command

### ISSUE THREAD

**Issue by odedponcz** [dragonflydb/dragonfly#271]
I am running the latest container using:
docker run --network=host --ulimit memlock=-1 docker.dragonflydb.io/dragonflydb/dragonfly:latest 

in redis-cli I am running "info server" 
I get the wrong version:
127.0.0.1:6379> info all
# Server
redis_version:df-v0.3.1

**Comment by romange** [comment]
How do you know that you run the latest container?
I am pretty sure it's not the latest.

**Comment by romange** [comment]
works as expected
