### ISSUE TITLE
replica instance crashes on REPLICAOF or when killed with ctrl+c

### ISSUE THREAD

**Issue by kostasrim** [dragonflydb/dragonfly#2714]
To reproduce:

First issue:
1. start `dragonfly` master and replica
2. connect to replica and issue replicaof 
3. ctr + c on the replica node

```
dragonfly: arena.c:1013: __malloc_arena_thread_freeres: Assertion `a->attached_threads > 0' failed.
*** SIGABRT received at time=1710163399 on cpu 7 ***
PC: @     0x7f468e8969fc  (unknown)  pthread_kill
    @     0x55f676347213        192  absl::lts_20230802::WriteFailureInfo()
    @     0x55f6763477e6        256  absl::lts_20230802::AbslFailureSignalHandler()
    @     0x7f468e842520  (unknown)  (unknown)

```

Second issue:
1. start `dragonfly` master and replica
2. connect to replica and issue replicaof (crashes immediately) 

```
I20240311 15:20:49.671481 151109 server_family.cc:2225] Replicating localhost:6379
*** SIGSEGV received at time=1710163249 on cpu 6 ***
PC: @     0x7efff3ea6949  (unknown)  malloc_trim
    @     0x562e96f81213        192  absl::lts_20230802::WriteFailureInfo()
    @     0x562e96f817e6        256  absl::lts_20230802::AbslFailureSignalHandler()
    @     0x7efff3e42520  (unknown)  (unknown)
[1]    151108 segmentation fault (core dumped)  ./dragonfly --port=6380 --alsologtostderr

```

**Comment by romange** [comment]
it's something new. @chakaz please check if it reproduces before and after the SSL commit.

**Comment by kostasrim** [comment]
yes I know, it happened when I merged main to one of my PR's so it should be one of the last commits

**Comment by chakaz** [comment]
Kostas and I discussed this today, and it looks like after a clean build this is not reproducible. Kostas will continue to try to repro it. Could you kindly update this bug with your findings?

@romange I'm not saying we shouldn't cleanup SSL, only that if it's reproducible, we should test with and without the fix.

**Comment by romange** [comment]
@chakaz  consider compiling mimalloc in debug mode with assertions enabled to reproduce.

**Comment by chakaz** [comment]
Adi was able to reproduce it via pytest (even though it doesn't repro for me locally), so lets continue in #2737
