### ISSUE TITLE
investigate and fix client_pause_with_replica failure

### ISSUE THREAD

**Issue by kostasrim** [dragonflydb/dragonfly#2717]
for reference of the failure see: https://github.com/dragonflydb/dragonfly/actions/runs/8221758390/job/22482493454#step:6:601

**Comment by romange** [comment]
@kostasrim  is it still relevant?

**Comment by kostasrim** [comment]
yes I think so. I don't recall seeing it fail recently but I would keep this open.

**Comment by kostasrim** [comment]
Hasn't failed ever since so I am closing this
