### ISSUE TITLE
Crash after stopping instance

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#2737]
Crash log:
46157➜ runtime error: member access within null pointer of type 'struct __node_type'
46157➜ : 345] RAW: Signal 11 raised at PC=0x559a4c61d347 while already in AbslFailureSignalHandler()
46157➜ @     0x559a4c61d347  (unknown)  util::ListenerInterface::TraverseConnectionsOnThread()
46157➜    @     0x559a4cab4f3d        192  absl::lts_20230802::WriteFailureInfo()
46157➜    @     0x559a4cab5510        256  absl::lts_20230802::AbslFailureSignalHandler()
46157➜    @     0x7f24312e8520  (unknown)  (unknown)
46157➜    @     0x559a4c61c9a9        224  util::ListenerInterface::TraverseConnections()::{lambda()#1}::operator()<>()
46157➜    @     0    @     0x559a4c6268b4         48  util::ProactorPool::DispatchBrief<>()::{lambda()#1}::operator()()
46157➜    @     0x559a4c642cb8         48  fu2::abi_400::detail::invocation::invoke<>()
46157➜    @     0x559a4c7b68b9         @     0x559a4c7994af       5136  util::    @     0x559a4c53701f         48  util::    @     0x559a4c58b478        512  util::fb2::det    @     0x559a4c589953         80  util::fb2::detail::(anonymous n    @     0x559a4c5a6e66         80  std::__inv    @     0x559a4c5a6a7b         80  std::__invoke<>()

How to reproduce? Run the following python code
```
async def test_crash(df_local_factory: DflyInstanceFactory):
    replica = df_local_factory.create(admin_port=ADMIN_PORT, proactor_threads=2)
    master = df_local_factory.create(admin_port=ADMIN_PORT + 1, proactor_threads=2)

    # Start instances and connect clients
    df_local_factory.start_all([ master,replica])
    c_master = master.client()
    c_replica = replica.client()

    await c_replica.execute_command("REPLICAOF localhost " + str(master.port))
    await disconnect_clients(c_master, c_replica)
```

**Comment by chakaz** [comment]
This seems to be a dup of https://github.com/dragonflydb/dragonfly/issues/2714
Unfortunately, it doesn't reproduce for me locally, even with `--count=1000` :scream: 
However, the call stack here helps. I imagine that it might be that we're removing the listener from `conn_list` and then call `Listener::PreShutdown()` which calls `DispatchTracker::TrackAll()`, which eventually calls `ListenerInterface::TraverseConnectionsOnThread`. I'm not entirely sure why this can happen, but we can easily add  `if (it == end()) return;` here:
https://github.com/romange/helio/blob/8985263c3acca038752e8f9fdd8e9f61d2ec2b6f/util/fibers/listener_interface.cc#L282

**Comment by chakaz** [comment]
@kostasrim @adiholden can you please help me and see if you can reproduce it in `main` updated with #2742 ? :pray:

**Comment by kostasrim** [comment]
@chakaz is it suppose to fix `malloc_trim` as well? Sanitizers failed (and I already run them yesterday against your branch). I can try with `ctr-c` instead (maybe they were separate issues :man_shrugging: )

**Comment by chakaz** [comment]
I was hoping that it would fix that, but it looks like it doesn't.
I created a PR in helio to fix the traversal code, that's likely to be related to the `ctrl-c` issue. I guess the `malloc_trim` is unrelated. Bummer.

**Comment by kostasrim** [comment]
@chakaz I will open a separate issue then
