### ISSUE TITLE
Dragonfly crashes at the next snapshot period if previous one was skipped

### ISSUE THREAD

**Issue by safa-topal** [dragonflydb/dragonfly#2754]
**Describe the bug**
If dragonfly skips a snapshot period due to SAVE operation taking longer than the defined snapshot_cron (example: if save takes more than 10min when snapshot cron is set to every 10min)

**To Reproduce**
1. Insert entries to DF (ideally GBs) and set the snapshot_cron to a relatively small value e.g: 1min
2. Ensure snapshotting takes more than 1min
3. See that process crashes if previous interval was skipped

**Expected behavior**
Dragonfly must not crash.

**Environment (please complete the following information):**
OS: Fedora 38
Kernel: 6.3.12-200.fc38.x86_64
Containerized?: toolbox
Dragonfly Version: 1.14.5

**Comment by adiholden** [comment]
@safa-topal I am running the scenario you describe and I am not getting a crash. 
Please send the crash stack trace so I can explore this crash better

**Comment by adiholden** [comment]
@romange yes

**Comment by romange** [comment]
We could not reproduce so far
