### ISSUE TITLE
Add migration statistics to migration status

### ISSUE THREAD

**Issue by BorysTheDev** [dragonflydb/dragonfly#2756]
Add number of keys sent to target node

**Comment by chakaz** [comment]
Hey @BorysTheDev, can you please elaborate a bit on what this issue is about? I didn't quite get it from the title.

**Comment by adiholden** [comment]
@chakaz note that this task is not for cluster v2 milestone

**Comment by chakaz** [comment]
Yes, I noticed that too late :(
