### ISSUE TITLE
LICENSE.md lists listence as BSL-1.1 while SPDX assigned it BUSL-1.1

### ISSUE THREAD

**Issue by ekohl** [dragonflydb/dragonfly#2758]
The license file says `BSL 1.1` here:
https://github.com/dragonflydb/dragonfly/blob/9db825013af78bd7c2f066d07a33e7cc4a2a78a0/LICENSE.md#L3

However, SPDX has assigned it [BUSL-1.1](https://spdx.org/licenses/BUSL-1.1.html). There is actually also BSL-1.0 which is Boost Software License 1.0 so this can be confusing.

**Comment by romange** [comment]
We will fix it though we have seen lots of places referencing this license as BSL. For example, https://mariadb.com/projects-using-bsl-11/

but I agree it's confusing. Will change it next week.

**Comment by ekohl** [comment]
> For example, https://mariadb.com/projects-using-bsl-11/

That one is also confusing because the link for BSL 1.0 (https://mariadb.com/bsl10) redirects to BSL 1.1 (https://mariadb.com/bsl11).

> but I agree it's confusing. Will change it next week.

Thanks!
