### ISSUE TITLE
Incorrect Storage of Flags in DragonflyDB Memcache

### ISSUE THREAD

**Issue by badraxas** [dragonflydb/dragonfly#2777]
**Describe the bug**
The bug involves the incorrect storage of flags in DragonflyDB Memcache under certain conditions.

**To Reproduce**
```
$ telnet 127.0.0.1 11211
Connected to localhost.
Escape character is '^]'.

set myKey 3 0 7
myValue
STORED

get myKey 
VALUE myKey 3 7
myValue
END

set myKey 4 0 8
myValue2
STORED

get myKey
VALUE myKey 3 8
myValue2
END
```

**Expected behavior**
We expected the flag to change to the right value after executing the second `set`.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS (Focal Fossa)
 - Kernel: Linux a92aa430986a 5.15.49-linuxkit-pr
 - Containerized?: occured with docker-compose (using official image : docker.dragonflydb.io/dragonflydb/dragonfly) and kubernetes
 - Dragonfly Version: v1.15.1

**Comment by r-pierre-viously** [comment]
Hi, I think there is an issue with this condition: https://github.com/dragonflydb/dragonfly/blob/main/src/server/string_family.cc#L659

When the flag was set to zero, the flag is updated, but no more since this is other than zero.
