### ISSUE TITLE
Cluster replication

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#2831]

**Comment by chakaz** [comment]
@adiholden can you please provide some context here? What exactly is not working / implemented currently? What is this task about? Thanks 🙏

**Comment by romange** [comment]
It's like in the old joke "Rabinovich, do you know to play on a Violin? Hmm, I do not know, I've never tried"

**Comment by adiholden** [comment]
We need to make sure that HA cluster works well while performing slot migration.
1. need to make sure replica does not reject executing commands not in slot ownership, as migration can start between source and target and replica might did not get the new config yet.
1. add tests for cluster with replicas, do slot migration and check data consistency 
2. support error flows in slot migration with replication, f.e if migraion connection is reset we restart the migration and do flush slots on master node, this flush slots needs to be replicated.

**Comment by adiholden** [comment]
@dranikpg can we close this task?

**Comment by adiholden** [comment]
@dranikpg ping
