### ISSUE TITLE
Error materializing acl file

### ISSUE THREAD

**Issue by safa-topal** [dragonflydb/dragonfly#2837]
**Describe the bug**
Can't load an acl file that is seemingly a valid acl file (no pubsub channel entry as it's not supported by Dragonfly yet)

**To Reproduce**
1. Create an acl file with the payload below:

```
user default on #password_hash1 +@all ~*
user testuser on #password_hash2 +@all ~*

```
3. Run `ACL LOAD` command
4. See error "Error materializing acl file"

**Expected behavior**
ACL LOAD works with the payload above

**Environment:**
 - Dragonfly Version: [e.g. 1.14.5]

**Additional context**

**Comment by kostasrim** [comment]
Hi @safa-topal 

try `USER` with caps lock :)

**Comment by safa-topal** [comment]
Hey @kostasrim, good, thanks!

Since workaround is simple, I am not in a rush for this. I now tested the workaround and it worked 🎉
