### ISSUE TITLE
Fix cluster_mgr.py

### ISSUE THREAD

**Issue by chakaz** [dragonflydb/dragonfly#2855]

**Comment by nicks64** [comment]
could you share some detail or description of what went wrong?

**Comment by chakaz** [comment]
We've made some changes to the management commands, and haven't yet updated `cluster_mgr.py` to use them.

**Comment by nicks64** [comment]
where are the management commands? do you mind sharing what i can do to contribute?

**Comment by chakaz** [comment]
First, thanks for your good intentions :)
This is one of the internal tasks that are probably best to be implemented by the core team. There are some moving parts and decisions that we haven't yet even documented.
However, if you are looking to contribute, please feel free to look at our ["good first issue" label](https://github.com/dragonflydb/dragonfly/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) or ["help wanted" label](https://github.com/dragonflydb/dragonfly/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22).
Thanks!

**Comment by chakaz** [comment]
With https://github.com/dragonflydb/dragonfly/pull/3118, https://github.com/dragonflydb/dragonfly/pull/3120, https://github.com/dragonflydb/dragonfly/pull/3124, and https://github.com/dragonflydb/dragonfly/pull/3129 (which adds tests, and will be merged soon)
This task is now finished :)
