### ISSUE TITLE
REPLTAKEOVER blocks all the commands during the critical section

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#2859]
Dragonfly rejects most of the commands during `TAKEN_OVER` state:

```c++
    case GlobalState::TAKEN_OVER:
      allowed_by_state = cid->name() == "REPLCONF" || cid->name() == "SAVE";
      break;
```

what's the reason for this strong condition?
here is the original discussion during the PR https://github.com/dragonflydb/dragonfly/pull/1314/files#r1233299840
even if we stay with the original implementation of rejecting immediately,
is not it enough to only block WRITE commands during this transition?

**Comment by kostasrim** [comment]
So do we only want to block `WRITE` commands ?

**Comment by adiholden** [comment]
@kostasrim yes
