### ISSUE TITLE
FR: Add maxclients in INFO and /metrics

### ISSUE THREAD

**Issue by steache** [dragonflydb/dragonfly#2912]
**Did you search GitHub Issues and GitHub Discussions First?**
y

**Is your feature request related to a problem? Please describe.**
n

**Describe the solution you'd like**
- add "maxclients" metric here https://github.com/dragonflydb/dragonfly/blob/main/src/server/server_family.cc#L1057 set via GetFlag(FLAGS_maxclients) so we can calculate number of free connections (n, %)
- add "maxclients" to INFO CLIENTS output here https://github.com/dragonflydb/dragonfly/blob/main/src/server/server_family.cc#L1937 again from GetFlag(FLAGS_maxclients) so it can be too checked from console :) 

**Describe alternatives you've considered**
- not doing it :)

**Additional context**
- we are pushing dragonfly to production, but in order for us to properly monitor it, we need few more informations :) 
- alternative solution for this is using the default (64000) maxclients / the value set via --maxclients flag per each cluster
- it's not critical, it just would be 10x times easier for everyone implementing alerting rules :) 
- we've too faced problem, when trying to determine health of cluster (master+slave), because there is no metric-label defining cluster, so we've come up with this funky relabeling rule which fills dragonfly_cluster with first part from (redis-1), (test-2) etc. pod name
- then you can for example check number of masters per cluster etc. (https://github.com/steache/dragonflydb-alerting-rules)

```
      relabelings:
        - sourceLabels: [pod]
          separator: "-"
          regex: "(.*)-(.*)"
          targetLabel: dragonfly_cluster
          replacement: "$1"
```

- thank you for considering this :)
- I've tried to implement it myself and send you patch, but I'm absolute c++ noob, so it went sideways (https://github.com/dragonflydb/dragonfly/compare/main...steache:dragonfly:main)

**Comment by kostasrim** [comment]
Hi @steache, thank you for reporting this. We added as an issue for the community but if it remains stale I will take care of it

**Comment by racamirko** [comment]
@kostasrim I'm volunteering. I'll push the PR and note it here once I run the test suite.

**Comment by kostasrim** [comment]
@racamirko Thank you for your contribution :)
