### ISSUE TITLE
Docker latest version 1.17 when provided volume param still doesnt preserve the data on disk 

### ISSUE THREAD

**Issue by muntdan** [dragonflydb/dragonfly#2917]
**Describe the bug**
Data is not persisted on disk, after docker restart keys should not be lost.

**To Reproduce**
docker volume create dragonfly-data
docker volume inspect dragonfly-data
docker run -d -v /dragonfly-data/:/data -p 6379:6379 --name dragonfly --ulimit memlock=-1 --memory=4g --cpus=8  docker.dragonflydb.io/dragonflydb/dragonfly

**Expected behavior**
After docker restart keys should not be lost

**Screenshots**

**Environment (please complete the following information):**
 - OS: Debian 6.1.85-1 (2024-04-11) x86_64 GNU/Linux
 - Kernel: # 6.1.0-20-amd64
 - Containerized: Docker
 - Dragonfly Version: 1.17

**Comment by toan-superman** [comment]
The same issue with version 1.17.1 after dragonfly restart on K8s I've lost all of data

**Comment by LockSwitchDavis** [comment]
Do you have any estimate of when it will be resolved?

**Comment by romange** [comment]
in september release
