### ISSUE TITLE
improve traffic logger

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#2937]
1. Add a version string at the beginning
2. Write serialized request size before serialising it - to allow  skipping invalid records.
3. Record `dbindex` from the context, so that for multi-database traffic we could replay it correctly if starting recording from the middle.
Consequently traffic replayer should issue "SELECT" at the start if the dbindex is not 0.
4. Adjust traffic replayer to the changes.

**Comment by romange** [comment]
Also, this is a bug: https://github.com/dragonflydb/dragonfly/blob/main/tools/replay/parsing.go#L33-L38

why does it read string length again if the original string has 0 length? this does not correlate to the code in the server and I do not understand the purpose of `if strLen == 0 {` block

**Comment by dranikpg** [comment]
> why does it read string length again if the original string has 0 length? this does not correlate to the code in the server and I do not understand the purpose of if strLen == 0 { block

Because you updated the writer code. Previosuly I was avoiding serialization of values above a few KB and instead wrote only their length

**Comment by romange** [comment]
Regarding (3) - instead of storing dbnum in every record, we could actually emit "SELECT" statement once for each connection when traffic logger starts.  This is better but requires adding state per connection for traffic logger

**Comment by dranikpg** [comment]
(2) Write serialized request size before serialising it - to allow skipping invalid records

Is still fragile 😆 I mean, if it's broken, why can't this value be broken as well
