### ISSUE TITLE
Startup errors with return code 132

### ISSUE THREAD

**Issue by Sulunia** [dragonflydb/dragonfly#296]
**Describe the bug**
Using docker, I am unable to run dragonfly at all. Platform seemingly fits all requirements, which makes it quite mysterious... :thinking: 

**To Reproduce**
I'm currently trying to run it with `docker run --network=host --ulimit memlock=-1 docker.dragonflydb.io/dragonflydb/dragonfly --vmodule=main_service=2 --logbuflevel=-1`
There is no output, besides a **return code 132**

**Screenshots**
![image](https://user-images.githubusercontent.com/9919801/190193372-1eb4d5e8-8d72-48ca-b36e-553c9e37de6d.png)

**Environment (please complete the following information):**
 - OS: Ubuntu Server 22.04
 - Kernel: 5.15.0-47
 - Containerized?: Yes, docker-compose/docker
 - Dragonfly Version: docker latest

**Reproducible Code Snippet**
```
docker run --network=host --ulimit memlock=-1 docker.dragonflydb.io/dragonflydb/dragonfly --vmodule=main_service=2 --logbuflevel=-1
```

**Additional context**
It's an embedded equipment, running a common x86 platform.

**Comment by ryanrussell** [comment]
@Sulunia 

I just tried your command on a Ubuntu 20.04 and it works fine. When I google error 132, I see stuff about cpu instruction sets.

Can you try this?
```bash
sudo cat /proc/cpuinfo | grep avx
```
Ref: [Exit Code 132 on SO](https://stackoverflow.com/questions/60930359/docker-containers-exit-code-132)

I suspect you have an older cpu model on this box?

**Comment by romange** [comment]
@ryanrussell is right. Also,
try running `docker run --network=host --ulimit memlock=-1 docker.dragonflydb.io/dragonflydb/dragonfly --logtostderr`
does it show anything?

**Comment by Sulunia** [comment]
> @Sulunia
> I suspect you have an older cpu model on this box?

Oooh, that's a nice catch. Apparently, this CPU lacks AVX instruction set.
![image](https://user-images.githubusercontent.com/9919801/190216274-5dc35dfa-a619-4482-8bd0-f83becee7126.png)

@romange 
There is no output, even with the command line provided. I suppose it's a "hard error" not having the required instruction set.

Is it possible to keep on using a dockerized dragonfly in this case?

**Comment by romange** [comment]
I do not think you can use even non-dockerized version of dragonfly on a hardware it does not support. Why do you want to run dragonfly on embedded hardware?

**Comment by Sulunia** [comment]
Fortunately, there is no specific or special reason to use dragonfly in this case, besides "I like the project and it's great" :smile: 

However, I'd recommend mentioning the required AVX support in order for dragonfly to work. Thanks for the help on cracking this case :sunglasses:

**Comment by perfectra1n** [comment]
If you're on Proxmox, be sure to set your CPU to `host` since you're most likely using a newer CPU than Proxmox thinks you are :)

![image](https://github.com/dragonflydb/dragonfly/assets/2390633/f248d158-92f0-4990-a725-afbd3bfd1cbe)
