### ISSUE TITLE
make expiry algorithm consistent

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#3]
See https://ably.com/blog/redis-keys-do-not-expire-atomically for motivation.

if we use transactions to set expiry or to access multiple possibly expired items, we should use a consistent clock value during the transaction execution. 

current behavior: we use real clock to set expiry and to test it.

**Comment by millette** [comment]
Duplicate of #6 ?

**Comment by romange** [comment]
Yep, closing the issue :)
