### ISSUE TITLE
maxmemory should support human-readable format like MB or GB

### ISSUE THREAD

**Issue by odedponcz** [dragonflydb/dragonfly#302]
Maxmemory is configured in bytes. For ease of use, inputs in human readable format should be allowed
i.e.
./dragonflydb --maxmemory 5GB
./dragonflydb --maxmemory 512MB
./dragonflydb --maxmemory 240GB

I do not think KB should be supported as min memory is 256MB anyways.

**Comment by romange** [comment]
we can use `ParseHumanReadableBytes` function from common.h.
One thing to note - absl flags support customer flags parsing. see here for example: 
https://github.com/abseil/abseil-cpp/blob/master/absl/flags/parse_test.cc#L201

**Comment by boazsade** [comment]
https://github.com/dragonflydb/dragonfly/issues/302

**Comment by lsvmello** [comment]
@romange the `ParseHumanReadableBytes` parses a slightly different format _(without the ending `B`)_. eg.: 2G, 512M.

Should it be changed to consider the B or it is not that important? Also case-sensitive?

**Comment by romange** [comment]
Not important. Case insensitive
