### ISSUE TITLE
High CPU on replication nodes

### ISSUE THREAD

**Issue by fernandomacho** [dragonflydb/dragonfly#3023]
I have 3 nodes 1 master and 2 slaves
The dragonfly service are balanced with 2 haproxy backend: 1 for write and 1 for read
The write backend has 1 active node (master) and 2 backup
Then read backend has 3 active nodes

The CPU consumption in the slaves is much higher than in the master, which has many more operations and clients.

**Master node info cpu**
```
# Cpu
used_cpu_sys:108497.612411
used_cpu_user:77347.641105
used_cpu_sys_children:0.0
used_cpu_user_children:0.0
used_cpu_sys_main_thread:15346.31872
used_cpu_user_main_thread:10099.612792`
```
**Slaves nodes info cpu**
```
# Cpu
used_cpu_sys:175787.384075
used_cpu_user:698887.401407
used_cpu_sys_children:0.0
used_cpu_user_children:0.0
used_cpu_sys_main_thread:23414.815817
used_cpu_user_main_thread:88751.989296
```
```
# Cpu
used_cpu_sys:159711.387120
used_cpu_user:619883.754609
used_cpu_sys_children:0.0
used_cpu_user_children:0.0
used_cpu_sys_main_thread:19626.342808
used_cpu_user_main_thread:77384.450443
```
**Master node info clients**
```
# Clients
connected_clients:621
client_read_buffer_bytes:14300672
blocked_clients:0
dispatch_queue_entries:0
```
**Slaves nodes info clients**
```
# Clients
connected_clients:296
client_read_buffer_bytes:80128
blocked_clients:0
dispatch_queue_entries:0
```
```
# Clients
connected_clients:293
client_read_buffer_bytes:78336
blocked_clients:0
dispatch_queue_entries:0
```

**Master node info stats**
```
# Stats
total_connections_received:75523574
total_commands_processed:548979436
instantaneous_ops_per_sec:233
total_pipelined_commands:437595
pipelined_latency_usec:296447137
total_net_input_bytes:7334320770324
connection_migrations:0
total_net_output_bytes:180508683607
rdb_save_usec:8365064914
rdb_save_count:32474907
instantaneous_input_kbps:-1
instantaneous_output_kbps:-1
rejected_connections:-1
expired_keys:11509854
evicted_keys:0
hard_evictions:0
garbage_checked:180544
garbage_collected:793
bump_ups:0
stash_unloaded:2388
oom_rejections:0
traverse_ttl_sec:584
delete_ttl_sec:18
keyspace_hits:55729030
keyspace_misses:247021789
keyspace_mutations:198153889
total_reads_processed:685020491
total_writes_processed:565628176
defrag_attempt_total:0
defrag_realloc_total:0
defrag_task_invocation_total:0
reply_count:565628176
reply_latency_usec:25731435102
blocked_on_interpreter:0
ram_hits:0
ram_misses:0
```

**Slaves nodes info stats**
```
# Stats
total_connections_received:22099138
total_commands_processed:1085733566
instantaneous_ops_per_sec:382
total_pipelined_commands:526580
pipelined_latency_usec:70386603695
total_net_input_bytes:49626944228
connection_migrations:0
total_net_output_bytes:4063665075847
rdb_save_usec:9260978956
rdb_save_count:32472056
instantaneous_input_kbps:-1
instantaneous_output_kbps:-1
rejected_connections:-1
expired_keys:0
evicted_keys:0
hard_evictions:0
garbage_checked:150340
garbage_collected:0
bump_ups:0
stash_unloaded:2259
oom_rejections:0
traverse_ttl_sec:0
delete_ttl_sec:0
keyspace_hits:386118703
keyspace_misses:26201422
keyspace_mutations:209587441
total_reads_processed:855333849
total_writes_processed:1184010146
defrag_attempt_total:0
defrag_realloc_total:0
defrag_task_invocation_total:0
reply_count:1184010146
reply_latency_usec:356413694117
blocked_on_interpreter:0
ram_hits:0
ram_misses:0
```
```
# Stats
total_connections_received:20864657
total_commands_processed:1063386088
instantaneous_ops_per_sec:322
total_pipelined_commands:491147
pipelined_latency_usec:29862867510
total_net_input_bytes:48141084284
connection_migrations:0
total_net_output_bytes:3926709680862
rdb_save_usec:8386962687
rdb_save_count:32474072
instantaneous_input_kbps:-1
instantaneous_output_kbps:-1
rejected_connections:-1
expired_keys:0
evicted_keys:0
hard_evictions:0
garbage_checked:150340
garbage_collected:0
bump_ups:0
stash_unloaded:2259
oom_rejections:0
traverse_ttl_sec:0
delete_ttl_sec:0
keyspace_hits:376367946
keyspace_misses:25827930
keyspace_mutations:209587485
total_reads_processed:833892490
total_writes_processed:1150830057
defrag_attempt_total:0
defrag_realloc_total:0
defrag_task_invocation_total:0
reply_count:1150830056
reply_latency_usec:300549200531
blocked_on_interpreter:0
ram_hits:0
ram_misses:0
```

**Enviroment:**
Master node: Ubuntu 20.04.6 LTS with kernel 5.15.0-73-generic
Slaves nodes: Ubuntu 22.04.4 LTS with kernel 5.15.0-73-generic

DragonFly version: 1.17.1 (on bare metal)
Uptime of dragonfly: 19-Apr (last upgrade to 1.17.1)

Init flag file (same on all nodes):
`--pidfile=/var/run/dragonfly/dragonfly.pid
--log_dir=/var/log/dragonfly
--dir=/var/lib/dragonfly
--version_check=true
--port=6392
--dbnum=24
--hz=1
--proactor_threads=8
--snapshot_cron=0 */1 * * *
--keys_output_limit=12288
--dbfilename=dump-{timestamp}`

Replica with sentinel

htop screenshot on master:
![imagen](https://github.com/dragonflydb/dragonfly/assets/62182142/604b5c75-ad17-4ecf-befc-ab4aef30eaf2)

htop screenshot on slaves:
![imagen](https://github.com/dragonflydb/dragonfly/assets/62182142/9929fe5f-ce6c-48a5-80dc-c6fe87b69be0)
![imagen](https://github.com/dragonflydb/dragonfly/assets/62182142/efd04bed-06ee-4b44-847a-46e14b2e59f8)

I have run MONITOR on one of the slaves (for a short time, the system is in production) and it looks like it may be related to the replication process.

There is no information in the logs.

Is this behavior expected? or does it actually seem that the slaves are consuming more CPU than expected?

Thanks in advance

**Comment by romange** [comment]
It is hard to say what's going on there based on this data. I suggest running a binary with debug symbols like this one:
`https://github.com/dragonflydb/dragonfly/releases/download/v1.17.1/dragonfly-x86_64-dbgsym.tar.gz` 
on slave nodes
and then profile it by running: `sudo perf record  -p $(pidof dragonfly) -g -F99  --call-graph=dwarf ` for ~30 seconds on a slave node when the process CPU is high. 
it will produce `perf.data` - you can DM me on discord or send it to me and I will take a look.

**Comment by fernandomacho** [comment]
Hi, we test this config of dragonfly:
1 master
2 slave

**On balancer**
1 read/write (master)
1 read (1 slave)

With this configuration, the CPU usage on the slave that does not receive read requests remains practically the same as the master.
Therefore it seems that this "excessive" CPU usage is due to the simultaneous replica + read operations.

Roman has been reviewing the profiling files and there doesn't seem to be any problem.
Therefore, this is not a bug, it is expected in this type of configuration.

Thank you very much for your help!
