### ISSUE TITLE
HTTL: access expiration time of hashes

### ISSUE THREAD

**Issue by Le0Developer** [dragonflydb/dragonfly#3026]
**Is your feature request related to a problem? Please describe.**
I'm trying to access the expiration time of a hash created using `HSETEX`, but no such command exists.

**Describe the solution you'd like**
`HTTL key field` which behaves like `TTL key` but for hashes.

**Describe alternatives you've considered**
Tracking expiration time in an extra hash, but that just wastes storage for redundant information that already exists.

**Related**
#687 which originally added `HSETEX`

**Comment by romange** [comment]
Seems we have the undocumented `FIELDTTL`  command that does exactly that.
Opened https://github.com/dragonflydb/dragonfly/issues/3026 for that

**Comment by Le0Developer** [comment]
Closing as dragonflydb/documentation#236 was merged.
Thanks!
