### ISSUE TITLE
JournalStreamer::WriterFb can rewritten without fiber creation

### ISSUE THREAD

**Issue by BorysTheDev** [dragonflydb/dragonfly#3042]
JournalStreamer::WriterFb is a fiber that exists only because it uses a synchronous socket API but the socket also implements AsyncSink API so it is possible to get rid of this fiber

**Comment by adiholden** [comment]
@BorysTheDev this is done right?

**Comment by romange** [comment]
Yes, it is done, should be released in 1.20
