### ISSUE TITLE
redis-py doesn't throw NoPermissionError on ACL mismatch

### ISSUE THREAD

**Issue by safa-topal** [dragonflydb/dragonfly#3047]
**Describe the bug**
When a Dragonfly ACL is violated with redis-py library, it does not throw NoPermissionError but instead throws ResponseError with message starting with `NOPERM:`.

**To Reproduce**
1. Violate an ACL with redis-py library
2. See that it throws ResponseError with `NOPERM:`

**Expected behavior**
redis-py should throw NoPermissionError.

**Environment (please complete the following information):**
 - Dragonfly Version: 1.16.1

**Comment by kostasrim** [comment]
Yep, we are sending the wrong error type -- I will fix this :)
