### ISSUE TITLE
Got "script tried accessing undeclared key" when key actually exists

### ISSUE THREAD

**Issue by howz97** [dragonflydb/dragonfly#3066]
**Describe the bug**
Got "script tried accessing undeclared key" when key actually exists

**To Reproduce**
install drongonfly 
```shell
docker run --network=host --ulimit memlock=-1 docker.dragonflydb.io/dragonflydb/dragonfly
```
execute
```shell
127.0.0.1:6379> set foo bar
OK
127.0.0.1:6379> get foo
"bar"
127.0.0.1:6379> eval "redis.call('GET', 'foo')" 0
(error) ERR Error running script (call to 77563f88f961d5772ea29fbc4a18558997365e67): @user_script:2: script tried accessing undeclared key
```

**Expected behavior**
eval should succeed

**Environment (please complete the following information):**
 - OS: [ubuntu 20.04]
 - Kernel: `Linux ip-172-31-40-58 5.15.0-1058-aws #64~20.04.1-Ubuntu SMP Tue Apr 9 11:11:55 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux`

 - Containerized?: Docker
 - Dragonfly Version: [e.g. 0.3.0]

**Reproducible Code Snippet**
```
# Minimal code snippet to reproduce this bug
```

**Additional context**

**Comment by dranikpg** [comment]
It doesn't matter if the key exists or not, it needs to be added to the EVAL command or specific script options should be used #272

**Comment by howz97** [comment]
I tried append the key to EVAL, while it return (nil) . Is this a bug? @dranikpg 
```shell
127.0.0.1:6379> set foo bar
OK
127.0.0.1:6379> get foo
"bar"
127.0.0.1:6379> eval "redis.call('GET', KEYS[1])" 1 foo
(nil)
127.0.0.1:6379> 
```

**Comment by romange** [comment]
@howz97  you should write : `eval "return redis.call('GET', KEYS[1])" 1 foo`
note the "return"
