### ISSUE TITLE
Enable ASAN when using MIMalloc

### ISSUE THREAD

**Issue by zhangh43** [dragonflydb/dragonfly#3070]
I want to enable ASAN to do memory check for DragonflyDB, but DragonflyDB uses MiMalloc. Are they compatible? Two options:

1. MiMalloc can be compiled with ASAN. 
2. Compile DragonflyDB with ASAN. 

Did anyone try this before? Any ideas?

**Comment by kostasrim** [comment]
Hello @zhangh43,

ASAN injects its own allocator and it also pads the region from the left and the right such that it finds overflows and underflows of memory.


Also in Dragonfly we use Fibers extensively and ASAN integration with `fcontext` is let's say incomplete which causes a few false positive that we have to manually turn off. There is a fully working integration with `ucontext` but the context switches are at least 50x slower so it's really not worth it to go over that route.

All in all, we do have sannitizers enabled and we do have a daily build that runs it and reports us the errors (and as I  said I personally disabled the false positives)

I hope this is helpful :)
