### ISSUE TITLE
CI: integrate github events with Discord 

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#309]
1. we should send "released" announcements into the announcement channel. Probably should be part of `.github/workflows/docker-release.yml` flow
2. we should introduce the "github" channel in our Discord and send there PRs and commits notifications.

This action can possible help with that:
https://github.com/Ilshidur/action-discord

**Comment by Tomato6966** [comment]
for the updates you can just go to --> repo settings --> webhooks --> create

paste discord channel webhook url

add /github to the end

in the repo settings webhook, allow json thingy
and then click send everything
