### ISSUE TITLE
dragonfly crashes if threads are more then expected

### ISSUE THREAD

**Issue by NobinKhan** [dragonflydb/dragonfly#3097]
**Describe the bug**
`I20240529 10:33:47.010128     1 init.cc:70] dragonfly running in opt mode.
* Logs will be written to the first available of the following paths:
/tmp/dragonfly.*
./dragonfly.*
* For the available flags type dragonfly [--help | --helpfull]
* Documentation can be found at: https://www.dragonflydb.io/docs
I20240529 10:33:47.010191     1 dfly_main.cc:646] Starting dragonfly df-dev-0000000
W20240529 10:33:47.010406     1 dfly_main.cc:685] SWAP is enabled. Consider disabling it when running Dragonfly.
I20240529 10:33:47.010416     1 dfly_main.cc:690] maxmemory has not been specified. Deciding myself....
I20240529 10:33:47.010419     1 dfly_main.cc:699] Found 1.93GiB available memory. Setting maxmemory to 1.55GiB
W20240529 10:33:47.010442     1 dfly_main.cc:366] iouring API is not supported. switching to epoll.
I20240529 10:33:47.088972     1 proactor_pool.cc:147] Running 12 io threads
E20240529 10:33:47.088999     1 dfly_main.cc:172] There are 12 threads, so 3.00GiB are required. Exiting...
`

**Environment (please complete the following information):**
 - OS: [fedora 39]
 - Kernel: # Command: `Linux 6.8.10-200.fc39.x86_64`
 - Containerized?: [podman]
 - Dragonfly Version: [1.18.1]

**Comment by adiholden** [comment]
Hi @NobinKhan 
Dragonfly is exiting as there is not enought memory to run with 12 threads.
you can see that the process found 1.93GiB available memory but 12 threads requeier 3GiB at least.
you should either use machine with more memory or reduce the number of threads with flag --proactor_threads=

**Comment by dranikpg** [comment]
I think we can close it, as it's not really a bug. Maybe the error message can be improved 🤷🏻‍♂️
