### ISSUE TITLE
stable sync replication dcheck fails over long latency connections

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#3112]
**Describe the bug**
With unreliable connections, replica crashes on `tx_executor.cc:116] Check failed: tx_data.lsn == *lsn_`

**To Reproduce**

1. Run the server on the cloud, make its port 6379 accessible to the local machine, run there DF
3. Run DF on your local machine, configure it to be a replica of cloud DF.
4. Run memtier on the cloud machine (DF master) with enough write traffic: `memtier_benchmark  -c 10 --threads 4  --ratio 1:0 --key-maximum 100000000 -d 100  -n 30000 --hide-histogram --distinct-client-seed`
5. At some point, the master DF (on the cloud machine) will print: `dflycmd.cc:273] Partial sync requested from stale LSN...`
6. The replica will crash around this time.

**Comment by adiholden** [comment]
I think that https://github.com/dragonflydb/dragonfly/pull/3686 fixes this but we need to verify.
The journal lsn when finalizing the full sync was sent before calling journal callback unregister which can block and this might cause sending wrong journal offset to replica when full sync finishes as more commands are writing to journal until the unregister returns

**Comment by romange** [comment]
I agree that someone needs to run this.

**Comment by BorysTheDev** [comment]
I've run a couple of times and everything works well
