### ISSUE TITLE
Horizontal Scaling

### ISSUE THREAD

**Issue by robd003** [dragonflydb/dragonfly#3114]
**Is your feature request related to a problem? Please describe.**
Right now Dragonfly only scales vertically. I'd like to be able to scale out to multiple hosts.

**Describe the solution you'd like**
The ability to connect to any host in the cluster and perform commands on any key. If that key is not on the current node then the request would be forwarded to the node that holds the key. Changes would be persisted out to replicas. The cluster should be kept in sync with Raft.

**Describe alternatives you've considered**
Paying for Redis Enterprise, but I really don't want to.

**Comment by romange** [comment]
AFAIK, Redis Enterprise does not allow forwarding commands for any key. You did not explain why multiple hosts is the  requirement for your use-case.

**Comment by romange** [comment]
Please see https://github.com/dragonflydb/dragonfly/discussions/1498 for more extended answer. Closing
