### ISSUE TITLE
FLUSHALL during slot migration causes assert failure

### ISSUE THREAD

**Issue by chakaz** [dragonflydb/dragonfly#3132]
```cpp
auto DashTable<_Key, _Value, Policy>::Traverse(Cursor curs, Cb&& cb) -> Cursor {
  ...

  // We fix bid and go over all segments. Once we reach the end we increase bid and repeat.
  do {
    SegmentType* s = segment_[sid];
    assert(s);
```

Open questions:
1. Should we forbid running FLUSHALL when a migration takes place?
2. Could this `assert` happen also in other flows / scenarios?

**Comment by BorysTheDev** [comment]
@dranikpg  thinks that maybe the dbtable is dropped and you're referencing a deleted pointer? snapshot copies it explicitly (the intrusive poiner)
