### ISSUE TITLE
GEOSEARCH still "PARTIALLY SUPPORTED"

### ISSUE THREAD

**Issue by piyongcai-liucai** [dragonflydb/dragonfly#3161]
DrgonfluDB is a great database. 
bug for the GEOSEARCH command, I have the following questions to consult
 1. When will I fully support it.
 2. When viewing the document, it does not indicate that those parts of the command are not supported, or that what uncertain actions exist.

 thanks very much!

**Comment by kostasrim** [comment]
Hi @piyongcai-liucai, thank you for the good words. 

1. I am not sure when this will be fully implemented but maybe somebody in the community will take care of this?
2. Which document are you referring to? Are you talking about our docs ?

**Comment by piyongcai-liucai** [comment]
> Hi @piyongcai-liucai, thank you for the good words.
> 
> 1. I am not sure when this will be fully implemented but maybe somebody in the community will take care of this?
> 2. Which document are you referring to? Are you talking about our docs ?

thanks your reply。

[document refer](https://www.dragonflydb.io/docs/command-reference/geospatial-indices/geosearch)

**Comment by kostasrim** [comment]
@piyongcai-liucai thank reporting this we will update it :)
