### ISSUE TITLE
CapturingReplyBuilder ignores OpStatus in SendError method

### ISSUE THREAD

**Issue by BagritsevichStepan** [dragonflydb/dragonfly#3190]
During testing the #3181, I caught one bug in the `CapturingReplyBuilder`. The test `MultiTest.Multiname` failes with the error:
```bash
/home/bagrstepan/Documents/GitHub/dragonfly/src/server/multi_test.cc:303: Failure
Value of: resp.GetVec()
Expected: has 2 elements where
element #0 is equal to 0x5fff23c9985b pointing to "OK",
element #1 is equal to 0x5fff23c9985b pointing to "OK"
  Actual: Vec: ['OK',e(ERR )]
, whose element #1 doesn't match
```

The problem is, that we don't check the `OpStatus` of  the`ErrorReply` in the `CapturingReplyBuilder::SendError(ErrorReply error)` method.

**Comment by romange** [comment]
@dranikpg  FYI
