### ISSUE TITLE
Add backup/restore Prometheus metrics

### ISSUE THREAD

**Issue by zacharya19** [dragonflydb/dragonfly#3210]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my DragonflyDB is failing to preform snapshot/restore and I have no visibility of it.
For example: When the IAM of the service is broken and DragonflyDB get's access denied.

**Describe the solution you'd like**
Expose Promethues metrics such as:
```
snapshot_failure_count
restore_failure_count
```

**Describe alternatives you've considered**
The logs has an error message, but using it for alerts is annoying.

**Additional context**

**Comment by zacharya19** [comment]
I will add: it can also be a general counter snapshot count (fail and success) in addition to a gauge with fail count.
Might be more useful that way.

**Comment by romange** [comment]
Does dragonfly proceed if it does not succeed to load the snapshot at the start?

**Comment by zacharya19** [comment]
It does stay alive, haven't checked if the connection is healthy.
It can also happened after successful boot (e.g. removing the permission to s3 after boot).
