### ISSUE TITLE
vector search - throws an exception when replacing an element 

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#3256]
Dragonfly crashes with the log below. 
First, we should be able to reproduce this scenario pretty easily.
Then, we should understand how to fix it.

```
transaction.cc:679] Unexpected exception Can't use addPoint to update deleted elements if replacement of deleted elements is enabled.
```

**Comment by dranikpg** [comment]
We re-use internal document ids, it might conflict with the fact that `replace_deleted` tries to do the same 🙂 Just disabling it might help
