### ISSUE TITLE
fix pytest skip tests

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#3262]
go over all pytests which are marked with
@pytest.mark.skip

check what is the reason we dont run them
find if we need to fix the test/dragonfly code to enable this tests

**Comment by kostasrim** [comment]
@adiholden @BorysTheDev what's the status of this ? Shall we close this or ?

**Comment by adiholden** [comment]
Borys fixed alot of skiped tests but we still have some.
We will make another effort on this but it will not be on Borys only. I will close this issue now
