### ISSUE TITLE
test_cluster_flushall_during_migration deadlock

### ISSUE THREAD

**Issue by kostasrim** [dragonflydb/dragonfly#3302]
https://github.com/dragonflydb/dragonfly/actions/runs/9873158205/job/27264815551?pr=3297#step:12:228

**Comment by kostasrim** [comment]
@BorysTheDev @chakaz

**Comment by kostasrim** [comment]
https://github.com/dragonflydb/dragonfly/pull/3573 disabled it here

**Comment by chakaz** [comment]
I'm closing this since it was re-enabled here https://github.com/dragonflydb/dragonfly/pull/3681 and has since passed.
Let's reopen if it fails again.
