### ISSUE TITLE
TTL for messages in SET

### ISSUE THREAD

**Issue by foboni** [dragonflydb/dragonfly#335]
**Did you search GitHub Issues and GitHub Discussions First?**
Yes

**Is your feature request related to a problem? Please describe.**
Yes, There is no way to set TTL for messages in a KEY

**Describe the solution you'd like**
We should be able to set a message TTL for collections such as SET, LIST etc.
This message TTL will not expire the KEY rather it expires messages

**Describe alternatives you've considered**

1. One dirty workaround is to use separate KEYs for each messages in a pattern (to achieve functionality similar to collections)

Example:
```
@00:00:00 SET mycollection:1 value1
@00:00:01 EXPIRE mycollection:1 60
@00:01:00 SET mycollection:2 value 2
@00:01:01 EXPIRE mycollection:1 60
@00:01:02 KEYS mycollection:*
# returns
1) mycollection:2
```
2. Using sorted SETs
```
Use sorted sets, and use a timestamp as the score. It's then trivial to delete items by score range,
which could be done periodically, or only on every write, with reads always ignoring the out of range elements,
by reading only a range of scores.
```
Source - https://groups.google.com/g/redis-db/c/rXXMCLNkNSs

**Comment by foboni** [comment]
A question in SO related to this

https://stackoverflow.com/questions/7577923/redis-possible-to-expire-an-element-in-an-array-or-sorted-set

**Comment by romange** [comment]
We can start with sets because we laid out our own implementation for this data-structure.

We can introduce a command `SADDEX  key ttl member member member`.
This command will set a TTL in seconds for each of the members.
The next SADDEX command for the same key must have the same TTL, otherwise the error will be returned. Similarly, calling SADDEX on an existing key that was created with SADD will also return an error.

subsequently, `SADD key member ...` will work on keys with TTL for members by using the TTL already set by previous SADDEX call. Of course, if SADD was used to create a set then no TTL is set.  

will it work for your case?

**Comment by foboni** [comment]
```
We can start with sets because we laid out our own implementation for this data-structure.
```
Okay, that's fine.

The proposed solution should work.

> SCARD will return approximate results because it can not know which members are expired without iterating on all of them.

Why do you think that it would return approx results ? Once a message is expired, it automatically gets removed from the SET. In that case `SCARD` should return correct result, right ?

**Comment by romange** [comment]
something needs to actually check and expire it. if we do lazy expiry, SCARD will be approximate. If we apply exact expiry then the CPU and memory usage will be much higher.

**Comment by romange** [comment]
> > command will set a TTL in seconds for each of the members.
> > The next SADDEX command for the same key must have the same TTL, otherwise the error will be returned. Similarly, calling SADDEX on an existing key that was created with SADD will also return an error.
> 
> Considering these issues, can we consider creating a new data type based on SET with expiry feature ?

I do not think that this warrants an introduction of a new data type. SADD will work as expected as long as you do not use SADDEX so it is backward compatible with the existing type.

**Comment by odedponcz** [comment]
There is no meaning for having the same TTL for all members of the set if the TTL is set with every SADDEX.
I suggest to allow any set to mix between TTL members and non expired members.
SADDEX will add memebers to the set with TTL
SADD will add members to the set with +INF TTL.

In this implementation errors are not required.

**Comment by foboni** [comment]
KeyDB has got similar feature, see [here](https://docs.keydb.dev/docs/commands/#expiremember)

## EXPIREMEMBER

#### Syntax:

```EXPIREMEMBER <key> <subkey> <timeout-in-seconds> <OPTIONAL:unit-time-format>```

#### Description:

Sets a timeout on a subkey (individual member of a set).

After the timeout has expired, the subkey will automatically be deleted. This 
command is similar to the EXPIRE command but is associated to individual members
of a set. 

If a subkey has an expiration set and is later moved or deleted before expiry, 
then the expiration behavior is undefined. Examples of this may include `SMOVE and SADD`.

The timeout can also be cleared, turning the subkey back into a persistent subkey,
using the `PERSIST` command.

TTL (time to live) is by default set in seconds, however you can optionally specify the unit to milleseconds 
The command format is `EXPIREMEMBER key subkey delay [Unit: s,ms]`. This time similar to EXPIRE can be queried with TTL and PTTL

#### Refreshing expires

It is possible to call `EXPIREMEMBER` using as argument a subkey that already has an
existing expire set.
In this case the time to live of a subkey is _updated_ to the new value.

#### Return:

Integer Reply, specifically:

* `1` if the timeout was set.
* `0` if `key` does not exist.

#### Examples:

```
keydb-cli> SADD key member1 member2 member3
(integer) 3
keydb-cli> SMEMBERS key
1) "member1"
2) "member2"
3) "member3"
keydb-cli> EXPIREMEMBER key member1 10
(integer) 1
keydb-cli> TTL key member1
(integer) 10
keydb-cli> EXPIREMEMBER key member1 10000 ms
(integer) 1
keydb-cli> TTL key member1
(integer) 10
```
*10 seconds later...*
```
keydb-cli> SMEMBERS key
1) "member2"
2) "member3"
keydb-cli> EXPIREMEMBER key member1 10
(error) ERR subkey does not exist
```
