### ISSUE TITLE
Support `PEXPIRETIME`

### ISSUE THREAD

**Issue by alexsnaps** [dragonflydb/dragonfly#3450]
**Is your feature request related to a problem? Please describe.**
Looking into alternatives to Redis, we tested [our server](https://github.com/Kuadrant/limitador/) with Dragonfly... Which worked well, other than the lack of support for `PEXPIRETIME`, which lets us be more aggressive wrt caching. As such support for it would be real beneficial to our usecase. 

**Describe the solution you'd like**
Support for `PEXPIRETIME` as per [redis 7.x](https://redis.io/docs/latest/commands/pexpiretime/)

**Describe alternatives you've considered**
Without it, we need to keep "two sources" of time and do diff across these, based of `PTTL`.

**Comment by chakaz** [comment]
Hey @alexsnaps, thanks for filing this!

Indeed, this is something we should fix.

If you're into C++, this might be a relatively easy contribution. I've also added "help wanted" and "good first issue" labels for other contributors to, perhaps, help.

**Comment by chakaz** [comment]
For those who consider contributing: implementing `PEXPIRETIME` (and while at it, `EXPIRETIME`) commands should be very similar to the existing implementation of `PTTL` (and `TTL`), so you could start with that.

**Comment by alexsnaps** [comment]
Yeah, if I read [this right](https://github.com/dragonflydb/dragonfly/blob/ff716bb8b0a65834830dc3523e2ab30c45d9048c/src/server/generic_family.cc#L1470-L1481) we'd need a `OpExpireTime` based of that `OpTtl`, that "just" avoids doing [the math](https://github.com/dragonflydb/dragonfly/blob/ff716bb8b0a65834830dc3523e2ab30c45d9048c/src/server/generic_family.cc#L1479) and return the expiry time as a `uint64_t` directly. Then have a `GenericFamily::ExpireTimeGeneric` do the unit conversion and write the result back.

**Comment by chakaz** [comment]
@alexsnaps generally yes, although I'd keep only one version (without "the math") and do the subtraction only for `TTL`/`PTTL`.
And also - we need unit tests (in `generic_family_test.cc`)

But yeah, that sounds like a plan to me! :)

**Comment by Eunoia1729** [comment]
Hey all, new to this repo. 
I'd be glad to take a stab at this :)

**Comment by romange** [comment]
Sure go ahead, send a PR :)
see https://github.com/dragonflydb/dragonfly/blob/main/CONTRIBUTING.md on how to setup the dev environment and how to build dragonfly from source
