### ISSUE TITLE
test_network_disconnect_small_buffer deadlock

### ISSUE THREAD

**Issue by kostasrim** [dragonflydb/dragonfly#3472]
see https://github.com/dragonflydb/dragonfly/actions/runs/10299101135/job/28505690954 + logs

**Comment by BorysTheDev** [comment]
I've investigated the ticket and have found a deadlock. 
0x5a50c4464eac  util::fb2::detail::FiberInterface::SwitchTo()
0x5a50c446141f  util::fb2::detail::Scheduler::Preempt()
0x5a50c3f4c4b3  dfly::ThreadLocalMutex::lock()
0x5a50c3c9a8d8  dfly::SliceSnapshot::OnJournalEntry()
0x5a50c3f540d8  dfly::journal::JournalSlice::AddLogRecord()
0x5a50c3f52570  dfly::journal::Journal::RecordEntry()
0x5a50c3f65bdb  dfly::RecordExpiry()
0x5a50c3f21d86  dfly::DbSlice::ExpireIfNeeded()
0x5a50c3f23c36  dfly::DashTable<>::Traverse<>()
0x5a50c3f23de3  dfly::DbSlice::DeleteExpiredStep()
0x5a50c3e61017  dfly::EngineShard::RetireExpiredAndEvict()
0x5a50c3e62638  dfly::EngineShard::Heartbeat()
0x5a50c3e628fd  dfly::EngineShard::RunPeriodic()

the lock in the dfly::EngineShard::RetireExpiredAndEvict()
and in the dfly::SliceSnapshot::OnJournalEntry()

this deadlock happens during a transaction so when we run a global transaction in replica, the replica transaction gets stuck too. Replica's transaction is executed under replica_ptr->GetExclusiveLock(); which leads to another part of dflycmd code blocking

**Comment by romange** [comment]
@BorysTheDev  do you have the other stacktrace that confirms the deadlock? what is "replica transaction" ?

**Comment by BorysTheDev** [comment]
> @BorysTheDev do you have the other stacktrace that confirms the deadlock? what is "replica transaction" ?

Of course. the file is attached
[stacks.txt](https://github.com/user-attachments/files/16624273/stacks.txt)

**Comment by romange** [comment]
I do not see `GetExclusiveLock` in the stacktrace

**Comment by romange** [comment]
oh, I see, this stack holds the acquire lock, starts transaction into the shard-queue but tx can not progress because shard queue 
is waiting for the lock to grab.
```
0x5a50c4464eac  util::fb2::detail::FiberInterface::SwitchTo()
0x5a50c446141f  util::fb2::detail::Scheduler::Preempt()
0x5a50c3f5a445  util::fb2::EventCount::await<>()
0x5a50c3f61600  dfly::Transaction::ScheduleInternal()
0x5a50c3f6296f  dfly::Transaction::Execute()
0x5a50c3f62a56  dfly::Transaction::Guard::Guard()
0x5a50c3e8f06b  dfly::DflyCmd::StartStable()
0x5a50c3f4135f  dfly::CommandId::Invoke()
0x5a50c3c4b322  dfly::Service::InvokeCmd()
0x5a50c3c4fdba  dfly::Service::DispatchCommand()
0x5a50c4032688  facade::Connection::DispatchSingle()
0x5a50c4032a12  facade::Connection::ParseRedis()
0x5a50c40350cf  facade::Connection::IoLoop()
0x5a50c4035391  facade::Connection::ConnectionFlow()
0x5a50c40364ec  facade::Connection::HandleRequests()
0x5a50c447325b  util::ListenerInterface::RunSingleConnection()
```

**Comment by romange** [comment]
I think that we should rewrite dflycmd code in such way that we never hold locks over `replica_ptr` while performing transactions.

**Comment by BorysTheDev** [comment]
Without this lock, we could never know about the deadlock in db_slice :-)

**Comment by romange** [comment]
so maybe I do not understand something. what's the root cause deadlock?

**Comment by BorysTheDev** [comment]
the same mutex is locked  in the dfly::EngineShard::RetireExpiredAndEvict()
and in the dfly::SliceSnapshot::OnJournalEntry()

**Comment by romange** [comment]
it's not locked there. they are trying to grab it there but can not.

**Comment by kostasrim** [comment]
@romange The problem is that we lock the same mutex `db_slice.GetSerializationMutex()` twice on the same `fiber`. 

We first lock it in `RetireExpiredAndEvict()` on line `637` and then eventually we log the expired items on the `journal` via (in the call path of `ExpireIfNeeded`) a call to `RecordExpire` which will apply the `callbacks registered by the snapshot`. These callbacks, acquire the same `mutex`:

```
>>384 void SliceSnapshot::OnJournalEntry(const journal::JournalItem& item, bool await) {                 
  385   // To enable journal flushing to sync after non auto journal command is executed we call         
  386   // TriggerJournalWriteToSink. This call uses the NOOP opcode with await=true. Since there is no  
  387   // additional journal change to serialize, it simply invokes PushSerializedToChannel.            
  388   std::unique_lock lk(db_slice_->GetSerializationMutex());                                         
  389   if (item.opcode != journal::Op::NOOP) {                                                          
  390     serializer_->WriteJournalEntry(item.data);
  391   }  
  392 
```

And we will deadlock because the same fiber acquires/locks the same mutex twice. 

Now I must say `jokes on me` because I left this very nice comment in `Heartbeat`:

```
  679   // Because TriggerOnJournalWriteToSink will lock the same lock leading to a deadlock.
  680   lk.unlock();
```

So I was aware, but I did not see that loop above might also lock the same mutex. 

IMO that's why I was not a bug fun of introducing this lock in db_slice, because it makes it really difficult to get all the call paths right and deadlock free. I think this is the only place I missed but let's see, my changes with the `DCHECK` should point us out to other issues -- if these exist. 

I will push a patch in a few minutes.

**Comment by romange** [comment]
I must say I am also not a big fan of all these locks. Unfortunately it's not enough. One should suggest a better approach to replace the current one

**Comment by kostasrim** [comment]
I agree :)
