### ISSUE TITLE
Inability to Authorize Non-Default User with RESP3 Protocol by `HELLO 3 AUTH non_default_user some_pass`

### ISSUE THREAD

**Issue by 0x12th** [dragonflydb/dragonfly#3476]
**Describe the bug**
When attempting to connect using a non-default user and the RESP3 protocol `HELLO 3 AUTH non_default_user some_pass`, an error message is returned: "WRONGPASS invalid username-password pair or user is disabled." However, the authorization succeeds when using the `AUTH` command directly without the RESP3 protocol by `AUTH non_default_user some_pass` but then using RESP2.

**To Reproduce**
Attempt to connect as a non-default user with the RESP3 protocol
```
> HELLO 3 AUTH non_default_user some_pass
> (error) WRONGPASS invalid username-password pair or user is disabled.
```

Attempt to authenticate using the non-default user without the RESP3 protocol:
```
> AUTH non_default_user some_pass
> OK
```

Attempt to connect using the RESP3 protocol with the default user:
```
> HELLO 3 AUTH default some_default_pass
> 1# "server" => "redis"
...
```

**Expected behavior**
The non-default user should be authorized when connecting with the RESP3 protocol without encountering the WRONGPASS error as `HELLO 3 AUTH non_default_user some_pass`.

**Environment (please complete the following information):**
 - OS: 22.04.1-Ubuntu SMP
 - Kernel: 6.5.0-14-generic 
 - Containerized: Docker (docker.dragonflydb.io/dragonflydb/dragonfly:1.21.0)
 - Dragonfly Version: df-v1.21.0

**Reproducible Code Snippet**
```
# Attempt to connect with RESP3 protocol and non-default user
HELLO 3 AUTH non_default_user some_pass
```

**Additional context**
In the source code, when using AUTH with a non-default user, the following error is sent: SendError(facade::kAuthRejected).
Reference: https://github.com/dragonflydb/dragonfly/blob/7b9bbc19d7df29a7b8651ed9060eb11ef883d5e0/src/server/server_family.cc#L2421
It's unclear why this behavior occurs and why documentation doesn't mention this limitation.

**Comment by romange** [comment]
Thanks, we will take a look

**Comment by kostasrim** [comment]
Hi @0x12th ,

thank you for reporting this, I will take a look

**Comment by kostasrim** [comment]
@0x12th Hi! Plz try our weekly build once it's out -- the issue should be fixed :)

**Comment by 0x12th** [comment]
> @0x12th Hi! Plz try our weekly build once it's out -- the issue should be fixed :)

Hi, thanks. In what build (version) or date is planning to release with this fix?

**Comment by kostasrim** [comment]
Hi @0x12th  I am not sure when the next release will be but you can pull the weekly build from here: https://github.com/dragonflydb/dragonfly/pkgs/container/dragonfly-weekly

**Comment by 0x12th** [comment]
> Hi @0x12th I am not sure when the next release will be but you can pull the weekly build from here: https://github.com/dragonflydb/dragonfly/pkgs/container/dragonfly-weekly

And this fix yet in release? I thought that this fix must be in release note and waiting for)
