### ISSUE TITLE
test_cluster_migration_cancel assertion failure

### ISSUE THREAD

**Issue by kostasrim** [dragonflydb/dragonfly#3484]
see: https://github.com/dragonflydb/dragonfly/actions/runs/10309432284/job/28539074826

```
>       assert await nodes[1].client.dbsize() == 0
E       assert 1 == 0
```

**Comment by BorysTheDev** [comment]
I can't reproduce it anymore, maybe it was fixed by #3653.

**Comment by BorysTheDev** [comment]
still exist

**Comment by kostasrim** [comment]
Recent failure https://github.com/dragonflydb/dragonfly/actions/runs/10772716043
