### ISSUE TITLE
FT.SEARCH - search on TAG not working

### ISSUE THREAD

**Issue by alexbatis** [dragonflydb/dragonfly#3511]
**Describe the bug**
When performing a FT.SEARCH query on a TAG field on a JSON document, no results are returned. However, the same functionality works both on a HASH document in dragonfly and a JSON document using redisearch

**To Reproduce**
1. Create the index:
```
FT.CREATE "json_city" ON JSON PREFIX 1 json_city: SCHEMA "$[\"name\"]" AS name TAG SEPARATOR | "$[\"population\"]" AS population NUMERIC SORTABLE "$[\"continent\"]" AS continent TAG SEPARATOR |
```
2. Create the records:
```
JSON.SET "json_city:01J57VZMXMTXNA912J4BV2NFV8" $ "{\"name\":\"London\",\"population\":8.8,\"continent\":\"Europe\"}"
JSON.SET "json_city:01J57VZMXZEF6WFQ5CS29JHP4F" $ "{\"name\":\"Athens\",\"population\":3.1,\"continent\":\"Europe\"}"
JSON.SET "json_city:01J57VZMXZXMS9EZ1QFH0YFS24" $ "{\"name\":\"Tel-Aviv\",\"population\":1.3,\"continent\":\"Asia\"}"
JSON.SET "json_city:01J57VZMY0Z1VY8WH7X784CFA8" $ "{\"name\":\"Hyderabad\",\"population\":9.8,\"continent\":\"Asia\"}"
```
3. Query all records to ensure index is setup correctly: 
```
FT.SEARCH json_city *
```
4. Search for cities that have `Europe` as the `TAG` attribute `continent`.
```
FT.SEARCH json_city "(@continent:{Europe})"
```
5. Observe no results found
```
127.0.0.1:6379> FT.SEARCH json_city "(@continent:{Europe})"
1) (integer) 0
```

**Expected behavior**
Expected behavior would be that cities with the `continent` field matching `Europe` would be found, like they are when using hashes or redisearch. This behavior is outlined in the [dragonfly FT.SEARCH docs](https://www.dragonflydb.io/docs/command-reference/search/ft.search).

**Screenshots**
dragonfly (not working as expected):
<img width="2168" alt="image" src="https://github.com/user-attachments/assets/cac4fc7b-623e-43d4-bea9-5af454031ad6">
[dragonfly docs](https://www.dragonflydb.io/docs/command-reference/search/ft.search):
<img width="2168" alt="Screenshot 2024-08-14 at 2 56 23 AM" src="https://github.com/user-attachments/assets/df239dd9-151c-4b4e-99a2-f829c4f8d80c">
dragonfly (working example using hashes) - taken from [dragonfly search announcement example](https://www.dragonflydb.io/blog/announcing-dragonfly-search):
<img width="2168" alt="image" src="https://github.com/user-attachments/assets/ac12fd52-65f1-4c2b-a148-c09d460314e6">
redis-stack (uses exact same code as reproduction steps above and demonstrates expected behavior)
<img width="2168" alt="Screenshot 2024-08-14 at 3 05 15 AM" src="https://github.com/user-attachments/assets/4c40137a-0d79-43d0-acac-34537a41e172">
<img width="2168" alt="Screenshot 2024-08-14 at 3 05 25 AM" src="https://github.com/user-attachments/assets/955aa058-41d9-4054-bcde-ba1fcf2bb140">
<img width="2168" alt="Screenshot 2024-08-14 at 3 05 31 AM" src="https://github.com/user-attachments/assets/bd53475f-846f-4e9b-bad7-84410cff3c01">
<img width="2168" alt="Screenshot 2024-08-14 at 3 05 37 AM" src="https://github.com/user-attachments/assets/e4e160c4-7e24-4287-b125-4a649d424a6e">

**Environment (please complete the following information):**
 - OS: Mac OS 14.6.1 (23G93)
 - Kernel: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000 arm64
 - Containerized?: Docker/Docker compose
 - Dragonfly Version: df-v1.21.1

**Reproducible Code Snippet**
```
FT.CREATE "json_city" ON JSON PREFIX 1 json_city: SCHEMA "$[\"name\"]" AS name TAG SEPARATOR | "$[\"population\"]" AS population NUMERIC SORTABLE "$[\"continent\"]" AS continent TAG SEPARATOR |

JSON.SET "json_city:01J57VZMXMTXNA912J4BV2NFV8" $ "{\"name\":\"London\",\"population\":8.8,\"continent\":\"Europe\"}"
JSON.SET "json_city:01J57VZMXZEF6WFQ5CS29JHP4F" $ "{\"name\":\"Athens\",\"population\":3.1,\"continent\":\"Europe\"}"
JSON.SET "json_city:01J57VZMXZXMS9EZ1QFH0YFS24" $ "{\"name\":\"Tel-Aviv\",\"population\":1.3,\"continent\":\"Asia\"}"
JSON.SET "json_city:01J57VZMY0Z1VY8WH7X784CFA8" $ "{\"name\":\"Hyderabad\",\"population\":9.8,\"continent\":\"Asia\"}"

FT.SEARCH json_city *

FT.SEARCH json_city "(@continent:{Europe})"
```

**Additional context**
Code for working hash example:
```
FT.CREATE cities PREFIX 1 city: SCHEMA name TEXT population NUMERIC SORTABLE continent TAG
HSET city:1 name London population 8.8 continent Europe
HSET city:2 name Athens population 3.1 continent Europe
HSET city:3 name Tel-Aviv population 1.3 continent Asia
HSET city:4 name Hyderabad population 9.8 continent Asia
FT.INFO cities
FT.SEARCH cities '@continent:{Europe}' SORTBY population DESC LIMIT 0 1 RETURN 2 name population
FT.SEARCH cities '@population:[0 5] @continent:{Asia}' RETURN 1 name
```

I've also tried escaping the string in many different ways, as some other issues mention incorrect query formatting. as dragonfly is intended to be a drop in redis replacement i would hope that i wouldn't need to format the query in a different way to get it to work.
```
FT.SEARCH json_city "(@continent:{Europe})"
FT.SEARCH json_city (@continent:{Europe})
FT.SEARCH json_city "@continent:\{Europe\}"
FT.SEARCH json_city "@continent:\{'Europe'\}"
```

My ultimate goal is to get this type of query working with [redis-om-node](https://github.com/redis/redis-om-node)

Thanks for your help!

**Comment by dranikpg** [comment]
Hi @alexbatis. Looks like we have an interfacing issue with our new improved json backend 😢 

We'll fix this issue in our next release, for now you can run Dragonfly with `--jsonpathv2=false`. I checked and it works
