### ISSUE TITLE
Improve docker-compose example

### ISSUE THREAD

**Issue by AlissonRS** [dragonflydb/dragonfly#3526]
The [sample docker-compose](https://github.com/dragonflydb/dragonfly/blob/main/contrib/docker/docker-compose.yml) crashes depending on the local dev machine with the error below (previously reported here #2916 #3097):

```
dragonfly-1  | W20240819 02:57:03.453827     1 dfly_main.cc:679] SWAP is enabled. Consider disabling it when running Dragonfly.
dragonfly-1  | I20240819 02:57:03.453833     1 dfly_main.cc:684] maxmemory has not been specified. Deciding myself....
dragonfly-1  | I20240819 02:57:03.453835     1 dfly_main.cc:693] Found 6.57GiB available memory. Setting maxmemory to 5.25GiB
dragonfly-1  | W20240819 02:57:03.453861     1 dfly_main.cc:367] Weird error 1 switching to epoll
dragonfly-1  | I20240819 02:57:03.533286     1 proactor_pool.cc:147] Running 24 io threads
dragonfly-1  | E20240819 02:57:03.533322     1 dfly_main.cc:168] There are 24 threads, so 6.00GiB are required. Exiting...
```

For local development, the `maxmemory` of **5.25GiB** seems like a lot for playing around, yet because it's trying to run with so many IO threads (24), it fails to initialize.

For local development, instead of exiting because the local machine doesn't have enough memory given the amount of threads, it should just automatically calculate how many threads fit its maxmemory, and maybe display some warning message for the dev if this could be a problem for a prod environment.

**Comment by kostasrim** [comment]
Hi @AlissonRS would you be interesting in contributing ?

**Comment by dranikpg** [comment]
> Hi @AlissonRS would you be interesting in contributing ?

The solution is just to add a --proactor_threads=4 or some other low value, each thread expects 256 mb
