### ISSUE TITLE
Using cluster announce IP as replica announce IP causing confusion

### ISSUE THREAD

**Issue by andydunstall** [dragonflydb/dragonfly#3541]
On the control plane all nodes set `--cluster_announce_ip` to the datastore DNS record as we use cluster emulated mode

However after https://github.com/dragonflydb/dragonfly/pull/3421 it means all replicas connected to the same master report as having the same IP/domain which makes debugging difficult, such as `INFO` shows:
```
# Replication
role:master
connected_slaves:2
slave0:ip=jsbc4ryrz.dragonflydb.cloud.,port=6385,state=stable_sync,lag=0
slave1:ip=jsbc4ryrz.dragonflydb.cloud.,port=6385,state=stable_sync,lag=0
master_replid:d1baedff6bf4dbcb8bbd37aabc69fa5c30b80b8e
```

During updates or incidents where we have syncing or unhealthy replicas, we can't easily work out which is which looking at master `INFO` (but would have to instead look at each replica individually). So its not a big issue but it is a bit of a pain and can slow us down

**Comment by romange** [comment]
Probably should separate to `cluster_announce_ip` and `replica-announce-ip` and keep it as separate flags
