### ISSUE TITLE
Support ZUNION command

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#356]
See https://redis.io/commands/zunion for more details.

For external contributors: we will also accept the basic functionality without supporting of optional arguments.

**Comment by ATM-SALEH** [comment]
I can have a look into this

**Comment by matchyc** [comment]
@romange Hi, I'm new here, a graduate student interested in **DF**! I have seen the primary codes for `zset` related commands, and trying to implement the function.
One question I met is that `zunionstore` is implemented by `read->union->temporary map result->add to destkey` such procedure. But `Union` does not require the last step, and we can send results back to the client after we got the intermediate result. 
So what kind of method is wanted by community? 
I'd like to propose two plans:
- Implement a function like `ToObject` or `ToScoredArray`, which enable df to transform `ScoredMap` to `ScoredArray` and just call `OutputScoredArrayResult`.
- Implement a function like `OutputScoredMapResult`, which requires allocating a `ScoredArray` in this function to get a sorted result.

Thanks for reading this

**Comment by ATM-SALEH** [comment]
@matchyc - I started working on this feature. However, happy as well if you take over

**Comment by romange** [comment]
Hi @ATM-SALEH since you already started I think it makes sense that you continue...
There are enough tasks for everyone :)

**Comment by matchyc** [comment]
> @matchyc - I started working on this feature. However, happy as well if you take over

Just go on!

**Comment by romange** [comment]
hey @ATM-SALEH  are you still working on it?

**Comment by ATM-SALEH** [comment]
Yes - I started working on it. However, couldn't manage time to allocate this week. Hoping to wrap this up this weekend

**Comment by romange** [comment]
Fixed by #717
