### ISSUE TITLE
Cannot write to master when replica becomes unavailable

### ISSUE THREAD

**Issue by bogdanp05** [dragonflydb/dragonfly#3606]
**Describe the bug**
In a master-replica setup, if the replica becomes unavailable e.g. due to network issues, Dragonfly blocks subsequent writes. This is a difference in behavior from Redis which still allows writes. 
Is there a way to change this behavior to make it like redis? In our setup it's quite common for a node to go down, but clients should still be able to write to Dragonfly.

Another related issues is that we call `CLIENT PAUSE` on the master when a replica has gone offline and this will throw a `Failed to pause all running clients` error.

**To Reproduce**
1. Deploy 2 Dragonfly nodes, one master, one replica 
2. Generate some load e.g. with memtier_benchmark
3. Brick the replica by e.g. by adding iptables drop rules
4. Writes are still possible for a bit until the replication lag increases to some value (in my case it was ~3k)
5. Writes are not possible anymore

**Expected behavior**
The master node should still be writable when the replica goes offline.

**Environment (please complete the following information):**
 - OS: Fedora 39
 - Kernel: 6.9.9
 - Containerized?: systemd-container
 - Dragonfly Version: 1.18.1

**Reproducible Code Snippet**
```
# Minimal code snippet to reproduce this bug
```

**Additional context**

**Comment by kostasrim** [comment]
Hi @bogdanp05, thank you for reporting this. Let me get back to you

**Comment by kostasrim** [comment]
@bogdanp05 what command do you use to drop packets with IP tables ?

**Comment by kostasrim** [comment]
Also @bogdanp05 from version `v 1.20` we introduced `--replication_timeout (Time in milliseconds to wait for the replication writes being stuck.); default: 10000;` which should solve your issue

**Comment by romange** [comment]
Yeah, this should be fixed in 1.21.4

**Comment by bogdanp05** [comment]
that sounds like what I need, thanks!
