### ISSUE TITLE
Support SMISMEMBER

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#361]
See https://redis.io/commands/smismember/ for more details

**Comment by AayushiSingh005** [comment]
Can you assign this to me?

**Comment by romange** [comment]
hey @AayushiSingh005 . Just shoot a PR and I will assign it to you.

**Comment by romange** [comment]
@AayushiSingh005  I suggest that you start with reading the README. Working on this task requires a good knowledge of C++ and some knowledge of Redis.
