### ISSUE TITLE
FT.AGGREGATE does not fully support the SORTBY option

### ISSUE THREAD

**Issue by BagritsevichStepan** [dragonflydb/dragonfly#3631]
Dragonfly does not parse the following command:
```
FT.AGGREGATE index "*" GROUPBY 0 REDUCE COUNT 0 AS count SORTBY 2 @count DESC MAX 100
```

**Comment by rcl-viveksharma** [comment]
same issue

**Comment by rcl-viveksharma** [comment]
any update

**Comment by BagritsevichStepan** [comment]
> any update

Hi Vivek, I will push the changes in one/two weeks. The fix should be released in the next version.

**Comment by rcl-viveksharma** [comment]
thanks mate waiting for it

**Comment by rcl-viveksharma** [comment]
any update mate ?

**Comment by romange** [comment]
Hello @rcl-viveksharma .  no need to ask us for status updates every few days.

**Comment by rcl-viveksharma** [comment]
we are waiting for this aggregate, for a month, thats why

**Comment by rcl-viveksharma** [comment]
hai @BagritsevichStepan was this merged
