### ISSUE TITLE
test_replicaof_flag_disconnect - Unable to terminate df

### ISSUE THREAD

**Issue by kostasrim** [dragonflydb/dragonfly#3677]
Stacktrace https://github.com/dragonflydb/dragonfly/actions/runs/10296756650/job/28498658061#step:6:952

**Comment by romange** [comment]
The key question is how this can happen:
```
37005➜ 06:30:10.654806 23975 accept_server.cc:25] Exiting on signal Terminated
....
37005➜ 06:30:10.655012 23975 listener_interface.cc:238] sock[10] After HandleRequests
37005➜ 06:30:10.655021 23975 listener_interface.cc:246] sock[10] Closing connection
37005➜ 06:32:10.727766 23976 main_service.cc:823] Received User defined signal 1
37005➜ 06:32:10.727891 23975 listener_interface.cc:203] Listener - 37005 waiting for 1 connections to close
....
```

so basically the signal itself caused Dragonfly to wake up and proceed after 2 minutes of inactivity.

**Comment by kostasrim** [comment]
:shrug: will investigate

**Comment by romange** [comment]
I do not think there are immediate things to investigate here besides adding vlogs to the shutdown code in listener_interface.cc

**Comment by kostasrim** [comment]
will do

**Comment by kostasrim** [comment]
duplicate of #3468
