### ISSUE TITLE
Too many connections at once causes Timeout Issues

### ISSUE THREAD

**Issue by wernermorgenstern** [dragonflydb/dragonfly#3695]
**Describe the bug**
This is all on AWS EKS.
We are using BullMQ Pro with DragonFly.  We have 45 Queues (47 threads on DragonFly), and a producer service, running 15 replicas.
And then a consumer/worker, running 50 replicas, with 30 workers per queue.

When we start up all 50 Consumer Replicas at once, for the Redis Connection to DragonFly, we see a lot of TIMEOUT errors.

However, when I start 2-3 replicas at a time, and wait till they are healthy, and then start 2-3 more, then everything works fine.

**To Reproduce**
See above

**Expected behavior**
I would like to be able to start 50 replicas, for 45 queues, and 30 workers per Queue, to be able to be started at once, instead of gradually ramp up

**Environment (please complete the following information):**
 - OS: [ubuntu 20.04]
 - Kernel: # Command: `uname -a`
 - Containerized?: Kubernetes
 - Dragonfly Version: 1.22.1

**Comment by romange** [comment]
I am sorry @wernermorgenstern it's not actionable on our side. there is not enough information to deduce that something is wrong with Dragonfly.
