### ISSUE TITLE
Update `DFLYCLUSTER SLOT-MIGRATION-STATUS` response format

### ISSUE THREAD

**Issue by andydunstall** [dragonflydb/dragonfly#3701]
The output of `DFLYCLUSTER SLOT-MIGRATION-STATUS` is a bit of a pain to parse (particularly in Go)
```
$ redis-cli dflycluster slot-migration-status
1) "out node_hbdc2uom7 FINISHED keys:0 errors:ERR UNKNOWN_MIGRATION"
```

- Each entry has a single line with multiple fields
- Fields separated by spaces, except for error which can have spaces
- Some fields have a key prefix like `keys` and `errors` but others don't
- Sometimes the response is an array, other times its the string `NO_STATE`
- ...

What do you think about updating to return an array of arrays to be consistent with the other cluster commands like `CLUSTER SHARDS`? Such as:
```
1) 1) "out"
   2) "node_hbdc2uom7"
   3) "finished"
   4) (integer) 0
   5) "ERR UNKNOWN_MIGRATION"
2) ...
```

Then if there are no migrations just return an empty array?

I'm happy to add a PR as looks like it's just reformatting a bit, but figured worth checking first

**Comment by BorysTheDev** [comment]
It looks reasonable to me, @adiholden are you ok if I do it?
