### ISSUE TITLE
investigate memory usage with strings

### ISSUE THREAD

**Issue by kostasrim** [dragonflydb/dragonfly#3723]
https://github.com/dragonflydb/dragonfly/actions/runs/10902172431/job/30253477949#step:12:742 

I added this test as part of  #3641 and it failed for string objects. I will for now only enable the new assertions for json types and investigate why it failed with strings.

**Comment by kostasrim** [comment]
Same for lists btw :)

**Comment by chakaz** [comment]
@kostasrim can you elaborate a bit on which test is failing for strings? :pray:

**Comment by kostasrim** [comment]
@chakaz https://github.com/dragonflydb/dragonfly/pull/3641/files#diff-c6ffd3f71af3ea9499e00368b3fedeba88f51ab614ce54f849e11cc2b5e05fd9R45 

Comment out the `type == "json"` part and it shall fail for string and lists :smile:
