### ISSUE TITLE
JSON logging

### ISSUE THREAD

**Issue by applike-ss** [dragonflydb/dragonfly#3724]
**Is your feature request related to a problem? Please describe.**
Dragonflys logging format is not configurable. This is an issue when you want to parse and aggregate your logs or store all logs in a structured way in for example elasticsearch.

**Describe the solution you'd like**
Add a `--log-format` option that can be set to `native` (current implementation, default) or `json` (new implementation needed)

**Describe alternatives you've considered**
I can also write a parser, but that is potentially error prone and not great for performance either.

**Comment by romange** [comment]
We are relying on a third party library to do the logging and unfortunately it does write json records. Due to these difficulties, we won't be able to do this.
