### ISSUE TITLE
test failed replication_test.py::test_take_over_counters

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#3776]
investigate https://github.com/dragonflydb/dragonfly/actions/runs/10993785520/job/30521012937

**Comment by kostasrim** [comment]
@adiholden do not assign this to @chakaz. It happens during shutdown and I think it's related to the one I am fixing

**Comment by kostasrim** [comment]
whoops was a hard crash. I did not see the traces

**Comment by chakaz** [comment]
It's been a while since we opened this, perhaps it was already resolved. Let's optimistically close it, and reopen if needed.

**Comment by romange** [comment]
@chakaz I am pretty sure it was not, I saw it two week ago again.

**Comment by chakaz** [comment]
Indeed, also just now:
https://github.com/dragonflydb/dragonfly/actions/runs/11763776680/job/32768184396#step:6:1067

**Comment by kostasrim** [comment]
https://github.com/dragonflydb/dragonfly/actions/runs/11977784310/job/33396431268#step:6:952
