### ISSUE TITLE
SETRANGE overflow

### ISSUE THREAD

**Issue by BorysTheDev** [dragonflydb/dragonfly#3778]
(setrange  '' 268435456 0) current result: ERR string exceeds maximum allowed size 
expected result: returns 268435457

**Comment by BorysTheDev** [comment]
As I understand in the chat Roman is OK if I change the limit. or I should comment out the test?

**Comment by adiholden** [comment]
If Roman is OK with it than do it

**Comment by BorysTheDev** [comment]
conflicts with tiered storage now so I will close it
