### ISSUE TITLE
messageBuffer, pmessageBuffer

### ISSUE THREAD

**Issue by yovanoc** [dragonflydb/dragonfly#382]
Hello, I'm using IORedis, and I would like to use "buffer" hooks, thanks

**Comment by romange** [comment]
Could you expand? Which commands are you referring to? 
Alternatively, a code snippet that reproduces the problem will help.

**Comment by yovanoc** [comment]
I don't know much more but here's from the ioredis readme:  (https://github.com/luin/ioredis)

<img width="992" alt="image" src="https://user-images.githubusercontent.com/7302317/195274012-04212298-2fcc-47d6-9eb8-f3873454671d.png">

We can listen buffer instead of string, and if I switch to dragonfly instead of a classic redis image it stop working

**Comment by romange** [comment]
Did you try using "message" instead of "messageBuffer"?

**Comment by yovanoc** [comment]
Yes, message work and give me strings, I want buffer. That's why they added messageBuffer

**Comment by romange** [comment]
@yovanoc  Thanks! I am just trying to pinpoint the issue here :)

I opened a task for this. Someone in the community will surely help me with setting up a nodejs test that reproduces the problem and I will be able to fix it then.

**Comment by yovanoc** [comment]
Perfect, I will read this and see if I can help too ! thanks !

**Comment by romange** [comment]
@yovanoc  we can not reproduce this on our side.
We run tests from https://github.com/luin/ioredis/blob/main/test/functional/pub_sub.ts and they pass.
Can you provide a minimal example that demonstrates this issue?

**Comment by yovanoc** [comment]
Ok weird, I will try to do a minimal reproduction then, thanks

**Comment by romange** [comment]
We did not succeed to reproduce. Will close after chrismukkah unless a minimal example is provided.

**Comment by romange** [comment]
Closing - unable to reproduce
