### ISSUE TITLE
Fix code scanning alert - Token-Permissions

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#3821]
Tracking issue for:
- [ ] https://github.com/dragonflydb/dragonfly/security/code-scanning/115

**Comment by dpgraham4401** [comment]
Hey @romange, only collaborators/maintainers can read the linked code scan (people looking for a good first issue cannot implement read what they need to fix).

**Comment by romange** [comment]
Are you saying these issues are not a good fit for external contributors? I can paste here the contents of the issue if that helps.

**Comment by romange** [comment]
This is the issue:
![image](https://github.com/user-attachments/assets/3fa08a1b-1951-4222-8cdb-88df126dd3d3)

**Comment by romange** [comment]
The online tool that should "fix" the problems is here: https://app.stepsecurity.io/secureworkflow
