### ISSUE TITLE
Allow to add date S3 prefix to backup filename

### ISSUE THREAD

**Issue by zacharya19** [dragonflydb/dragonfly#3824]
**Did you search GitHub Issues and GitHub Discussions First?**
Yes, there is already an issue and a closed PR on adding date macros (https://github.com/dragonflydb/dragonfly/issues/1637 and https://github.com/dragonflydb/dragonfly/pull/2118), but those support macros only in the file name.

**Is your feature request related to a problem? Please describe.**
Over time, Dragonfly backups in S3 cost money, and it's hard to do a cleanup or estimate cost when having so many files in the same folder.

**Describe the solution you'd like**
I would like to be able to use the following config flag:
`--dbfilename 'ym={year}-{month}/dd={day}/{timestamp}'`
Adding another flag for the date dir is fine as well.

**Describe alternatives you've considered**
Using filename prefix, it does help with S3 Prefix filter, but the folder is getting too huge to query.

**Additional context**

**Comment by zacharya19** [comment]
On a second thought, this might be tricky, as DragonflyDB will need to compare date folders to find latest backup to restore from.

From self-hosted users: I recommend you create an offline pipeline that will move/delete old backups from this directory, otherwise Dragonfly startime can be significant due to all the files it needs to search to find latest backup.

**Comment by kostasrim** [comment]
@romange any thoughts on this one ?

**Comment by wernermorgenstern** [comment]
Would lifecycle policies in S3 work for now, to clean up the folders and files?

**Comment by zacharya19** [comment]
Yes, S3 lifecycle would do the trick.
