### ISSUE TITLE
RedisTimeoutException Error with Dragonfly Causing 100% CPU Usage

### ISSUE THREAD

**Issue by devbaran** [dragonflydb/dragonfly#3868]
**Describe the bug**
We are experiencing a RedisTimeoutException error when attempting to connect to Dragonfly (with dotnet7 backend app). This results in 100% CPU usage, causing instability in the application. I am running 4 applications on Docker, all with stable CPU usage. Two of these applications are using Dragonfly containers, but only one of them encounters this error.

**To Reproduce**
1. Start the Dragonfly container using docker-compose up.
2. Attempt to connect to Redis using the .NET 7 backend application.
3. Observe the logs for timeout errors.
4. See the CPU usage spike to 100%.

**Expected behavior**
We expected the application to connect to Redis without timeout errors and for the CPU usage to remain stable.

**Environment (please complete the following information):**
- OS: Windows 11 Version 24H2 (OS Build 26100.1882)
- WSL2
- Docker Version: 27.2.0

**Additional context**
- When switching the Docker image from Dragonfly to Redis, the application runs without any issues. However, using Dragonfly results in 100% CPU usage and causes it not to work. 
- **The same project runs smoothly on an M1 chip MacBook Pro with macOS 15 Sequoia**.

**Comment by romange** [comment]
It's not actionable, closing.
