### ISSUE TITLE
Support KEEPTTL and GET options for SET command

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#389]
Dragonfly currently does not support those options with "SET" command.
https://redis.io/commands/set/

For keepttl see TODO here: https://github.com/dragonflydb/dragonfly/blob/main/src/server/string_family.h#L34

For "GET", the functionality is there: https://github.com/dragonflydb/dragonfly/blob/main/src/server/string_family.h#L33 but it's not implemented for "SET" command.

**Comment by nmathew98** [comment]
Hi if this is not urgent could I be assigned to this?

**Comment by romange** [comment]
It's not urgent but it's on first come first serve basis. Just shoot a PR when you have it implemented.

**Comment by nmathew98** [comment]
> It's not urgent but it's on first come first serve basis. Just shoot a PR when you have it implemented.

Ok, will try to push a PR out by weeks end

**Comment by romange** [comment]
Fixed.
