### ISSUE TITLE
"wrong number of arguments" must be in lower case

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#390]
Some testing frameworks expect this message in lower case.
See below io-redis tests run.

![image](https://user-images.githubusercontent.com/3674760/195962466-851a3a4b-b17b-41fe-afe0-da323ed59cc7.png)

**Comment by LucianeFernandesRoque** [comment]
Hi I want to issue,please. Thx

**Comment by romange** [comment]
Send a pr then 🙂. Thanks

**Comment by Tomato6966** [comment]
> Some testing frameworks expect this message in lower case. See below io-redis tests run.
> 
> ![image](https://user-images.githubusercontent.com/3674760/195962466-851a3a4b-b17b-41fe-afe0-da323ed59cc7.png)

in https://github.com/dragonflydb/dragonfly/edit/main/src/facade/facade.cc
line 55
use
tolower(cmd)

but i dont know if it works for not single chars too

**Comment by romange** [comment]
This is a c++ project that requires good c++ knowledge to contribute. sorry.

**Comment by LucianeFernandesRoque** [comment]
> This is a c++ project that requires good c++ knowledge to contribute. sorry.

Sorry, @romange  I thought I could do it, I have Ruby rails as my main language.. Thx
