### ISSUE TITLE
Zrank [WITHSCORE] support

### ISSUE THREAD

**Issue by Flo4604** [dragonflydb/dragonfly#3921]
**Is your feature request related to a problem? Please describe.**
Redis supports ZRANK key member [WITHSCORE] this is not possible with dragonfly

**Describe the solution you'd like**
I would want the [WITHSCORE] option to be supported.

**Describe alternatives you've considered**
Right now I am doing a multi call with zrank and zscore

**Additional context**
-

**Comment by Diskein** [comment]
@adiholden i'd like to work on it

**Comment by kostasrim** [comment]
Hi @Diskein, feel free to submit a PR :)

**Comment by Flo4604** [comment]
Thanks!

**Comment by Flo4604** [comment]
fixed by #4001
