### ISSUE TITLE
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.

### ISSUE THREAD

**Issue by Super-long** [dragonflydb/dragonfly#393]
**Describe the bug**
I tried to compile dragonfly and dive into the source code, but after I executed ". /helio/blaze.sh -release" I encountered the following problem, What should I do to solve this problem？

<img width="1218" alt="截屏2022-10-16 17 03 56" src="https://user-images.githubusercontent.com/46051144/196027307-23b4c9c8-243e-41b8-8385-0ba100de152c.png">

**Environment (please complete the following information):**
 - OS: ubuntu 20.04
 - Kernel: Linux VM-16-16-ubuntu 5.4.0-126-generic 142-Ubuntu SMP Fri Aug 26 12:12:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 - Dragonfly Version: commit 15725f49b91

**Comment by matchyc** [comment]
Please try to install dependencies in helio directory, just use the script `install-dependencies.sh`. 
I suppose that would be enough for you to solve the current problem.

**Comment by romange** [comment]
@Super-long  specifically you need to run `sudo apt install libxml2-dev`.

then, remove `build-opt/CMakeCache.txt` and run `. /helio/blaze.sh -release` again. 
FYI, I submitted https://github.com/romange/helio/commit/83bdf4ef1cb05c53deb6b83aeaa336e67b145371 to make it more clear.
