### ISSUE TITLE
Replication tests for different sizes of container and values

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#3931]
Add test cases to replication tests testing big containers size f.e hundreds of of items in list
and also replication for big container items f.e 2 items in list with size of 10K

This should be simple to add as this PR  https://github.com/dragonflydb/dragonfly/pull/3844  introduces to new params to seeder

**Comment by BorysTheDev** [comment]
unfortunately we have next bug https://github.com/dragonflydb/dragonfly/issues/3503 that doesn't allow to write a good tests
