### ISSUE TITLE
Cluster replicas attempt outgoing migrations

### ISSUE THREAD

**Issue by andydunstall** [dragonflydb/dragonfly#3964]
Say you have two shards

Shard A has a master (A1) and replica (A2), and owns slots 0-6000
Shard B has a master (B1) and a replica (B2), and owns slots 6001-16000

If you start a migration with source=shard A, target = B1, then propagate the cluster config to all shards

Both A1 (master) and A2 (replica) will attempt to start an outgoing migration? Though it should only be the master A1

**Comment by BorysTheDev** [comment]
During migration we do next steps:
1) RestoreStreamer::WriteEntry() where we serialize the object and create a string with data
2) JournalWriter::Write() where we do copy of the string 
3) JournalStreamer::Write() where we do one more copy and caching data for sending

If the serialized object is quite big and we send data not fast the  size of JournalStreamer::pending_buf_ can be significantrly increased
