### ISSUE TITLE
DF crash if DFLY_PASSWORD var is set

### ISSUE THREAD

**Issue by BorysTheDev** [dragonflydb/dragonfly#3994]
steps to reproduce:

1. export DFLY_PASSWORD=test
2. ./dragonfly/build-dbg/dragonfly

*** Check failure stack trace: ***
    @     0x6139af0b920f  google::LogMessage::Fail()
    @     0x6139af0b9155  google::LogMessage::SendToLog()
    @     0x6139af0b892a  google::LogMessage::Flush()
    @     0x6139af0bc7a2  google::LogMessageFatal::~LogMessageFatal()
    @     0x6139ae1d7935  ParseFlagsFromEnv()
    @     0x6139ae1d8225  main
    @     0x7caec3e29d90  (unknown)
    @     0x7caec3e29e40  __libc_start_main
    @     0x6139ae1d2475  _start
*** SIGABRT received at time=1729848981 on cpu 1 ***
PC: @     0x7caec3e969fc  (unknown)  pthread_kill
    @     0x6139af13f887         64  absl::lts_20240116::WriteFailureInfo()
    @     0x6139af13fae1         96  absl::lts_20240116::AbslFailureSignalHandler()
    @     0x7caec3e42520  (unknown)  (unknown)

**Comment by kostasrim** [comment]
```
  628   if (getenv("DFLY_PASSWORD")) {
  629     LOG(FATAL) << "DFLY_PASSWORD environment variable was deprecated in favor of DFLY_requirepass";
  630   }
```

I am closing this, the failure is expected :)

**Comment by BorysTheDev** [comment]
we need to update our docs in this case https://www.dragonflydb.io/docs/managing-dragonfly/using-tls

**Comment by imtyche** [comment]
如此糟糕的文档，docker部署就一条命令。对于新人小白太不友好了。
