### ISSUE TITLE
Unaccounted memory on pipeline mode

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#4002]
**Describe the bug**
Missing used memory stats when sending reply to client on pipeline mode

**To Reproduce**
1. Start dragonfly
2. run in redis-cli `debug populate 1 test 1000 rand type hash elements 100000`
3. run the following python code:
```
import os
import redis
from redis import BlockingConnectionPool, Redis

r = Redis(
    connection_pool=BlockingConnectionPool(
        max_connections=10,  # https://redis.uptrace.dev/guide/go-redis-debugging.html#connection-pool-size
        timeout=60,  # https://redis.uptrace.dev/guide/go-redis-debugging.html#timeouts
        host="localhost",
        port=6379,        
        socket_keepalive=True,
        retry_on_error=[
            ConnectionError,
            redis.exceptions.ConnectionError,
            redis.exceptions.TimeoutError,
        ],
        protocol=3,
    )
)
assert r.ping()

pipe = r.pipeline(transaction=False)

for i in range(1_00):
    pipe.hgetall("test:0")

print("Executing...")
pipe.execute()
print(f"Executed")
```
4. run `info memory` and see the high rss vs used. There is no metric that covers the missing gap

**Comment by BorysTheDev** [comment]
The problem is temporary allocations in the: 
std::vector<>::reserve()
0x624d2b462e2a  dfly::(anonymous namespace)::OpGetAll()
0x624d2b464122  dfly::(anonymous namespace)::HGetGeneric()::{lambda()#1}::operator()()

and 

std::vector<>::vector<>()
0x624d2bd385ae  facade::CapturingReplyBuilder::SendStringArr()
0x624d2b4642af  dfly::(anonymous namespace)::HGetGeneric()
0x624d2b4663b3  dfly::HSetFamily::HGetAll()

first we gather all values in HSET, and second we do a copy for the reply.
I think we can implement move semantics for the reply and avoid the copy

**Comment by BorysTheDev** [comment]
@adiholden Most of the unaccounted memory in this case is a Connection::reply_builder_ 
During the pipeline, we also create some temporary buffers for every command, but in the end, all replies are put in the Connection::reply_builder_. So I think we can iterate all connections and take into account how many memory is used for replies

**Comment by adiholden** [comment]
@BorysTheDev 
we discussed to limit the number of squashed commands when running in pipeline mode. can you please create PR for this

**Comment by romange** [comment]
@BorysTheDev  @adiholden  what's the status of this? I am interested in the following use-case:

1. create hundreds keys with large strings (100KB each)
2. send mgets with multiple keys in pipeline
3. Observe that RSS grows orders of magnitude compared to the dataset used size.

Are we fully tracking the memory usage in this case?

**Comment by BorysTheDev** [comment]
@romange we track only buffers but we don't track temporary objects

**Comment by romange** [comment]
Please do, and you see a gap, let's open an issue for this scenario as well.
