### ISSUE TITLE
MEMORY USAGE for STREAM keys always return (integer) 0

### ISSUE THREAD

**Issue by trisua** [dragonflydb/dragonfly#4028]
**Describe the bug**
MEMORY USAGE for STREAM keys always return (integer) 0

**To Reproduce**
Steps to reproduce:
1. Create stream using `XADD test-stream * just test`
2. Query stream size `MEMORY USAGE test-stream`
3. Result `(integer) 0`

**Expected behavior**
1. Create stream using `XADD test-stream * just test`
2. Query stream size `MEMORY USAGE test-stream`
3. Result `(integer) 4736`  (example from redis_version:7.2.6)

**Environment (please complete the following information):**
 - OS: `Ubuntu 24.04`
 - Kernel: `Linux 6.8.0-47-generic #47-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 22:03:50 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux`
 - Containerized?: `Docker version 27.3.1, build ce12230` `image: 'docker.dragonflydb.io/dragonflydb/dragonfly:v1.24.0'`
 - Dragonfly Version: v1.24.0

**Comment by kostasrim** [comment]
Hi @trisua, you are right this is a bug and thank you for reporting. 

See: 

```
  size_t MallocUsedStream(unsigned encoding, void* streamv) {
    // stream* str_obj = (stream*)streamv;
    return 0;  // TODO
  }

```
