### ISSUE TITLE
dfly_main.cc:370] Weird error 1 switching to epoll

### ISSUE THREAD

**Issue by maxpain** [dragonflydb/dragonfly#4042]
I use dragonfly kubernetes operator.

Should I ignore this?

```
I20241103 12:44:55.885782     1 init.cc:78] dragonfly running in opt mode.
I20241103 12:44:55.885856     1 dfly_main.cc:693] Starting dragonfly df-v1.24.0-7870f594660539f48894e37a8fd9d6a133fa21ff
* Logs will be written to the first available of the following paths:
/tmp/dragonfly.*
./dragonfly.*
* For the available flags type dragonfly [--help | --helpfull]
* Documentation can be found at: https://www.dragonflydb.io/docs
I20241103 12:44:55.885980     1 dfly_main.cc:737] maxmemory has not been specified. Deciding myself....
I20241103 12:44:55.885986     1 dfly_main.cc:746] Found 2.00GiB available memory. Setting maxmemory to 1.60GiB
W20241103 12:44:55.886010     1 dfly_main.cc:370] Weird error 1 switching to epoll
I20241103 12:44:55.963719     1 proactor_pool.cc:147] Running 4 io threads
I20241103 12:44:55.965265     1 dfly_main.cc:272] Listening on admin socket any:9999
I20241103 12:44:55.966229     1 server_family.cc:817] Host OS: Linux 6.6.58-talos x86_64 with 4 threads
I20241103 12:44:55.971194     1 snapshot_storage.cc:115] Load snapshot: Searching for snapshot in directory: "/data"
W20241103 12:44:55.971225     1 server_family.cc:931] Load snapshot: No snapshot found
I20241103 12:44:55.974581    13 listener_interface.cc:101] sock[12] AcceptServer - listening on port 6379
I20241103 12:44:55.974856    12 listener_interface.cc:101] sock[11] AcceptServer - listening on port 9999
```

**Comment by romange** [comment]
yeah, it's ok, we need to change the wording of this.
the sad thing is that k8s/docker switched to blocking io_uring kernel APIs by default. it's possible to workaround by running containers as root/unconfined or providing custom security profiles. in that case, DF will use io_uring.

**Comment by maxpain** [comment]
@romange What's the difference in the performance between those APIs?

**Comment by romange** [comment]
depends on the hardware and the usecase really. currently it may reach upto 10% with iouring being more efficient but can also be negligible. When we integrate more advanced io_uring features the difference may become larger (~20%).

**Comment by romange** [comment]
Also, the snapshotting is more efficient with io_uring. SSD tiering working only with io_uring.

**Comment by dbackeus** [comment]
For the record: A "quick and dirty" fix for this is to add the following to the Dragonfly resource spec:

```yaml
  podSecurityContext:
    seccompProfile:
      type: Unconfined
```

A more secure way would be to more granularily allow only `io_uring_setup`, `io_uring_enter` and `io_uring_register` syscalls in addition to the default ones.
