### ISSUE TITLE
Command `PUBLISH` fails with `NOPERM` error in v1.24.0

### ISSUE THREAD

**Issue by bogdanp05** [dragonflydb/dragonfly#4050]
**Describe the bug**
Dragonfly throws a `NOPERM` error for `PUBLISH` on a user with `+@pubsub` category ACL set.

**To Reproduce**
1. Start Dragonfly  `taskset -c 0-1 ./dragonfly --logtostderr --port 6970` 
2. Connect as the default user `redis-cli -u redis://default@localhost:6970`
3. Create a new user with `@pubsub` category `ACL SETUSER foo ON >mypwd +@pubsub +set +get ~*`
4. Log in as that user `redis-cli -u redis://foo:mypwd@localhost:6970`
5. Try to publish a message on a channel, see the error:
```
localhost:6970> publish bar_chan pub
(error) NOPERM foo has no ACL permissions
```

**Expected behavior**
The publish command should work for users with `+@pubsub` category. This used to work, up until at least v1.21.4.

**Environment (please complete the following information):**

 - OS: Fedora 39
 - Kernel: 6.9.7
 - Containerized?: systemd-container
 - Dragonfly Version: 1.24.0

**Reproducible Code Snippet**

**Additional context**

**Comment by kostasrim** [comment]
Hi @bogdanp05, 

Thank you for reporting this. I will take a look and ping

**Comment by kostasrim** [comment]
Hi @bogdanp05, 

This used to be a bug in dragonfly. The query gets now rejected with `NOPERM` just like Valkey and the reason is that you are not `specifying a channel`: `acl setuser foo &bar_chan`

**Comment by bogdanp05** [comment]
Thanks for the answers! I confirm it now behaves the same as Redis/Valkey 7.2.
If I'm not mistaken, Dragonfly initially did not support setting channels on an ACL user. So I think the "bug" of allowing `publish` when not specifying a channel was to maintain backwards compatibility.

**Comment by kostasrim** [comment]
yep but I got it implemented now so we you should expect full compatibility :)

**Comment by bogdanp05** [comment]
Yep, just that the ACL's of users created before channels were a thing now need to be updated to include `&*` before upgrading to 1.24 to not break the publish command for them. 
Ok, should be doable. Thanks again for checking!
