### ISSUE TITLE
ERR unknown command `HEXPIRETIME` / HPEXPIRETIME

### ISSUE THREAD

**Issue by draftpin** [dragonflydb/dragonfly#4096]
**Describe the bug**
For some reason command HEXPIRETIME and HPEXPIRETIME gives error - "unknown command" and does not work in CLI
In the same time HEXPIRE command works correctly and all these commands were implemented at the same time since redis v.7.4.0

**To Reproduce**

1. redis-cli
2. HEXPIRETIME
3. (error) ERR unknown command `HEXPIRETIME`
4. HPEXPIRETIME
5. (error) ERR unknown command `HPEXPIRETIME
6. HEXPIRE
7. (error) ERR wrong number of arguments for 'hexpire' command

**Expected behavior**
Should show expire time 

**Screenshots**
No need, easy to reproduce

**Environment (please complete the following information):**
 - OS: Ubuntu 24.04.1 LTS
 - Kernel: 6.8.0-48-generic
 - Containerized: Bare Metal
 - Dragonfly Version: v1.24.0

**Reproducible Code Snippet**
```
# See above
```

**Additional context**
This is also included in dragonfly tests here:
https://github.com/dragonflydb/dragonfly/blob/d3ef0a3630234748f73d61a0ea3bf756e90c0774/tests/fakeredis/test/test_hypothesis.py#L504
But for some reason does not work

**Comment by romange** [comment]
Dragonfly supplies the equivalent FIELDTTL command:

https://www.dragonflydb.io/docs/command-reference/generic/fieldttl
