### ISSUE TITLE
Boolean search not working, index not working

### ISSUE THREAD

**Issue by canparam** [dragonflydb/dragonfly#4129]
**Describe the bug**
When I index a boolean field with TAG it doesn't work.

**To Reproduce**
1. Insert records using `JSON.SET j1 . '{"active":true,"id":1}'`
2. Creat index `FT.CREATE test ON JSON PREFIX 1 j SCHEMA $.id AS id NUMERIC $.active AS active TAG`
3. Query records using `ft.search test '*'`
4. Result
![image](https://github.com/user-attachments/assets/9dc659a1-7761-4ac7-9751-b6815866297b)

# Server
`redis_version:6.2.11
dragonfly_version:df-v1.25.1`

at version v1.23.0 everything still works fine

![image](https://github.com/user-attachments/assets/6e982464-89b0-42a8-b147-72134ff67dc9)

**Comment by adiholden** [comment]
@canparam thank you for reporting the bug
