### ISSUE TITLE
logrotate's prerotate script on Debian exits with non-zero code

### ISSUE THREAD

**Issue by s0xDk** [dragonflydb/dragonfly#4153]
logrotate service on Debian fails with the following errors:

```
logrotate[1999823]: error: error running non-shared prerotate script for /var/log/dragonfly/dragonfly.hostname.dfly.log.INFO.20241117-021241.1233.log of '/var/log/dragonfly/dragonfly*.log '
logrotate[1999823]: error: error running non-shared prerotate script for /var/log/dragonfly/dragonfly.hostname.dfly.log.WARNING.20241117-021241.1233.log of '/var/log/dragonfly/dragonfly*.log '
```
 
The `/etc/logrotate.d/dragonfly` script has this code:

```
prerotate
    if lsof -t $1 > /dev/null; then
    # file is open. Skipping rotation."
    exit 1
    fi
endscript
```
 which exits with non-zero code and makes logrotate service fail.
 
 I believe it should be updated to `exit 0`

**Comment by s0xDk** [comment]
I checked the logrotate manual:

> nosharedscripts
>               Run prerotate and postrotate scripts for every log file which is rotated (this is the default, and overrides the sharedscripts option).  The absolute path to the log file is passed as first argument to the script.  The abso‐
>               lute path to the final rotated log file is passed as the second argument to the postrotate script.  **_If the scripts exit with error_**, the remaining actions will not be executed for the affected log only.

`If the scripts exit with error` make me thing `exit 1` is probably OK.

Will investigated this further...

**Comment by romange** [comment]
Should we close this @s0xDk  ?

**Comment by s0xDk** [comment]
@romange I tried to figure out why `exit 1` makes the logrotate service stop, while according to the logrotate documentation it should just prevent the rotate action for the affected log file. But I still can't figure this out. Replacing `exit 1` with `exit 0` _appears_ to solve the problem, but I can't explain exactly why this is happening.

When I have more time to dig deeper, I'll let you know. In the meantime, feel free to close this ticket if you'd like.

**Comment by s0xDk** [comment]
I have an idea that `exit 1` might work when logrotate calls an **external** script rather than the inline script.

**Comment by s0xDk** [comment]
I just made a PR to fix this.

**Comment by romange** [comment]
we will cherry-pick it to 1.25.3 this week.
