### ISSUE TITLE
[Feature Request] Supabase Foreign Data Wrapper?

### ISSUE THREAD

**Issue by harrisrobin** [dragonflydb/dragonfly#4206]
**Did you search GitHub Issues and GitHub Discussions First?**
I have searched and i don't see anyone else asking for this right now.

**Is your feature request related to a problem? Please describe.**
Just a feature request

**Describe the solution you'd like**
I would like for Dragonflydb to create an extension so that we can use it via [Supabase's FDW](https://supabase.com/docs/guides/database/extensions/wrappers/overview). For a lot of people using the redis extension, this would be a good way to switch

**Describe alternatives you've considered**
Building my own, although im not familiar with rust.

**Additional context**

**Comment by chakaz** [comment]
Hi @harrisrobin 
I'm afraid I'm not familiar with Supabase FDW. What exactly does it require from Redis? Is there some module it uses?

**Comment by harrisrobin** [comment]
@chakaz 

Supabase's FDW allows us to query data from external sources as if they were coming from Supabase's postgresql database. This is really useful when you have parts of your data stores in a redis-like store but still need to query it or even perform joins with data in your sql database. 

Currently, you can see how others do it [here](https://github.com/supabase/wrappers) along with all the FDW extensions which include firebase, clickup, redis, mysql, auth0, stripe and more. 

Let me know if this makes sense and if you think this could be something on your roadmap. 

Thank you
