### ISSUE TITLE
Ability to know how much memory a key used (e.g. Redis `MEMORY USAGE` command)

### ISSUE THREAD

**Issue by wernermorgenstern** [dragonflydb/dragonfly#4282]
**Did you search GitHub Issues and GitHub Discussions First?**
Yes

**Is your feature request related to a problem? Please describe.**
I need to know which key Prefixes take up the most memory.  Redis has the command `MEMORY USAGE` and also `OBJECT`

**Describe the solution you'd like**
be able to scan all keys, and determine how much memory is used for each key

**Describe alternatives you've considered**
I can assume that a hash contains so many bytes, but if we use a bigger HASH, than it won't be accurate enough

**Comment by wernermorgenstern** [comment]
I think it works in 1.25, but not in 1.24.
If that can be confirmed, that I am good on this one.

**Comment by romange** [comment]
@wernermorgenstern can you provide a minimal reproducible example of something that does not work for you?
