### ISSUE TITLE
circular dependency in quicklist nodes causes deadlock

### ISSUE THREAD

**Issue by kostasrim** [dragonflydb/dragonfly#4294]
It was discovered while pushing huge list entries in one of my PR's. https://github.com/dragonflydb/dragonfly/pull/4262/files#diff-35fc27c757d9b3830899712b367143f5c61f801b8f252b7bfa6e59bfbde6da49R59 

It's easy to reproduce in `test_replication_all`  case `(2, 2 * [1], dict(key_target=1_000, huge_value_percentage=2), 500)`

![Screenshot from 2024-12-11 15-34-03](https://github.com/user-attachments/assets/10409d11-745f-402a-9199-dd5099b15743)

**Comment by romange** [comment]
How can I reproduce exactly?

**Comment by kostasrim** [comment]
> How can I reproduce exactly?

https://github.com/dragonflydb/dragonfly/pull/4262/files#diff-f41a28e79426b76916ad0fb750e102f83955a92be0f24dda7ae4fda79d74ca8cR52

Use the test case above ^^ and https://github.com/dragonflydb/dragonfly/pull/4262/files#diff-35fc27c757d9b3830899712b367143f5c61f801b8f252b7bfa6e59bfbde6da49R61 and change 

from `redis.apcall('LPUSH', key, unpack(randstr_sequence(false)))` to
`redis.apcall('LPUSH', key, unpack(randstr_sequence(is_huge))) and it will `deadlock` after a few runs (for me every 3-4).

Then once it deadlocks `pgrep dragon and then gdb -p port_number`

**Comment by romange** [comment]
@kostasrim so I should use the kpr1 branch?

**Comment by romange** [comment]
I tried to follow instructions and it does not work for me. Can you please create a branch for me where I can run test_replication_all to reproduce it?

Thanks

**Comment by kostasrim** [comment]
@romange yes yes give me a few minutes though

**Comment by kostasrim** [comment]
@romange https://github.com/dragonflydb/dragonfly/pull/4300

**Comment by romange** [comment]
Thank you!

**Comment by kostasrim** [comment]
Let me know if you have any issue, I tried it locally and it failed immediately
