### ISSUE TITLE
Stream memory stats missing 

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#4321]
This PR https://github.com/dragonflydb/dragonfly/pull/4067/files#diff-c6ffd3f71af3ea9499e00368b3fedeba88f51ab614ce54f849e11cc2b5e05fd9 solved memory tracking for steam entries.

When running <info memory> we should see the memory used by each type type_used_memory_[type] but stream family is missing when we have stream data

**Comment by BorysTheDev** [comment]
The problem is reproducible only for snapshot loading
