### ISSUE TITLE
dragonfly is not supported build by epoll completely？

### ISSUE THREAD

**Issue by zhidongMao** [dragonflydb/dragonfly#452]
IoMgr in src/server/io_mgr.cc，it depends on iouring，and IoMgr is depended by tiered_storage，so it is can not build by epoll(force_epoll) completely？

**Comment by romange** [comment]
Everything depends on iouring lib even if the api is not present. Why is it
a problem?

**Comment by zhidongMao** [comment]
To support the old kernel (linux kernel<5.1) ,  I try to use epoll to replace the uring procator with the epoll procator (as well as dragonfly supported). But I found tiered_storage must run with the iouring, so in my old kernel(centos 7), I can not build the project. Can dragonfly run without iouring? If it can, why the tiered_storage depends on iouring instead of epoll?

**Comment by zhidongMao** [comment]
sorry, it is not a bug. But it should support epoll completely as dragonfly said. I am a little puzzled.

**Comment by romange** [comment]
1. Already *built* Dragonfly can run without iouring API on epoll only systems. For that you can just download the binary or the docker. see our get started guide.
2. Dragonfly and its dependency helio are not designed to be **built** without the iouring library but afaik this library can be built on older kernels, therefore you should be able to build the project as is even if iouring API is not supported. 
3. If you have problems building the project (i.e. compilation problems) please attach the output.

**Comment by zhidongMao** [comment]
ok, it solves my problem, thankyou.
