### ISSUE TITLE
Does the dragonfly support the  redis cluster mode ? (where has introduce the dragonfly cluster ?)

### ISSUE THREAD

**Issue by tiandong19860806** [dragonflydb/dragonfly#453]
### Discussed in https://github.com/dragonflydb/dragonfly/discussions/445

<div type='discussions-op-text'>

<sup>Originally posted by **tiandong19860806** October 29, 2022</sup>
Hi  all,

       Does the dragonfly support the  redis cluster mode ?

such like below:

(1) dragonfly cluster is three nodes
spring.redis.cluster.nodes=
192.168.4.21:7001, 192.168.4.21:7002,
192.168.4.22:7001, 192.168.4.22:7002,
192.168.4.23:7001, 192.168.4.23:7002

(2) java code to connect dragonfly cluster (like protecol : redist cluster)
if(!StringUtil.isEmpty(password)){
	jedisCluster = new JedisCluster(hostAndPorts, connectionTimeout, soTimeout, maxAttempts, password, poolConfig);
}
else {
	jedisCluster = new JedisCluster(hostAndPorts, connectionTimeout, soTimeout, maxAttempts, poolConfig);
} 
</div>

**Comment by romange** [comment]
Lets discuss it in discussions https://github.com/dragonflydb/dragonfly/discussions/445
