### ISSUE TITLE
dir argument is sensitive to the trailing slash

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#480]
if we pass `--dir /foo` then dragonfly tries to save `/foodump...` which is incorrect. 
if we provide the unexisting directory we silently switch to none.

the expected behavior: 
1. it should verify that `/foo` is indeed a directory and join with it the filename correctly.
2. in case `/foo` does not exist, it should at least output an error that the passed directory does not exist. maybe even exit with the error.

**Comment by dranikpg** [comment]
If we provide a non-existent directory DF tries to create it and returns an error if it fails

**Comment by romange** [comment]
hmm, did not work for me. It prints `Data directory is ""` , once the folder does not exist.

**Comment by dranikpg** [comment]
Thats for reads, but for writes it all ok. Try saving a snapshot
