### ISSUE TITLE
log printings do not correspond to actual behavior when saving

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#488]
I run dragonfly with `./dragonfly --alsologtostderr --dir /mnt/vol1/df`  but `df` dir does not exist.
Then I saved it with "SAVE DF".
Below is the log output:
```
I20221114 09:49:51.903038  1696 server_family.cc:380] Data directory is ""                                             │
I20221114 09:49:51.903124  1696 server_family.cc:128] Checking "dump"                                                  │
I20221114 09:49:51.903201  1699 listener_interface.cc:87] sock[52] AcceptServer - listening on port 6379               │
I20221114 09:49:58.320340  1697 server_family.cc:935] Saving "/mnt/vol1/dfdump-2022-11-14T09:49:58-summary.dfs" finishe│
d after 2 ms                                                                                                      
```

however when `ls /mnt/vol1/df/` outputs all the saved files correctly. So the actual behavior is correct but the log printings are confusing: "data directory" and "saving" lines are wrong.

**Comment by dranikpg** [comment]
I'm not sure about what to do with the data directory. In case the folder doesn't exist, df falls back to its CWD. So technically the output is correct.

In case the folder doesn't exist, should we print a warning?

**Comment by romange** [comment]
Does not it try to create it? At least this is what I saw it did.

**Comment by dranikpg** [comment]
It does for writes, but not for reads

**Comment by romange** [comment]
hmm, it's inconsistent I am afraid.

**Comment by dranikpg** [comment]
I'd say its pretty much expected. Why should it create a new folder when you just want to read from it? I guess it should just print a warning and that's all. Or not?

**Comment by romange** [comment]
let's do the warning.

**Comment by romange** [comment]
also `last_save_file` in the persistence section has the wrong path (str join vs path join).
