### ISSUE TITLE
Replication TODOs

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#529]
1. Improve replica error handling and cancellation
2. Allow running replication on single threaded instances
3. Update various information for the info command

**Comment by dranikpg** [comment]
1. Hint rdb db size in rdb
2. Print log on reconnecting

**Comment by dranikpg** [comment]
1. We should not print tons of logs in case of cancellation

**Comment by adiholden** [comment]
@dranikpg please let me know if there is anything to do here, if not lets close this issue

**Comment by dranikpg** [comment]
Last two comments are still open

**Comment by romange** [comment]
We should go through the code and grep for TODOs

**Comment by adiholden** [comment]
@dranikpg we added yesterday - "go through the code and grep for TODOs".

**Comment by romange** [comment]
Closing this. Please opened specific issues if needed.
