### ISSUE TITLE
could we discuss investing $100k-300k in dragonfly?

### ISSUE THREAD

**Issue by jamesefhawkins** [dragonflydb/dragonfly#53]
i'm from hedgehog.vc (and i'm a cofounder of posthog.com)... we invest $100k to $300k+ in open source startups as a fun way to embrace other open source projects, and to help you learn from us

i can see there is a company formed around the project, and i read on HN that you're bootstrapped. i was curious if you'd consider taking funding or if you'd just like to talk about it?

if interested, id love to chat - james at posthog dot com, if not feel free to close this issue - hope it's ok to ask like this

**Comment by odedponcz** [comment]
Taking this offline.
