### ISSUE TITLE
Docs Website for Dragonfly

### ISSUE THREAD

**Issue by tamalchowdhury** [dragonflydb/dragonfly#554]
**Did you search GitHub Issues and GitHub Discussions First?**
Yes, it's a new issue.

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I want to create a `docs` link in the website that will link to a new documentation website like `docs.dragonfly.io`. I would like to port all the instructions from various readme files here on this repo to the new docs site. While I add them, I may also enhance them with code highlight and screenshots when needed.

I am planning to use [Docusaurus](https://docusaurus.io/docs) to build the documentation site.

**Describe alternatives you've considered**
No alternatives considered, but I am open to suggestions.

**Additional context**
Want to improve the overall web presence of Dragonfly, as my devrel initiative.

**Comment by odedponcz** [comment]
This is a great suggestion. I think the documentation site deserve a separate repository. 
1. Lets create a new repository for that dragonfly-doc
2. Lets break this to subtasks under the new documentation repository. 
What do you think?

**Comment by tamalchowdhury** [comment]
Yes sure. Let's do it. Please make a new repo. I'll start contributing to
that.

**Comment by odedponcz** [comment]
https://github.com/dragonflydb/documentation 
Lets continue there and close this one.
