### ISSUE TITLE
introduce a periodic check for a new version

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#558]
we've setup a service that tells which version is the latest:

`curl -i -H 'User-Agent: DragonflyDB/0.12.0' https://run-stage-43h632k3xq-ew.a.run.app/v1` 

we should perform a daily check and if there is a new version, output a message to the info log at most once per process run. `LOG_FIRST_N ` can help with that.

**Comment by romange** [comment]
also during startup

**Comment by boazsade** [comment]
This is not working with HTTP URL of "version.dragonflydb.io"
For version you can run 
```
curl -i -H 'User-Agent: DragonflyDB/0.12.0' https://version.dragonflydb.io/v1
```
To get daily stats:
```
curl -i -H 'User-Agent: DragonflyDB/0.12.0' https://version.dragonflydb.io/v1/daily
```
Please note that this will not log development versions (i.e. local builds)
