### ISSUE TITLE
Request for tool TPDNE-dl

### ISSUE THREAD

**Issue by patranger** [dragonflydb/dragonfly#565]
**Did you search GitHub Issues and GitHub Discussions First?** Yes
Many users may find their feature is already being discussed. Help us keep duplicates to a minimum by searching for your feature first to see if it is already in progress.

**Additional context**

I have working with cybersecurity for some time and I often have to use OPSEC tools, which is why I try to keep up to date with new tools. I saw that there is a new tool useful during OPSEC for downloading generated AI images. It is worth adding them to the repository because it is useful for the work of cybersecurity specialists.
https://codeberg.org/nanoory/TPDNE-dl

**Comment by romange** [comment]
I think you opened a request in the wrong project.
