### ISSUE TITLE
integrate release drafter app into the repo

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#574]
see this for more info:

https://github.com/marketplace/actions/release-drafter

**Comment by devangjhabakh** [comment]
@romange has nobody been assigned this yet? if so, i can take this.

**Comment by romange** [comment]
@devangjhabakh  I see you are a Berkley graduate. Care to take a look at https://github.com/dragonflydb/dragonfly/issues/253 ? I think it's more interesting for someone who studied CS. 

Specifically, I am interested only in items (1), (2), (3) parts of this task. The tool needs to send skewed zipf distribution in range 1..N with alpha < 1.
