### ISSUE TITLE
implement hits/misses stats

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#575]

**Comment by vortex73** [comment]
Please expand upon this issue. This is my first foray into OS . I'm fluent in python.

**Comment by romange** [comment]
definition of done `redis-cli info stats` should provide statistics about hits and misses.

**Comment by romange** [comment]
the stats should come from SliceEvents that track events per each shard but do not have per table granularity (which is fine).
there is already system in place to aggregate stats from all threads so it should be pretty easy to add.

the event itself should be tracked, IMHO, inside ` DbSlice::FindExt` function, which I believe is enough to track any lookup scenario to Dragonfly keys.

**Comment by devangjhabakh** [comment]
@romange doesn't look like anyone has been assigned this yet. I would like to contribute, do you want to assign it to me? Unless @vortex73 you'd like to confirm that you're working on this.

**Comment by romange** [comment]
Someone on the team actually implemented this but have not opened a pr yet.
