### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by ThatOneCalculator** [dragonflydb/dragonfly#578]
**Did you search GitHub Issues and GitHub Discussions First?**
Yes

**Is your feature request related to a problem? Please describe.**
Yes, as of right now DragonflyDB only runs on Linux/Docker. 

**Describe the solution you'd like**
FreeBSD and possibly OpenBSD support.

**Comment by romange** [comment]
It's not on the roadmap, sorry.

**Comment by ThatOneCalculator** [comment]
I get that, but is there any chance we could see it eventually? That's what a feature *request* is for, after all :)

**Comment by romange** [comment]
Some feature requests are aligned with the roadmap and some do not. 
We use iouring API underneath and it's Linux specific.

**Comment by tuxillo** [comment]
Such a shame, I was hoping we could get it working in [DragonFly BSD](https://www.dragonflybsd.org) too :smile:

**Comment by RBloemers** [comment]
HNY!

It's 2025 now 😇, 2 years further, any chance on an update on this?

**Comment by chakaz** [comment]
I'm thrilled to say that Dragonfly now _builds_ on FreeBSD, starting with https://github.com/dragonflydb/dragonfly/pull/4412

Please note that:
1. This is mostly experimental, or intended for development purposes at most, as we do not actively test and are even aware of breaks on FreeBSD
2. FreeBSD does not implement io uring (a Linux feature), which means Dragonfly will be inherently slower on FreeBSD

If anyone would like to assist here, specifically in reporting bugs, adding a GitHub runner, etc, we would welcome this!

And a happy new year :)
