### ISSUE TITLE
Support FlushDB command for replication

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#580]

**Comment by adiholden** [comment]
**The Problem:**
Flush DB command executed on master on all shards and will be passed to replica in all shards fibers. If we execute the flushdb in replica in all shard fibers we must make sure that execution of one fiber does not deletes entries that were written after the flush of the other fiber.
**Suggested solution:**
In replica flow fiber, once FlushDB command executed fiber will hold all executions in the until the execution is done in all flow fibers.
JournalExecutor class will handle which command we should hold the executions flow for, f.e FlushDB, FlushAll
After we call JournalExecutor.execute inside StableSyncDflyFb we will check if the executed command should hold the execution.
If so we will create a BlockingCounter counter in replica for the number of flow fibers, each fiber that gets to the hold execution command will decrease the value of this counter.
Once all fibers decrease the counter -> the FlushDB command was executed on all flow fibers -> we can continue with the execution.
**Assumptions:**
Hold execution commands are written to all flow shards and are in the same order. i.e 
In the following example transaction 1 will be journaled before transaction 2 in all journal shards
Shard1 journal
txid:1 , command: FlushAll
.... more command...
txid:2 , command: FlushDB 1

Shard2 journal
txid:1 , command: FlushAll
.... more command...
txid:2 , command: FlushDB 1

**Comment by adiholden** [comment]
@romange @dranikpg can you review the suggested solution

**Comment by dranikpg** [comment]
If we have more flows than shards on the replica this scenario can indeed happen. 

It seems valid, but I'm not sure we should work from "general to specific". Could it be part of the mechanism we are going to design to support multi-key commands? Or a global commands a totally separate class?

 > If so we will create a BlockingCounter
We need some kind of higher level orchestrator to handle all those coordination issues. It can consist just of a blocking counter for now. 

Once you start implementing it, don't forget to connect it to cancellation - so that if a single flow fails, the other ones don't block forever.

**Comment by romange** [comment]
As a general remark, Boost.Fibers call such primitive a barrier:
https://www.boost.org/doc/libs/1_81_0/libs/fiber/doc/html/fiber/synchronization/barriers.html

1. I do not know if we pass txid to replica but it seems that for transactions that have txid we must pass it.
2. Once a first replica flow receives flushdb command, it must create a blocking counter so that everyone else will be able to decrement it and wait on it (barrier) but why do you want to execute flushdb from all the flows?
each one of them broadcasts flushdb to all replica shards (correct me if I am wrong). So if you already determine what is the first flow that creates a barrier, I think it can be chosen as the only one that sends flushdb command to all the shards.
3. I agree that we need a barrier.

**Comment by romange** [comment]
As a note - we should currently reject flushdb inside a transaction.
