### ISSUE TITLE
Support key expire and eviction for replication

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#582]
Master should update replica when it delete an entry because it was expired or evicted
Replica should not expire keys or evict them

**Comment by romange** [comment]
Is it how it works in Redis?

**Comment by adiholden** [comment]
@romange yes

**Comment by romange** [comment]
I think that replica can expire an item by itself based on its clock. eviction should be replicated of course.

**Comment by adiholden** [comment]
@romange I think that there is a problem with replica expiring items, because if user update the expire time of some key, it can take time untill the replica will get this update from master and it can delete the entry while the master will keep the entree because the expiration time was increased

**Comment by romange** [comment]
Need to make sure that Replica state disables the independent expiry and eviction logic.

**Comment by adiholden** [comment]
@dranikpg can we close this issue?

**Comment by dranikpg** [comment]
I think yes
