### ISSUE TITLE
Replication should only execute deterministic commands

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#604]
f.e
spop

**Comment by romange** [comment]
Also RENAME should be implemented as "SETVAL" and "DEL", imho

**Comment by dranikpg** [comment]
Why should you encode the whole value just to rename it? Doesn't that slow down the whole flow a lot?

**Comment by romange** [comment]
Because how we allocate from heap per thread. If we move objects without
copying it messes up stats.

Rename is a management command and it can be slow

**Comment by adiholden** [comment]
SDIFFSTORE should be rewrite

**Comment by adiholden** [comment]
The non deterministic commands that need to be rewrite:
spop
blpop
brpop

**Comment by dranikpg** [comment]
You already listed them 😅  Lets exclude the blocking ones in this issue and strike through the ones that were implemented: spop and {p}expire{at}
