### ISSUE TITLE
replication support multi command

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#606]

**Comment by adiholden** [comment]
Suggested solution:
1. add new op codes - multi_command, exec. 
2. when writing command to journal we will set command / multi command op code for journal entry.
3. On multi command when we do unlock at the end of transaction we will calc the unique shard count of the multi transaction, after that each journal in the transaction will write the exec opcode with the txid and the unique shard count.
5. journal reader will return only after it got exec when reading multi commands, it will return the data of all the commands of the shard transaction.
6. replica module change - Replica::ExecuteEntry will push to tx_sync vector all the commands of entry ,today each entry has only one command, in this change we will push multiple command.

@romange @dranikpg

**Comment by romange** [comment]
can you provide here (or in the internal doc :) ) an example?
i.e. suppose we have
```
multi 
set x foo
mset x foo y bar   # x, y on 2 shards
mset x foo y bar z hhh  # y, z on the same shard
exec
```
what it will do?

**Comment by adiholden** [comment]
On master side when user calls exec we start execution of command

after execution of the first command:
write journal of shard 1
txid: 1, op: multi, payload : set x foo 
no write journal of shard 2

after  execution of the second command:
write journal of shard 1
txid: 1, op: multi, payload : mset x foo
write journal of shard 2
txid: 1, op: multi, payload : mset y bar

after  execution of the third command:
write journal of shard 1
txid: 1, op: multi, payload : mset x foo
write journal of shard 2
txid: 1, op: multi, payload : mset y bar z hhh

all commands execution are finished in the UnlockMulti flow
go over all shard, find which shards last txid is 1, from this update the transaction unique shard count
write journal of shard 1
txid: 1,  op: exec, unique shard count: 2
write journal of shard 2
txid: 1,  op: exec, unique shard count: 2

in replica side:
reader of shard 1:
txid: 1, op: multi, payload : set x foo 
txid: 1, op: multi, payload : mset x foo
txid: 1, op: multi, payload : mset x foo
txid: 1,  op: exec, unique shard count: 2

create data:
txid: 1
shard count: 2
command vec:
set x foo
mset x foo
mset x foo

reader of shard 2:
txid: 1, op: multi, payload : mset y bar
txid: 1, op: multi, payload : mset y bar z hhh
txid: 1,  op: exec, unique shard count: 2

create data:
txid: 1
shard count: 2
command vec:
mset y bar
mset y bar z hhh

In Replica::ExecuteEntry
we will create entry for txid 1 in the tx_sync_execution with barrier of count 2 (shard count)
The execution of this by journal executor will be:

multi 
set x foo
mset x foo
mset x foo
mset y bar
mset y bar z hhh
exec
