### ISSUE TITLE
Masterauth missing

### ISSUE THREAD

**Issue by meruiden** [dragonflydb/dragonfly#618]
Normally in redis when using REPLICAOF to replicate a master using a password, you'd set the masterauth config setting. But since config isn't supported yet (config set masterauth ...), it's impossible to connect to a master that is password protected.

Am I missing something here? Or is this feature simply not supported yet.

**Comment by romange** [comment]
Are you talking about replicating from Redis master, right?

**Comment by meruiden** [comment]
Not exactly. We currently have a KeyDB setup with 2 instances. 1 master and 1 read-only replica. both using requirepass. I was trying to setup the same infra we have right now using DragonflyDB and got stuck on the replica not being able to connect to the master because of the masterauth option missing.

**Comment by romange** [comment]
Oh, we do not support DF-DF replication for now - it's something that the team is actively working on right now.
@meruiden do you mind to dm me (we have slack or discord whatever is convenient for you) ?

**Comment by meruiden** [comment]
Ah okay, in that case I'll wait for the release :) I thought it did because of the api_status.md page. I joined the Discord channel just now, I'm @CorneAtRaidflux in Discord. Thanks!

**Comment by romange** [comment]
fixed by #1000
