### ISSUE TITLE
feat: introduce a dragonfly_version metric

### ISSUE THREAD

**Issue by tamcore** [dragonflydb/dragonfly#637]
As the title says, please add a metric like `dragonfly_version`. Could even combine that, with exposing an additional `dragonfly_version_update` or something, if the integrated update check found an update.

Memcached for example exports the following
```
# HELP memcached_version The version of this memcached server.
# TYPE memcached_version gauge
memcached_version{version="1.6.17"} 1
```

Another example from Victoria Metrics, which would probably work better, as the output of `dragonfly --version` is relatively long, would be something like
```
vm_app_version{version="vmstorage-20221220-230939-tags-v1.85.3-cluster-0-g30b15111a", short_version="v1.85.3-cluster"} 1
```

So, for Dragonfly, I could see something like
```
dragonfly_version{version="v0.13.1-f7e70bc45ad045e6ea49f6b1118df554189aaf2d", short_version="v0.13.1"} 1
```
---
In the same go, I'd even suggest to deprecate the `dragonfly_up` metric, as that's redundant to querying `up{job="argocd-dragonfly-metrics"}` or `up{pod="argocd-dragonfly-0"}` (direct examples from my setup) directly.

**Comment by romange** [comment]
Ok, we will provide `dragonfly_version{version="v0.13.1"}` and deprecate `_up`

**Comment by romange** [comment]
Also will add hit/miss metrics and rss memory.
