### ISSUE TITLE
implement BRPOPLPUSH

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#646]
It's required by sidekiq  frameworkl https://sidekiq.org/

**Comment by manast** [comment]
And by BullMQ https://bullmq.io/ 👍

**Comment by ashotland** [comment]
> It's required by sidekiq frameworkl https://sidekiq.org/

Sidekiq pro, OSS seems to work.

**Comment by alexanderadam** [comment]
[`brpoplpush` still seem to be used](https://github.com/sidekiq/sidekiq/pull/5823#issuecomment-1479779239), so I don't think dragonflydb is fully compatible yet.

**Comment by romange** [comment]
@alexanderadam we implemented this command. Have you seen any issues with it?

**Comment by alexanderadam** [comment]
I didn't test yet.
Why is the issue still open then?

**Comment by romange** [comment]
Closing as completed :)
