### ISSUE TITLE
Docker compose usage

### ISSUE THREAD

**Issue by PabloSzx** [dragonflydb/dragonfly#65]
What's the expected docker-compose usage?

![image](https://user-images.githubusercontent.com/8672915/171211065-a57279d4-18f2-4bb6-b496-79090be0ac92.png)

and is it possible to use docker port binding?

tested `dragonfly --port 6379 --network=host --ulimit memlock=-1` and it doesn't work either

**Comment by romange** [comment]
I verified that `docker run -p 6379:6379 --network=host --ulimit memlock=-1 dragonfly` works with port binding. Will come back to you regarding docker compose

**Comment by zacharya19** [comment]
This is not a docker-compose issue, you're trying to pass flags to Dragonfly that are not related to it, but to docker (such as, `rm`, `ulimit`, `network`), try removing those params and it should work.
Instead of network host use docker-compose port forwarding and you can use `ulimit` param, e.g.:
```
ulimits:
      memlock: -1
```

**Comment by romange** [comment]
What @zacharya19  said.

**Comment by romange** [comment]
@PabloSzx  did it work for you? Can we close?

**Comment by PabloSzx** [comment]
yep, it works, thank you
