### ISSUE TITLE
High CPU usage while idle

### ISSUE THREAD

**Issue by occasionallydavid** [dragonflydb/dragonfly#66]
DragonflyDB appears to be continuously polling, with no sleeps or wakeups, on all CPUs even when completely idle.

Beyond energy efficiency, this makes it a liability in combination with any laptop battery, or any environment where Dragonfly must run alongside other servers (say, a classic LAMP style VPS environment)

Is there any way to adjust the design so that CPU usage is proportional to load? Ideally there are no wakeups when there are no connections or background work, although this is something Redis never managed to achieve either.

**Comment by romange** [comment]
can you please provide more info? say paste here htop screenshot showing the CPU usage?
I am asking because on my 8 CPU machine I see only 10% CPU usage (as 0.1 CPU) compared to 800% at full load.
The reason why there is some CPU usage is because of the 1ms resolution timer that handles expiry stuff.

**Comment by occasionallydavid** [comment]
Is it possible to adjust this timeout, say by calculating it precisely, or making it adapt with load?

Going by powertop, my (already busy) laptop with all the usual heavyweight apps open (Firefox, Thunderbird, Signal) still experiences 40% more wakeups just with the idle DF running.

Thanks :)

Hardware:

```
model name	: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
```

Htop:

![image](https://user-images.githubusercontent.com/62972099/171227261-d039d6ce-e16f-4b97-b45e-fcd92e28e5cf.png)

Powertop with:

![image](https://user-images.githubusercontent.com/62972099/171228124-7dc6106b-f3b0-4b71-b751-346039295aed.png)

Powertop without:

![image](https://user-images.githubusercontent.com/62972099/171228286-857b9d28-4a0a-4fb1-8391-c42b1cfddc12.png)


<details>
<summary>perf trace -s</summary>

```
timeout -sINT 10 perf trace  -s -p 435769  

 Summary of events:

 Proactor0 (435770), 54604 events, 14.1%

   syscall            calls  errors  total       min       avg       max       stddev
                                     (msec)    (msec)    (msec)    (msec)        (%)
   --------------- --------  ------ -------- --------- --------- ---------     ------
   io_uring_enter     27305      0  3819.403     0.000     0.140     2.856      0.93%


 Proactor1 (435771), 56848 events, 14.7%

   syscall            calls  errors  total       min       avg       max       stddev
                                     (msec)    (msec)    (msec)    (msec)        (%)
   --------------- --------  ------ -------- --------- --------- ---------     ------
   io_uring_enter     28433      0  3784.537     0.000     0.133     1.450      0.93%


 Proactor2 (435772), 55079 events, 14.3%

   syscall            calls  errors  total       min       avg       max       stddev
                                     (msec)    (msec)    (msec)    (msec)        (%)
   --------------- --------  ------ -------- --------- --------- ---------     ------
   io_uring_enter     27543      0  3802.154     0.000     0.138     4.179      0.92%


 Proactor3 (435773), 55007 events, 14.2%

   syscall            calls  errors  total       min       avg       max       stddev
                                     (msec)    (msec)    (msec)    (msec)        (%)
   --------------- --------  ------ -------- --------- --------- ---------     ------
   io_uring_enter     27502      0  3779.044     0.000     0.137    15.439      1.03%


 Proactor4 (435774), 54784 events, 14.2%

   syscall            calls  errors  total       min       avg       max       stddev
                                     (msec)    (msec)    (msec)    (msec)        (%)
   --------------- --------  ------ -------- --------- --------- ---------     ------
   io_uring_enter     27388      0  3813.848     0.000     0.139    16.186      1.01%


 Proactor5 (435775), 54896 events, 14.2%

   syscall            calls  errors  total       min       avg       max       stddev
                                     (msec)    (msec)    (msec)    (msec)        (%)
   --------------- --------  ------ -------- --------- --------- ---------     ------
   io_uring_enter     27444      0  3798.395     0.000     0.138     3.085      0.92%


 Proactor6 (435776), 55140 events, 14.3%

   syscall            calls  errors  total       min       avg       max       stddev
                                     (msec)    (msec)    (msec)    (msec)        (%)
   --------------- --------  ------ -------- --------- --------- ---------     ------
   io_uring_enter     27571      0  3797.901     0.000     0.138     3.022      0.92%

```
</details>

**Comment by romange** [comment]
it's really weird.  dragonfly should not get CPU so high in the idle state. 
I am trying to think of what causes it. Can you pls do the following? 
1. run `./dragongly --logtostderr` if running native or  `docker run ... `  - it should show you some dragonfly logs in the terminal.
1. Go to you localhost:6379 in your browser - you should see an HTTP page.
2. go to this url http://localhost:6379/profilez?profile=on
3. 10s later go to this one  http://localhost:6379/profilez?profile=off 
4. this should display a graph and create a `.perf` file in `/tmp` folder you should see its name in the log. Can you please attach it here?

**Comment by occasionallydavid** [comment]
I had to zip them due to attachment restrictions on GitHub

[issue66.zip](https://github.com/dragonflydb/dragonfly/files/8807453/issue66.zip)

**Comment by occasionallydavid** [comment]
FYI dropping kSpinLimit to 0 on this hardware brings the CPU usage to closer to 30% (as reported by top across all CPUs, previously this was closer to 400/500%)

<details>
<summary>timeout -sINT 10 perf trace -s -p  440125</summary>

```
 Summary of events:

 Proactor0 (440126), 52655 events, 14.2%

   syscall            calls  errors  total       min       avg       max       stddev
                                     (msec)    (msec)    (msec)    (msec)        (%)
   --------------- --------  ------ -------- --------- --------- ---------     ------
   io_uring_enter     26332      0  9436.170     0.000     0.358    15.424      0.89%


 Proactor1 (440127), 56237 events, 15.2%

   syscall            calls  errors  total       min       avg       max       stddev
                                     (msec)    (msec)    (msec)    (msec)        (%)
   --------------- --------  ------ -------- --------- --------- ---------     ------
   io_uring_enter     28121      0  9401.739     0.000     0.334    14.731      0.89%


 Proactor2 (440128), 52172 events, 14.1%

   syscall            calls  errors  total       min       avg       max       stddev
                                     (msec)    (msec)    (msec)    (msec)        (%)
   --------------- --------  ------ -------- --------- --------- ---------     ------
   io_uring_enter     26084      0  9417.545     0.000     0.361     6.671      0.86%


 Proactor3 (440129), 52638 events, 14.2%

   syscall            calls  errors  total       min       avg       max       stddev
                                     (msec)    (msec)    (msec)    (msec)        (%)
   --------------- --------  ------ -------- --------- --------- ---------     ------
   io_uring_enter     26324      0  9419.898     0.000     0.358     4.138      0.86%


 Proactor4 (440130), 52910 events, 14.3%

   syscall            calls  errors  total       min       avg       max       stddev
                                     (msec)    (msec)    (msec)    (msec)        (%)
   --------------- --------  ------ -------- --------- --------- ---------     ------
   io_uring_enter     26457      0  9429.960     0.000     0.356     6.960      0.86%


 Proactor5 (440131), 52175 events, 14.1%

   syscall            calls  errors  total       min       avg       max       stddev
                                     (msec)    (msec)    (msec)    (msec)        (%)
   --------------- --------  ------ -------- --------- --------- ---------     ------
   io_uring_enter     26087      0  9417.025     0.000     0.361    13.400      0.87%


 Proactor6 (440132), 52182 events, 14.1%

   syscall            calls  errors  total       min       avg       max       stddev
                                     (msec)    (msec)    (msec)    (msec)        (%)
   --------------- --------  ------ -------- --------- --------- ---------     ------
   io_uring_enter     26094      0  9415.588     0.000     0.361     3.270      0.86%

```
</details>

**Comment by romange** [comment]
I attached the svg that I succeeded to get from the profiler. 
It does not seem that the problem is with syscalls. I am 99.9% sure it's some artifact of this laptop architecture.

I see you built the binary yourself.  could you build it in debug mode and without changes? if you run `./helio/blaze.sh`  from the project dir it will create build-dbg subfolder where you can build dragonfly. could you repeat the profiling cycle and send me again the perf file please?  I think there is a single hotspot that causes this. 

![pprof001](https://user-images.githubusercontent.com/3674760/171249038-25000063-0741-470b-8c33-8074e187c388.svg)

**Comment by occasionallydavid** [comment]
[issue66-dbg.zip](https://github.com/dragonflydb/dragonfly/files/8807978/issue66-dbg.zip)

**Comment by occasionallydavid** [comment]
Debug build perf top:

![image](https://user-images.githubusercontent.com/62972099/171254559-8b14a559-3dd6-4571-8c7a-0c5756d75e9c.png)

Annotated pause():

![image](https://user-images.githubusercontent.com/62972099/171254687-dd45ed31-ad75-40de-84b0-15b176ca4c9d.png)

Run() has very little usage, seems to be related to that spin

**Comment by romange** [comment]
yes, you are absolutely correct. It did not show such extreme behavior on my amd machine , on my intel laptop and on any of the cloud instances I run dragonfly.

**Comment by occasionallydavid** [comment]
Just curious what generation / chip your Intel laptop is? I have extremely vague memories of the pause instruction changing at some point. This CPU is from Q3 2015, and (due to chipset bug with this particular Dell laptop) is running without any microcode updates

**Comment by romange** [comment]
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
```

**Comment by occasionallydavid** [comment]
Hmm, so your CPU is Kaby Lake and mine is Skylake. Going to try that reboot-with-microcode now

**Comment by romange** [comment]
I am trying to fix what the right fix will be. I need to poll in cloud env, so probably we need a runtime flag.
In ideal it could be autoconfigured but I am not sure how to determine that `pause` is so cpu consuming...

**Comment by romange** [comment]
Can you  reduce the multiplicative factor in `Pause()` from 100 to 1 ?

**Comment by romange** [comment]
it's best we will be able to calibrate automatically. On my laptop for example, dragonfly can run without any changes.
We need first to understand what to change. If reducing the factor from 100 to 1 solves the issue, I will be able to write the calibrator, I hope.

**Comment by occasionallydavid** [comment]
Reducing the factor from 100 to 1 reduces top-measured %CPU from 400-500% to around 80% with the debug build. Powertop-measured wake count is approximately identical

**Comment by occasionallydavid** [comment]
Just to report, no change in behaviour with microcode updates applied:

```
[    0.000000] microcode: microcode updated early to revision 0xea, date = 2021-01-25
```

**Comment by occasionallydavid** [comment]
https://aloiskraus.wordpress.com/2018/06/16/why-skylakex-cpus-are-sometimes-50-slower-how-intel-has-broken-existing-code/

**Comment by romange** [comment]
I think the easiest solution will be to expose run-time arguments directly. you will find what works best for you and report here. I will try to implement a simple calibration procedure that will adjust those arguments according to what you tell me.

**Comment by occasionallydavid** [comment]
Some X/Y problem missing in my original report: I just want to develop against DF locally and don't care about performance at all. A single thread that sleeps politely and offers 10 requests/sec but is extremely kind to battery is much more desirable in this environment :)  I know it's difficult to squeeze both use cases in one binary, but really I think maybe that is what this bug was asking for. Ideally maybe something like a `--dev` flag?

**Comment by romange** [comment]
lets try with spinlock arguments and if these won't work to your satisfaction we will add `--dev` flag! :)

**Comment by romange** [comment]
I created a branch named SpinArgs2 for dragonfly. you will also need to update helio submodule with `git submodule update` after the switch.  There I introduced two flags: `proactor_pause_count` and `proactor_spin_limit` that should control the spinning.
Please also remove `_deps\glog-*` before rebuilding dragonfly - I fixed a small bug there as well.

Once you rebuild, pls run with `./dragonfly --vmodule=proactor=1 --logtostderr`
it will print you  among other lines something like this:
`proactor.cc:111] Running 10 Pause(10) took 707us` .
pls run dragonfly with smaller values for the flags, whatever makes your cpu usage calm. say, proactor_pause_count=2 and  proactor_spin_limit=2. But pls keep both flags non-zero. If you are happy with the cpu usage, pls tell me parameter values and the measurements you got in the log. 

Thanks!

**Comment by occasionallydavid** [comment]
It's probably something to do with me, but I can't find "took" from that new log line anywhere:

```
dragonfly] ag -w took |cat
src/server/db_slice.h:129:  // Returns second=true if insertion took place, false otherwise.
doc/dashtable.md:150:As you can see on the graph, Redis uses 50% more memory even before BGSAVE starts. Around second 14, BGSAVE kicks off on both servers. Visually you can not see this event on Dragonfly graph, but it's seen very well on Redis graph. It took just few seconds for Dragonfly to finish its snapshot (again, not possible to see) and around second 20 Dragonfly is already behind BGSAVE. You can see a distinguishable cliff at second 39
helio/util/fiber_sched_algo.cc:104:      VLOG(1) << "Execution of " << fibers_ext::short_id(prev_picked_) << " took too long "
helio/util/fiber_sched_algo.cc:112:      LOG(INFO) << "Took " << delta_micros / 1000 << " ms since it woke and till became active "
helio/util/uring/proactor.cc:423:    VLOG(1) << "io_uring_register_files took " << absl::ToInt64Microseconds(duration) << " usec";

dragonfly] git status
On branch SpinArgs2
Your branch is up-to-date with 'origin/SpinArgs2'.

nothing to commit, working tree clean
[21:31:55 eldil!63 dragonfly] 
[21:31:56 eldil!63 dragonfly] git fetch
[21:31:59 eldil!64 dragonfly] git submodule summary
[21:32:07 eldil!65 dragonfly] git status
On branch SpinArgs2
Your branch is up-to-date with 'origin/SpinArgs2'.

nothing to commit, working tree clean
```

**Comment by romange** [comment]
oh shit I forgot to update helio submodule. please pull and update again

**Comment by occasionallydavid** [comment]
It doesn't seem possible on this laptop to get usage below 30% (reported by top) regardless of the values given in the flags

I haven't used io_uring in anger yet, but note `io_uring_wait_cqes()` supports what looks like a select-like timeout, with the proviso that "this function isn’t safe to use for applications that split SQ and CQ handling between two threads".  In the case of DF, is there no possibility of just having the kernel handle wakes in a non-polling fashion?

**Comment by romange** [comment]
I think reducing from 800 to 30 is great progress already. The rest can be attributed to expiry policy.  Please change line engine_shard_set.cc:58 to use greater values than 1ms. will it fix the problem?.

**Comment by romange** [comment]
Also, are you still in debug mode?

**Comment by occasionallydavid** [comment]
I ran with:

`./dragonfly  --proactor_threads=1 --proactor_pause_count=1 --proactor_spin_limit=1`

And bumped the interval to 1000ms, and now DF has disappeared into the background noise even in powertop output. I don't know what this breaks, though. `redis-cli` seems to do what I expect though

Nope, these are opt builds

**Comment by romange** [comment]
and are you saying that increasing any of the flags will bring it back to front? what ` Running 10 Pause(10)` line prints ?

**Comment by occasionallydavid** [comment]
With the default flags, top reports ~5% CPU and pause timing is:

```
I20220531 22:18:54.884318 15522 proactor.cc:111] Running 10 Pause(10) took 277us
```

With the jinxed flags from above, ~0.7% CPU and:

```
I20220531 22:21:30.137244 15615 proactor.cc:111] Running 10 Pause(10) took 18us
```

**Comment by romange** [comment]
Good idea. Will do. I will send you the PR shortly.

**Comment by romange** [comment]
Created https://github.com/dragonflydb/dragonfly/pull/70.

Feel free to use this branch and if everything is fine I will submit it later today.
