### ISSUE TITLE
Support select command for replication

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#670]
On master side write to journal the select command in all shard journals
On replica execute the select command. Note we dont need to sync the execution between the shards

Here is an example why the select commands need to be executed on replica as well:
In the command flow:

set key1 value1
select 1
select 0
move key1 1

If we dont run select 1 in replica than db 1 will not be created in replica and therefor the move command will not be executed

**Comment by romange** [comment]
I understand what you.are saying but the example is not very good because "select 1; move key 1" moves from 1 to 1

**Comment by adiholden** [comment]
After reviewing the implementation of move command I found that it creates the db if it does not exists and therefor its ok to not write the select to journal.
Closing this issue
