### ISSUE TITLE
TTL for messages in HSET

### ISSUE THREAD

**Issue by micw** [dragonflydb/dragonfly#687]
**Did you search GitHub Issues and GitHub Discussions First?**
Yes.

**Is your feature request related to a problem? Please describe.**
#335 allows to set TTL for set members. This should also be possible for HSET

**Describe the solution you'd like**
Implement HSADDEX similar to SADDEX

**Comment by romange** [comment]
Ok, can you provide some context about how you want to use this feature?
Also, feel free to join our discord server and ping me directly

**Comment by micw** [comment]
Hello, thank you a lot for the fast response.

One reason is consistency ^^ Since it it possible for set members, why shouldn't it be possible for hash members?

We are currently using KeyDB as cache for our IoT platform which seems to be a dead end.  So I look around for a good replacement and dragonfly looks very promising.

We use HSETs as cache for IoT gateways The Key is the gateway ID. The hash key is the ID of a device received by that gateway. The hash value contains a JSON with metadata about the device. That way I can easily cache which gateway received which device + metadata. I use "EXPIREMEMBER" of keydb to evict devices from that cache that have not be seen for a while.

Maybe there are alternative approaches which looks less elegant to me:

* Using keys of "Gateway + Device Id" for each entry - requires a key scan to retrieve the data for one gateway
* Put a timestamp into the hash value and evict programmatically - would be an ugly workaround but would work.

Kind regards,
Michael.

**Comment by romange** [comment]
Hi Michael,
why do you consider keydb is a dead end? Is it because of its maintenance prospects, or do you have actual problems with it in production?
I am asking to understand what kind of value a multi-threaded server provides for your use-case. Is it latency, throughput, complexity, cost, something else?

**Comment by micw** [comment]
> regarding your use-case - are gateway ids relatively constant, or are they also added and removed constantly?

relatively constant. while a gateway lasts a few years, devices may be added/removed every few months. Even faster if a gateway is moved around.

> why do you consider keydb is a dead end? Is it because of its maintenance prospects, or do you have actual problems with it in production?

Mainly because of https://github.com/Snapchat/KeyDB/issues/470 and https://github.com/Snapchat/KeyDB/issues/494 - The last "stable" release is a year old. Plus a lot of open "priority 1" issues affecting stability and performance.

In production we have a lot of outages that my colleague has tracked down to already known, still open issues. ATM we have (hopefully) mitigated the main issue (cluster out of sync, cannot re-sync). But I'm looking around for a replacement.

**Comment by romange** [comment]
Michael, I can create a similar feature to SADDEX called HSETEX, but I would appreciate it if you could provide your contact information. This way, I can receive feedback on how the feature is working and make any necessary improvements. We can communicate through Discord, Slack, or email. If it's ok by you, please send me an email to roman at  dragonflydb.io 
or DM me on discord (linked from the README).
