### ISSUE TITLE
MONITOR does not display lua commands correctly

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#756]
This is how redis displays when receiving `eval "return redis.call('get', 'bar')" 0`

```
1675588394.760960 [0 127.0.0.1:38756] "eval" "return redis.call('get', 'bar')" "0"
1675588394.761052 [0 lua] "get" "bar"
```

**Comment by boazsade** [comment]
The reason we don't  see this at DF and do see this with Redis is that we are getting an error from DF Saying "ERR script tried accessing undeclared key". I can move the monitor to return before that, and then we would see this in the monitor, but I have to make sure that this don't break anything else.
The other issue is with eval itself. This command is successful with Redis, but not with DF
