### ISSUE TITLE
Provide official image on DockerHub

### ISSUE THREAD

**Issue by Reverier-Xu** [dragonflydb/dragonfly#759]
Hi, thank you for your awesome project!

I'd like to ask you add an official image on DockerHub. The official docker repo `docker.dragonflydb.io` is very slow in some country/area and no one offers a mirror for this site, DockerHub have mirrors that provide better experience.

If not, I'm curious as to your reasons for not wanting to do so? Most of the projects I've seen have chosen to use DockerHub to host their images.

Please forgive me if I offend.

**Comment by romange** [comment]
We currently host them on github repositories. Can you pull the package below? Is it as slow as using 
docker.dragonflydb.io ?

https://github.com/dragonflydb/dragonfly/pkgs/container/dragonfly/68214343?tag=v0.15.0

**Comment by Reverier-Xu** [comment]
> We currently host them on github repositories. Can you pull the package below? Is it as slow as using docker.dragonflydb.io ?
> 
> https://github.com/dragonflydb/dragonfly/pkgs/container/dragonfly/68214343?tag=v0.15.0

I found several mirror sites for ghcr.io that available in my country, the pulling speed is much faster than before. Thank you!
