### ISSUE TITLE
Any plan about static compile?

### ISSUE THREAD

**Issue by tosone** [dragonflydb/dragonfly#76]
Also nice project.

We know vcpkg is a great c/c++ deps managerment tool. [helio](https://github.com/romange/helio) and dragonfly have many deps, maybe we can static compile with vcpkg, and release the binary on github, other guys can download it run anywhere.

**Comment by gaby** [comment]
@tosone Was this ever done?

**Comment by tosone** [comment]
https://github.com/dragonflydb/dragonfly/releases yes, you can download it on release page.
