### ISSUE TITLE
Regression tests fail due to replica didnt finish running journal commands

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#770]
Bug description:
Currently we see fail in regression tests in github actions. My suspect is that replica got all the commands from master and is executing them, but in tests we perform the diff check between master and replica before replica finished the commands execution.

**I tried to fix this before** by comparing total_commands_processed returned from INFO command executed on replica twice while waiting 0.5 miliseconds between the first and the second executing.
This fix does not seem to solve the problem on github, I think that the machine there is small so replica is not running between the checks, and its hard to say what is the time in miliseconds that will ensure that replica will executor fiber will run and will ensure that the test will be stable.

**New suggestion**
ROLE command will return replica offset 
In master this will represent the number of journal records we sent:
for each flow I will save the number of record written to journal. The ROLE command will return the replica offset value in this format <flow_id>,<journal_num> repeated as number of flows
In replica this will represent the number of journal records we executed:
each flow I will save the number of records executed. The ROLE command will return the offset value in the same format.
<flow_id>,<journal_num> repeated as number of flows

We will be able to compare values in test and if the values are the same this means replica finished executing the commands and we can check the diff between master and replica.

**Comment by adiholden** [comment]
@dranikpg @romange

**Comment by dranikpg** [comment]
I support the idea of tracking it manually.

But I'm not sure, if we should use the ROLE command (with a format different from usual), or create some debug command for it

**Comment by adiholden** [comment]
@dranikpg I spoke with Roman and he also suggested to user sub debug/dfly command for this
