### ISSUE TITLE
General Question: System requirements for a remote VM (eg. LightSail at AWS)

### ISSUE THREAD

**Issue by inglesuniversal** [dragonflydb/dragonfly#78]
Do you have the recommended specs as a bare minimum for this project to run on a remote server?

Thanks

**Comment by romange** [comment]
I am not familiar with LightSail. 

Please note that Dragonfly requires kernel 5.10 and for kernel less than 5.12 it needs memlock limit of at least 64kb if running via container.  Based on AWS docs, even the smallest instance should be able to run DF.  The rule of thumb - it needs at least 256MB per CPU and the smallest instance has 512MB.

**Comment by romange** [comment]
Closing. Feel free to reopen if you need more info
