### ISSUE TITLE
Write journal record should not be blocking on some flows

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#788]
When writing record to journal streamer it might result in fiber switch.
In some flows this can be a problem as we hold iterators and after the switch back to the fiber the iterator can be invalid.

We could fix the bug in this flows, but we might miss some of them. Also we might do future changes that will cause this bug.

A better solution would be having a flag in writing to journal a record which will ensure there will be no switch. This flag will be enabled in the flows in which we are overwriting the journal record (non auto journal). In the flow of auto journal inside the transaction framework we will set the flag to false, so it will enable a switch as in this flow there is no problem to do the switch.

**Comment by dranikpg** [comment]
> This flag will be enabled in the flows in which we are overwriting the journal record (non auto journal)

This flag should only be enabled inside heatbeat based expiry

**Comment by adiholden** [comment]
@dranikpg why? we have this bug the same bug of invalid iterator in non auto journal commands
