### ISSUE TITLE
Error from server: ERR wrong number of arguments for 'zpopmin' command

### ISSUE THREAD

**Issue by Morranto** [dragonflydb/dragonfly#801]
**Describe the bug**
get an error when running redis-benchmark

error message "Error from server: ERR wrong number of arguments for 'zpopmin' command"

**To Reproduce**

```
user# ./dragonfly 
```
in another shell
```
user# redis-benchmark
```

**Expected behavior**
exit successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/56924967/218758242-a3170bb9-0ca3-4370-bdaf-b2bbe09658b9.png)

**Environment (please complete the following information):**
 - OS: [ubuntu 22.04]
 - Kernel: Linux iZ2zej734af822gkjiah1mZ 5.15.0-56-generic 62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 - Containerized?: none
 - Dragonfly Version: v0.16.0-b62a590a3c8f89598267fb14cc360c4b99b2d20d

**Reproducible Code Snippet**
```
# Minimal code snippet to reproduce this bug
```

**Additional context**

the version of redis-benchmark is 7.0.8

**Comment by romange** [comment]
yeah, we do not support zpopmin yet. Do you need it? :)

**Comment by Morranto** [comment]
> yeah, we do not support zpopmin yet. Do you need it? :)

no，i just found it by chance 😬
