### ISSUE TITLE
json type not support root path as '.' , so some tools or code may throw error

### ISSUE THREAD

**Issue by liuzhuoling2011** [dragonflydb/dragonfly#811]
`W20230214 08:41:52.302026    11 json_family.cc:1611] path '.': Invalid JSONPath syntax: Expected '$' or function expression`

![image](https://user-images.githubusercontent.com/8407297/219262407-9924d889-b033-4bd8-98bb-56a02cd198dd.png)

**Comment by romange** [comment]
Can you please provide the full redis-cli command that triggers this error?

**Comment by liuzhuoling2011** [comment]
The tool is [RedisInsight](https://github.com/RedisInsight/RedisInsight)

Here is the code:
![image](https://user-images.githubusercontent.com/8407297/219265478-241dccf3-4590-4596-8dd5-c13591b768a1.png)

**Comment by liuzhuoling2011** [comment]
@iko1 Thanks for your kind help
1. for redisinsight tool, I find it use 'json.debug memory' command but dragonfly not have, so throw error
2. for jsonpath style, maybe I need change my habits, lol

**Comment by liuzhuoling2011** [comment]
@romange Hi, I find the reason why redisinsight cant work
1. [JSON.SET](https://redis.io/commands/json.set/) key path value [NX | XX]   `current version not support [NX | XX] params`
2. [JSON.DEBUG MEMORY](https://redis.io/commands/json.debug-memory/) key [path]     `current version not support memory params`
