### ISSUE TITLE
The dragonfly process shuts down automatically without any log output

### ISSUE THREAD

**Issue by boomballa** [dragonflydb/dragonfly#814]
Every time the dragonfly process is started, the next day the process will automatically exit without any log output

The instance startup command is ：
dragonfly --alsologtostderr --requirepass=pwd4dba --cache_mode=true -dbnum 1 --bind 10.196.3.191 --port 16379   --dir /home/dba/redis/drogonfly16666/  --maxmemory=48gb --keys_output_limit=12288 --dbfilename dragon.rdb  > dragonfly.error 2>&1  &

Instance startup log output：
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/8543659/219606588-eb92334e-4b59-4c3f-9642-919b1e04e446.png">

final log output：
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/8543659/219606916-699c8ff1-51e3-444f-a570-28030d2eb529.png">

The reason for the instance crash was not found in the system log, so I am very confused. Is the phenomenon of this process automatically exiting? Is it because I personally used the parameters to start the instance improperly or the current version of dragonfly has an automatic exit mechanism ?

**Comment by romange** [comment]
This should not happen.
@boomballa , I am guessing dragonfly.error is empty? 

can you please download our latest version  
https://github.com/dragonflydb/dragonfly/releases/download/v0.15.0/dragonfly-x86_64.unstripped.tar.gz 
and see if the problem persists. 

Also, I do not understand why you have so many info logs about slow context switching. Do you run anything else on this machine?

**Comment by boomballa** [comment]
@romange  Ok thanks, I'll try that and see if the same happens.
Yes, I ran some performance tests using memtier_benchmark.

**Comment by romange** [comment]
i see. in that case I also suggest wrapping the command within a shell script and output the error code when the dragonfly process finishes. This way at least we will know if it's 0 - normal, or something else.

another likely thing - if you run it like this remotely via a terminal,  and the connection break, the process might get SIGTERM signal which may be the reason for its orderly shutdown. You can use `nohup  dragonfly  <arguments> & ` to alleviate that.

**Comment by romange** [comment]
@boomballa did you solve it?

**Comment by boomballa** [comment]
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/8543659/219999181-af300d14-3422-405c-8f0b-94ee5a245b74.png">

@romange  I tested it again with the version you gave me, and the crash still occurs.
**System:** Debian GNU/Linux 11
**dragonfly version:**
`shell:~$ ./dragonfly-x86_64 --version
dragonfly v0.15.0-3449ba8a7bab1b5168433eba983e7fa245439cd2
build time: 2023-02-05 06:39:08`
**Log output:**
`I20230217 18:16:02.634668 2739566 proactor_pool.cc:66] Running 56 io threads
I20230217 18:16:02.676084 2739566 server_family.cc:378] Data directory is "/home/dba/redis/drogonfly16666"
I20230217 18:16:02.676177 2739566 server_family.cc:464] Loading /home/dba/redis/drogonfly16666/dragon.rdb
I20230217 18:16:02.676779 2739787 rdb_load.cc:2026] Loading RDB produced by version 999.999.999
I20230217 18:16:02.676779 2739580 listener_interface.cc:86] sock[173] AcceptServer - listening on port 16379
I20230217 18:16:02.676851 2739787 rdb_load.cc:2033] RDB age 14.2 days
I20230217 18:16:02.676879 2739787 rdb_load.cc:2038] RDB memory usage when created 53.02MiB
I20230217 18:16:03.309792 2739583 dfly_main.cc:229] Your current version '0.15.0' is not the latest version. A newer version '0.16.0' is now available. Please consider an update.
I20230217 18:16:07.937300 2739787 server_family.cc:576] Done loading RDB, keys loaded: 670222
I20230217 18:16:07.937431 2739787 server_family.cc:577] Loading finished after 5.26 s`

**Comment by romange** [comment]
@boomballa  I do not see a crash. 
Can you try running `nohup ./dragonfly-x86_64 ... &` ?

**Comment by boomballa** [comment]
@romange  This is being tested. The version you gave me was tested before, and it doesn't seem to work. `nohup ./dragonfly-x86_64 ... & `  is currently being tested.

<img width="934" alt="image" src="https://user-images.githubusercontent.com/8543659/220023559-60476be0-8b44-4f16-858f-09a111324a5f.png">

**Comment by boomballa** [comment]
@romange Use the` ./dragonfly-x86_64 ... &` method to start, and there is no crash anymore. Thank you for your guidance and help.

By the way, is the replica function not supported yet? The description of the new version mentions that` Dragonfly is now compatible with redis-sentinel, allowing to support H/A setups.` Doesn’t it mean master-slave failover?

**Comment by romange** [comment]
Yes, it means. We support m/s replication, you can try it out in test environment.

We are ironing out the last bugs before announcing it.

**Comment by boomballa** [comment]
@romange  Okay, I am looking forward to it very much. Thanks for your hard work.Is there an estimated time for the official release of the m/s replication version?

**Comment by romange** [comment]
@boomballa  next week. closing this issue.
