### ISSUE TITLE
Testing Plan of Replication

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#824]
1. Correctness - covered
2. Performance - missing 
3. Failure scenario   - covered

**Comment by ashotland** [comment]
Initial benches:
https://github.com/dragonflydb/benchmarks/tree/main/benches/replication

Some read from replica after write to master latency measurements
Running
python3 benches/replication/read_after_write_test.py ip-172-31-40-245.ec2.internal ip-172-31-43-9.ec2.internal ip-172-31-44-67.ec2.internal
While also running 
memtier_benchmark -s ip-172-31-40-245.ec2.internal -p 6379 --ratio 1:0 -t 18 -c 30 -d 256 --distinct-client-seed --test-time=120 --hide-histogram

DF (microsecs):
Min: 247
Max: 1813
Median: 327
Mean: 812.233
90%: 1717
99%: 1778


REDIS (microsecs):
Min: 294
Max: 5539
Median: 3945
Mean: 3500.152
90%: 4355
99%: 4746

**Comment by ashotland** [comment]
We can consider a better way to measure read from replica after write to master latency with pubsub by publishing to master and subscribing to replica

**Comment by romange** [comment]
I actually not sure if pubsub is replicated. Have you checked it with redis?

**Comment by ashotland** [comment]
Stumbled on this idea and wrote it so we don't forget, we'll need research some more if  we decide it is of interest.

**Comment by ashotland** [comment]
https://github.com/dragonflydb/benchmarks/tree/main/benches/replication#readme
