### ISSUE TITLE
Support GET option for SET command

### ISSUE THREAD

**Issue by talbii** [dragonflydb/dragonfly#841]
It is possible to supply the `GET` argument when setting a new string value, in order to return the old value (this is equivalent to `GETSET`). Currently Dragonfly supports this (i.e., there is no syntax error), however an "OK" is returned instead of the old value.

**Example**
```shell
> SET k1 "Hello"
"OK"
> SET k1 "World" GET
"OK" # expected: "Hello"
> GET k1
"World"
```

**Comment by romange** [comment]
#484  is related to this.
