### ISSUE TITLE
EXPIRE commands do not support optional flags [NX | XX | GT | LT]

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#842]
Add support to optional flags for the following expire commands 
EXPIRE
EXPIREAT
PEXPIRE
PEXPIREAT

**Comment by UkuLoskit** [comment]
@romange I would like to work on this next

**Comment by romange** [comment]
Sure, no problem. Have you checked why your current pr fails the regtests by any chance?

**Comment by lsvmello** [comment]
Is anything missing on this issue?

**Comment by romange** [comment]
Hi @lsvmello how you been?! great to have you back!

**Comment by adiholden** [comment]
This issue is done, closing it. FYI @lsvmello
