### ISSUE TITLE
JSON.RESP path arg should be optional 

### ISSUE THREAD

**Issue by ashotland** [dragonflydb/dragonfly#852]
JSON.SET item:2 $ '{"name":"Wireless earbuds","description":"Wireless Bluetooth in-ear headphones","connection":{"wireless":true,"type":"Bluetooth"},"price":64.99,"stock":17,"colors":["black","white"], "max_level":[80, 100, 120]}'

JSON.RESP item:2 
yields
(error) ERR wrong number of arguments for 'json.resp' command

should behave like JSON.RESP item:2 $

**Comment by iko1** [comment]
I'm pretty sure that you can open the same bug on each JSON command, the path is required.

**Comment by romange** [comment]
@iko1  why are you saying this? 
https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/json-resp.html  says that path is optional.

**Comment by iko1** [comment]
Indeed, in the official documentation of both Json implementations, the path is optional.
What I'm saying is if you set the path argument to be optional and set the default value of the path to the root on one JSON command in the projects' JSON implementation, I recommend doing the same change in each Json command, to be aligned with the other JSON implementations.

**Comment by romange** [comment]
Got ya!
