### ISSUE TITLE
Arguments of XREVRANGE are flipped

### ISSUE THREAD

**Issue by talbii** [dragonflydb/dragonfly#856]
**Description**

In `XRANGE`, the `-` and `+` tokens select the minimum and maximum IDs, respectively. So, the command

```shell
XRANGE stream - +
```
selects all items in the stream. In the context of `XREVRANGE`, the arguments to the command are flipped, i.e.,:

```shell
XREVRANGE stream end begin [COUNT count]
```
so, calling `XREVRANGE stream - +` should produce no meaningful output, however, it outputs the stream (in reverse):

```
127.0.0.1:6379> XRANGE stream - +
1) 1) "1676993775209-0"
   2) 1) "f1"
      2) "v1"
2) 1) "1676993779209-0"
   2) 1) "f2"
      2) "v2"
3) 1) "1676993781122-0"
   2) 1) "f3"
      2) "v3"
127.0.0.1:6379> XREVRANGE stream - +
1) 1) "1676993781122-0"
   2) 1) "f3"
      2) "v3"
2) 1) "1676993779209-0"
   2) 1) "f2"
      2) "v2"
3) 1) "1676993775209-0"
   2) 1) "f1"
      2) "v1"
```
whereas `XREVRANGE + -` produces an empty array.

Likewise for specific ranges.

**Comment by FZambia** [comment]
Many thanks for fixing this @talbii - all our standalone Redis tests in [Centrifuge](https://github.com/centrifugal/centrifuge) library now passing with DF 1.3.0

**Comment by romange** [comment]
@FZambia Great to hear! If you have any feedback regarding how Dragonfly interacts with Centrifuge, I would love to hear it.

**Comment by FZambia** [comment]
@romange no particular feedback at this point. It works – which is great - but of course it would be cool to stress it out on Linux machine. Hopefully will be able to do this at some point and share sth.
