### ISSUE TITLE
Print replica port in ROLE

### ISSUE THREAD

**Issue by dranikpg** [dragonflydb/dragonfly#859]
We now track the replica port and store it in ReplicaRoleInfo, but don't print it in the ROLE command, only the ip

**Comment by romange** [comment]
Can you expand, please?

**Comment by dranikpg** [comment]
We now track the replica port and store it in ReplicaRoleInfo, but don't print it in the ROLE command, only the ip

**Comment by romange** [comment]
@ashotland Do you know why Redis print replica port in Role? When it is used?
In Dragonfly we open multiple connections so we can not blindly implement this feature.

**Comment by dranikpg** [comment]
its the replica's external listening port, its sent during greet
