### ISSUE TITLE
On replica snapshotting records pushed to channel can be OOO 

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#879]
When snapshotting master we must send serialized db entries and journal entries by the order we serialized them.
When serializing db entry we update it version and push it to channel, then if we get a journal change to that entry we first check the entry version and because it was serialized we dont serialize it again and we write the journal change. The replica must get the serialized entry first and the journal change later.
The reason that the records can be pushed to channel OOO is in the following sernario:
1. main loop serializes db entry and push to channel, channel is full and there for fiber preempts
2. pull from channel fiber is running removing entry from channel 
3. update command for a serialized db entry is running, the entry version is updated so we dont serialize it, we serialize the journal change and push to channel, which does not preempt because it is not full
4. main loop runs again push to channel success 

Because db entry push to channel was executed at step 4, we get OOO records.

**Comment by adiholden** [comment]
To fix this bug I suggest that we enforce the order of the records in the pulling fiber which writes to the socket.
We have 2 fibers writing to the channel of specific shard, one of the main loop and the other is the fiber pulling data from tx queue. 
Therefore in the pulling we can track the last record id pushed to socket and use a local queue to hold the pulled records which should not be sent yet.

**Comment by romange** [comment]
> To fix this bug I suggest that we enforce the order of the records in the pulling fiber which writes to the socket. We have 2 fibers writing to the channel of specific shard, one of the main loop and the other is the fiber pulling data from tx queue. Therefore in the pulling we can track the last record id pushed to socket and use a local queue to hold the pulled records which should not be sent yet. @romange @dranikpg

One thing to note - we can not assume how many fibers write to the channel. It will be more than two in the future because some transactions will execute in a fiber that  is not from tx-queue

**Comment by dranikpg** [comment]
Again, good catch 🏆 I wonder how many more bugs we have with such fiber cases

> pull from channel fiber is running removing entry from channel

this wakes up the waiting fiber but its not guaranteed to be placed first by the scheduler, right?

We can either implement your suggestion or add a ticket lock, maybe it'll be useful for other scenarios as well
