### ISSUE TITLE
Test Redis -> Dragonfly Replication

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#880]
Migration path
1. Should work for zero-down time migration purpose
2. Reduce time to value to allow dragonfly running alongside with Redis master

**Comment by ashotland** [comment]
Found https://github.com/dragonflydb/dragonfly/issues/887

**Comment by romange** [comment]
please update

**Comment by ashotland** [comment]
We have https://github.com/dragonflydb/dragonfly/blob/main/tests/dragonfly/redis_replicaiton_test.py
@adiholden made it pass :1st_place_medal: 

I am closing this and we'll open new specific issues for bugs.
