### ISSUE TITLE
Fullsync from Redis doesn't work

### ISSUE THREAD

**Issue by ashotland** [dragonflydb/dragonfly#887]
Simple repro 

Run Redis (as master)
Write to Redis (e.g. set key val)

Run Dragonfly
Make Dragonfly replica of redis
Read from Dragonfly (e.g. get key)
Expect the same value but observe nil

**Comment by romange** [comment]
@ashotland  need more details in the task :)

**Comment by ashotland** [comment]
> @ashotland need more details in the task :)

Sure, added.

**Comment by ashotland** [comment]
It works with redis-6.2 :)
