### ISSUE TITLE
implement pubsub command

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#90]
I already submitted `psubscribe/punsubscribe` functionality. What's left to do for 2.8 is 

* https://redis.io/commands/pubsub-channels/
* https://redis.io/commands/pubsub-numpat/
* https://redis.io/commands/pubsub-help/  (not 2.8 per-ce but nice to have regardless)

I will be able to guide on how to do that.

**Comment by zacharya19** [comment]
dibs.
