### ISSUE TITLE
Adjust HELM charts to support replication

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#912]

**Comment by romange** [comment]
@Pothulapati  I am guessing we do not need it, right?

**Comment by Pothulapati** [comment]
It's confusing. If we don't support replication why do we even [have a `replicaCount` value](https://github.com/dragonflydb/dragonfly/blob/main/contrib/charts/dragonfly/values.yaml#L6) that allows multiple replicas to exist? 🤔 If we have a way to configure an instance to be a replica during init (i.e through command line flags, environment variables), We can configure `*-0` to be master always and other instances to be replica in a static manner and get things working in a normal manner.

If we don't want to do any of that, We can close this issue 👍🏼

**Comment by romange** [comment]
maybe it's for horizontal scale? just deploying multiple instances of Dragonfly?

**Comment by Pothulapati** [comment]
Hmm, Valid but we are still providing a single service to access any of that instances part of the horizontal scale which means with default configuration, Users can't be sure on which instance they are landing.

For deploying multiple instances, Users can deploy a helm chart multiple times with different names, namespaces. I don't think anyone would want multiple instances of Dragonfly with the same name, and Service.

I guess, We can leave it for now as it works for the normal case i.e `1` instance and allows users to do something on their own when they want multiple instances (i.e create new services, etc) or manually configure replication.

**Comment by joeky888** [comment]
https://github.com/Enapter/charts/blob/master/keydb/templates/secret-utils.yaml#L17

```sh
for node in {0..{{ (sub (.Values.nodes | int) 1) }}}; do
      if [ "${host}" != "{{ include "keydb.fullname" . }}-${node}" ]; then
          replicas+=("--replicaof {{ include "keydb.fullname" . }}-${node}.{{ include "keydb.fullname" . }}-headless {{ .Values.port }}")
      fi
done
```

This is how KeyDB helm chart does. It uses a Multi-Master StatefulSet, so redis clients only have to randomly pick one of them to connect, for example: 

Pod `keydb-0` will have the args `--replicaof keydb-1 --replicaof keydb-2`.
Pod `keydb-1` will have the args `--replicaof keydb-0 --replicaof keydb-2`.
Pod `keydb-2` will have the args `--replicaof keydb-0 --replicaof keydb-1`.

The interesting part is that this KeyDB chart utilized a Fully-Connected Mesh Network, it is great for a small KeyDB cluster, however, [I wonder if they can provide an option to use a Ring Network.](https://github.com/Enapter/charts/issues/76)

![image](https://github.com/dragonflydb/dragonfly/assets/6928939/13140a77-fee0-4c9a-97fd-10ec122896a2)

**Comment by romange** [comment]
There are no immediate plans to support this
