### ISSUE TITLE
Errors Running Sidekiq with Dragonfly

### ISSUE THREAD

**Issue by ashotland** [dragonflydb/dragonfly#923]
2023-03-09T14:07:47.995Z pid=533208 tid=bh04 ERROR: heartbeat: ERR invalid expire time in 'expire' command
Using large expiry value
https://github.com/sidekiq/sidekiq/blob/main/lib/sidekiq/launcher.rb#L13
We have constexpr int64_t kMaxExpireDeadlineSec = (1u << 27) - 1;

WARNING: Your Redis instance will evict Sidekiq data under heavy load.
The 'noeviction' maxmemory policy is recommended (current policy: '').
See: https://github.com/mperham/sidekiq/wiki/Using-Redis#memory
https://github.com/sidekiq/sidekiq/blob/4c101d243e9589cd3d1a81060dac602beb1652a1/lib/sidekiq/embedded.rb#L45

For sidekiq v >=7 
https://github.com/sidekiq/sidekiq/blob/4c101d243e9589cd3d1a81060dac602beb1652a1/lib/sidekiq/embedded.rb#L42
It won't start at all as Dragonfly doesn't specify a valid redis version number

Porposed fixes:

Expiry: Instead of returning error truncating large expiry value, can have a flag for that.

maxmemory_policy: list it in info compatible with redis

version: list there the max redis version we are compatible with and add dragonfly_version field

**Comment by romange** [comment]
expire - we can support "5 * 365 * 24 * 60 * 60" as well, I can make the
change.


maxmemory_policy -  agreed.
version - agreed.

**Comment by ashotland** [comment]
Related issues:
Sidkiq v>=7 requires RESP3 support  #218 
BRPOP sometimes not WAI #945
