### ISSUE TITLE
Connection drop on QUIT when busy

### ISSUE THREAD

**Issue by pascaldekloe** [dragonflydb/dragonfly#935]
The connection is simply dropped when there are commands in the pipeline. Reproduce with a simple nc(1) session as follows.

```
% echo 'subscribe foo\nunsubscribe foo\nquit\n'| nc localhost 6379
% 
```

The server must respond to all three commands before closing the connection.

**Comment by romange** [comment]
I could reproduce another problem around that area.
with file `1.txt` like:
```
subscribe foo
unsubscribe foo
```

`cat 1.txt | redis-cli --pipe` would stuck. I am assuming this is the problem you described.
