### ISSUE TITLE
Kernel >= 5.10 reasons?

### ISSUE THREAD

**Issue by clemenko** [dragonflydb/dragonfly#96]
I am trying to test with Rocky/Centos/RHEL 8.6. Which technically is the latest with a 4.18 kernel. Clearly dragonflydb does not work. Trying to understand why? This will severally limit the deployments to Ubuntu only. 

Will older kernels be supported?

**Comment by romange** [comment]
Hi Andy,

If you read Readme you will see the reasons for 5.10 requirements. DF uses iouring API which was introduced in 5.4. in practice it became stable in 5.10. 

DF can run on alpine, bullseye and Ubuntu.

Re rhel/rocky distros - i do not have much experience with them. I've read it is possible to upgrade their kernels via elrepo. It is not the case?

**Comment by romange** [comment]
Closing - feel free to continue the discussion in discussions :)
