### ISSUE TITLE
crash on pytest - test_subsribers_with_active_publisher

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#964]
**Describe the bug**
crash on test - test_subsribers_with_active_publisher

dragonfly/connection_test.py::test_subsribers_with_active_publisher[df_factory0-3-10] 
--------------------------------------------------------------------------------------------------------------- live log setup ---------------------------------------------------------------------------------------------------------------
[2023-03-20 09:54:55.815 DEBUG] Using selector: EpollSelector
*** SIGSEGV received at time=1679298896 on cpu 15 ***
/home/adi/dragonfly/src/server/main_service.cc:1408:70: runtime error: member call on address 0x7f1be4239f30 which does not point to an object of type 'ConnectionContext'
0x7f1be4239f30: note: object has invalid vptr
 00 00 00 00  29 d1 a3 15 1c 7f 00 00  18 02 2d 82 74 10 26 34  e0 d3 33 f4 1b 7f 00 00  02 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
[failure_signal_handler.cc : 332] RAW: Signal 11 raised at PC=(nil) while already in AbslFailureSignalHandler()
/home/adi/dragonfly/src/facade/conn_context.h:26:12: runtime error: member access within address 0x7f1bf8159080 which does not point to an object of type 'ConnectionContext'
0x7f1bf8159080: note: object has invalid vptr
 00 00 00 00  a9 06 b2 09 1c 7f 00 00  18 02 2d 82 74 10 26 34  50 ce 33 f4 1b 7f 00 00  02 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
[failure_signal_handler.cc : 332] RAW: Signal 11 raised at PC=(nil) while already in AbslFailureSignalHandler()
/home/adi/dragonfly/src/server/main_service.cc:1417:30: runtime error: member call on address 0x7f1bf433d970 which does not point to an object of type 'Connection'
0x7f1bf433d970: note: object has a possibly invalid vptr: abs(offset to top) too big
 00 00 00 00  d0 d3 33 f4 1b 7f 00 00  f0 de 33 f4 1b 7f 00 00  00 00 00 00 00 00 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              possibly invalid vptr
[failure_signal_handler.cc : 332] RAW: Signal 11 raised at PC=(nil) while already in AbslFailureSignalHandler()
    @     0x561abf940c6f         64  absl::lts_20230125::WriteFailureInfo()
    @     0x561abf940e79         96  absl::lts_20230125::AbslFailureSignalHandler()
    @     0x7f1c0b210520       3728  (unknown)
    @     0x561abe873dfe         48  util::ProactorPool::Await<>()::{lambda()#1}::operator()()
    @     0x561abe87d59c         48  util::ProactorPool::DispatchBrief<>()::{lambda()#1}::operator()()
    @     0x561abe8b771f         48  fu2::abi_400::detail::invocation::invoke<>()
    @     0x561abe8b666e         64  fu2::abi_400::detail::type_erasure::invocation_table::function_trait<>::internal_invoker<>::invoke()
    @     0x561abf1ddd0a         96  fu2::abi_400::detail::type_erasure::tables::vtable<>::invoke<>()
    @     0x561abf1dde81         80  fu2::abi_400::detail::type_erasure::erasure<>::invoke<>()
    @     0x561abf1ddf12         64  fu2::abi_400::detail::type_erasure::invocation_table::operator_impl<>::operator()()
    @     0x561abf50b68d       2816  util::uring::Proactor::Run()
    @     0x561abf8bb372         48  util::ProactorPool::SetupProactors()::{lambda()#1}::operator()()
    @     0x561abf8beaed         48  std::__invoke_impl<>()
    @     0x561abf8be5c2         32  std::__invoke_r<>()
    @     0x561abf8bde45         48  std::_Function_handler<>::_M_invoke()
    @     0x561abe97b2e5         48  std::function<>::operator()()
    @     0x561abf8e3a3c        176  base::start_cpp_function()
    @     0x7f1c0b262b43  (unknown)  (unknown)
FAILED

**Comment by romange** [comment]
can we close it @adiholden
