### ISSUE TITLE
Benchmark Sidekiq

### ISSUE THREAD

**Issue by ashotland** [dragonflydb/dragonfly#966]

**Comment by alexanderadam** [comment]
Is it [fully compatible to Sidekiq yet](https://github.com/dragonflydb/dragonfly/issues/646)?

**Comment by ashotland** [comment]
Summary of current status:

Testing with sidekiq (OSS) seems ok now.
Sidekiq 7 uses resp3 by default, resp3 support is included in the upcoming v1.1 df release. 
@alexanderadam I have not tested with sidekiq pro so would love to know how it goes if you try it.

Perforamnce wise DF doesn't seem to maximize its cores and currently bottlenecks on producers side (saad + lpush) so we should have a lot of room for improvement.

I've created two small scripts to to that mimics sidekiq's task creation logic that may help with performance improvements work:
in pythhon: https://github.com/dragonflydb/ops/blob/main/sidekiq-playground/repro.py
and rubby: https://github.com/dragonflydb/ops/blob/main/sidekiq-playground/repro.rb

**Comment by ashotland** [comment]
Moved to https://github.com/dragonflydb/.github-private/issues/44
