### ISSUE TITLE
dragonfly with df_snapshot_format=true only saves snapshots with timestamp in a file

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#970]
it seems that `ExtendFilenameWithShard` always forces file with timestamp even when extension is provided.

I do not remember why it was decided.

**Comment by royjacobson** [comment]
@romange - @adiholden and I spoke about this a bit and we think that the current behavior is confusing.

What do you think about something like adding a simple string replacement support? So the default file name would be `dump-{timestamp}` and users can choose whether to add a timestamp or not unrelated to the existence of the filename extension.

**Comment by romange** [comment]
Sounds good
