### ISSUE TITLE
 Master-slave relationship cannot be established normally

### ISSUE THREAD

**Issue by boomballa** [dragonflydb/dragonfly#981]
I started two instances of dragonfly on the same machine, and the two instances cannot create a master-slave relationship normally.

The startup commands for the two instances are:
nohup dragonfly --requirepass=pwd4dba --bind 10.196.3.191 --port 16667 --dir /home/dba/redis/drogonfly16667/ --maxmemory=16gb --keys_output_limit=12288 --dbfilename dragon.rdb &
nohup dragonfly --requirepass=pwd4dba --bind 10.196.3.191 --port 16668 --dir /home/dba/redis/drogonfly16668/ --maxmemory=16gb --keys_output_limit=12288 --dbfilename dragon.rdb &

Confirm that the instance status is normal:
<img width="1859" alt="image" src="https://user-images.githubusercontent.com/8543659/227217582-63e2dc33-552a-4174-96eb-d05194fd3ad8.png">

I used the 4.0.11 and 6.0.14 versions of the redis-cli client to try to establish a master-slave relationship with command  `REPLICAOF` and `SLAVEOF`.will throw an error：
`(error) ERR could not greet master Bad message`

<img width="999" alt="image" src="https://user-images.githubusercontent.com/8543659/227218114-a93380ab-bcba-41c2-83ce-4f1100ce1b6c.png">

**Environment (please complete the following information):**
 - OS: [Debian GNU/Linux 11]
 - Kernel: Linux  5.10.0-18-amd64 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux
 - Containerized?: [Bare Metal, Docker, Docker Compose, Docker Swarm, Kubernetes, Other]
 - Dragonfly Version: [v1.0.0]

**Comment by romange** [comment]
@adiholden we forgot to support authenticated master 🤦🤦🤦

**Comment by romange** [comment]
@boomballa  meanwhile try without a requirepass flag. We will fix it soon :)

**Comment by boomballa** [comment]
> @boomballa meanwhile try without a requirepass flag. We will fix it soon :)
@romange Ok, I will try the no-password mode first, and the online environment must still require password authentication 
 😄

**Comment by boomballa** [comment]
@adiholden First of all thanks for your hard work on the fix. Just now I tried to use the new version to verify the instance with requirepass to try to establish a master-slave relationship, but an error is still reported `(error) ERR could not greet master Bad message`，Please guide me on this, is there a problem with my usage method or the bug has not been completely fixed.

**Comment by adiholden** [comment]
Hi @boomballa 
please path the flag --masterauth=<master_pass> to the replica, this way the replica will know how to auth with master

We will add this to our documentation. Sorry for not writing this before in the issue.

**Comment by boomballa** [comment]
> Hi @boomballa please path the flag --masterauth=<master_pass> to the replica, this way the replica will know how to auth with master
> 
> We will add this to our documentation. Sorry for not writing this before in the issue.

@adiholden OK, I'll try it out.

**Comment by boomballa** [comment]
@adiholden It has been verified that after configuring --masterauth, the master-slave can be established normally, thanks.
