### ISSUE TITLE
Error when systemd `PrivateNetwork=true` is set

### ISSUE THREAD

**Issue by solracsf** [dragonflydb/dragonfly#983]
**Describe the bug**

When [PrivateNetwork=true](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#PrivateNetwork=) is set an error is printed: 

`dns_resolve.cc:106 Error calling getaddrinfo Temporary failure in name resolution`

**To Reproduce**
1. set `PrivateNetwork=true` on the service unit
2. restart the service

**Expected behavior**

Detect `PrivateNetwork=true` setting and bypass DNS.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.0.4
 - Kernel: 5.15.0-67-generic
 - Dragonfly Version: 1.0

**Comment by solracsf** [comment]
Main goal of `PrivateNetwork=true` is to allow a service to listen on `loopback` **only** regardless of how the service binary is configured. So, any hostname or IP other than `localhost/127.0.0.1` can't be used, making `getaddrinfo` useless here.

Other services supports this quite well (redis, nginx...).

Maybe this is connected to https://github.com/dragonflydb/dragonfly/issues/979 as when using that option on redis, TCP is disabled and `getaddrinfo` is not used.

**Comment by solracsf** [comment]
> also curious how "localhost" is resolved in that case

I think it is not; with `port 0` redis is expecting a `unixsocket` **only** so no need to resolve anything.

**Comment by talbii** [comment]
Hi, @solracsf, could you provide a minimal working example? When I run Dragonfly as a service with the same parameters as yours, I instead get the error:

```
Could not open port 6379, error: Address family not supported by protocol
```

Which makes sense, as Dragonfly attempts to open port 6379 but is instead blocked by `PrivateNetwork=true`. I could not get the DNS error you mentioned.

---

Here is the steps I used:

1. Create a new service (`myservice.service`) by creating a file under `/etc/systemd/system/`:
```
# /etc/systemd/system/myservice.service
[Unit]
Description=Testing running Dragonfly as a system service.

[Service]
ExecStart=/path/to/dragonfly --logtostderr
PrivateNetwork=true
ProtectSystem=full
RestrictAddressFamilies=AF_UNIX
```

2. Reload daemons: `sudo systemctl daemon-reload`
3. Launch the service: `sudo systemctl start myservice.service`
4. Dragonfly crashes (by the same reasons as above), but with the error
```
Could not open port 6379, error: Address family not supported by protocol
```
which can be viewed using `systemctl status myservice.service`.

**Comment by solracsf** [comment]
Did you also set the `unixsocket`?
I must confess that in the meanwhile I've switched to TCP socket so I can't recall the full config 😞

**Comment by talbii** [comment]
I have tried to do that as well, no luck there.

I guess now that `--port 0` is supported this isn't relevant anymore.

**Comment by solracsf** [comment]
Closing, i'll do another try on next release and reopen if needed.
