### ISSUE TITLE
Threads and maxmemory autodetection should respect cgroup limits

### ISSUE THREAD

**Issue by uncycler** [dragonflydb/dragonfly#986]
When launching dragonfly in a container with cgroup memory and cpu limits, maxmemory is set to the host value instead of the limit.

When starting, dragonfly should respect those limits.

**Comment by romange** [comment]
The simple heuristic is for convenience.
Do you know how an app can fetch it from the environment? 

I am guessing it's simpler to pass an argument than for us to parse cgroups filesystem. Unless there is a simple api call that provides this info...

**Comment by uncycler** [comment]
For example, Java with the flag -XX:+UseContainerSupport (which is default since a while).

I am no expert, but I guess it's only a matter of reading `/sys/fs/cgroup/memory.max` and `/sys/fs/cgroup/cpu.max`?

**Comment by romange** [comment]
Should I ask him to send a PR? 

![image](https://user-images.githubusercontent.com/3674760/227795123-379cd1f9-9640-44a9-971c-0c78ecbe2909.png)

**Comment by talbii** [comment]
Lets start with maxmemory

**Comment by pomazanbohdan** [comment]
Need support 
```
    environment:
      - MAXMEMORY=2gb
```
in docker-compose file

**Comment by romange** [comment]
@pomazanbohdan why not pass arguments `--maxmemory=2gb` ?

**Comment by pomazanbohdan** [comment]
> @pomazanbohdan why not pass arguments `--maxmemory=2gb` ?

Using the environment option is more native when using the docker-composer file.

**Comment by pomazanbohdan** [comment]
![image](https://user-images.githubusercontent.com/696713/229795109-3c6d96ed-7c2d-41f1-b844-a0d8cb3c211a.png)

![image](https://user-images.githubusercontent.com/696713/229795173-dee5eb68-a1ce-4dc8-82a3-c455c9f645da.png)




That's all I could do)

**Comment by romange** [comment]
@pomazanbohdan You run it on your laptop, I guess.  We do not support weaker/old processors for now. What's your `/proc/cpuinfo`  output ?

About the environment variable - can you please explain in more detail how your docker compose would look like if we support env vars? Specifically, are you talking about using `env_file` option in docker compose file?

**Comment by pomazanbohdan** [comment]
Server CPU: Xeon X5650
I use Proxmox, and launch DragonFly in VM - LXC
