### ISSUE TITLE
Crash due to data race

### ISSUE THREAD

**Issue by vvhungy** [dragonflydb/dragonfly#997]
I'm running a redis cluster with rps ~ 240k; and when start trying with dragonfly, I got coredump frequently (process lived no more than 30minutes).

The dragonfly/redis mostly uses command HGET to get data. Commands pattern
- hget: >99.9%
- hset/hdel/hgetall/smembers/sadd/srem/ping: <0.1%

Below is what getting from console log

> mimalloc: error: thread 0x21e1a520: corrupted thread-free list
> mimalloc: error: thread 0x21e1a520: corrupted thread-free list
> mimalloc: error: thread 0x21e19010: corrupted thread-free list
> mimalloc: error: thread 0x21e19010: corrupted thread-free list
> mimalloc: error: thread 0x21e18eb0: corrupted thread-free list
> *** SIGBUS received at time=1679890128 on cpu 2 ***
> [failure_signal_handler.cc : 332] RAW: Signal 11 raised at PC=0x68cf34 while already in AbslFailureSignalHandler()
> PC: @           0x68ab90  (unknown)  _mi_free_block_mt
>     @           0x7524cc       4928  absl::lts_20230125::AbslFailureSignalHandler()
>     @     0xffffb4915804         32  (unknown)
>     @           0x51980c         32  _ZNSt17_Function_handlerIFN6facade8OpStatusEPN4dfly11TransactionEPNS2_11EngineShardEEZNS3_18ScheduleSingleHopTIZNS2_10HSetFamily4HGetEN4absl12lts_202301254SpanINSC_IcEEEEPNS2_17ConnectionContextEEUlS4_S6_E_EEDTclfp_fpTLDnEEEOT_EUlS4_S6_E_E10_M_managerERSt9_Any_dataRKSN_St18_Manager_operation
>     @           0x5e4640        208  dfly::Transaction::RunQuickie()
>     @           0x5e4978        112  dfly::Transaction::ScheduleUniqueShard()
>     @           0x5e7870        160  std::_Function_handler<>::_M_invoke()
>     @           0x644638        240  util::fibers_ext::FiberQueue::Run()
>     @           0x5c8260        256  boost::fibers::worker_context<>::run_()
>     @           0x5c7984  (unknown)  boost::context::detail::fiber_entry<>()

Also trying to get the coredump file but still not successfully.
systemd threw msgs like this "**_systemd-coredump[xxxxxxx]: Failed to get EXE, ignoring: No such process_**"

**Run command**
`./dragonfly-latest --bind 0.0.0.0 --dbnum 1 --proactor_threads 12 --maxmemory 5368709120 --port 3800 --save_schedule "*:30" --dbfilename dump.rdb --df_snapshot_format=false --dir /data/redis-3800/ --log_dir /data/redis-3800/  >/data/redis-3800/console.log 2>&1 &`

**Environment:**
 - OS: [Amazon Linux 3 (AL2023)]
 - Kernel: 6.1.15-28.43.amzn2023.aarch64
 - EC2 instance c7g.4xlarge (ARM64)
 - Dragonfly Version: [latest code as of 2023-03-27]

Pls help to check.
Tks.

**Comment by romange** [comment]
Hi @vvhungy  sorry about that. Can you please add here your command line?

**Comment by romange** [comment]
Also, can you please join our discord and ping me at #general channel?

**Comment by vvhungy** [comment]
Run command:
`./dragonfly-latest --bind 0.0.0.0 --dbnum 1 --proactor_threads 12 --maxmemory 5368709120 --port 3800 --save_schedule "*:30" --dbfilename dump.rdb --df_snapshot_format=false --dir /data/redis-3800/ --log_dir /data/redis-3800/  >/data/redis-3800/console.log 2>&1 &`

Also after start, I enable replication from the redis-master to this dragonfly instance from redis-cli: REPLICAOF host port.

**Comment by romange** [comment]
I see. Can you please disable `--save_schedule "*:30"` and see if the problem persists? 
Also dm'ed you :)

**Comment by romange** [comment]
Confirming that I succeed to reproduce it with an empty database on c7g.4xlarge.
To reproduce (in opt mode) run:
 `memtier_benchmark -t 8 --command "hget __key__ foo"   --hide-histogram -c 10 -n 800000`
